### ISSUE TITLE
data.get_data() should be consistent across datasets

### ISSUE THREAD

**Issue by matthew-brett** [nipy/dipy#10]
`dipy.data.get_data('small_64')` returns npy files for the gradients and bvalues, but `dipy.data.get_data('small_101D')` returns text files, so they need to be loaded using different commands (`np.load` compared to `np.loadtxt`).   For consistency they should be the same, or (preferably) return data, rather than filenames.

**Comment by theaverageguy** [comment]
Is this one still active @arokem ?

**Comment by arokem** [comment]
I believe so.

**Comment by theaverageguy** [comment]
Shall I work on the return types of both functions to fix this ? What would be the best way?

**Comment by skoudoro** [comment]
fix by #1283, closing
