### ISSUE TITLE
Progress bar works only for some data

### ISSUE THREAD

**Issue by arokem** [nipy/dipy#1014]
Moving the conversation that started over on #981 to here.

**Comment by arokem** [comment]
@ghoshbishakh : I think that if the server doesn't automatically provide data size, then we need to fall back on whether or not the data-size was provided as metadata for this data-set (this is information we removed in #971)

**Comment by ghoshbishakh** [comment]
yes so bringing back the data set metadata and autometically flling back is the way to go. I am working on it.

**Comment by arokem** [comment]
Cool -- :+1: -- thanks for taking a look!

**Comment by sahmed95** [comment]
Following.

**Comment by arokem** [comment]
This is resolved through #1015
