### ISSUE TITLE
viz.fvtk has no attribute 'ren' 

### ISSUE THREAD

**Issue by sahmed95** [nipy/dipy#1016]
From the examples, in [reconst_dti.py](https://github.com/nipy/dipy/blob/master/doc/examples/reconst_dti.py#L218) we get an AttributeError : fvtk has no attribute 'ren'. Ran this in python2.7 and got the same error. 

```python
>>> from dipy.viz import fvtk
>>> ren = fvtk.ren()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'ren'
```
Refer to #981 

Update : Same in Python3

**Comment by arokem** [comment]
You'll need to have VTK installed. See: https://neurostars.org/p/3724/#3726

**Comment by sahmed95** [comment]
Oh, Thanks. Will it be better if we warn the user or suggest that VTK should be installed. Someone who is just going through the examples might not know this.

**Comment by arokem** [comment]
Agreed - a better message would be great to have.

**Comment by sahmed95** [comment]
What is the correct error type ? AttributeError ? I am adding an else statement to raise a warning "VTK not installed"

**Comment by Garyfallidis** [comment]
import error

**Comment by sahmed95** [comment]
@Garyfallidis Thanks. I hope this fixes the issue. :smile:

**Comment by sahmed95** [comment]
When packages are not installed the optional_pakage function from utils.optpkg takes care of the import error. Instead of raising an error it returns a TripWire message as the import. Calling any attribute of this TripWire object should raise the ImportError and print the message. Example. 
Thus, if VTK is not installed.
```python
vtk, have_vtk, setup_module = optional_package('vtk')
ren = vtk.ren()
```
Should show the TripWire error. But it doesn't.

fvtk documentation says "# Allow import, but disable doctests if we don't have vtk".

I tried with other optional packages like tables in io.dpy and it was giving me the expected TripWire error. For new users, who are just going through the examples, this might be frustrating and a warning message would be nice.

I will dig into it and see why fvtk isn't showing a warning. Any comments from your side would be helpful.
