### ISSUE TITLE
Documentation does not mention Scipy as a dependency for VTK widgets.

### ISSUE THREAD

**Issue by theaverageguy** [nipy/dipy#1020]
While working with VTK widgets I came across the error:
no module named scipy.interpolate.

Obviously scipy needs to be installed but the documentation does not warn us about this.
Will take this up.

**Comment by sahmed95** [comment]
Can you please give a link to the file from where you get the error. Or post a code snippet how you got it?  You can use http://paste.ubuntu.com/. Even I want to understand how to deal with VTK.

**Comment by arokem** [comment]
Dependencies are described here:
http://nipy.org/dipy/dependencies.html#dependencies

**Comment by arokem** [comment]
And that's linked from here: http://nipy.org/dipy/installation.html

But happy to add it in other places, if it makes it easier.

**Comment by matthew-brett** [comment]
When #1019 is merged, dipy should install scipy automatically.

**Comment by theaverageguy** [comment]
I am working on VTK Widgets from now on for my application in GSoC. I would like to contribute with about 2-3 widgets this week.
Thanks. :)

**Comment by arokem** [comment]
I think we can close this one (feel free to reopen if I've missed something)
