### ISSUE TITLE
display in dsi example is broken

### ISSUE THREAD

**Issue by samuelstjean** [nipy/dipy#1023]
Seems like the web rendering had a problem again maybe.

![screenshot from 2016-03-31 15-47-35](https://cloud.githubusercontent.com/assets/3030760/14177765/24a5c674-f758-11e5-95c6-e7cefa146380.png)

**Comment by manu-tej** [comment]
@samuelstjean PR #1024 should solve the problem

**Comment by manu-tej** [comment]
closed through #1024
