### ISSUE TITLE
Fetcher files not found on Windows

### ISSUE THREAD

**Issue by arokem** [nipy/dipy#1030]
See test failures on the bots: 

http://nipy.bic.berkeley.edu/builders/dipy-bdist32-27/builds/342/steps/shell_11/logs/stdio

And on Appveyor:

https://ci.appveyor.com/project/arokem/dipy/build/1.0.675/job/ceb07013pjref2u4

**Comment by manu-tej** [comment]
There seems to be an issue with the with slash ( \ ) in address . It should be replaced with backward slash ( \ ) for windows.

**Comment by ghoshbishakh** [comment]
@arokem did this error arise after merging  #1015

**Comment by arokem** [comment]
@ghoshbishakh - I think it did. Let's see if @manu-tej's PR resolves this...

**Comment by manu-tej** [comment]
closed through #1035
