### ISSUE TITLE
tracking.interfaces imports SlowAdcOpdfModel, but it is not defined

### ISSUE THREAD

**Issue by matthew-brett** [nipy/dipy#1037]
See: http://nipy.bic.berkeley.edu/builders/dipy-py2.6-32/builds/758/steps/shell_9/logs/stdio

`dipy/tracking/interfaces.py` has this line:

```
from ..reconst.shm import (SlowAdcOpdfModel, MonoExpOpdfModel, QballOdfModel,
```

but `dipy.reconst.shm` does not define `SlowAdcOpdfModel` .

**Comment by arokem** [comment]
This looks like a repeat of https://github.com/nipy/dipy/issues/115
