### ISSUE TITLE
SFM example using deprecated code

### ISSUE THREAD

**Issue by alexsavio** [nipy/dipy#1040]
The example in: http://nipy.sourceforge.net/dipy/examples_built/sfm_reconst.html#example-sfm-reconst

Is using this code:

```
import dipy.reconst.peaks as dpp
```

which is deprecated.

**Comment by arokem** [comment]
This was fixed here: https://github.com/nipy/dipy/commit/171e7b7ab7c56962f3f4ac2698504d6edf90f3eb

**Comment by arokem** [comment]
How should we propagate this to the website? Cherry pick this commit into `maint/0.11.x` and rebuild the docs?

**Comment by Garyfallidis** [comment]
Yes.

**Comment by arokem** [comment]
Any idea why it's not already on the website? The updated version of this
tutorial is in the 0.11 release.

**Comment by Garyfallidis** [comment]
@arokem This looks good to me
http://nipy.org/dipy/examples_built/sfm_reconst.html#example-sfm-reconst
We don't use sourceforge anymore.

**Comment by alexsavio** [comment]
IMO if you have the documentation elsewhere already I would only keep one.
Maybe Google sent me to the sourceforge version. I am sorry for the confusion.

**Comment by arokem** [comment]
No worries. We should probably take down the sourceforge website, and
redirect from that link. @Garyfallidis: do you have the permissions on SF?
Or maybe @matthew-brett can help with that?

**Comment by Garyfallidis** [comment]
I have access to the sourceforge login but I want to hear first what Matthew thinks about this. Before making any drastic changes.
@alexsavio use dipy.org from now on. And thank you for reporting this problem. We didn't know that the two websites were not sync.

**Comment by Garyfallidis** [comment]
I looked a bit inside sourceforge and didn't find what link I need to update. I 'll wait for feedback from Matthew.

**Comment by matthew-brett** [comment]
​Sounds like a good idea to redirect.  When I was redirecting nibabel, I
put a redirect in each page, pointing to the github version.

Files should be in the public html directory on sourceforge - in the old
Makefile, this was:

WWW_SF=nipy@web.sourceforge.net:/home/groups/n/ni/nipy/htdocs/dipy

**Comment by Garyfallidis** [comment]
Can't find it. Where do I need to go? In each page? Sorry not clear.

**Comment by matthew-brett** [comment]
I haven't done this for ages, but if you look at the Makefile for the docs, from a few years ago, you'll see the sourceforge lines there.  I'm guessing that you can ssh into nipy@web.sourceforge.net and then navigate to the given directory to see the files.  I seem to remember that I made a script that went through all the pages and replaced the content with a message and a redirect to the matching github page, but I can't find that script on my laptop at the moment.

**Comment by Garyfallidis** [comment]
Hm... I don't know the pass for user nipy. And I have no access using my sourceforge username.

**Comment by arokem** [comment]
Any success here? Anything I can do to help?

**Comment by Laski** [comment]
Hi! I'm new to dipy and I've had some issues with the tutorial until I found that there are two different docs. Any update here should be appreciated by the next ones to come.

**Comment by arokem** [comment]
@Laski : Thanks for the feedback! Are you referring to the fact that there is one tutorial for reconstruction with SFM and another tutorial for tracking with SFM?

**Comment by Laski** [comment]
You're welcome! I'm referring to the fact that there are two docs for dipy actually searchable from Google ([here](http://nipy.org/dipy/documentation.html) vs [here](http://nipy.sourceforge.net/dipy/documentation.html)), which are for different versions. If you have current (0.11.0) version but get by mistake to the (0.10.0dev) there are things that may not work.

**Comment by arokem** [comment]
Ah yes - that's the sourceforge version mentioned above in this same
thread. Thanks.

@Garyfallidis: any luck taking down the SF pages? As you can see, it's
causing some confusion.

**Comment by arokem** [comment]
Looks like this has been resolved. Closing
