### ISSUE TITLE
Inconsistency in specifying S0 values in multi_tensor and single_tensor 

### ISSUE THREAD

**Issue by sahmed95** [nipy/dipy#1061]
As pointed out by @etpeterson in https://github.com/nipy/dipy/pull/1058#discussion_r64775504

> Looks like dipy may be a little conflicted also. Single_tensor uses S0=1 and multi_tensor uses S0=100, though others seem to prefer the 100 area.

In dipy/sims/voxel.py multi_tensor specifies S0=100 while single_tensor specifies S0=1

Should it be consistent over both functions ?

**Comment by arokem** [comment]
Yes. Best to set a global variable, and then use it in all the function definitions. There are many places in which this is set to 100, and only a few in which this is set to 1, so I guess we should probably go with 100 everywhere. There's even (at least) one place where S0 is set to 150... (https://github.com/nipy/dipy/blob/master/dipy/sims/voxel.py#L484)

**Comment by sahmed95** [comment]
PR for the fix : #1063
