### ISSUE TITLE
[Docs] Examples using deprecated function

### ISSUE THREAD

**Issue by Laski** [nipy/dipy#1070]
Hi! Dipy newbie here. While doing the [examples](http://nipy.org/dipy/examples_index.html) in the docs I found that some of them calls the `fvtk.ren()` method, which has been deleted [here](https://github.com/nipy/dipy/commit/e3827a341a244f6cce853ff7037b7e3d9085166b). I know the visualization has now its own (updated) section, but the having non-working examples is a bit confusing for newcomers.

**Comment by Laski** [comment]
Oh, I see now that the problem is fixed by installing vtk
> conda install vtk
so I think the docs should say that.

**Comment by arokem** [comment]
I think this was sorted out by https://github.com/nipy/dipy/pull/1021
