### ISSUE TITLE
There should be way to overall check to verify the input data is an ndarray or a "memmap"

### ISSUE THREAD

**Issue by rutgerfick** [nipy/dipy#1074]
Sometimes datasets are imported as a "memmap" instead of an ndarray, which can cause errors if you don't convert them to an array in the fitting process. For example, I tried to fit some data with the new mapmri module and because memmaps can't be concatenated it gave me the error "ValueError: zero-dimensional arrays cannot be concatenated",

If you don't know about this it's hard see that the type of the data is the problem, instead of for example the size of the array. Can there be an overall check that when you start fitting some data it will give you a specific ValueError to change the data type, or to correct it internally?

**Comment by matthew-brett** [comment]
Would you mind posting a tiny code snippet in numpy showing the concatenation problem?  I think this must be a numpy bug, if the behavior of memmaps is different than other arrays...

**Comment by rutgerfick** [comment]
from tempfile import mkdtemp
import os.path as path
filename = path.join(mkdtemp(), 'newfile.dat')
fake_data = np.memmap(filename, dtype='float32', mode='w+', shape=(5))
fake_data[:] = np.arange(5)
fake_b0_mask=np.r_[True,True,False,False,False]
fake_mean_b0 = fp[fake_b0_mask].mean()
fake_data_with_one_b0 = np.r_[fake_mean_b0, fp[~fake_b0_mask]]

**Comment by rutgerfick** [comment]
This should produce the ValueError. 
The whole problem can be avoided by using an np.asarray(fake_data) for example, but I thought perhaps a specific check could be put somewhere when you give the data to any module?

**Comment by matthew-brett** [comment]
I think this is the problem reported here : https://github.com/numpy/numpy/issues/7403

It's certainly surprising.

In this case though, you can solve it with `np.asscalar` on the output.

The memmaps arise because of the way that dipy / nibabel loads images from disk.

**Comment by matthew-brett** [comment]
Also this should be fixed in the next version of numpy (1.12).

**Comment by skoudoro** [comment]
It seems that this problem has been resolved so closing. 

Feel free to reopen it if necessary!
