### ISSUE TITLE
Needed PRs for merging recobundles into Dipy's master

### ISSUE THREAD

**Issue by MarcCote** [nipy/dipy#1099]
# Dipy PR's

This document describes the list of Pull Requests that needs to be merge into Dipy's Master. Except stated otherwise the up-to-date code can be found in the branch https://github.com/Garyfallidis/dipy/tree/recobundles.

_This issue is mainly for @Garyfallidis and me to track down which PRs still need to be made._
### dipy/viz/colormap.py:distinguishable_colormap

Generates colors that are maximally perceptually distinct.
- [x] Code 
- [x] DOC
- [ ] TEST
- [x] Example
### dipy/viz/actor.py:slicer

We need to check what changed.
- [x] Code 
- [x] DOC
- [x] TEST
- [x] Example
### dipy/viz/actor.py:odf_slicer

I don't think this one is urgent?
- [x] Code 
- [x] DOC
- [x] TEST
- [x] Example
### dipy/viz/actor.py:text_overlay

Maybe we should wait for the Ranveer's 2D UI component.
- [ ] DOC
- [ ] TEST
- [ ] Example
### dipy/viz/actor.py:text_3d

I've started to make some tests for this one(see https://github.com/MarcCote/dipy/tree/TST_text3d).
- [ ] DOC
- [ ] TEST
- [ ] Example
### dipy/viz/actor.py:figure

TODO.
- [ ] DOC
- [ ] TEST
- [ ] Example
### dipy/viz/utils.py

This PR would include only the functions vtk_matrix_to_numpy, numpy_to_vtk_matrix, shallow_copy, get_bounding_box_sizes. It would also fixes typos and other small changes.
- [ ] DOC
- [ ] TEST
- [ ] Example
### dipy/viz/utils.py:vtk_matrix_to_numpy and dipy/viz/utils.py:numpy_to_vtk_matrix

TODO
- [ ] DOC
- [ ] TEST
- [ ] Example
### dipy/viz/utils.py:matplotlib_figure_to_numpy

TODO
- [ ] DOC
- [ ] TEST
- [ ] Example
### dipy/viz/actor.py:Container

This also includes dipy/viz/actor.py:grid, dipy/viz/utils.py:get_grid_cells_position and the whole file dipy/viz/layout.py
- [ ] DOC
- [ ] TEST
- [ ] Example
### dipy/viz/utils.py:auto_orient and dipy/viz/utils.py:auto_camera

We need to better define their behavor and make some tests. 
- [ ] DOC
- [ ] TEST
- [ ] Example
### dipy/viz/timeline.py

TODO
- [ ] DOC
- [ ] TEST
- [ ] Example
### dipy/segment/clustering.py:QuickBundlesX

TODO
- [x] Code
- [ ] DOC
- [x] TEST
- [ ] Example
### dipy/segment/clustering.py:QuickBundlesOnline

We should check if we couldn't integrate the Online behavior directly to QuickBundles and QuickBundlesX.
- [ ] Code 
- [ ] DOC
- [ ] TEST
- [ ] Example

**Comment by skoudoro** [comment]
This issue was moved to fury-gl/fury#33
