### ISSUE TITLE
Dipy.align.reslice: either swallow the scipy warning or rework to avoid it

### ISSUE THREAD

**Issue by jchoude** [nipy/dipy#1107]
When calling dipy.align.reslice and use scipy 0.17.1, we get the following UserWarning:

```
scipy/ndimage/interpolation.py:435: UserWarning: The behaviour of affine_transform with a one-dimensional array supplied for the matrix parameter will change in scipy 0.18.0.
  "The behaviour of affine_transform with a one-dimensional "
```

This is caused by a change in behavior from Scipy, between 0.17.1 and 0.18, as explained [in Scipy's doc](http://docs.scipy.org/doc/scipy-0.18.0/reference/generated/scipy.ndimage.affine_transform.html).

For us, there won't be any consequence, since the behavior won't change, because we do not use the `offset` parameter. However, the warning might be misleading or simply distracting for end users, and it will still be present in scipy 0.18. That means that it will pollute our logs for a long time.

Two ideas:
1- Swallow the warning by using something like [this](https://github.com/scikit-image/scikit-image/blob/master/skimage/_shared/_warnings.py#L77) (as was suggested in issue #641 )
2- Simply reformat the matrix we send as a diagonal matrix, which will provide exactly the same behavior, without the warning.

I would go for option 2, but would like to have some other advice before proceeding @Garyfallidis @arokem

**Comment by arokem** [comment]
Yes: I like option 2 better too. Presumably changing this line?

https://github.com/nipy/dipy/blob/master/dipy/align/reslice.py#L71

to the following?

    R = np.diag(new_zooms / zooms)

**Comment by sahmed95** [comment]
Changing to ```R = np.diag(new_zooms / zooms)``` fails the test
```
FAIL: dipy.align.tests.test_reslice.test_resample
----------------------------------------------------------------------
Traceback (most recent call last):
  File "dipy/dipy/align/tests/test_reslice.py", line 25, in test_resample
    assert_almost_equal(new_zooms, new_zooms_confirmed)

AssertionError: 
Arrays are not almost equal to 7 decimals

(mismatch 100.0%)
 x: array([ 1. ,  1.2,  2.1])
 y: array([ 1.7320508,  2.0784609,  3.6373067], dtype=float32)
```

**Comment by sahmed95** [comment]
@arokem Any comments on this ? Is changing test parameters okay or is ```R = np.diag(new_zooms / zooms) ``` not the correct way to go. @jchoude

**Comment by arokem** [comment]
Yes. I must have gotten that wrong. @jchoude : what would you suggest here?

**Comment by dimrozakis** [comment]
Hey @arokem & @sahmed95.

`R` used to be a diagonal array. I changed it to a single dimensional array in https://github.com/nipy/dipy/pull/757/commits/b6fc887d4309f7bbd76ff10c20b86953de708bde. The reason for that, as explained in the commit message and in [scipy's docs](http://docs.scipy.org/doc/scipy-0.18.0/reference/generated/scipy.ndimage.affine_transform.html) is:

>A diagonal matrix can be specified by supplying a one-dimensional array-like to the matrix parameter, in which case a more efficient algorithm is applied.

So I would suggest against changing it back to a 2D array, since that will increase computation time of `reslice`.

**Comment by jchoude** [comment]
Sorry for the delay.

I don't mind leaving it as a 1D array. However, what was not clear to me was the potential difference in behavior between Scipy 0.17.1 and 0.18 when supplying a 1D array, exactly in the same doc that @dimrozakis pointed out.

Currently, our behavior is consistent, since the offset that we pass is always np.zeros(3,). We might simply need to ensure that we don't change the offset, else the result might not be consistent between versions of scipy.
