### ISSUE TITLE
.eddy_rotated_bvecs file throws error from io.gradients read_bvals_bvecs function

### ISSUE THREAD

**Issue by mrjeffs** [nipy/dipy#1117]
after using fsl eddy the resulting bvecs file ext becomes .eddy_rotated_bvecs
when read_bvals_bvecs reads the newly created .eddy_rotated_bvecs it tests the extension
if ext in ['.bvals', '.bval', '.bvecs', '.bvec', '.txt',  '']:
i modified it to 
if ext in ['.bvals', '.bval', '.bvecs', '.bvec', '.txt', '.eddy_rotated_bvecs', '']:
and it seemed to work without error.

**Comment by Garyfallidis** [comment]
Okay good. Can you make a pull request @mrjeffs with that addition? It is a bit strange to change the end of the filename in this way. But I think we should support it.

**Comment by mrjeffs** [comment]
great thanks. will do. FSL eddy chooses not to overwrite the orig bvecs when it recalculates vectors.

**Comment by Garyfallidis** [comment]
They should have done something like filename_eddy_rotated.bvecs
Anyway... :)

**Comment by skoudoro** [comment]
done on #1411
