### ISSUE TITLE
pip install dipy failing on my windows

### ISSUE THREAD

**Issue by blandeau** [nipy/dipy#1118]
Hi,

I am trying to install dipy on windows  following the installation instructions but `pip install dipy` throws the following error 

> ---
> 
> Command "C:\Users\landeau\AppData\Local\Continuum\Anaconda3\python.exe -u -c "im
> port setuptools, tokenize;**file**='C:\Users\landeau\AppData\Local\Temp\pi
> p-build-h1as7h4g\dipy\setup.py';exec(compile(getattr(tokenize, 'open', open)(_
> _file__).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record C:\U
> sers\landeau\AppData\Local\Temp\pip-_x2ni44h-record\install-record.txt --single-
> version-externally-managed --compile" failed with error code 1 in C:\Users\lande
> au\AppData\Local\Temp\pip-build-h1as7h4g\dipy\

Could you please help me? Thanks

**Comment by arokem** [comment]
Following:
http://stackoverflow.com/questions/28142839/pip-install-numpy-python-2-7-fails-with-errorcode-1

Do you have a 'pip.log' file somewhere (presumably in your home directory)?

Does it have a similar message about "unable to find vcvarsall.bat" towards
the end? It might mean that you need a compiler.

Might be helpful to know what version of Windows and what version of Python
you are doing this on.

Alternatively, if it's all the same to you, you could install this using
conda (which you would need to install separately, see:
http://conda.pydata.org/docs/install/quick.html):

    conda install -c conda-forge dipy

**Comment by arokem** [comment]
No further information. Closing.
