### ISSUE TITLE
Buildbots failing with workflow merge

### ISSUE THREAD

**Issue by arokem** [nipy/dipy#1119]
I think the merge of #1087 causes the following buildbot failures (both the same): 

http://nipy.bic.berkeley.edu/builders/dipy-bdist-whl-3.3/builds/41/steps/shell_10/logs/stdio
http://nipy.bic.berkeley.edu/builders/dipy-bdist-whl-2.7/builds/43/steps/shell_10/logs/stdio

**Comment by matthieudumont** [comment]
WIll look into it

**Comment by matthieudumont** [comment]
Does the build only fail on osx?

It might have to do with os.path.getmtime not working the same on osx.

**Comment by arokem** [comment]
Thanks for taking a look! Indeed, it seems to be an OSX thing. You can see the status of all the bots here: 

http://nipy.bic.berkeley.edu/waterfall

Also, it is failing locally on my laptop (a mac). I'll try to see if I can find a fix on my setup.

**Comment by arokem** [comment]
https://github.com/nipy/dipy/pull/1120

**Comment by arokem** [comment]
Looks like this was fixed in #1120
