### ISSUE TITLE
restore throws scipy error

### ISSUE THREAD

**Issue by mrjeffs** [nipy/dipy#1133]
when i tested restore on a simple dataset it fails with the following error in fitting:

/home/toddr/Software/dipy/dipy/reconst/dti.py:1463: RuntimeWarning: overflow encountered in exp
  y = np.exp(np.dot(design_matrix, tensor))
/home/toddr/Software/dipy/dipy/reconst/dti.py:1472: RuntimeWarning: overflow encountered in square
  se = residuals *\* 2
/home/toddr/Software/anaconda2/lib/python2.7/site-packages/scipy/optimize/minpack.py:427: RuntimeWarning: Number of calls to function has reached maxfev = 1600.
  warnings.warn(errors[info][0], RuntimeWarning)
Traceback (most recent call last):
  File "/home/toddr/Software/anaconda2/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-14-b91f11d9be57>", line 1, in <module>
    fit = tenmodel.fit(data, mask)
  File "/home/toddr/Software/dipy/dipy/reconst/dti.py", line 799, in fit
    _self.args, *_self.kwargs)
  File "/home/toddr/Software/dipy/dipy/reconst/dti.py", line 1713, in restore_fit_tensor
    this_sigma))
  File "/home/toddr/Software/anaconda2/lib/python2.7/site-packages/scipy/optimize/minpack.py", line 380, in leastsq
    raise TypeError('Improper input: N=%s must not exceed M=%s' % (n, m))
TypeError: Improper input: N=7 must not exceed M=3

code:
`m='RESTORE'
bvals, bvecs = read_bvals_bvecs(str(fbvals), str(fbvecs))
gtab = gradient_table(bvals, bvecs)
img = nib.load(str(fdwi))
data = img.get_data()
mask_img = nib.load(str(mask_fname))
mask = mask_img.get_data()
sigma = ne.estimate_sigma(data, N=1)
tenmodel = dti.TensorModel(gtab, fit_method=m, sigma=sigma, jac=False)
fit = tenmodel.fit(data, mask)`

sigma looks like this:
array([ 62.45582199,  17.0501461 ,  17.86696243,  17.74765205,
        18.39748955,  18.6872139 ,  18.46704483,  17.99226189,
        19.60660362,  18.0275898 ,  17.51873589,  17.92651176,
        17.71314049,  18.14698982,  16.06102943,  16.74896622], dtype=float32)

same error when jac=True as well. no error with OLS or WLS methods.
scipy.**version**
'0.18.1'
np.**version**
'1.11.1'

any ideas?
jeff

**Comment by arokem** [comment]
It looks like what would happen if a lot of your measurements get thrown out as outliers. How many directions of measurement do you have? Any chance you could share a minimal data-set with me, so that I can debug?

**Comment by mrjeffs** [comment]
it is an old set with 1 b0 and 15 directions. is that below this implementation's minimum. camino's restore works nicely. i can email you a zip file.
tangentially: is there a tensor median filter method?

**Comment by arokem** [comment]
Yeah - with few directions and relatively small sigma, you might end up
rejecting so many directions that you end up with less measurements than
parameters. Feel free to email me the data, if you want me to take a look.

What is a tensor median filter method? Is it something like the median
filter described in the following link?

http://scikit-image.org/docs/dev/auto_examples/applications/plot_rank_filters.html

**Comment by mrjeffs** [comment]
ah, ok. i wonder why camino doesn't have this problem? higher rejection threshold?
wrt median filter seems yes scikit median filter would work with r=1 (disk(1)?). is there a method/function in dipy to access the numpy array of the tensor for filtering then make that the array that calculates fa etc?

**Comment by arokem** [comment]
When you say "the numpy array of the tensor" what exactly do you mean?

The TensorFit object has a variety of attributes that you can access and
filter in this way: https://github.com/nipy/dipy/blob/master/dipy/reconst/
dti.py#L835-L1134

I'm not sure about the differences between our implementation and Camino's.
Our implementation follows the Vistasoft implementation rather closely.

**Comment by mrjeffs** [comment]
its my lack of python mojo causing me to not see a direct way to save via nibabel or filter via scikit the fitted tensor. did you get the files after i granted acccess?

**Comment by arokem** [comment]
If by "fitted tensor", you mean the 3x3 quadratic form of the tensor, this
should save it to file:

   nib.save(nib.Nifti1Image(tensor_fit.quadratic_form, affine), '/path/to/
filename.nii.gz')

I did get the file -- thanks. I will take a look.

**Comment by mrjeffs** [comment]
ok ariel, thanks, what i am looking for is the upper triangle 6 vols of the tensor as in:
Dxx,Dxy,Dxz,Dyy,Dyz,Dzz. your design matrix is:
design_matrix[j, :] = (Bxx, Byy, Bzz, Bxy, Bxz, Byz, dummy).
you have defined 2 slicing variables for the lower triangle derived from the quadratic form:
_lt_rows = np.array([0, 1, 1, 2, 2, 2])
_lt_cols = np.array([0, 0, 1, 0, 1, 2])
tensor_fit.quadratic_form[..., _lt_rows, _lt_cols]
for compatibility with camino and FSL i need the advanced slicing codes for extracting the upper triangle from the quatratic form eg. _ut_rows and _ut_cols
(assuming the 3x3 quadratic has both U & L)
j

**Comment by mrjeffs** [comment]
i tested _ut_rows and _ut_cols above and they match the fsl tensors from dtifit.

**Comment by skoudoro** [comment]
What is the conclusion of this old discussion @arokem, @mrjeffs?  Can I close it? 

I will wait until Sunday and if no answer, I will close it. Thank you for your feedback!

**Comment by arokem** [comment]
Yeah. I think it's fine to close.
