### ISSUE TITLE
The shebang again! Python: bad interpreter: No such file or directory

### ISSUE THREAD

**Issue by Garyfallidis** [nipy/dipy#1139]
I am reporting the following problem using Ubuntu 16.04 LTS with the scientific python libraries installed using apt-get install. Dipy and nibabel were installed locally by adding their directories to the PYTHONPATH.
Also the dipy/bin directory was added to the actual PATH in .bashrc and sourced. Dipy and nibabel are in their master branch.

Then I tried to run any of the new command lines e.g.
dipy_median_otsu
and got 
bash: Devel/dipy/bin/dipy_median_otsu: python: bad interpreter: No such file or directory

When I did
which python 
I got /usr/bin/python

I then replaced #!python with #!/usr/bin/python and that worked! Which is very unexpected and very strange! That means to me that #!python is not yet supported fully in major distributions. Then I thought okay maybe the python installation is not correct. And repeated the same procedure in a VM with Ubuntu 16.10 where all the packages and python was installed using anaconda. The same thing happened. 
python: bad interpreter: No such file or directory

I know that @matthew-brett, @jchoude, @matthieudumont and others have discussed before about the issues of changing shebang to !#python rather than  !#/usr/bin/env python Could it be that this was a bit too rushed decision. If we do bring it back using /usr/bin/env python would that affect other operating systems?

Please lets try to figure this out asap and definitely before the upcoming release. It may affect many users.

**Comment by matthew-brett** [comment]
I think there's no sensible way of supporting ordinary pip install and doing the PYTHONPATH etc way that you are using here.   I'm sure you know, but the right way of doing what you are doing here is:

```
pip install -e .
```

**Comment by ghoshbishakh** [comment]
I think as it was discussed #!python works well with pip but not when
installing inplace and linking with PYTHONPATH
I faced similar problem with #! python

**Comment by jchoude** [comment]
I tend to agree with @matthew-brett . Personnally, for development purposes, I just create a new venv, pip install all the libs to the venv, and call the bin scripts with the full path. It might not be the most optimal way, but it has always worked with the classical /usr/bin/env python.

The other thing to think is that our developer workflow is certainly not the classical enduser workflow. Most endusers will simply pip install a dipy release and be done with it. I guess that's the main case we should test and validate. As for us, we can adjust our workflow accordingly.

**Comment by matthew-brett** [comment]
The command lines should just work if you install with `pip install -e .`  Here's me making a new virtualenv:

```
$ pip install -e .
$ dipy_median_otsu
usage: dipy_median_otsu [-h] [--save_masked] [--median_radius int]
                        [--numpass int] [--autocrop] [--vol_idx str]
                        [--dilate str] [--out_dir str] [--out_mask str]
                        [--out_masked str] [--force] [--out_strat string]
                        [--mix_names] [--log_level string] [--log_file string]
                        input_files
```

**Comment by Garyfallidis** [comment]
Did try this and it didn't work. I am not on a virtualenv. So, if I don't add anything in my PYTHONPATH and I go and run this command (pip install -e .) in the dipy directory it fails with permission issues. It is asking to install nibabel in dist-packages. Which is something that I clearly do not want. I want both dipy and nibabel to be installed in my home directory.
```  
creating /usr/local/lib/python2.7/dist-packages/nibabel
error: could not create '/usr/local/lib/python2.7/dist-packages/nibabel': Permission denied
```

**Comment by matthew-brett** [comment]
Right - you should be doing a user install if you don't want to work in a virtualenv:

```
pip install --user -e .
```

**Comment by matthew-brett** [comment]
This page is a little out of date (it predates Linux wheels), but still somewhat relevant:

https://matthew-brett.github.io/pydagogue/installing_on_debian.html

**Comment by Garyfallidis** [comment]
Okay what pip install -e does is it will go and add the project path at /usr/local/lib/python2.7/dist-packages/easy-install.pth

**Comment by matthew-brett** [comment]
`pip install --user -e .` - installs the equivalent path link in your user directory tree.

**Comment by Garyfallidis** [comment]
If you don't provide ```--user``` then you cannot really uninstall it automatically. You have to go and change the .pth file in dist-packages. If you do provide ```--user``` then you can uninstall as well.

**Comment by Garyfallidis** [comment]
But if you do provide the `--user` flag it goes and puts the command lines under .local That is really strange too. That means that every time that I need to switch to a different branch I will have to rerun the command `pip install --user -e .`  after having uninstalled the previous version. Correct @matthew-brett ?

**Comment by Garyfallidis** [comment]
Even if we consider that there is an alternative way using pip to access the command lines. Still it looks like a bug to me that the shebang `#!python` does not work correctly although `which python` shows the correct path. So, if this is a bug where should I submit an issue? In python or debian? Or both? Any ideas? By the way in Ubuntu 14.04 I didn't have this problem. I think.

**Comment by matthew-brett** [comment]
Have a look at the files generated by `pip install --user -e .` in `~/local/bin` - they point to the source files in the development directory.  So I think you can change branches and get the newest versions of the scripts, with no problem.  If there's a new script, I guess you'll have to do another `pip install --user -e .`.

**Comment by Garyfallidis** [comment]
Yes, this is what I mean too. You need to reinstall only when new scripts arrive. Not all the time. Which is not that bad. But still PYTHONPATH was easy to explain to people especially in workshops with psychologist that code a bit because they are so used with playing with environment variables. Now we will have to be a bit more fancy I suppose. Finally, if you think that this (`#!python not working in debian`) is a bug and it should be reported let me know. You have looked into these issue for much longer and more detail than me. Thumbs up for the feedback! :)

**Comment by matthew-brett** [comment]
For the bug report - see: http://unix.stackexchange.com/questions/11907/shebang-and-path#11910 - so no, I don't think it's a bug.

I do think we should avoid PYTHONPATH for new user / developers - pip is the future - and so the default should be

```
pip install --user -e .
```
