### ISSUE TITLE
pytables version and streamlines_format.py example

### ISSUE THREAD

**Issue by skoudoro** [nipy/dipy#1142]
I am still playing with dipy examples and i got a problem with streamlines_format.py.  (dipy has been installed on new environnement via conda install on OS X 10.11)

I got an import error after running this command (means pytables dependency miss on conda package ?) :
`from dipy.io.dpy import Dpy ; dpw = Dpy('fornix.dpy', 'w')` 

So I install pytables (last version - 3.3.0), and now i get the following error :
`AttributeError: 'module' object has no attribute 'openFile'`

Indeed, the function name is "open_file" with pytables 3.3.0.

So my question is which version of pytables should i use for dipy 0.11.0?

if i can continue with pytables 3.3.0, should i create a new branch for correcting this problem ?

Thanks in advance, 

Serge

**Comment by Garyfallidis** [comment]
Yes, please do. Thank you @skoudoro

**Comment by arokem** [comment]
We should add pytables as a conda dependency: https://github.com/conda-forge/dipy-feedstock/issues/4
