### ISSUE TITLE
[Bug] connectivity matrix image in streamline_tools example

### ISSUE THREAD

**Issue by mdesco** [nipy/dipy#1154]
The connectivity.png figure in the example shows three subfigures (2 rtop figures from EAP estimation and the connectivity matrix with "msd"  over it). See here. 

I don't know where this comes from but is wrong. Only the connectivity matrix should be displayed. I have looked at the code and it seems right...

<img width="698" alt="screenshot 2016-11-25 13 42 54" src="https://cloud.githubusercontent.com/assets/2170887/20625705/50d66d74-b315-11e6-843c-0cc23082bb89.png">

**Comment by arokem** [comment]
Thanks for reporting! Looks like we have an issue with cleaning up figures between examples. My theory is that this was introduced in this commit: https://github.com/nipy/dipy/commit/55166f71f6626f5e5f0acb79ace31efab1bea6cd. I think that `plt.close('all')` might have been there to do the cleanup after each example (and was removed in that commit). @Garyfallidis : WDYT?

**Comment by Garyfallidis** [comment]
I can replicate the issue. Let me try it and will get back to you.

**Comment by Garyfallidis** [comment]
Thanks for reporting @mdesco !!
It should be good now. See here 
http://nipy.org/dipy/examples_built/streamline_tools.html#example-streamline-tools
