### ISSUE TITLE
fvtk volume doesn't handle affine (crashes notebook)

### ISSUE THREAD

**Issue by kesshijordan** [nipy/dipy#1161]
When I try to use the fvtk volume function without an affine, it works... with an affine, however, I get the error that it needs scalar data to volume render, and the notebook crashes. See toy example, below.

ERROR: In ../Rendering/Core/vtkVolume.cxx, line 720
vtkVolume (0x3ce14e0): Need scalar data to volume render

"The kernel appears to have died. It will restart automatically"

from dipy.viz import fvtk

import numpy as np
a = np.zeros([20,21,22]).astype('uint8')
a[10:15,10:15,10:15] = 255
ren = fvtk.ren()

roi_actor = fvtk.volume(a, affine=np.eye(4), voxsz = np.array([1,1,1], float), info=1)
fvtk.add(ren,roi_actor)
fvtk.show(ren)

**Comment by Garyfallidis** [comment]
Yes, it makes sense. This is an old function that needs to be refactored. Thanks for reporting!

**Comment by kesshijordan** [comment]
Is there anything else that displays roi's? I can't give the contour function an affine... but i was going to try to modify that to get something working.

Thanks!
Kesshi

**Comment by kesshijordan** [comment]
I combined the contour function in fvtk.py and the slicer code from actor.py, and it now works to display an roi using the affine. I haven't written tests for it yet but I can put it up as a work-in-progress.

**Comment by Garyfallidis** [comment]
That is excellent news @kesshijordan ! :+1:

**Comment by kesshijordan** [comment]
Thanks, @Garyfallidis. I created a pull request for this  #1163

**Comment by skoudoro** [comment]
The PR #1165 resolve this issue and is merged.

Can we close this issue @kesshijordan ?

**Comment by kesshijordan** [comment]
Yes. Thanks, @skoudoro.
