### ISSUE TITLE
Potential replacement for CVXOPT?

### ISSUE THREAD

**Issue by arokem** [nipy/dipy#1167]
https://github.com/biosustain/optlang

Released under Apache license.

**Comment by arokem** [comment]
Another one, much more similar to cvxopt (I think), also licensed under Apache: 

http://www.cvxpy.org/en/latest/license/index.html

**Comment by Garyfallidis** [comment]
So many possibilities! How nice!

**Comment by skoudoro** [comment]
I think, it is done via #1285, we close this issue ?

**Comment by arokem** [comment]
indeed!
