### ISSUE TITLE
Time for a new release - scipy 0.18?

### ISSUE THREAD

**Issue by matthew-brett** [nipy/dipy#1169]
I just set of a wheel build, and noticed that the current release of dipy errors out with the current release of scipy:

```
======================================================================
ERROR: Failure: ImportError (cannot import name nanmean)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/venv/local/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/venv/local/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/venv/local/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/venv/local/lib/python2.7/site-packages/dipy/reconst/sfm.py", line 25, in <module>
    from scipy.stats import nanmean
ImportError: cannot import name nanmean
```

https://travis-ci.org/MacPython/dipy-wheels/jobs/191741388#L413

Time for a new release?

**Comment by arokem** [comment]
Past time for a release, for sure.

If we want to handle different versions, we could (should?) do what we did here: 

https://github.com/nipy/dipy/pull/1166

**Comment by jchoude** [comment]
Also, the interpolation code in dipy.tracking.interpolation errors out when using Numpy 1.12, because the Deprecation Warning was finally changed to an Error (see https://docs.scipy.org/doc/numpy/release.html#deprecationwarning-to-error)

Do we have a buildbot using the 1.12 release yet?

**Comment by jchoude** [comment]
Also, my previous message could also be linked with https://github.com/nipy/dipy/issues/728

**Comment by arokem** [comment]
Could this be related? http://nipy.bic.berkeley.edu/builders/dipy-bdist32-27/builds/401/steps/shell_12/logs/stdio

**Comment by jchoude** [comment]
No, you would get an error like:

```
File "dipy/tracking/local/interpolation.pyx", line 116, in dipy.tracking.local.interpolation.nearestneighbor_interpolate (dipy/tracking/local/interpolation.c:2847)
    return data[index]

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
```

Casting the index to an int fixes the issue. I'm testing the code right now.

**Comment by arokem** [comment]
Gotcha - yes. @matthew-brett might be able to comment on the versions of
dependencies on those bots.

Just checking: is this error only happening on Python 2.7? I believe it
might be.

And while we're at it, we should probably decomission the bots running 2.6 (
http://nipy.bic.berkeley.edu/builders/dipy-py2.6-32, http:/
/nipy.bic.berkeley.edu/builders/dipy-py2.6, ). We dropped support  for 2.6
in https://github.com/nipy/dipy/pull/1075

@matthew-brett - I tried to find my way around nibotmi to do this myself,
but couldn't figure this out. Would you mind doing this (dropping the 2.6
bots)? Thanks!

**Comment by jchoude** [comment]
I'm not sure if it is happening only on 2.7. It was reported to me by a end user. I don't have his exact setup to replicate, but on my tests on 2.7 it fixes the issue.

For my knowledge, what would cause the behavior to differ for Python >= 3?

**Comment by matthew-brett** [comment]
Sorry -  I should have renamed them - but I believe all the 'py26' bots are in fact using Python 2.7.

**Comment by arokem** [comment]
@jchoude : seems like I am wrong. I just confirmed that this would fail with that error message on both Python 2.7 and 3.5. 

@matthew-brett : thanks!

**Comment by fmorency** [comment]
+1

**Comment by arokem** [comment]
Yeah - we're working on it. I think that all we have left for the release are the following: 

https://github.com/nipy/dipy/pull/1245
https://github.com/nipy/dipy/pull/1241
https://github.com/nipy/dipy/pull/1243
https://github.com/nipy/dipy/pull/1164
https://github.com/nipy/dipy/pull/1156

I think we should postpone merging the LPCA PR (#1233) until after the release, given that it looks like there might be more work to do there.

**Comment by arokem** [comment]
🎉
