### ISSUE TITLE
Automate workflow generation

### ISSUE THREAD

**Issue by arokem** [nipy/dipy#1179]
See: https://github.com/nipy/dipy/pull/1123/files#r89196846

**Comment by arokem** [comment]
This might be useful: https://github.com/google/python-fire

**Comment by skoudoro** [comment]
is it the same as #1253 ? Should I close this issue @arokem  ?  (python-fire tool seems nice, maybe we should create a new issue to change the command line generation. I need to play a little bit with it)

**Comment by arokem** [comment]
Yeah - we can close this.
