### ISSUE TITLE
peaks warning while CSD reconstructing

### ISSUE THREAD

**Issue by salma1601** [nipy/dipy#1181]
Hi Dipy experts,

I systemtically have a warning when I FIT `ConstrainedSphericalDeconvModel` to my subjects data.
Is it something expected ?

>/usr/lib/python2.7/dist-packages/dipy/direction/peaks.py:504: RuntimeWarning: invalid value encountered in double_scalars
  return np.sqrt(numer / denom)

Thanks !

**Comment by Garyfallidis** [comment]
Yes, it is expected. We are considering suppressing those warnings as they seem create more panic than help.

**Comment by arokem** [comment]
How about doing something like this? https://github.com/nipy/dipy/pull/1289

**Comment by salma1601** [comment]
>We are considering suppressing those warnings as they seem create more panic than help
+1

**Comment by skoudoro** [comment]
It seems to be done, can I close this issue?

**Comment by salma1601** [comment]
yes, thanks
