### ISSUE TITLE
CSD vs CSA

### ISSUE THREAD

**Issue by salma1601** [nipy/dipy#1182]
Dear Dipy experts,

I have data with only 30 gradient directions not regularly distributed on the sphere. I compared the tracks computed both with CSD (`recursive_response`, `auto_response`) and CSA and it looks like for all my subjects CSD with recursive response gives the best results (just visually). I am a little surprised by my results since it is said in the doc that CSD _is mainly useful with datasets with gradient directions acquired on a spherical grid_. Does it make sense to choose my CSD tracks even if my data does not fulfill this constraint ?
Thanks !
Salma

**Comment by arokem** [comment]
Hi! This depends on so many different aspects of the data and the analysis that it is really hard to speculate about this, without empirical testing of the specific case. I think that the best way to know whether your resulting streamlines make sense is to compare them with the original data you collected. We have a method for doing that in http://nipy.org/dipy/examples_built/linear_fascicle_evaluation.html (full disclosure and disclaimer: I am a co-author of the original paper describing this method, and my opinion is not necessarily shared by other Dipy developers; I'd be curious to hear what others suggest...)

**Comment by salma1601** [comment]
Ok, thanks à lot ! I will use this method (and others if suggestions) to check my streamlines quality.
Thanks a lot for contributing to devolop such useful and user-friendly tool and for answering my questions!
