### ISSUE TITLE
unable to use fvtk.show after ubuntu 16.10 install

### ISSUE THREAD

**Issue by salma1601** [nipy/dipy#1185]
Dear dipy experts,

I used to visualize my streamlines smoothly with
```Python
from dipy.viz import fvtk
from dipy.viz.colormap import line_colors

streamlines_actor = fvtk.line(streamlines, line_colors(streamlines)
r = fvtk.ren()
fvtk.add(r, streamlines_actor)
fvtk.show(r)
```

However since my install of ubuntu 16.10 the `fvtk.show(r)` throws strange errors

>libGL error: unable to load driver: i965_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: i965
libGL error: unable to load driver: i965_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: i965
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast

Do you have any hints on how to visualize my streamlines ?

**Comment by salma1601** [comment]
I did a complete reinstall of ubuntu, reverting to 14.04. Now things are better because I can save figures with `fvtk.record`, however I can not interact with the 3D plot of `fvtk.show`: it throughs the following error, shutting down my ipython

>Mesa 11.2.0 implementation error: invalid target in _swrast_choose_texture_sample_func
Please report at https://bugs.freedesktop.org/enter_bug.cgi?product=Mesa
Mesa 11.2.0 implementation error: invalid target in _swrast_choose_texture_sample_func
Please report at https://bugs.freedesktop.org/enter_bug.cgi?product=Mesa
Erreur de segmentation (core dumped)

Do you guys advice a particular version of ubuntu ?
Thanks !

**Comment by MarcCote** [comment]
Sorry for the delay, I've totally missed this issue. 

Have you solved your issue? If so, please share what you did to solve it. If not, please provide the following information so we can better target the source of the issue:
- What is your VTK version ?
- The output of this command `glxinfo | grep render`

**Comment by salma1601** [comment]
Thanks for your reply !
>Have you solved your issue? If so, please share what you did to solve it.

Not really ! I switched back to unbuntu 14.04, this improved things since now I can see the `fvtk` plot. However as soon as I try to interact with it (ie when I click with the mouse) python crashes and I have this error
>Mesa 11.2.0 implementation error: invalid target in _swrast_choose_texture_sample_func
Please report at https://bugs.freedesktop.org/enter_bug.cgi?product=Mesa
Mesa 11.2.0 implementation error: invalid target in _swrast_choose_texture_sample_func
Please report at https://bugs.freedesktop.org/enter_bug.cgi?product=Mesa
Erreur de segmentation (core dumped)

Here are the outputs  of `vtkpython`
>vtk version 6.3.0
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
ImportError: No module named site

and of `glxinfo | grep render`

>direct rendering: Yes
    GLX_MESA_multithread_makecurrent, GLX_MESA_query_renderer, 
    GLX_MESA_multithread_makecurrent, GLX_MESA_query_renderer, 
OpenGL renderer string: Mesa DRI Intel(R) HD Graphics 5500 (Broadwell GT2) 
    GL_ARB_conditional_render_inverted, GL_ARB_conservative_depth, 
    GL_MESA_texture_signed_rgba, GL_NV_conditional_render, GL_NV_depth_clamp, 
    GL_ARB_conditional_render_inverted, GL_ARB_conservative_depth, 
    GL_NV_conditional_render, GL_NV_depth_clamp, GL_NV_light_max_exponent,

**Comment by MarcCote** [comment]
One thing you could try is running your command like this 
`LIBGL_ALWAYS_SOFTWARE=1 python your_script.py`. I have to use that on my laptop to run vtk stuff since I don't have a dedicated graphic card.

**Comment by salma1601** [comment]
>One thing you could try is running your command like this
LIBGL_ALWAYS_SOFTWARE=1 python your_script.py

This worked for me, thanks a lot !
