### ISSUE TITLE
Test failures for cluster code with current numpy master

### ISSUE THREAD

**Issue by matthew-brett** [nipy/dipy#1191]
PR #1186 has a new matrix entry testing dipy against current numpy and scipy master builds, to make sure that we don't distribute stuff that will break on the next release of numpy / scipy.

This finds some new test failures on the cluster code, which appear to be because of a change in the way that numpy compares arrays.  I explored a little, and realized that I didn't understand the intention behind the tests, and in particular, whether the tests were really intended to test the behavior of `np.array(clusters)`.  Test failures are of the form:

```
======================================================================
FAIL: dipy.segment.tests.test_clustering.test_cluster_getitem
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/nipy/dipy/venv/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/build/nipy/dipy/venv/lib/python3.5/site-packages/dipy/segment/tests/test_clustering.py", line 120, in test_cluster_getitem
    [data[indices[i]] for i in advanced_indices])
  File "/home/travis/build/nipy/dipy/venv/lib/python3.5/site-packages/numpy/testing/utils.py", line 852, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/home/travis/build/nipy/dipy/venv/lib/python3.5/site-packages/numpy/testing/utils.py", line 776, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal
(mismatch 100.0%)
 x: array([ array([[  0.,   1.,   2.],
       [  3.,   4.,   5.],
       [  6.,   7.,   8.],...
 y: array([ array([[  0.,   1.,   2.],
       [  3.,   4.,   5.],
       [  6.,   7.,   8.],...
```

https://travis-ci.org/nipy/dipy/jobs/208736688#L2742

You should be able to replicate the test failures by first doing:

```
pip install -U --pre -f https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com numpy
```

**Comment by matthew-brett** [comment]
This one still there - would be good to fix this before the release, so new numpy doesn't break dipy when it's released.

**Comment by matthew-brett** [comment]
@MarcCote - I think this is your code?

**Comment by MarcCote** [comment]
You are right the intention is not to test `np.array` which seems to be called implicitly by `assert_array_equal`. I just wanted to compare the result of advanced indexing on the `Cluster` object vs manually selecting one data element at the time. I'll have a closer look.

**Comment by MarcCote** [comment]
See #1194

**Comment by matthew-brett** [comment]
The tests are still failing against current numpy master, after #1194 was merged - see https://travis-ci.org/nipy/dipy/jobs/214060347#L2762 .
