### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by arokem** [nipy/dipy#1197]
### Improve the front page: 

- [ ] Change the `getting started` example
- [ ] Include a few more images on the front page

### CLI documentation

See http://elef.soic.indiana.edu/documentation/0.12.0.dev/reference_cmd/

- [x] Suppress warnings

### Check the citation system

- [ ] Some bibtex item types are not currently rendered correctly

**Comment by ghoshbishakh** [comment]
I need suggestions on what to include in the main page. Like what should the getting started section contain. Also what images should we include.

About the bibtex rendering it should be working fine and I will add all the publications from the present website.

About warning supression I am looking into it tonight.

**Comment by arokem** [comment]
https://github.com/nipy/dipy/pull/1237

**Comment by skoudoro** [comment]
Not anymore relevant, closing
