### ISSUE TITLE
[Docs] Error while generating docs

### ISSUE THREAD

**Issue by ghoshbishakh** [nipy/dipy#1200]
```
Traceback (most recent call last):
  File "../tools/make_examples.py", line 122, in <module>
    exec(open(script).read(), namespace)
  File "<string>", line 98, in <module>
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
make: *** [Makefile:122: rstexamples-stamp] Error 1
```

**Comment by ghoshbishakh** [comment]
https://github.com/nipy/dipy/blob/master/doc/examples/quick_start.py#L98

**Comment by ghoshbishakh** [comment]
@jchoude can you give me a clue how to fix this?

**Comment by jchoude** [comment]
This seems to be related to the new versions of numpy which are strict on indexing. Check if middle axial is not really a float (created on the division). If that's the case, cast it to int and make sure you get the correct slice.

**Comment by arokem** [comment]
#1202 should fix it.

**Comment by jchoude** [comment]
@ghoshbishakh Can you check if the new master is ok for you and fixes this?

**Comment by ghoshbishakh** [comment]
@jchoude it is fixed now. I am trying to build all the examples and update the site.
