### ISSUE TITLE
Move data files out of dropbox => persistent URL

### ISSUE THREAD

**Issue by arokem** [nipy/dipy#1209]
For example, the b0 file for `fetch_syn` is giving me a 404: 

https://dl.dropboxusercontent.com/u/5918983/b0.nii.gz

Code/data that would need to be changed is here: 

https://github.com/nipy/dipy/blob/master/dipy/data/fetcher.py#L255
https://github.com/nipy/dipy/blob/master/dipy/data/fetcher.py#L279
https://github.com/nipy/dipy/blob/master/dipy/data/fetcher.py#L322
https://github.com/nipy/dipy/blob/master/dipy/data/fetcher.py#L338
https://github.com/nipy/dipy/blob/master/dipy/data/fetcher.py#L379
https://github.com/nipy/dipy/blob/master/dipy/data/fetcher.py#L390

**Comment by Garyfallidis** [comment]
Other people complained to me recently. I suppose we need to move most of them. Take the lead if you can. Do you have an account for Dipy in figshare?

**Comment by arokem** [comment]
We don't need a dipy account for this. On further thought, we don't even
need to put this on Figshare (a commercial entity, so maybe we want to stay
away from that). I'll upload these data to the UW library's data
repository, or maybe Zenodo, or some-such. Await impending PR with that.

**Comment by arokem** [comment]
Fixed in #1219
