### ISSUE TITLE
Switching branches in windows and pip install error

### ISSUE THREAD

**Issue by Garyfallidis** [nipy/dipy#1210]
@matthew-brett and all 
In windows 10 after I switch branches and do 
pip install --user -e .
I get compilation errors.
But if we download the specific branch and pip install it is all good.
I believe that for some reason the binary files are not deleted and pip install does not replace them.
In linux we do make clean; make ext. But what is the clean option in Windows?

**Comment by Garyfallidis** [comment]
Is this the ```--no-cache``` option?

**Comment by matthew-brett** [comment]
The `--no-cache` option should affect an `-e` install.

Is there any problem with doing `git clean -fxd`?  That will clean up your source for you, but you should probably check `git status` beforehand to make sure you're not going to delete anything you want.

**Comment by Garyfallidis** [comment]
Okay this will probably do the trick. Will investigate more and get back to you. I find it difficult to replicate the problem in my machine. Will work with the postdoc who identified the problem first and get back to you. May take a few days. Thanks!

**Comment by arokem** [comment]
What's the status on this one?

**Comment by arokem** [comment]
Was this resolved?

**Comment by maryamafzali** [comment]
Yeah, It is resolved.

Thank you,
