### ISSUE TITLE
bundle visualisation using nibabel API: wrong colormap

### ISSUE THREAD

**Issue by arnaudbore** [nipy/dipy#1236]
Hi,

If I want to reproduce [this visualisation](http://nipy.org/dipy/examples_built/viz_bundles.html#show-every-point-of-every-streamline-with-a-different-color) using nibabel API to load my tract file I need to change colors with np.concatenate(colors). The issue here seems to be linked with the new API and the ArraySequence format. Thanks to @MarcCote

**Comment by Garyfallidis** [comment]
Hi @arnaudbore and very sorry for delaying to get back to you. Can you give us an example showing the issue?

**Comment by Garyfallidis** [comment]
Sorry, let me be more precise. For me when I run this example in my computer it works.

![image](https://cloud.githubusercontent.com/assets/134276/26695198/ec76393e-46d7-11e7-9cea-c3597922391b.png)

Are you using master? Or the release version? 0.11?

**Comment by skoudoro** [comment]
Closing this issue. Feel free to reopen it if you still have this problem @arnaudbore.
