### ISSUE TITLE
DKI microstructure model tests still fail intermittenly

### ISSUE THREAD

**Issue by arokem** [nipy/dipy#1242]
This seems to be a failure in predicting from the model: https://travis-ci.org/nipy/dipy/jobs/231992444, but it might just be a numerical precision issue.

**Comment by RafaelNH** [comment]
Yup should only be a numerical precision issue! I didn't spot this before cause I am not able to reproduce this intermit fail in my local PC! I create a PR to address this:

PR #1244

**Comment by skoudoro** [comment]
Should we close this issue @arokem @RafaelNH ?
