### ISSUE TITLE
Interactor bug in viz_ui example

### ISSUE THREAD

**Issue by dmreagan** [nipy/dipy#1247]
Python 3.6, VTK 7.1.0, Windows 10

I see a bug in the viz_ui example related to the sliders. After I interact with the disk on the `LineSlider2D` or `RingSlider2D`, I am no longer able to interact with the cubes. Interacting with the panel, the buttons, the text box, or even the slider line or ring fixes the problem, and I can interact with the cubes once more. The problem appears only with the disk. 

Discovered while working on #1246.

**Comment by dmreagan** [comment]
@ranveeraggarwal Have you had a chance to try the viz_ui example under VTK 7.1.0?

**Comment by ranveeraggarwal** [comment]
@dmreagan not yet, I have some trouble setting it up (on my MacOS). I should be able to get it up by this weekend.

**Comment by dmreagan** [comment]
@ranveeraggarwal I'm not sure about Mac, but I've used VTK 7 builds from a group called Clinical Graphics. @Garyfallidis also just worked with the conda-forge people to update their builds.

**Comment by ranveeraggarwal** [comment]
@dmreagan [this](https://anaconda.org/clinicalgraphics/vtk) looks nice, I will try this out.

**Comment by MarcCote** [comment]
@dmreagan I think the changes we made for PR #1262 (in the handle_events method around https://github.com/nipy/dipy/pull/1262/files#diff-8edf9b236ab5f6609200bd485fc3a079R163) should correct the behavior you observed. That said, I haven't tested with VTK 7.1.0. Can you check again, after #1262 is merged or if you pull @ranveeraggarwal's `ui` branch?

**Comment by dmreagan** [comment]
I do not see the behavior with @ranveeraggarwal's `ui` branch, so it looks like you are correct. Closing.
