### ISSUE TITLE
Windows doc installation update is needed for Python 3, Anaconda and VTK support

### ISSUE THREAD

**Issue by Garyfallidis** [nipy/dipy#1248]
To successfully install dipy in windows 10 with Python 3.6 I had to:

Find which is the correct Visual C++ compiler for Python 3.6.
Cython needs the exact compiler which was used to create CPython for the specific version of Python.
When you run python in a terminal you can get the MSC_VER and then find the relevant compiler using this list

```
Visual C++ 2008  (9.0)          MSC_VER=1500
Visual C++ 2010 (10.0)          MSC_VER=1600
Visual C++ 2012 (11.0)          MSC_VER=1700
Visual C++ 2013 (12.0)          MSC_VER=1800
Visual C++ 2015 (14.0)          MSC_VER=1900
Visual C++ 2017 (15.0)          MSC_VER=1910
```

In my case it was MSC_VER=1900 so I installed visual build tools 2015. See more info about that here:

https://wiki.python.org/moin/WindowsCompilers
http://landinghub.visualstudio.com/visual-cpp-build-tools

For vtk 7.1.0 conda-forge or conda do not have vtk 7.1.0 for Python 3. However clinicalgraphics provide a working version.

``conda install -c clinicalgraphics vtk=7.1.0
``

**Comment by matthew-brett** [comment]
Compilation advice for Windows over at http://matthew-brett.github.io/pydagogue/python_msvc.html gives a summary of MSVC and Python versions.

**Comment by Garyfallidis** [comment]
Yes, I saw that. Good job.

**Comment by arokem** [comment]
@Garyfallidis: How did you get `MSC_VER` in the Python command line? Is it
in `os.environ`?

Could you please add these details to the documentation, as long as it's
all fresh in your memory?

**Comment by Garyfallidis** [comment]
Just call python or ipython the MSC version is always shown.

The real difficulty to figure this out for my case was not find the compiler version  the difficulty was that a) they were websites saying that you can compile using later Visual Studio versions and b) that if you have other versions of visual studio and the current version the error messages were coming out very messy. We had two windows computers both with Visual Studio 2017 and Visual Studio Build tools 2015 and they both had different behaviors.

Yes, of course we need an installation update that is why I started this issue to gather my thoughts and see what the others say.

**Comment by jchoude** [comment]
@Garyfallidis there are also two other older issues:

#1084 
#1146 

that all seem to be related directly or not to this. Should we close some of them / update them?
