### ISSUE TITLE
Switch testing to pytest?

### ISSUE THREAD

**Issue by arokem** [nipy/dipy#1280]
I have a feeling we've discussed this before. Nose is no longer being developed, and from what I have heard and experienced myself, it looks like pytest (https://docs.pytest.org/en/latest/) is a good way to go. Looks like maybe nose2 is also an option (http://nose2.readthedocs.io/en/latest/).

**Comment by skoudoro** [comment]
I do not think nose2 is a good option (last commit January 3rd). Pytest is actively and better maintained and I agree with you when you said it is way to go (as soon as possible).

**Comment by thechargedneutron** [comment]
What exactly needs to be done here? As far as I can infer, I need to remove all dependencies on nose and replace it with `pytest`. Anything else (like changing travis file etc.) ??

**Comment by arokem** [comment]
Yes. That's the gist of it. And indeed, travis config would also need to be adjusted to use pytest. 

Things might get complicated, though. For example because of older numpy.testing dependency on nose.

Because of the sensitivity of this kind of change, it would be good to discuss the strategy towards changing this. For example, do we want to change it all in one fell swoop, or do we envision having an intermediate stage that depends on both pytest and nose, until we can stabilize?

**Comment by skoudoro** [comment]
I made a really quick test: `pytest --doctest-modules --durations=10 -svv dipy` and the result was quite positive ! 
- 80% of tests run without any failure on OSX python 3.
- 20% do not run.

Base on that, I think it will be better to avoid the intermediate stage. Of course, this is a preliminary thought, many chances that I do not see all tricky part

**Comment by thechargedneutron** [comment]
Okay I'll try over this weekend. Can you guide me on how to build the tests locally so as to check if the changes do not affect current behaviour?

**Comment by jhlegarreta** [comment]
I can also work on it during the weekend if the work can be shared/divided.

**Comment by thechargedneutron** [comment]
@skoudoro @arokem  Can we use unittests as well? There are certain functions including SkipTest and TestProgram which are there in unittests. Pytest does not have (probably) these mentioned functions. PR #1414

**Comment by arokem** [comment]
Doesn't this work for skipping? 

https://docs.pytest.org/en/latest/skipping.html
