### ISSUE TITLE
Existing MAPMRI tutorial does not render correctly and MAPL looks hidden in the existing tutorial.

### ISSUE THREAD

**Issue by Garyfallidis** [nipy/dipy#1291]
http://nipy.org/dipy/examples_built/reconst_mapmri.html#example-reconst-mapmri

**Comment by arokem** [comment]
That example does include MAPL. It was changed in the PR that introduced MAPL: 

https://github.com/nipy/dipy/pull/1153/files#diff-aa743bb3a0919f172e5dca3244da2ab3 

Rendering's borked though. That should be fixed.

**Comment by Garyfallidis** [comment]
Okay, cool.

**Comment by Garyfallidis** [comment]
Also this tutorial seems like needing better datasets. Which is something we talked about in the past. Real datasets in  high resolution that can expose the power of Mapmri.

**Comment by arokem** [comment]
Yeah - we should switch this to use the recently added CFIN data: https://github.com/nipy/dipy/blob/master/dipy/data/fetcher.py#L1001

**Comment by skoudoro** [comment]
It seems to be fixed by #1424, I close this issue
