### ISSUE TITLE
Error-handling when pytables not installed

### ISSUE THREAD

**Issue by arokem** [nipy/dipy#1306]
I think I missed a bug in my review of #1241 

If you don't have pytables installed, then this line will evaluate to False: 

https://github.com/nipy/dipy/blob/master/dipy/io/peaks.py#L19

which means that when you reach this line:
https://github.com/nipy/dipy/blob/master/dipy/io/peaks.py#L37

There will be no variable `TABLES_LESS_3_0` in your namespace, resulting in a cryptic `NameError`

**Comment by skoudoro** [comment]
Right, I take this one ! Unfortunately, I can not do it now so I will create a PR at the end of the week.

**Comment by arokem** [comment]
Thanks!

**Comment by aarya22** [comment]
@skoudoro It would also be more helpful to edit cryptic NameError message to ask the user to check if they have pyTables installed.
