### ISSUE TITLE
step_helpers gives a wrong error message

### ISSUE THREAD

**Issue by zhangfanmark** [nipy/dipy#1309]
https://github.com/nipy/dipy/blob/master/setup_helpers.py#L228-L229

found_ver and min_ver should be reversed. 

Now, it gives an error message: 
"RuntimeError: We need Cython version 0.22, but found version 0.25.1"

**Comment by skoudoro** [comment]
Good Catch, Thank you @zhangfanmark !

**Comment by arokem** [comment]
Closed through #1310
