### ISSUE TITLE
Warnings raised in csdeconv for upcoming numpy 1.14

### ISSUE THREAD

**Issue by arokem** [nipy/dipy#1323]
See: https://travis-ci.org/nipy/dipy/jobs/268292931, and conversation in #1322

**Comment by jhlegarreta** [comment]
@arokem I was having a look at this, but I do not see where the issue is. Tried to search for changes in signature of `assert_equal`, but only found that it changed for complex or array values, and in this case, we get a boolean, which is fine, right? Any ideas where to look into?

**Comment by arokem** [comment]
It's got to do with this clause: https://github.com/nipy/dipy/blob/master/dipy/reconst/tests/test_csdeconv.py#L231

It's designed to catch this particular warning: 
https://github.com/nipy/dipy/blob/master/dipy/reconst/csdeconv.py#L130

But if any other warning is raised, it gets caught in this as well. 

I am not sure what warning gets raised here. The best way to debug this would be to install the pre-release version of numpy, run this locally with a debugger, and drop into the stack to see where the warning is coming from.

**Comment by skoudoro** [comment]
I just fix this issue on PR #1335. Can you have a look @arokem @jhlegarreta  ? 

Thanks !

**Comment by jhlegarreta** [comment]
@skoudoro I had little idea on how to fix it, but the change looks OK. Interesting.
Restarting the Travis builds that failed in my PRs. 
Thanks Serge.

**Comment by jhlegarreta** [comment]
Travis builds are back to green. Hats off to @skoudoro !
