### ISSUE TITLE
Fix inspect.getargspec deprecation warning in Python 3

### ISSUE THREAD

**Issue by jhlegarreta** [nipy/dipy#1327]
The `USE_PRE=1` builds are failing among others because the 
```
DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
   specs = inspect.getargspec(fnc)
```
deprecation warning is being displayed due to the use of Python 3.

**Comment by jhlegarreta** [comment]
I'm looking into this. Would using

    try: #Python3
        specs = inspect.signature(fnc)
    except AttributeError: # Python2
       specs = inspect.getargspec(fnc)

solve the issue?

I've seen that others suggest using `inspect.getfullargspec()`, which seems to be fine:
https://docs.python.org/3/library/inspect.html

**Comment by naveenkumarmarri** [comment]
I've raised PR #1413  for this issue, can someone review it?

**Comment by jhlegarreta** [comment]
@skoudoro  The corresponding card in the [dipy 0.14.0 card](https://github.com/nipy/dipy/projects/1) can be marked as **WIP**.

**Comment by skoudoro** [comment]
Thanks for pointing that @jhlegarreta

**Comment by skoudoro** [comment]
#1413 is merged and card updated,  you can close this issue @jhlegarreta.
