### ISSUE TITLE
Trying QuickBundles (Python3 and vtk--> using: conda install -c clinicalgraphics vtk)

### ISSUE THREAD

**Issue by Drigomaniac** [nipy/dipy#1333]
Hi All, 
After reading the docs and a couple of issues here (in github), I realized there are compatibility issues when installing vtk and anaconda for python 3. 

The quick fix I found was to install vtk 7.1.0 like this --> https://anaconda.org/clinicalgraphics/vtk --> `conda install -c clinicalgraphics vtk 
*Also mentioned in this post by Eleftherios: https://github.com/nipy/dipy/issues/1248  

But when I follow the vtk segment (in http://nipy.org/dipy/examples_built/segment_quickbundles.html#example-segment-quickbundles):
`ren = fvtk.ren()
ren.SetBackground(1, 1, 1)
fvtk.add(ren, fvtk.streamtube(sstreams2, fvtk.colors.white))
fvtk.record(ren, n_frames=1, out_path='fornix_initial.png', size=(600, 600))
`

I can see a window created but it disappears as soon as I created it yet the 'fornix_initial.png' get created. Any solution? 

*I also tested VTK (https://www.vtk.org/Wiki/VTK/Examples/Python/Cylinder ) and it seems to work correctly. Not sure what to do now, should I try a different vtk installation?

I am using OSX Sierra (10.12.6)  and Python 3.6.1

**Comment by skoudoro** [comment]
Hi @Drigomaniac,

`fvtk.record` just save a image. If you want to keep the window and play with it, use `fvtk.show(ren, reset_camera=False)`

For selecting between interactive or not, you can look at the example http://nipy.org/dipy/examples_built/tracking_quick_start.html#example-tracking-quick-start

We will correct that or feel free to correct this example via a new PR. 

Thanks !

**Comment by Drigomaniac** [comment]
Yeap, that did it. It seems that the vtk problem and the rendering of the image worked well. 
Thanks for your rapid response, 
Rodrigo
