### ISSUE TITLE
Coveralls seems baggy let's remove it

### ISSUE THREAD

**Issue by Garyfallidis** [nipy/dipy#1337]
Hi all,
coveralls has not been helpful so far. Can we please remove it? 
Does anyone know how to do this?
I am not even sure how this program was added in our github project.

**Comment by arokem** [comment]
+1 what a PITN

**Comment by arokem** [comment]
I found this page: 

![screen shot 2017-09-18 at 6 38 38 pm](https://user-images.githubusercontent.com/118582/30572105-a2962e36-9ca0-11e7-9335-fed05a034dac.png)

Should I hit the red button?

**Comment by Garyfallidis** [comment]
Press-on FORCEFULLY!!! :)

**Comment by arokem** [comment]
Done!
