### ISSUE TITLE
Variable string input does not work with self.get_io_iterator() in workflows

### ISSUE THREAD

**Issue by Garyfallidis** [nipy/dipy#1338]
Hi @matthieudumont,

variable string currently works only as an optional parameter.
Can you look at this and see if we can integrated as an accepted input?

Let me know what you think.

**Comment by matthieudumont** [comment]
Hi, I currently dont have time to work on this so if you guys need this asap you are better off not waiting for me. Otherwise, I will eventually look into that when the time comes. 

Also sorry for late reply, somehow I dont receive github emails anymore, JC pointed this to me.

**Comment by thechargedneutron** [comment]
Hi @Garyfallidis I would like to work on this if @matthieudumont is unable to work on it. 

Can you provide an example/reproducible code where variable string input gives error / unexpected behavior?
