### ISSUE TITLE
Deprecate dipy.io.trackvis?

### ISSUE THREAD

**Issue by arokem** [nipy/dipy#1339]
At the very least, we need to update this line in the documentation: https://github.com/nipy/dipy/blob/master/dipy/io/trackvis.py#L10

See for example conversation here: https://mail.python.org/pipermail/neuroimaging/2017-September/001525.html

An easy fix for now would be to replace that function with a call out to nibabel and a deprecation warning.

**Comment by skoudoro** [comment]
I see an opportunity for me to learn and migrate DIPY to the new streamlines API. I will create a new PR and work on it next week

**Comment by arokem** [comment]
Fantastic!

**Comment by jchoude** [comment]
I fully support deprecating the old code. +1 from me.

**Comment by matthew-brett** [comment]
As the author of the old code - fine with me too.

**Comment by arokem** [comment]
Hey @skoudoro : have you had a chance to look into this?

**Comment by skoudoro** [comment]
yes @arokem, I started to look at this and I have a local PR. Maybe, I should push it with a WIP tag.

**Comment by arokem** [comment]
That would be great.
