### ISSUE TITLE
Quickbundles tutorials miss reference

### ISSUE THREAD

**Issue by Garyfallidis** [nipy/dipy#1371]
Some of the segmentation tutorials using QuickBundles do not have a reference to the original QuickBundles paper.

**Comment by jhlegarreta** [comment]
@Garyfallidis @skoudoro I had a look at this, but everything seems to be in place in the code:
[doc/examples/segment_quickbundles.py](https://github.com/nipy/dipy/blob/master/doc/examples/segment_quickbundles.py) contains a reference to the (original?) paper.

It is also visible on the [website](http://nipy.org/dipy/examples_built/segment_quickbundles.html#example-segment-quickbundles). 

It's also in the [python class](https://github.com/nipy/dipy/blob/master/dipy/segment/quickbundles.py) containing the method implementation and the [segmentation metrics](https://github.com/nipy/dipy/blob/master/dipy/segment/metric.py) as well.

Now it's true that [Enhancing QuickBundles with different metrics and features](http://nipy.org/dipy/examples_built/segment_extending_clustering_framework.html#example-segment-extending-clustering-framework) does not cross-ref it.

So I'm wondering if that is not the intended reference (present in [cite.rst](https://github.com/nipy/dipy/blob/master/doc/cite.rst) also), or else, it is missing from somewhere else that I did not spot. I'd be happy to fix this.

**Comment by skoudoro** [comment]
All the QuickBundles tutorials should have a reference to the original paper.

**Comment by jhlegarreta** [comment]
@skoudoro thanks. OK, I'll submit a patch set having this in mind.
