### ISSUE TITLE
New test failures with pre-release numpy

### ISSUE THREAD

**Issue by arokem** [nipy/dipy#1376]
On new PR #1375, we stumbled on these failures on the pre-release Travis bot: https://travis-ci.org/nipy/dipy/jobs/302550184

**Comment by skoudoro** [comment]
Hi @arokem, Thanks for this information ! 

It seems to be the same issue as #1352 (print formatting with doctest)

We just need to add `from .testing import setup_test` where tests failed.

**Comment by arokem** [comment]
Closed through #1377
