### ISSUE TITLE
is there any defined function that reads locally stored data or is all downloaded? I refer to nii or nifti files

### ISSUE THREAD

**Issue by Dimitrievici** [nipy/dipy#1382]
## Description
[Please provide a general introduction to the issue/proposal.]

[If reporting a bug, attach the entire traceback from Python and follow the way to reproduce below]
[If proposing an enhancement/new feature, provide links to related articles, reference examples, etc.]

## Way to reproduce
[If reporting a bug, please include the following important information:]
- [x] Code example
- [ ] Relevant images (if any)
- [ ] Operating system and version (run `python -c "import platform; print(platform.platform())"`)
- [ ] Python version (run `python -c "import sys; print("Python", sys.version)"`)
- [ ] dipy version (run `python -c "import dipy; print(dipy.__version__)"`)
- [x] dependency version (numpy, scipy, nibabel, h5py, cvxpy, vtk)
    * import numpy; print("NumPy", numpy.__version__)
    * import scipy; print("SciPy", scipy.__version__)
    * import nibabel; print("Nibabel", nibabel.__version__)
    * import h5py; print("H5py", h5py.__version__)
    * import cvxpy; print("Cvxpy", cvxpy.__version__)
    * import vtk; print(vtk.vtkVersion.GetVTKSourceVersion())

**Comment by arokem** [comment]
You might want to have a look at nibabel:
http://nipy.org/nibabel/gettingstarted.html

**Comment by skoudoro** [comment]
As @arokem said, [Nibabel](http://nipy.org/nibabel/gettingstarted.html) is a good call with more option, otherwise you can use : 
```
from dipy.io.image import load_nifti, save_nifti

arr = load_nifti('/path/to/my_image.nii')
```
more info with dipy [here](http://nipy.org/dipy/reference/dipy.io.html#dipy.io.image.load_nifti)

**Comment by skoudoro** [comment]
Does it resolve your problem @Dimitrievici ?

**Comment by skoudoro** [comment]
I'll close this for now, but feel free to reopen if you any other problem!
