### ISSUE TITLE
Assert equality, instead of asserting that `a == b` is true

### ISSUE THREAD

**Issue by arokem** [nipy/dipy#1387]
For example, here: https://github.com/nipy/dipy/blob/master/dipy/workflows/tests/test_reconst_dti.py#L45

This is because asserting equality gives more informative error messages.

**Comment by thechargedneutron** [comment]
I am new to dipy and would like to take up this issue. Should I also replace `assert_true(x <= y)` with `assert_less(x, y)`?

**Comment by skoudoro** [comment]
yes @thechargedneutron, thanks for doing this !

**Comment by thechargedneutron** [comment]
@arokem  @skoudoro  Please review. :smile:
