### ISSUE TITLE
Running dipy 'Intro to Basic Tracking' code and keep getting error. On Linux Centos

### ISSUE THREAD

**Issue by cbinhb** [nipy/dipy#1397]
>>> color = line_colors(streamlines
... )
/ifshome/cboyle/anaconda3/lib/python3.6/site-packages/dipy/viz/colormap.py:233: RuntimeWarning: invalid value encountered in true_divide
  orient = np.abs(orient / np.linalg.norm(orient))

After that, I get this error when trying to visualize but I'm guessing it's due to the first error above:

...     fvtk.record(r, n_frames=1, out_path='deterministic.png',
...                 size=(800, 800))
... 
libGL error: failed to load driver: swrast
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  149 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  66
  Current serial number in output stream:  67

**Comment by arokem** [comment]
Are you running on a headless machine? You might need to run this under
[XVFB](https://linux.die.net/man/1/xvfb)

**Comment by cbinhb** [comment]
Hope this doesn't sound stupid but I am working with a monitor. is that what you mean? I do connect to a Linux Centos grid which is where I created my environment and run everything. I use XQuartz for visualization with fsl, etc. tools and it works fine.

**Comment by arokem** [comment]
No - not stupid - apologies for the jargon, but yes: that is what I meant
-- a computer without a monitor.

Do I understand correctly that you are x forwarding from another machine,
on which things are running? That might still be the issue. Could you
please try running this under XVFB?

**Comment by cbinhb** [comment]
Sure. Can you give me more guidance as to how to run this "under XVFB". I
did go to the link but still not quite sure.

**Comment by cbinhb** [comment]
I did type XVFB at my Unix prompt and this is what I get (and it is now
"hanging"):

_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be
created.

Initializing built-in extension Generic Event Extension

Initializing built-in extension SHAPE

Initializing built-in extension MIT-SHM

Initializing built-in extension XInputExtension

Initializing built-in extension XTEST

Initializing built-in extension BIG-REQUESTS

Initializing built-in extension SYNC

Initializing built-in extension XKEYBOARD

Initializing built-in extension XC-MISC

Initializing built-in extension SECURITY

Initializing built-in extension XINERAMA

Initializing built-in extension XFIXES

Initializing built-in extension RENDER

Initializing built-in extension RANDR

Initializing built-in extension COMPOSITE

Initializing built-in extension DAMAGE

Initializing built-in extension MIT-SCREEN-SAVER

Initializing built-in extension DOUBLE-BUFFER

Initializing built-in extension RECORD

Initializing built-in extension DPMS

Initializing built-in extension Present

Initializing built-in extension X-Resource

Initializing built-in extension XVideo

Initializing built-in extension XVideo-MotionCompensation

Initializing built-in extension SELinux

Initializing built-in extension GLX

The XKEYBOARD keymap compiler (xkbcomp) reports:

> Internal error:   Could not resolve keysym XF86AudioMicMute

Errors from xkbcomp are not fatal to the X server

**Comment by cbinhb** [comment]
I just spoke to a colleague and the visualization works fine on our local
machines so to your point it may be the 'headless' issue. Just thought I
would try but if it gets too complicated I can always revert to that.

**Comment by arokem** [comment]
Strangely enough, the best documentation I could find about XVFB is the
wikipedia page: https://en.wikipedia.org/wiki/Xvfb

It works on most variants of linux. In our testing, we use the python
xvfbwrapper: https://pypi.python.org/pypi/xvfbwrapper/0.2.9

**Comment by cbinhb** [comment]
Okay thank you.  I will try using the Python wrapper and see if that works.

**Comment by arokem** [comment]
I'll close this for now, but feel free to reopen if you run into further issues!

**Comment by cbinhb** [comment]
Hi Ariel -

Thanks again for your responsiveness and help. On another note, it appears
that my good friend and mentor Jack Van Horn is coming to speak for your
institute soon. Small world!

**Comment by cbinhb** [comment]
Hi Ariel. Still having troubles with this. I  was able to find a way around it with the tracks but now trying to visualize my response function per your CSD reconstruction steps and can't. I tried using the xvfbwrapper by using the simple example from wikipedia and putting the begin and end around the code using fvtk. Then I get this error message (which I sent to our internal support team to see if they could help):

ERROR: In ../Rendering/OpenGL2/vtkOpenGLRenderWindow.cxx, line 828
vtkXOpenGLRenderWindow (0x1f05200): GL version 2.1 with the gpu_shader4 extension is not supported by your graphics driver but is required for the new OpenGL rendering backend. Please update your OpenGL driver. If you are using Mesa please make sure you have version 10.6.5 or later and make sure your driver in Mesa supports OpenGL 3.2.

Segmentation fault (core dumped)

**Comment by cbinhb** [comment]
Hey Ariel.

I tried to re-open this issue as you suggested but it seems that I'm unable
to when someone else has closed it. I wrote more on the issue but not sure
if you've seen it since it's still labeled "closed". Still trying to
resolve. Please let me know if you can help.

Thank you.
Christina

ps worked with Julio some who suggested trying on older version, 2.7. I did
that but still getting same error. I also tried it on PC instead of MAC and
same error there as well.

**Comment by arokem** [comment]
Hi Christina, 

If I understand the situation correctly, it seems that you are using an older driver for your graphics card. I would think that your support team should be able to fix that. Let us know how that goes. I will reopen the issue for now, so we can make sure to loop back.

**Comment by cbinhb** [comment]
Thanks Ariel. I'm waiting on IT support now and yes, I'm hoping they will
be the one who can resolve this problem. Stay tuned.

**Comment by skoudoro** [comment]
Hi @cbinhb, 

Do you still have your error? 

If yes, you need to update `opengl` version. you need at least `opengl 3.2`. I got this error and I fixed it with this update. 

Can I close this issue?

**Comment by skoudoro** [comment]
Closing for now, feel free to reopen it.
