### ISSUE TITLE
New test errors on Python 3 Travis bots

### ISSUE THREAD

**Issue by arokem** [nipy/dipy#1399]
We're now seeing this across several PRs. 

```
======================================================================
ERROR: dipy.reconst.tests.test_dti.test_mask
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/nipy/dipy/venv/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/build/nipy/dipy/venv/lib/python3.4/site-packages/dipy/reconst/tests/test_dti.py", line 520, in test_mask
    assert_almost_equal(dtifit_w_mask.S0_hat[0, 0, 0], dtifit.S0_hat[0, 0, 0])
  File "/opt/python/3.4.6/lib/python3.4/unittest/case.py", line 841, in assertAlmostEqual
    if round(abs(second-first), places) == 0:
TypeError: type numpy.ndarray doesn't define __round__ method

```

Let's keep discussions about it here, so that we can all debug it together. 

Is anyone already looking into this? @skoudoro ?

**Comment by arokem** [comment]
Googling for this, I'm a bit mystified. This seems to have been discussed a while back: 

http://thread.gmane.org/gmane.comp.python.numeric.general/37179

But I imagine it must've been fixed since.

**Comment by aarya22** [comment]
Maybe use np.round instead of round? 

https://stackoverflow.com/questions/41319292/error-typeerror-type-numpy-ndarray-doesnt-define-round-method

**Comment by arokem** [comment]
To answer @aarya22's question over on #1395, the issue is that we don't have control of this rounding operation, because it is happening inside of the assertion, that we are getting from numpy. So, we can't change the way `round` is called.

**Comment by aarya22** [comment]
Ah I see its in the unittest, not in our code.

**Comment by aarya22** [comment]
I came across this from the folks over at pyTorch, maybe something is being skipped in Travis?

https://github.com/pytorch/pytorch/issues/4260

**Comment by skoudoro** [comment]
no clue for the moment, still investigating and it starts to make me crazy.

Trusty image change on Travis as you can see [here](https://blog.travis-ci.com/2017-12-12-new-trusty-images-q4-launch) and our error appear almost at the same time. I'm still not sure if there is a link between this 2 events.

**Comment by skoudoro** [comment]
Can you use the previous Trusty image on your last PR @arokem ?

**Comment by arokem** [comment]
Oh yeah - check it out. Here it only happens with the pre-release version: 

https://travis-ci.org/nipy/dipy/jobs/323884050

And now, boom! So it definitely has to do with the 1.14 release of numpy (3 days ago...).

**Comment by arokem** [comment]
Take a look at #1400: maybe that fixes it?
