### ISSUE TITLE
[Question] rint() or round()

### ISSUE THREAD

**Issue by nilgoyette** [nipy/dipy#1402]
Any tracking experts can help me but this is mostly a question for @matthew-brett and @omarocegueda I opened this issue because they are not active on gitter.

My original question was: why do you use `rint` instead of `round`? I thought there was a mathematical or anatomical advantage but I couldn't guess what it was. At 0.5, `rint` prefers the left voxel and `round` prefers the right voxel. Both are "wrong", or equally right.

@matthew-brett told me that there's only a technical advantage: it was simpler to code. Can you confirm this? There's no other good reason to do this?

My real question is more: will my results be equally **valid** if I change `rint` to `round`?

**Comment by matthew-brett** [comment]
Chuck Harris replied that numpy sets the FPU to do round-to-even for rint as well, so I think that means that rint and round are interchangeable for our purposes.  I mean, rint and round will give the same answers.

**Comment by nilgoyette** [comment]
Thank you @matthew-brett! Thanks to your investigation, we were able to take a well-informed decision here at my work.
