### ISSUE TITLE
Avoid promoting jet color map in examples

### ISSUE THREAD

**Issue by dmreagan** [nipy/dipy#1403]
## Description
When #1347 is merged, several examples will explicitly use the jet color map. Jet and other rainbow color maps are widely disliked in the visualization community, and in recent years have slowly been replaced as defaults in many libraries and tools. `odf_slicer` already defaults to matplotlib's plasma rather than jet. The examples should be updated to reflect that. 

## Relevant examples include:
* reconst_csd.py
* reconst_dsid.py
* reconst_mapmri.py
* reconst_shore.py
* sfm_reconst.py
* simulate_multi_tensor.py

**Comment by arokem** [comment]
Agreed. This has come up previously here: https://github.com/nipy/dipy/pull/1143#discussion_r86406380
