### ISSUE TITLE
Error using CSD model on data 

### ISSUE THREAD

**Issue by cbinhb** [nipy/dipy#1405]
A bit new to using DiPy with fibertracking but keep getting this error when trying to use the CSD model on my data. Any clues as to what might be wrong? 

/ifshome/cboyle/anaconda3/lib/python3.6/site-packages/dipy/reconst/csdeconv.py:130: UserWarning: Number of parameters required for the fit are more than the actual data points
  warnings.warn(msg, UserWarning)

**Comment by arokem** [comment]
How many directions of measurements do you have in your data?

What are you using as `sh_order` (the default value is 8).

 This warning typically arises when you are trying to fit the model with
the `sh_order` set too high relative to the number of measurements in your
data. For example, I believe using the default value requires at least 45
directions of measurements.

**Comment by cbinhb** [comment]
Actually I think it was causing a problem when I used this line first (from the Dipy examples for CSD to calibrate response/ratio etc) and in turn used "response" in my csd_fit line. 

response, ratio = auto_response(gtab, data, roi_radius=10, fa_thr=0.7)

It's indicating the "parameters" or arguments for the function are too many correct? So took "response" out of my CSD equation. Does this make sense? 

You did give me some information I need with regard to sh_order since I wasn't sure what that was. How do you specify the default since I do have 45 (HARDI) directions?

**Comment by cbinhb** [comment]
it does give me error saying sh_order must be an even number when I try 45. Maybe it's 46?

**Comment by cbinhb** [comment]
The documentation is a bit confusing.

**Comment by cbinhb** [comment]
oops maybe you were right - getting the error again. My data has 46 directions, what should my csd_model equation have as parameters?

**Comment by cbinhb** [comment]
ok! reduced sh_order to 4 and it worked. I obviously need to figure out what SH number should be but for now I'm good. Thank you!

**Comment by arokem** [comment]
I would use 4 or 6. Given you have 46 directions, 8 is too much.

I'll close this for now, but feel free to reopen if you run into more
related issues.

**Comment by cbinhb** [comment]
Thank you!
