### ISSUE TITLE
window.record() resolution limit

### ISSUE THREAD

**Issue by dmreagan** [nipy/dipy#1420]
## Description
`window.record()` can be used to save a render to a PNG image. If you set the `size` to be higher than your monitor size, the resulting image will be capped to just under your monitor's resolution. For example, if you set `size=(5000, 5000)`, but your monitor's resolution is (1920, 1080), the image width will end up being something like 1916 pixels. 

## Way to reproduce
Run any viz example that saves a render with `window.record()`, but change the `size` to be very high. Tested on Windows and Mac with VTK 7.

**Comment by ShreyasFadnavis** [comment]
Can you review my pull request for this? #1453

**Comment by dmreagan** [comment]
@ShreyasFadnavis  and @karandeepSJ report that they had no trouble with large resolutions on their systems.  Can you both report which OS, Python, and VTK versions you are using to get these successful results?

**Comment by ShreyasFadnavis** [comment]
@dmreagan I tested this on both Windows 10 and Ubuntu 16.04. 
Python Version: 3.6.4
VTK Version: 7.1.1

**Comment by karandeepSJ** [comment]
Ubuntu 16.04
Python Version: 3.5.2
VTK Version: 8.1.0

**Comment by thechargedneutron** [comment]
@dmreagan  Is this issue on Ubuntu as well? Upon changing the size to (6000, 6000) I got a file with a size of (6000, 6000).

**Comment by thechargedneutron** [comment]
@skoudoro  very nicely figured the problem. @dmreagan  I have added a patch in my branch [here](https://github.com/thechargedneutron/dipy/tree/window_resolution). Can you please verify if this is working fine since this issue is not there on Ubuntu I guess.

**Comment by skoudoro** [comment]
This issue was moved to fury-gl/fury#13
