### ISSUE TITLE
DOC/RF - update/standardize tracking examples 

### ISSUE THREAD

**Issue by gabknight** [nipy/dipy#1432]
Some idea to ease the introduction to the various tractography algorihtms/examples

- Standardize tracking example names starting with `tracking_`.
- Add figures to all examples (e.g. probabilistic_fiber_tracking.py has none)
- Uniformize the way streamlines are generated, saved and visualised e.g.:
```
pft_streamline_generator = ParticleFilteringTracking(dg,
                                                     cmc_classifier,
                                                     seeds,
                                                     affine,
                                                     max_cross=1,
                                                     step_size=step_size,
                                                     maxlen=1000,
                                                     pft_back_tracking_dist=2,
                                                     pft_front_tracking_dist=1,
                                                     particle_count=15,
                                                     return_all=False)
streamlines = Streamlines(pft_streamline_generator)
save_trk("pft_streamline.trk", streamlines, affine, shape)


renderer.clear()
renderer.add(actor.line(streamlines, line_colors(streamlines)))
window.record(renderer, out_path='pft_streamlines.png', size=(600, 600))

if interactive:
    window.show(renderer)

```

Current tracking examples:
- :ref:`example_introduction_to_basic_tracking`
- :ref:`example_probabilistic_fiber_tracking`
- :ref:`example_deterministic_fiber_tracking`
- :ref:`example_tracking_tissue_classifier`
- :ref:`example_particle_filtering_fiber_tracking`
- :ref:`example_sfm_tracking`

**Comment by skoudoro** [comment]
great ideas :-)

> Uniformize the way streamlines are generated, saved and visualised e.g.:

I think this point is done on  #1379. Could you have a look? I can correct this.

**Comment by jhlegarreta** [comment]
If Cython is not needed (still having issues compiling files) and once #1379 merged, I can propose a patch set to address the rest of the issues.

**Comment by gabknight** [comment]
Ok! No cython is needed for this. Let's wait for #1379 and #1431 to be merged.
