### ISSUE TITLE
New version of h5py messing with us?

### ISSUE THREAD

**Issue by arokem** [nipy/dipy#1433]
See: https://travis-ci.org/arokem/dipy/jobs/341509073#L600

Does anyone understand where that hash is stored?

**Comment by skoudoro** [comment]
The SHA of the new version of h5py seems to be ok [here](https://travis-ci.org/arokem/dipy/jobs/341509073#L559)
but it failed when `cvxpy` try to get its dependencies. I do not find `cvxpy` on the PRE-WHEELS server.

Can it be a conflicting reason?  any idea @matthew-brett ?

**Comment by skoudoro** [comment]
This error disappeared @arokem. I still do not understand what happens, but it is not anymore a problem.

#1435 appears in place of this one :-)

**Comment by skoudoro** [comment]
Can we close this issue @arokem?

**Comment by arokem** [comment]
Yes.
