### ISSUE TITLE
Sliders in examples don't react properly to clicks

### ISSUE THREAD

**Issue by dmreagan** [nipy/dipy#1454]
## Description
Some viz examples use `LineSlider2D` and `DiskSlider2D` to change properties of actors in the scene. The sliders work correctly if you drag the handle. But if you click directly on the path, the value of the slider changes without updating the corresponding actor. 

## Way to reproduce
Run an example like *viz_ui.py* in interactive mode. Click directly on the slider path instead of dragging the handle.

**Comment by skoudoro** [comment]
done in #1457, closing
