### ISSUE TITLE
DiskSlider does not rotate actor in opposite direction

### ISSUE THREAD

**Issue by karandeepSJ** [nipy/dipy#1458]
## Description
Some viz examples use 'DiskSlider2D' to rotate actors. The slider rotates the actor in a single direction, irrespective of whether you slide clockwise or counter-clockwise.

## Way to reproduce
Run an example like _viz_ui.py_ in interactive mode. Click on the rotation slider and move your mouse in clockwise and counter-clockwise directions.

**Comment by skoudoro** [comment]
fix by #1460. closing
