### ISSUE TITLE
Logo/banner on README not the correct one!

### ISSUE THREAD

**Issue by Garyfallidis** [nipy/dipy#1462]
Logo on readme not the correct one @jhlegarreta 
Just see #1305 
I send you a good quality version in your email.
Also available here
https://elef.soic.indiana.edu/dipy/static/images/dipy-logo.png

Thanks!

**Comment by jhlegarreta** [comment]
@Garyfallidis @skoudoro Sorry folks. I also received the email. Thanks.

PR #1464 hopefully fixes the issue. Note that the size will be that of the original image. If this is too large, let me know the desired size.
