### ISSUE TITLE
Error on "from dipy.core.gradients import gradient_table"

### ISSUE THREAD

**Issue by paultimothymooney** [nipy/dipy#1467]
When I run the following code 

`from dipy.core.gradients import gradient_table`

I get the following error message

`ImportError: dlopen: cannot load any more object with static TLS`

**Comment by skoudoro** [comment]
Hi @paultimothymooney, It sounds like a system configuration error rather than a bug. 

Can you tell us more about your environment? (python version, OS, Dipy version, Anaconda or pip?  , etc). What is the last installed library? (maybe dll conflict).
