### ISSUE TITLE
Uploading Windows wheels

### ISSUE THREAD

**Issue by matthew-brett** [nipy/dipy#1473]
I've now built 0.13.0 wheels for all versions of Windows we support, over at:

* https://ci.appveyor.com/project/matthew-brett/dipy-wheels

with driving repo at:

* https://github.com/MacPython/dipy-wheels

There's a single test failure for Python 3.6, 32-bit - described at #1472 .  I suppose it's benign?  It looks like it's a numpy issue rather than a Dipy one.  So, for that wheel, I just temporarily skipped the tests before upload.

Any objection to pushing up the built wheels?

**Comment by arokem** [comment]
Seems fine to me!

**Comment by skoudoro** [comment]
No objection 👍, Thank you!

**Comment by matthew-brett** [comment]
Done.
