### ISSUE TITLE
Streamtube visualization problem with vtk 8.1

### ISSUE THREAD

**Issue by jimcost** [nipy/dipy#1490]
## Description
I am in the midst of using nibabel and dipy to help run/visualize post-processing analyses. I am working through the ['Tractography...' ](http://nipy.org/dipy/examples_built/segment_quickbundles.html#example-segment-quickbundles) example and the code fails on 

`ren = fvtk.ren()`
`ren.SetBackground(1, 1, 1)`
`fvtk.add(ren, fvtk.streamtube(streamlines, fvtk.colors.white))`
`fvtk.record(ren, n_frames=1, out_path='fornix_initial.png', size=(600, 600))`

> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> <ipython-input-6-4641ae68e053> in <module>()
>       1 ren = fvtk.ren()
>       2 ren.SetBackground(1, 1, 1)
> ----> 3 fvtk.add(ren, fvtk.streamtube(streamlines, fvtk.colors.white))
>       4 fvtk.record(ren, n_frames=1, out_path='fornix_initial.png', size=(600, 600))
>       5 
> 
> ~/anaconda3/lib/python3.6/site-packages/dipy/viz/actor.py in streamtube(lines, colors, opacity, linewidth, tube_sides, lod, lod_points, lod_points_size, spline_subdiv, lookup_colormap)
>     333     poly_mapper.SetScalarModeToUsePointFieldData()
>     334     poly_mapper.SelectColorArray("Colors")
> --> 335     poly_mapper.GlobalImmediateModeRenderingOn()
>     336     poly_mapper.Update()
>     337 
> 
> AttributeError: 'vtkRenderingOpenGL2Python.vtkOpenGLPolyDataMapper' object has no attribute 'GlobalImmediateModeRenderingOn'

## Way to reproduce
*OS:*
Darwin-17.4.0-x86_64-i386-64bit
*Python:*
3.6.3 |Anaconda, Inc.| (default, Oct  6 2017, 12:04:38) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
*dipy:*
0.13.0
*Numpy:*
1.13.3
*Scipy:*
0.19.1
*Nibabel:*
2.2.1
*H5PY:*
2.7.0
*CVXPY:*
0.4.11
*VTK:*
8.1.0

**Comment by jimcost** [comment]
I commented out like 335 in 'actor.py' and the code executes. However, the color scheme looks funky.

![fornix_clusters](https://user-images.githubusercontent.com/6710629/38117389-e43246d2-3371-11e8-8923-4becd002d3f5.png)

**Comment by dmreagan** [comment]
I've just discovered the same issue with `GlobalImmediateModeRenderingOn`. [It seems they removed it in VTK 8.1](https://www.vtk.org/Wiki/VTK/API_Changes_8_0_1_to_8_1_0). Perhaps it isn't safe to remove if you are seeing strange results without it. You could try downgrading to an older VTK until we have it worked out.

**Comment by dmreagan** [comment]
You can see similar behavior in the *viz_bundles.py* example if you change the lines to streamtubes. 

Here it is with VTK 7.1.1:
![bundle1_tubes vtk7](https://user-images.githubusercontent.com/6951528/38157421-bebb7250-3454-11e8-83ab-5b70cdc1b05d.png)

and here it is with VTK 8.1:
![bundle1_tubes_vtk8](https://user-images.githubusercontent.com/6951528/38157426-c89dd218-3454-11e8-8fbd-c116aceeac8d.png)

**Comment by Garyfallidis** [comment]
@jimcost thank you for reporting this. Please change the title to "Streamtube visualization problem with vtk 8.1"

**Comment by jimcost** [comment]
No problemo, I appreciate the response. Shall I leave the post open?

**Comment by dmreagan** [comment]
Yes, leave it open. I'll take a deeper look at this issue when I'm able.

**Comment by jimcost** [comment]
Man, I have had no luck reverting to an earlier VTK version! I gotta give it up, or I'll get zero work done today. I'll stick to the commented hack for now.
