### ISSUE TITLE
Updating streamlines API in streamlinear.py

### ISSUE THREAD

**Issue by Garyfallidis** [nipy/dipy#1500]
This a note to myself to update line 901 of streamlinear.py with the following masking trick using the new Streamlines API.

Here is an example of what needs to be done rather than using list comprehension.

```
import numpy as np
from dipy.tracking.streamline import Streamlines
s = Streamlines()
initial = Streamlines([np.randon.rand(5, 3), np.random.rand(2, 3), np.ones((5, 3))])
initial = Streamlines([np.random.rand(5, 3), np.random.rand(2, 3), np.ones((5, 3))])
new = initial[[True, False, True]]
```

**Comment by skoudoro** [comment]
This issue is fixed, there is no more list comprehension in `streamlinear.py`.

Closing
