### ISSUE TITLE
Mathematical expressions are not rendered correctly in reference page

### ISSUE THREAD

**Issue by albayenes** [nipy/dipy#1507]
Hi,

In reference page http://nipy.org/dipy/reference/dipy.reconst.html mathematical expressions are not rendered correctly. To see one of them http://nipy.org/dipy/reference/dipy.reconst.html#mean-kurtosis

**Comment by matthew-brett** [comment]
:) oops.

**Comment by matthew-brett** [comment]
That'll teach me not to dive in and fix something straightaway ...

**Comment by grubdragon** [comment]
Hey, can I take this up?

**Comment by skoudoro** [comment]
Hi @grubdragon, look at #1508,  it seems to be already done

**Comment by grubdragon** [comment]
Ahh okay @skoudoro

**Comment by grubdragon** [comment]
Ah okay @skoudoro
Could you suggest me an issue to get started?

**Comment by skoudoro** [comment]
Thanks for pointing that @albayenes. #1508 merge and doc updated. it should be good now. Closing

**Comment by skoudoro** [comment]
@grubdragon, there is always something to improve in the documentation or a tutorial to create.  Feel free to start with that.
