### ISSUE TITLE
Scipy stopped supporting scipy.misc.imread

### ISSUE THREAD

**Issue by Garyfallidis** [nipy/dipy#1519]
With the latest scipy version 
```
from scipy.misc import imread
```
is not available anymore.

In their website they suggest using
```
from imageio import imread
```
However vtk does provide some png readers too. A note here that we were using imread only in dipy.viz. We need to decide for a replacement asap. This change will affect any DIPY users who try to use DIPY's visualization with latest scipy version.

**Comment by arokem** [comment]
IIUC, this is the only place that we use this function: 

https://github.com/nipy/dipy/blob/master/dipy/viz/window.py#L898

Is that correct?

Could we use the skimage equivalent? 

http://scikit-image.org/docs/dev/api/skimage.io.html#skimage.io.imread

I think that it's already a dependency for the otsu segmentation, right? If not, I wouldn't mind adding it as a dependency.

**Comment by Garyfallidis** [comment]
I have a fix for this in PR https://github.com/nipy/dipy/pull/1528
VTK provides readers for PNG files. No need for other dependencies.

**Comment by arokem** [comment]
Yeah - looks great. I guess we can close this when that PR is in.

**Comment by Garyfallidis** [comment]
Yep, yep!

**Comment by Garyfallidis** [comment]
:)

**Comment by skoudoro** [comment]
fix by #1528, closing
