### ISSUE TITLE
New version of CVXPY changes API

### ISSUE THREAD

**Issue by arokem** [nipy/dipy#1527]
See CI failures here: https://travis-ci.org/nipy/dipy/builds/381032191

I think this is because of a new release of CVXPY that changed their API to disallow "strict equality" in defining constraints on optimization. 

Any thoughts @rutgerfick ?

**Comment by arokem** [comment]
@matthew-brett : this issue could be related to difficulties that the CVXPY has building the manylinux wheels for their software. I believe you are a wheel-building maven. Would you mind taking a look at the discussion about this on https://github.com/cvxgrp/cvxpy/issues/503 ? 

Thanks!

**Comment by rutgerfick** [comment]
Hi @arokem,
Sorry for the late reply.
I'm afraid I'm not sure what the issue is at this time. I'll try to take a better look in the next weeks.
Best,
Rutger

**Comment by arokem** [comment]
I believe this is resolved through #1542
