### ISSUE TITLE
Actor.label not working anymore

### ISSUE THREAD

**Issue by wasserth** [nipy/dipy#1551]
## Description
When running the minimal example from the Actor.label documentation is results in a black window without any text.

## Way to reproduce
```
from dipy.viz import window, actor
ren = window.Renderer()
l = actor.label(text='Hello')
ren.add(l)
window.show(ren)
```

**Comment by Garyfallidis** [comment]
Makes sense @wasserth they were changes from vtk 5 to 6 and beyond. And it seems we missed that. Can you make a PR with the change?
