### ISSUE TITLE
Should we retire our Python 3.5 travis builds?

### ISSUE THREAD

**Issue by arokem** [nipy/dipy#1562]
Any reason to keep these around?

**Comment by matthew-brett** [comment]
Are you planning to drop support for Python 3.5?

**Comment by skoudoro** [comment]
> Any reason to keep these around?

- By default, Conda-Smithy generates packages for Python 2.7, 3.5 and 3.6. 
- It seems we still have some download from python3.5 [on all platforms](https://anaconda.org/conda-forge/dipy/files).

Otherwise, I do not see other reason...

**Comment by matthew-brett** [comment]
I would have thought Python 2.7, 3.5 and 3.6 was a reasonable list.  Dropping 3.5 seems a bit premature, even when 3.7 comes out.  Don't all your dependencies still support 3.5?

**Comment by arokem** [comment]
OK - I guess that's a "no"! Thanks.
