### ISSUE TITLE
viz.ui.ListBoxItem2D text overflow

### ISSUE THREAD

**Issue by karandeepSJ** [nipy/dipy#1569]
## Description
If the text provided to a `ListBoxItem2D` object is longer than its width, then the text overflows out of the background and out of the list-box. It should go upto the width and replace the remaining characters by a "..."

## Way to reproduce
```
import dipy.viz.ui as ui
import dipy.viz.window as window
values = ['abcdefghijklmnopqrstuvwxyz']
listbox = ui.ListBox2D(values=values, size=(300, 300))
sm=window.ShowManager(size=(600,600))
sm.ren.add(listbox)
sm.start()
```

**Comment by skoudoro** [comment]
This issue was moved to fury-gl/fury#15
