### ISSUE TITLE
SF threshold in PMF is not relative

### ISSUE THREAD

**Issue by frheault** [nipy/dipy#1582]
When using the LocalTracking a _ProbabilisticDirectionGetter_ needs to be provided, _ProbabilisticDirectionGetter_ requires a _relative_peak_threshold_. Which is supposed to ensure that a linear scaling of FODf amplitude does not affect the tracking.

Example:
Same datasets, artificially scaled FODf (factor 0.1, 1, 10) should produced identical tracking. This is not the case. The results are that tracking using the factor 0.1 results in 0 streamlines and a large difference is observable between the local tracking using the factor 1 and the factor 10.

https://drive.google.com/open?id=1j-V6xx4Y18e1B_LsKgdGT0t8qdUYkVCz
@gabknight is the sfthreshold aimed to cover this situation ?

**Comment by skoudoro** [comment]
fix by #1583, closing
