### ISSUE TITLE
Add a random seed for reproducibility

### ISSUE THREAD

**Issue by GuillaumeTh** [nipy/dipy#1585]
I checked the code of _pft and I think we must to add a random seed to be reproducible.

Here the links of the random issue:
https://github.com/nipy/dipy/blob/9994c2a83f49a3e909b569051326b58f04a14bb2/dipy/tracking/local/localtrack.pyx#L479
https://github.com/nipy/dipy/blob/9994c2a83f49a3e909b569051326b58f04a14bb2/dipy/tracking/local/localtrack.pyx#L499

I think we can just add `random.seed(random_seed_number)` in pft_tracker.

**Comment by arokem** [comment]
I think that if they want reproducible results, users should fix the random in the script that calls this

**Comment by arokem** [comment]
Sorry: should be "fix the random *seed*"
