### ISSUE TITLE
viz.ui.FileMenu2D

### ISSUE THREAD

**Issue by MarcCote** [nipy/dipy#1618]
## Description
The `FileMenu2D` class, introduced in #1592, could be refactored to avoid reimplementing scrolling and selection logic that are already done in `ListBox2D` component. Also, the `scroll_callback` is responsible for updating the colors of the text in the slots which seems weird. It would be better if the scroll only tells which slots should be displayed on the screen, then let the slots decides how to render themselves.

## Related comments
https://github.com/nipy/dipy/pull/1570#issuecomment-397904982
https://github.com/nipy/dipy/pull/1570#issuecomment-397906003

**Comment by skoudoro** [comment]
This issue was moved to fury-gl/fury#16
