### ISSUE TITLE
3.7 wheels

### ISSUE THREAD

**Issue by effigies** [nipy/dipy#1620]
## Description

Over at nipy/nipype#2682, I was adding Python 3.7 to the Travis test matrix, and ran up against the issue that no dipy wheels are available for 3.7, and `pip install dipy` was failing to build in that environment.

Is it possible to get 3.7 wheels pushed to PyPI for the latest release of dipy? I don't have any notion how difficult this would be, so apologies if it's too large a request.

**Comment by skoudoro** [comment]
Thanks for this info, we will look at it and let you know ASAP.

**Comment by matthew-brett** [comment]
They seemed to build OK by just adding 3.7 to the matrix entries of the dipy-wheels repo:

* https://travis-ci.org/MacPython/dipy-wheels
* https://ci.appveyor.com/project/matthew-brett/dipy-wheels

although the Python 3.6 builds failed on Appveyor for some reason.

I've uploaded the wheels.  Chris - do they work for you now?

**Comment by effigies** [comment]
Yup, looks like this works.

https://travis-ci.org/nipy/nipype/jobs/416415201

Thanks Matthew!
