### ISSUE TITLE
Link broken on website

### ISSUE THREAD

**Issue by kesshijordan** [nipy/dipy#1632]
## Description
The Module Index link is broken
http://nipy.org/dipy/py-modindex.html

404
File not found

The site configured at this address does not contain the requested file.

If this is your site, make sure that the filename case matches the URL.
For root URLs (like http://example.com/) you must provide an index.html file.

## Way to reproduce
Go to:
http://nipy.org/dipy/documentation.html#documentation
Scroll to bottom and click "Module Index"

**Comment by skoudoro** [comment]
good catch, Thank you @kesshijordan

**Comment by skoudoro** [comment]
Note: Following [this](https://github.com/nipy/dipy/blob/master/doc/conf.py#L179), this link should not appear. So we have to remove `modindex` from `index.rst` or find a way to link it to API reference (via `sys.path.append(0, os.path.abspath('dipy')` in `conf.py`

**Comment by ShreyasFadnavis** [comment]
@skoudoro is there a PR for this yet? If not, I can go ahead with this..

**Comment by arokem** [comment]
Yes. Works for me. Might have been fixed on the recent release. Closing.
