### ISSUE TITLE
Blank png saved/displayed on documentation

### ISSUE THREAD

**Issue by kesshijordan** [nipy/dipy#1633]
## Description
Example rendering is blank for life_candidates.png
http://nipy.org/dipy/examples_built/linear_fascicle_evaluation.html#example-linear-fascicle-evaluation

## Way to reproduce
- go to link, above
- I tried running the example, and if you set interactive=True the render comes up in the interactive window but the saved .png is still blank

**Comment by jhlegarreta** [comment]
I've been able to reproduce the issue. It looks like the data underlying the actors is correctly computed, since at @kesshijordan  says, if the interactive mode is on, the figure does get displayed. I may have another look in the coming days if I find the time.

**Comment by kesshijordan** [comment]
Thanks for fixing this, @jhlegarreta !
