### ISSUE TITLE
Use logging instead of print statements

### ISSUE THREAD

**Issue by arokem** [nipy/dipy#1634]
For example in RecoBundles: 

https://github.com/nipy/dipy/blob/master/dipy/segment/bundles.py#L162

Currently controlled through a "verbose" attribute, but would be good to control this through the standard Python mechanism: https://docs.python.org/3/library/logging.html

**Comment by Garyfallidis** [comment]
I disagree with @arokem. This is the class in Python. Logging is called at the workflow level. I do not think that logging needs to be enabled at this level. We have never done this before.

**Comment by jchoude** [comment]
Just to make sure I understand your point @Garyfallidis , do you mean there should be no prints / logging at all in the class, or that it shouldn't go through the python logging facilities?

I personnally prefer, when using logging (no matter where in the code) to use the python logging facilities. It makes it easier to redirect specific types of outputs. For example, when running on a cluster, we might want to redirect all messages to a text file instead of the terminal.

**Comment by Garyfallidis** [comment]
Nope. Here is what I mean.

In the main API we can and should continue using print statements.
When calling workflows from cmd then logging is enabled and the prints from the core API are saved in the log file as the other logging texts.

So, we shouldn't change the standard prints to logging in the entire API. Logging only in the workflows.
@jchoude and @arokem does this explanation clarify my point?

**Comment by jchoude** [comment]
It does clarify your point. 

I personnally prefer the logging solution because it is cleaner and offers more control (eg: splitting warnings, info and debug messages in different files in 3 lines of code), but I am not a main user of workflows, so I guess that won't bother me much.

**Comment by arokem** [comment]
At the very least, we should fence every print statement with a `verbose`
flag. For example in the data module, we have print statements that the
user can't control. For example:
https://github.com/nipy/dipy/blob/master/dipy/data/fetcher.py#L617-L627.
But if we do that, we may as well let users control verbosity globally and
use the logging module...

**Comment by Garyfallidis** [comment]
Okay, this is a larger discussion not related to the specific PR. 
I still think that simple print is easier to use in the main API - logging needs pretty good understanding and experience. 
Also global logging means that if you get that on then you may start receiving many more messages that you really want to see. Imaging getting stdouts from every module load in a script. Anyway... this is food for thought. I think not the priority for this release but we can keep this thread open for ideas and discussion.

**Comment by arokem** [comment]
That's right. Not related to any particular PR. That's why I posted it as a
separate issue, not a comment on the PR.

**Comment by skoudoro** [comment]
Since https://github.com/nipy/dipy/pull/1862 has been merged, should we keep this issue open?

**Comment by arokem** [comment]
Closed by #1862
