### ISSUE TITLE
Advice for saving results from MAPMRI

### ISSUE THREAD

**Issue by mattcieslak** [nipy/dipy#1637]
Hello,

I was looking into the pam5 format and was wondering if there is an example of using it to save the results from a 3dSHORE or MAPMRI reconstruction. Do any MAPMRI or 3dSHORE users have any recommendations on storing data?

Thanks!

**Comment by skoudoro** [comment]
Hi @mattcieslak, 

Is my answer [here](https://github.com/nipy/dipy/pull/1641#issuecomment-422217158) enough for your question?

It would be good if you can create a short tutorial for the other users 😄 .

**Comment by Garyfallidis** [comment]
Hi @mattcieslak, pam5 is used for saving the results from peaks_from_model which can have any model that can generate ODFs (or FODs). This is used to primarily save ODFs (optional), their peaks and ODFs as spherical harmonics coefficients. To save the SHORE or MAPMRI models you can save directly their coefficients as Nifti images (dipy.io.image.save_nifti) and the same for their different maps/metrics. 

But the real question is what you really want to do. What is the application in mind?

**Comment by mattcieslak** [comment]
Hi @Garyfallidis, I just wanted to make sure I had all the necessary information to calculate propagator metrics and calculate ODFs after the lengthy fitting process is over. So It looks like is should just do a save_nifti on the coefficients and then re-load them in the appropriate model class and I can go about calculating ODFs and metrics?

**Comment by Garyfallidis** [comment]
Yes, you can do that @mattcieslak. Load them in a Fit class and then later calculate other metrics, including the ODF.

**Comment by arokem** [comment]
Looks like we can close this one, but feel free to reopen if you still have questions.
