### ISSUE TITLE
Local Tracking - BinaryTissueClassifier - dropping the last point

### ISSUE THREAD

**Issue by jchoude** [nipy/dipy#1661]
## Description
@gabknight This is the old classical question: should the last point of a streamline, the point that makes it finished (eg: reaching a `0` value in a Binary map), be kept or not in the tractogram?

When using `local_tracking` with a `BinaryTissueClassifier`, once a streamline exits the `True` valued voxels of the mask, a `ENDPOINT` flag is raised, the number of steps (`i` in the loop) is incremented by 1. This means that the tracker will keep the last point, even if, in fact, it is outside the mask.

I think we should probably drop that last point. Else, semantically, it doesn't make a lot of sense. Let's say I track, and then just do a endpoint filtering with the same mask, I will be missing some streamlines, since the endpoints will be outside of the mask.

@gabknight do you agree that this should be the behavior? If so, @czotti could help implementing it.

**Comment by gabknight** [comment]
@jchoude yes ok. Removing the `i += 1` in dipy/tracking/local/localtrack.pyx:189 should do the trick. Let's also remove the last point for the `INVALIDPOINT` case. 

I would do that for `local_tracker` but not for `pft_tracker`. (`BinaryTissueClassifier` cannot be used for PFT, only `ConstrainedTissueClassifier`). Removing the last point of streamlines stopping in a voxel with lower then 100% GM is not ideal. Moreover, I would rather have all streamlines extend further in the GM for connectivity analysis.  

The annoying thing with this is that PFTracking and localTracking will have different behavior when both use e.g. `CMCTissueClassifier`. I suggest clarifying what happen to the last points in the doc. What do you think?

@czotti Do you want to give it a go? The code modification is easy, but the modification will break all `localTracking` tests. :)

**Comment by jchoude** [comment]
@gabknight Thanks for that! I agree that PFTracking shouldn't be modified.

**Comment by skoudoro** [comment]
fixed by #1666. Closing this issue
