### ISSUE TITLE
CST Image in bundle extraction is not oriented well

### ISSUE THREAD

**Issue by arokem** [nipy/dipy#1673]
I think that because we are using the default output we're looking at the bundle from the superior direction, which makes it look not that great: 

![cst_l_recognized_bundle](https://user-images.githubusercontent.com/118582/49247852-305c4a00-f3cd-11e8-8c34-6670323afcf6.png)

We should look at it from a medial or lateral vantage point, which looks much better: 

<img width="655" alt="screen shot 2018-11-29 at 11 53 03 am" src="https://user-images.githubusercontent.com/118582/49247922-597cda80-f3cd-11e8-9cb1-8fd3f0178128.png">

**Comment by skoudoro** [comment]
@BramshQamar, Can you look at this issue? 

Thank you

**Comment by arokem** [comment]
Fixed in #1681
