### ISSUE TITLE
cannot import packages of dipy.viz

### ISSUE THREAD

**Issue by snapfinger** [nipy/dipy#1717]
## Description
Just found this problem exists when I use Jupyter Notebook. Python scripts work well.

`from dipy.viz import window` -> `ImportError: cannot import name window` 
`from dipy.viz import actor` -> `ImportError: cannot import name actor`
there's no problem with `import dipy.viz` 

```
ImportError                               Traceback (most recent call last)
<ipython-input-21-b18fdc2dd925> in <module>()
      4 sphere = get_sphere('symmetric724')
      5 
----> 6 from dipy.viz import window
      7 
      8 # Enables/disables interactive visualization

ImportError: cannot import name window
```

## Way to reproduce
- [x] Code example: see above
- [ ] Relevant images (if any)
- [x] Operating system and version: Darwin-17.6.0-x86_64-i386-64bit
- [x] Python version: `2.7.15 |Anaconda custom (64-bit)| (default, May  1 2018, 18:37:05)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]`
- [x] dipy version: `0.15.0`
- [x] dependency version (numpy, scipy, nibabel, h5py, cvxpy, fury)
NumPy 1.12.1
SciPy 0.19.1
Nibabel 2.3.1
H5py 2.7.1
fury 0.1.4

**Comment by snapfinger** [comment]
interestingly the issue disappeared after a reboot

**Comment by imanusita** [comment]
i hv dipy 0.16.0 version 
and i hv the same problm

**Comment by skoudoro** [comment]
Did you install FURY package @imanusita?  

To install it: `pip install fury`

**Comment by imanusita** [comment]
ya ya now it s working thnk u so much ^^

Le sam. 23 mars 2019 à 22:59, Serge Koudoro <notifications@github.com> a
écrit :

**Comment by imanusita** [comment]
now it s working thnk u ^^

**Comment by imanusita** [comment]
is there any source for dipy exept their site i want somethng more general , it s kind of hard to use only examples i need the general case , for example in median_ostu it s not clear for me (as a begginer ) to understand the arguments used , i ll be so thnkfull if u give me other sources

**Comment by skoudoro** [comment]
Hi @imanusita,

Your question is not related to this PR. Can you create a new issue or ask your question on [dipy gitter](https://gitter.im/nipy/dipy) chat, or via the mailing list. You will reach out to more people and it is easier to follow for us.

Thank you

**Comment by RosaPetit** [comment]
I have a similar problem in my case is: 

**from dipy.viz import window, actor

# Enables/disables interactive visualization
interactive = False

ren = window.Renderer()** 

I have this problem: 

**AttributeError                            Traceback (most recent call last)
Input In [24], in <cell line: 13>()
     10 # Enables/disables interactive visualization
     11 interactive = False
---> 13 ren = window.Renderer()
     15 evals = tenfit.evals[13:43, 44:74, 28:29]
     16 evecs = tenfit.evecs[13:43, 44:74, 28:29]

AttributeError: module 'fury.window' has no attribute 'Renderer**

**Comment by skoudoro** [comment]
What is your dipy version @RosaPetit ?  what is your FURY version?

pip show fury 
pip show dipy

Many chances that you just have to update your version.

see here: https://stackoverflow.com/questions/71100449/cannot-import-name-vtk-from-fury-window/71208426#71208426

**Comment by RosaPetit** [comment]
**I have a similar problem but we this:** 

from dipy.data import get_sphere
sphere = get_sphere('repulsion724')

from dipy.viz import window, actor

# Enables/disables interactive visualization
interactive = False

ren = window.Renderer()

evals = tenfit.evals[13:43, 44:74, 28:29]
evecs = tenfit.evecs[13:43, 44:74, 28:29]

**the problem:**

ttributeError: module 'fury.window' has no attribute 'Renderer'

**I already installed fury**

**Comment by RosaPetit** [comment]
I have fury version 0.80 and dipy version 1.5,  but it still doesn't work

**Comment by skoudoro** [comment]
Hi @RosaPetit,

if you have FURY 0.8.0 and DIPY 1.5.0, it means that `window.Renderer()`  does not exist anymore. It has been replaced by `window.Scene()`. 

Can you tell us where your script comes from? It seems that your script needs to be updated.

**Comment by RosaPetit** [comment]
Yes! That was the problem:

I used  "window.Scene()" instead of   "window.Renderer()" and it work perfectly

https://fury.gl/v0.3.x/release_notes/releasev0.2.0.html

I was trying to follow this example

https://dipy.org/documentation/1.0.0./examples_built/reconst_dti/#example-reconst-dti

Thanks very much for the answers!

**Comment by skoudoro** [comment]
Great!

Just make sure to use the correct version of the documentation.

So use the documentation for the 1.5.0 here: https://dipy.org/documentation/1.5.0/examples_built/reconst_dti/#example-reconst-dti

and not the one you give above for 1.0.0

> https://dipy.org/documentation/1.0.0./examples_built/reconst_dti/#example-reconst-dti

**Comment by pjsjongsung** [comment]
On a related note, I see that when I google dipy tutorials, it often doesn't show the most recent documentation.
It might be a good idea to add the link to the most recent version like scipy does.

**Comment by skoudoro** [comment]
Yes, you are right @pjsjongsung.

This is related to this issue #2379
