### ISSUE TITLE
cannot import name window

### ISSUE THREAD

**Issue by muyinglin** [nipy/dipy#1718]
I installed dipy,when I import dipy.viz,it's right,but when I "from dipy.viz import window, actor"，the error warning is "cannot import name window".

**Comment by skoudoro** [comment]
Hi @muyinglin,

Did you install Fury ? this is an optional dependency for visualisation. 

`pip install fury`

**Comment by skoudoro** [comment]
closing, If you still have this problem, Feel free to reopen it @muyinglin.

**Comment by muyinglin** [comment]
I'm sorry, but I really don't understand your meaning,could you please explain it in detail,thank you very much.

**Comment by skoudoro** [comment]
You need to install a python package named FURY.

To install this package, you need to run this command on a terminal :  `pip install fury` 

After installing this package, your problem should disappear. Let me know if it works

**Comment by muyinglin** [comment]
Ok,this worked,thank you very much.
