### ISSUE TITLE
using code style

### ISSUE THREAD

**Issue by Borda** [nipy/dipy#1721]
Hello, 
this is more-less just open question or suggestion, where you would assume to use a tool for quality check and automatic code review on code quality like [codacy](codacy.com) or [codeFactor](codeFactor.io)?

**Comment by skoudoro** [comment]
Hi @Borda,

Thank you for your suggestion. We are currently using [pep8speaks](https://github.com/OrkoHunter/pep8speaks) but it does not seem to work as expected. So I think, it is a good idea to switch tool. 

But it will be good to have other opinions

**Comment by skoudoro** [comment]
I just added Codacy. Thanks for your suggestion @Borda. Closing
