### ISSUE TITLE
Plan for dropping Python 2 support.

### ISSUE THREAD

**Issue by arokem** [nipy/dipy#1731]
## Description

[Many software projects](https://python3statement.org/) in the scientific python ecosystem are moving to require Python 3 for their usage. For example, both [numpy](https://github.com/numpy/numpy/blob/master/doc/release/1.16.0-notes.rst) and [scipy](https://github.com/scipy/scipy/blob/master/doc/release/1.2.0-notes.rst) have made their last releases to support Python 2. Though they both have plans for long-term support of Python 2 through 2020, it seems that after the end of next year, we would be on our own. 

## Proposed course of action 

I propose that we consider making our current release cycle the last to provide full support for Python 2.7. The next release cycle would then drop the Python 2 bots, but we would continue long-term support through a maintenance branch and by back-porting crucial fixes through 2020. At that point, users who want to continue using Python 2 would be on their own. Given the movements in the rest of the scientific Python ecosystem, these users would need to be particularly hardy anway. 

Thoughts?

**Comment by jchoude** [comment]
I fully approve this!

**Comment by arokem** [comment]
Just to add: one main thing we should think about here is what kind of effort LTS for Python 2 through 2020 would require, and whether it's worth it. Our conda download numbers do suggest that some users are getting it for their Python 2 installations, but we don't know whether they would just switch if we nudged them more firmly.

**Comment by skoudoro** [comment]
+1, Since we plan to bump the major version to DIPY 1.0.0 this year, I think this a good opportunity

**Comment by jchoude** [comment]
I know that I, for one, still get the Python 2 version by default, since our labs common setup uses that. We are already working on migrating the internal tools based on Python 2.7 to Python 3, so that would be one more incentive.

**Comment by arokem** [comment]
Yup. Your outfit is probably very well-equipped to deal with the
transition. We just want to make sure that we don't turn that incentive
into something that drives (especially less technically-savvy) users away.

**Comment by arokem** [comment]
@skoudoro : yes, 1.0 would be a very clean point to do this. 

Is that slated for the release after the upcoming one?

**Comment by arokem** [comment]
BTW, looks like nibabel is planning to drop support for Python 2 as early as January 2020 (https://github.com/nipy/nibabel/issues/735)

**Comment by skoudoro** [comment]
> Is that slated for the release after the upcoming one?

yes, it will be, end of June / begin July

**Comment by arokem** [comment]
Resolved  by #1775
