### ISSUE TITLE
DeprecationWarning: This function is deprecated. Please call randint(0, 10000 + 1) instead    C:\Users\ranji\Anaconda3\lib\site-packages\ipykernel_launcher.py:14: DeprecationWarning: `imsave` is deprecated! `imsave` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0. Use ``imageio.imwrite`` instead.

### ISSUE THREAD

**Issue by Ranjithavidyashankar** [nipy/dipy#1754]
batch_size = 16
sample_idx = np.random.random_integers(low=0, high=10000, size=batch_size)
r_samples = x_test_noise[sample_idx, :, :, :]
rec_samples = model.predict(x=r_samples)
fig = np.zeros(shape=(image_size*2, image_size*batch_size, 1))
r_samples = r_samples * 255
rec_samples = rec_samples * 255

for idx in range(batch_size):
    fig[:image_size, idx*image_size: (idx+1)*image_size, :] = r_samples[idx, :, :]
    fig[image_size:, idx * image_size: (idx + 1) * image_size, :] = rec_samples[idx, :, :]

fig = fig.reshape(image_size*2, image_size*batch_size)
scipy.misc.imsave('out.jpg', fig)

**Comment by skoudoro** [comment]
Hi @Ranjithavidyashankar, 

We do not use `scipy.misc.imsave` on DIPY.

Closing, feel free to reopen it with more details.
