### ISSUE TITLE
NI Learn info from sensors designed to acseptible eeg format?

### ISSUE THREAD

**Issue by josheeg** [nipy/dipy#1757]
## Description
NI Learn info from sensors designed to acseptible eeg format?

[If reporting a bug, attach the entire traceback from Python and follow the way to reproduce below]
[If proposing an enhancement/new feature, provide links to related articles, reference examples, etc.]

## Way to reproduce
[If reporting a bug, please include the following important information:]
NI Learn info from sensors designed to acseptible eeg format?
I use arduino's and have made small sensors that would send data to a virtual rs232 usb virtual com port.
Now I know there is some data on where I put the sensors to add but how would I get that data into numpy and into ni learn easy?
any reference tutorials to try to put together and fallow up here?

**Comment by arokem** [comment]
I think you have the wrong repo. If this pertains to nilearn, you might want to report it there: 

https://github.com/nilearn/nilearn
