### ISSUE TITLE
additional parameters for dipy_track_local workflow 

### ISSUE THREAD

**Issue by gabknight** [nipy/dipy#1758]
- Step size : should be a parameter controlled by the user. It is now fixed to 0.5

**Comment by skoudoro** [comment]
> Step size : should be a parameter controlled by the user. It is now fixed to 0.5

good catch, I am surprised that is not a parameter. 

> Stopping_files ...

Agree, Let's do it during the Workshop!

**Comment by gabknight** [comment]
Edited the description, split this issue in 2: see #1811

**Comment by skoudoro** [comment]
fix by #1766
