### ISSUE TITLE
Deprecation warning when running median_otsu

### ISSUE THREAD

**Issue by jjuranek** [nipy/dipy#1761]
C:\ProgramData\Anaconda3\lib\site-packages\dipy\core\histeq.py:22: VisibleDeprecationWarning: Passing `normed=True` on non-uniform bins has always been broken, and computes neither the probability density function nor the probability mass function. The result is only correct if the bins are uniform, when density=True will produce the same result anyway. The argument will be removed in a future version of numpy.

**Comment by skoudoro** [comment]
Hi @jjuranek,

Thanks for this information, we will update that soon. It seems to be a long time this parameter is deprecated.
