### ISSUE TITLE
Threshold default in QballBaseModel

### ISSUE THREAD

**Issue by scott-trinkle** [nipy/dipy#1763]
Is there a reason that `min_signal` has the default value of 1. in the `QballBaseModel` class (and possibly elsewhere)? 

The data I am working are scaled between [0, 1], so using the default parameters when reconstructing with `CsaOdfModel` results in identical ODFs at every voxel, with the first SH coefficient = .5 / sqrt(pi) and all others being around 0. Setting `min_signal = 1e-3` or so fixes the problem. 

I had to dig around a lot to find the source of the problem, I think setting a new default could save others some time, unless there is a specific reason it is set so high.

**Comment by jchoude** [comment]
Out of curiosity, is the normalization to the [0, 1] range done at data conversion time, or later on in your processing?

**Comment by scott-trinkle** [comment]
the "rawest" version of the specific dataset I'm using came off the scanner as floats in [-1.12, 1.12] (not actually [0, 1]) to my knowledge, but I didn't acquire the data myself. At this point I'm not doing any normalization myself.

**Comment by scott-trinkle** [comment]
actually, I misspoke, the raw data is 16-bit uints. The normalization to [-1.12,1.12] happened sometime during denoising, registration, etc. 

Either way: I still think setting the threshold default lower might be a good idea, I can imagine others might have the same problem in the future.

**Comment by scott-trinkle** [comment]
Looking at the code a bit more, I see that `min_signal` also defaults to 1 in `ResidualBootstrapWrapper` (also in dipy/reconst/shm.py). This class says in the documentation:

> ...We assume that the signals are
        normalized so we clip the bootsrap samples to be between `min_signal`
        and 1...

so the default is to clip to [1,1], which should probably also change.

**Comment by skoudoro** [comment]
fixed by #1772, closing
