### ISSUE TITLE
DTI metrics workflow: mask is optional, but crashes when no mask provided

### ISSUE THREAD

**Issue by jchoude** [nipy/dipy#1764]
## Description
In the `dipy_fit_dti` workflow help message, the `mask` argument is said to be optional (`default: no mask used`). However, if no mask is provided, the script crashes and says that an argument is missing.

What should be the real behavior? 
- Make the argument really optional?
- Leave it mandatory and change the help message?

I would prefer to have it optional, but I want your opinions.

@skoudoro @Garyfallidis

**Comment by arokem** [comment]
+1 for refactoring to allow this to be optional

**Comment by skoudoro** [comment]
> What should be the real behavior?

The original behavior should be mandatory. The goal was to educate and give good habits to the user instead of having a blind mask generation.

But I think, we should discuss this point. Currently, it is mandatory for all models

**Comment by jchoude** [comment]
Ok. I agree with not using a blind mask generation. However, I feel like in somes cases people might not want to use a mask.

**Comment by arokem** [comment]
I guess you can always pass a volume full of 1's, if you want to do the entire volume. But that's a bit of a kludge.

**Comment by skoudoro** [comment]
ok, maybe we can offer 2 optional parameters: `--generate-mask (bool) - default false` and `mask_file (string) default None`. If both parameters are set, priority to mask_file.

What do you think?

**Comment by jchoude** [comment]
Would the `mask_file` argument be in the optional section? If so, how does it handle having multiple masks (as for the syntax already supported for multiple dwi / bval / bvec)?
