### ISSUE TITLE
Maybe `read_*` should return full paths?

### ISSUE THREAD

**Issue by arokem** [nipy/dipy#1777]
Currently, a function like `read_stanford_hardi` will return an image object and a gradient table object. That makes it easy for us to use when we write examples, but as I've learned this week, it makes it hard for users when they try to adapt the examples to their own data, because file i/o is the first thing they'll need to do and it's not obvious how to go about it. 

What if we had `read_stanford_hardi` return file-names/full paths instead of returning the img and gtab and then we explicitly did the file i/o in the example? Maybe it would make using the examples easier?

**Comment by araikes** [comment]
As a novice DIPY users, this would be really helpful, or even just a separate tutorial called "How Do I Read In My Data."

**Comment by arokem** [comment]
Thanks for the feedback! If we can add a separate tutorial for this, that might be easier, at least as a start.

**Comment by skoudoro** [comment]
Currently, fetch_* return full path and then read_*  return the data and gtab. I think, this is the logic behind fetch_* / read_* and we shouldn't modify this part.

But I agree we should create a tutorial on "How to read my data" and make sure that all our tutorial follow this logic

**Comment by arokem** [comment]
The problem with fetch_* is that the results are a bit cryptic. Maybe we should extend get_fnames, so that it knows how to post-process the things that come out of fetch_*? 

I'm thinking of something like the the following API: 

```
data_fname, bval_fname, bvec_fname = get_fnames("stanford_hardi")
img = nib.load(data_fname)
gtab = gradient_table(bval_fname, bvec_fname)
```
Hopefully that way the handling of I/O in the examples becomes more transparent.

**Comment by skoudoro** [comment]
This makes sense to me and I really like this format. 

This implies that `get_fnames` will fetch the data, and we will not use `read_*` anymore on the tutorials (just for the tests), right?
