### ISSUE TITLE
Probabilistic Direction Getter gallery example

### ISSUE THREAD

**Issue by araikes** [nipy/dipy#1779]
## Description
The examples given in the example for getting probabilistic streamlines (http://nipy.org/dipy/examples_built/probabilistic_fiber_tracking.html#example-probabilistic-fiber-tracking) demonstrate saving the streamline_generator, not the actual streamlines. The code on the website is: 

```
from dipy.data import default_sphere

prob_dg = ProbabilisticDirectionGetter.from_shcoeff(csd_fit.shm_coeff,
                                                    max_angle=30.,
                                                    sphere=default_sphere)
streamlines_generator = LocalTracking(prob_dg, classifier, seeds, affine, step_size=.5)

save_trk("probabilistic_shm_coeff.trk", streamlines_generator, affine, labels.shape)
```

This should be (as in the Quick Start Tracking):
```
from dipy.data import default_sphere
from dipy.tracking.streamline import Streamlines

prob_dg = ProbabilisticDirectionGetter.from_shcoeff(csd_fit.shm_coeff,
                                                    max_angle=30.,
                                                    sphere=default_sphere)
streamlines_generator = LocalTracking(prob_dg, classifier, seeds, affine, step_size=.5)
streamlines = Streamlines(streamlines_generator)
save_trk("probabilistic_shm_coeff.trk", streamlines, affine, labels.shape)
```

## Way to reproduce
[If reporting a bug, please include the following important information:]
- [x ] Relevant images (if any)
Streamline generator export (open the image and zoom and you will see several small streamlines): 
![3D_View2](https://user-images.githubusercontent.com/18663624/54443297-93b08480-46fd-11e9-8686-e548abc05cf1.png)

Streamlines export as in the revised code:
![3D_View2](https://user-images.githubusercontent.com/18663624/54443320-9dd28300-46fd-11e9-8328-953b34df63ba.png)

**Comment by skoudoro** [comment]
Thanks for pointing that out @araikes! It should normally work with the `streamlines_generator` too so I will check `save_trk` function before updating the tutorial.

**Comment by gabknight** [comment]
Thanks @araikes. Saving the streamlines_generator works fine on my system. For clarity, we should always add the `Streamline(.)` in examples. I will go ahead and prepare the PR. @skoudoro do know what could have caused the issue?

**Comment by skoudoro** [comment]
No idea @gabknight. Maybe a memory error, or just a visualization problem.

I tried on Windows and Mac and I can not reproduce the problem, so hard to help...
