### ISSUE TITLE
Conversion from MRTrix SH basis to dipy

### ISSUE THREAD

**Issue by scott-trinkle** [nipy/dipy#1782]
MRtrix3 changed their SH basis moving from versions (0.2.x) to (0.3.x) ([details here](https://mrtrix.readthedocs.io/en/latest/concepts/orthonormal_sh_basis.html)).

The difference between the MRtrix3 and Dipy SH bases now just has to do with the ordering of the coefficients, and a somewhat complicated (-1)^m factor. 

I wrote a quick function that will reorder mrtrix3 SH images into the Dipy basis, so that I can import FODs/etc. computed with mrtrix3 into python for further processing and visualization using Dipy. 

[Here](https://github.com/scott-trinkle/hardi/blob/master/mrtrix3_to_dipy_sh/mrtrix3_to_dipy_SH.ipynb) is a jupyter notebook I made including the function and a quick toy example validating that both softwares expand the same data onto the same coefficients after the mrtrix3 coefficients are converted into the Dipy basis. 

I'm happy to make a PR to include this in "dipy/reconst/shm.py" if it would be useful, otherwise I thought I'd just post it here for others to find as needed.

**Comment by gabknight** [comment]
The is a relevant issue on this here: #392 .

mrtrix 0.2.x basis is supported in dipy. If I understand correctly the basis in 0.3.x only have a normalization factor compared to 0.2.x.
