### ISSUE TITLE
ENH: Save seeds in TRK/TCK

### ISSUE THREAD

**Issue by AntoineTheb** [nipy/dipy#1791]
## Description
It has been brought up in meetings that it would be really useful to know where a tract started, for "debugging", analysis and other purposes. For example, to see if an underepresented region in a tractogram is the result of less seeds, or if a streamline going through an "hard" region is the result of a streamline powering through or two separate streamlines.

Using the property `data_per_streamline` of the `Tractogram` class, each seed could be saved with its corresponding streamline using `seeds` as the key. 

Here's an example of its usage, where white dots are a seed:
![image](https://user-images.githubusercontent.com/10272382/54615495-9a5c3600-4a34-11e9-94e4-97c130bc4ca2.png)

I already have much of the work done, **a PR will be opened soon**

**Comment by GuillaumeTh** [comment]
I know @frheault must refactor trk saving. Maybe something like the seed saving could be a important to support.

@frheault do you want to support that in your function ?

**Comment by skoudoro** [comment]
fixed by #1792, closing
