### ISSUE TITLE
Removed/renamed DetTrackPAMFlow?

### ISSUE THREAD

**Issue by mgxd** [nipy/dipy#1794]
## Description
This issue is popping up in [nipype builds](https://circleci.com/gh/nipy/nipype/8384?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)

https://github.com/nipy/nipype/blob/232ac23bfd48240906e7e629e98eec854bfdcb1c/nipype/interfaces/dipy/tracks.py#L23

Looks like version `0.16.0` removed `dipy.workflows.tracking.DetTrackPAMFlow` - has this been refactored to https://github.com/nipy/dipy/blob/193a8d95d9b5505a94c14b101c1aab49bb0ec43b/dipy/workflows/tracking.py#L21? cc @skoudoro

**Comment by skoudoro** [comment]
Hi @mgxd,

Indeed, I need to make this smarter. I will create a PR this week to fix that.

thank you for pinging me
