### ISSUE TITLE
function parameters 

### ISSUE THREAD

**Issue by imanusita** [nipy/dipy#1797]
where can i find explanation for the parameter used in the different pre-defined functions ? 
some examples use parameters which are not defined 
thnk u

**Comment by skoudoro** [comment]
Hi @imanusita, 

There is many solutions: 

1. you have all function description on the following page: http://nipy.org/dipy/reference/index.html

2. On IPython terminal, just do `help(my_function)``

```
In [2]: import dipy.denoise.nlmeans as nl
In [3]: help(nl.nlmeans)
```

3. Add some plugins, to your IDE. depends on which one your are using

Hope it helps.

**Comment by imanusita** [comment]
owkey thnk u i hope so too
