### ISSUE TITLE
crossing fibers & fractional anisotropy 

### ISSUE THREAD

**Issue by imanusita** [nipy/dipy#1802]
how does crossing fibers effect fractional anisotropy ? 
and what s diffrential deviation

**Comment by RafaelNH** [comment]
Regarding the effects of crossing fibres in diffusion anisotropy, I've personally explored that as part of the following article (see, for example, the geometry of the diffusion tensor as a function of crossing fiber in figure 1):

[Henriques RN et al. (2015). Exploring the 3D geometry of the diffusion kurtosis tensor—Impact on the development of robust tractography procedures and novel biomarkers. NeuroImage 111: 85-99](https://www.sciencedirect.com/science/article/pii/S1053811915000968?via%3Dihub)

A plot of FA vs crossing fiber can be also found in my PhD Thesis (panel A of figure 7.1.).

[Henriques RN (2018). Advanced Methods for Diffusion MRI Data Analysis and their Application to the Healthy Ageing Brain (Doctoral thesis). https://doi.org/10.17863/CAM.29356](https://www.repository.cam.ac.uk/handle/1810/281993)

Other literature suggestions:

[De Santis S et al. (2014). Why diffusion tensor MRI does well only some of the time: variance and covariance of white matter tissue microstructure attributes in the living human brain. Neuroimage 89, 35-44. doi: 10.1016/j.neuroimage.2013.12.003.](https://www.ncbi.nlm.nih.gov/pubmed/24342225)

[Jones DK et al (2013) White matter integrity, fiber count, and other fallacies: the do's and don'ts of diffusion MRI. NeuroImage 73:239-54. doi: 10.1016/j.neuroimage.2012.06.081](https://www.ncbi.nlm.nih.gov/pubmed/22846632)

**Comment by imanusita** [comment]
thn k u soo much ^^
