### ISSUE TITLE
datasets

### ISSUE THREAD

**Issue by imanusita** [nipy/dipy#1809]
hey everyone i need database with different brain diseases ( edemma , autisme , alzhiemer , ...... ) 
thnx for helping ^^

**Comment by RafaelNH** [comment]
Hi @imanusita! Can you post this type of questions in gitter instead?  Dipy issues should be used to report problems/concerns/suggestions regarding Dipy's code development. See also:
[https://help.github.com/en/articles/about-issues](https://help.github.com/en/articles/about-issues)

**Comment by arokem** [comment]
Another good place for this particular question would be neurostars:
https://neurostars.org/
