### ISSUE TITLE
Unusual behavior in Dipy IVIM implementation/example

### ISSUE THREAD

**Issue by rutgerfick** [nipy/dipy#1817]
## Description
Dear Dipy developers,

As always, I admire the beautiful work you do for the neurimaging community.

However, coming across your IVIM example, I noticed some unusual behavior:
- the values the model finds for D* diffusivity occasionally are over 300x that of free water - while the optimization bounds for D* water diffusivity should be at most 20e-9 m^2/s.
- Also, the histogram of the perfusion volume fractions have a strange peak at 0.25 (which appears to be some threshold in your IVIM implementation algorithm).

I've added a link to a demonstration of the described behavior below, compared to a reference Dmipy IVIM implementation.

Kind regards,
Rutger Fick

## Way to reproduce
[If reporting a bug, please include the following important information:]
- [x] Code example: your own IVIM example, but I compare implementations at https://nbviewer.jupyter.org/github/AthenaEPI/dmipy/blob/master/examples/example_ivim.ipynb
- [x] Operating system and version (run `python -c "import platform; print(platform.platform())"`): Linux-4.15.0-47-generic-x86_64-with-debian-stretch-sid
- [x] Python version (run `python -c "import sys; print("Python", sys.version)"`): '2.7.15 |Anaconda, Inc.| (default, Dec 14 2018, 19:04:19) \n[GCC 7.3.0]
- [x] dipy version (run `python -c "import dipy; print(dipy.__version__)"`): 0.16.0
- [x] dependency version (numpy, scipy, nibabel, h5py, cvxpy, fury)
    * import numpy; print("NumPy", numpy.__version__): 1.16.2
    * import scipy; print("SciPy", scipy.__version__): 1.1.0
    * import nibabel; print("Nibabel", nibabel.__version__): 2.3.3
    * import h5py; print("H5py", h5py.__version__) N/A
    * import cvxpy; print("Cvxpy", cvxpy.__version__): 1.0.21
    * import fury; print("fury", fury.__version__): N/A

**Comment by arokem** [comment]
Hi Rutger, Thanks for reporting. We'll take a look.

Have you had a chance to try the VarPro implementation of IVIM (recently
added in #1726)?

**Comment by ShreyasFadnavis** [comment]
@rutgerfick thank you so much for pointing this out. I will look into the resources you have shared and the issues you have pointed out!

**Comment by rutgerfick** [comment]
@arokem You can compare the results for VarPro yourself if you just change the solver option in the notebook reference above.

I'm not familiar with the implementation but the VarPro results seem to look within expected boundaries. My only doubts are why you hard-constraint the D* volume fraction to be below 0.25. The resulting D* volume fraction image mostly reflects the constraint on the optimizer rather than the data. Also VarPro is much slower (20+ min for the slice compare to 1min+ for your other solver) but that's of secondary concern I suppose.

**Comment by arokem** [comment]
I think that the issue of very high D* values could be fixed through a change to this line: 

https://github.com/nipy/dipy/blob/master/dipy/reconst/ivim.py#L289 

to something like: 

```
self.bounds = ((0., 0., 0., 0.), (np.inf, .3, 0.2, 1.))

```
(did I get the scale right?)

Where does that 0.25 come from?

**Comment by rutgerfick** [comment]
Seems its hard-coded into BOTH your implementations. No comments indicating as to why.

https://github.com/nipy/dipy/blob/4c6ae6af0ae292fcad01ce22ebd0986be1bab342/dipy/reconst/ivim.py#L289

https://github.com/nipy/dipy/blob/4c6ae6af0ae292fcad01ce22ebd0986be1bab342/dipy/reconst/ivim.py#L784

I suggest you document it somewhere or put a warning since this is typically one of those impossible-to-know blackbox settings that may mysteriously affect your results (and clearly does if you take a look at the parameter maps).

**Comment by ShreyasFadnavis** [comment]
@arokem what do you suggest? Should I write the documentation? Or should I write warnings for the bounds...?

**Comment by arokem** [comment]
I think that we should change the bounds and maybe set them as a global variable, so they apply to both implementations. 

Better documentation would certainly also be useful to have. 

@rutgerfick : do you have a good reference for the 20e-9 m^2/s number?

**Comment by rutgerfick** [comment]
@arokem for example [Gurney et al 2018](https://journals.plos.org/plosone/article/file?id=10.1371/journal.pone.0194590&type=printable). But essentially they find that simply fixing D* to 7e-9 results in the second-best results for D and f (after fancy bayesian fitting), which is also the Dmipy implementation that I compared with the Dipy one. The question is therefore pertinent what is gained by including fancy MIX fitting for IVIM, but frankly I'm not an IVIM expert :-)

Also keep in mind that [these guys](https://www.ncbi.nlm.nih.gov/pubmed/25693668) also essentially say that D* is an unstable and unreliable biomarker, and should be interpreted with caution.

**Comment by arokem** [comment]
Thanks! These are useful references.
