### ISSUE TITLE
.trk file

### ISSUE THREAD

**Issue by imanusita** [nipy/dipy#1822]
i thought every thing was ok and they r just warning  but i couldn t find my .trk file ? 
where would be the prob 
![wa](https://user-images.githubusercontent.com/48869104/57182728-c592cb80-6ea2-11e9-9232-36f72db35014.PNG)

**Comment by skoudoro** [comment]
Hi @imanusita,

The warnings here are not related to your problem. You need to use `save_trk` function and specify the path if you want to find your Trk. Currently, it seems that you are just visualizing them.

I`m closing this issue.
