### ISSUE TITLE
Fury visualizing bug - plane only visible for XY-slice of FODs

### ISSUE THREAD

**Issue by rutgerfick** [nipy/dipy#1825]
## Description
The new Dipy visualization tool using fury doesn't work correctly.
It only shows slices when the FOD plane is in XY and z-axis has dimension 1. If the plane is in YZ or XZ then it will only show a line.

## Way to reproduce

```python
from dipy.data import get_sphere
from dipy.viz import window, actor
import numpy as np
sphere = get_sphere(name='symmetric724')

random_fods_x = np.random.rand(1, 20, 20, len(sphere.vertices))
random_fods_y = np.random.rand(20, 1, 20, len(sphere.vertices))
random_fods_z = np.random.rand(20, 20, 1, len(sphere.vertices))

# x will only show a single line of FODs
ren = window.Renderer()
fod_spheres = actor.odf_slicer(
    random_fods_x, sphere=sphere, scale=0.9, norm=False, colormap='plasma')
ren.add(fod_spheres)
window.show(ren)

# y will only show a single line of FODs
ren = window.Renderer()
fod_spheres = actor.odf_slicer(
    random_fods_y, sphere=sphere, scale=0.9, norm=False, colormap='plasma')
ren.add(fod_spheres)
window.show(ren)

# only in z you will see a plane of FODs
ren = window.Renderer()
fod_spheres = actor.odf_slicer(
    random_fods_z, sphere=sphere, scale=0.9, norm=False, colormap='plasma')
ren.add(fod_spheres)
window.show(ren)
```

[If reporting a bug, please include the following important information:]
- [x] Code example
- [x] Relevant images (if any)
- [x] Operating system and version (run `python -c "import platform; print(platform.platform())"`) Linux-4.15.0-47-generic-x86_64-with-debian-stretch-sid
- [x] Python version (run `python -c "import sys; print("Python", sys.version)"`) 2.7.15 |Anaconda, Inc.| (default, Dec 14 2018, 19:04:19) \n[GCC 7.3.0]
- [x] dipy version (run `python -c "import dipy; print(dipy.__version__)"`) '0.16.0'
- [x] dependency version (numpy, scipy, nibabel, h5py, cvxpy, fury)
    * import numpy; print("NumPy", numpy.__version__) N/A
    * import scipy; print("SciPy", scipy.__version__) N/A
    * import nibabel; print("Nibabel", nibabel.__version__) N/A
    * import h5py; print("H5py", h5py.__version__) N/A
    * import cvxpy; print("Cvxpy", cvxpy.__version__) N/A
    * import fury; print("fury", fury.__version__) ('fury', u'0.2.0')

**Comment by skoudoro** [comment]
Hi @rutgerfick,

This is a normal behavior. if you want to have a specific plane direction, you need to set up the extent (`actor.display_extent(...)` ). More information on this tutorial: http://fury.gl/latest/auto_examples/viz_advanced.html#sphx-glr-auto-examples-viz-advanced-py

**Comment by rutgerfick** [comment]
Ah! That helps a lot !!
I was looking at the CSD example and was in confusion as to what I was doing wrong.
Thanks, I'll close the issue then.
