### ISSUE TITLE
When fetching ... 'tput' is not reco...

### ISSUE THREAD

**Issue by Garyfallidis** [nipy/dipy#1829]
operable program or batch file.
Download Progress: [--------------------] 1.84%  of 304.72 MB'tput' is not recognized as an internal or external command,
operable program or batch file.
Download Progress: [--------------------] 1.84%  of 304.72 MB'tput' is not recognized as an internal or external command,
operable program or batch file.
Download Progress: [--------------------] 1.85%  of 304.72 MB'tput' is not recognized as an internal or external command,
operable program or batch file.
Download Progress: [---------------

To replicate just try
```
from dipy.data import fetcher
fetcher.fetch_bundle_atlashcp842()
```

**Comment by arokem** [comment]
Annoying, but harmless, I think. 

Someone was trying to be clever: https://github.com/nipy/dipy/blob/master/dipy/data/fetcher.py#L55, but if `tput` is not available, this will raise this error (presumably from the system call) and then go on to the except clause. 

I would suggest getting rid of the try clause and always doing the fall-back option.

**Comment by Garyfallidis** [comment]
Okay this still needs fixing. I have seen cases where the download never completes. Only saw this in Windows.

**Comment by Garyfallidis** [comment]
Git blame suggests @skoudoro ... sorry.

**Comment by Garyfallidis** [comment]
Probably not his fault but providing a fix asap. Cheers!
