### ISSUE TITLE
bvec file dimension  prob 

### ISSUE THREAD

**Issue by imanusita** [nipy/dipy#1831]
i dowloaded my data as dicom files and converted it mricron to nifti and i got bval and bvec of 1ko for each and after runing i got that error what s wrong 
![bvec](https://user-images.githubusercontent.com/48869104/57660457-f41d4e80-75e6-11e9-9549-132e36f7c40a.PNG)

**Comment by gabknight** [comment]
"the bvec file should have three rows". 
Sometime bvecs are save in three columns; see `numpy` `loadtxt(.)` and `savetxt(.)` to re-organise the file. Otherwise, it is related to the data you are using, check that the bvecs/bvals were correctly extracted.
