### ISSUE TITLE
Which file to convert  from dicom to nifti?!

### ISSUE THREAD

**Issue by imanusita** [nipy/dipy#1834]
the dimesnison of my image was [256,256,36,2] which seemed unlogical
in fact i dowloaled a data and i got many files i used to have dti file but in that dataset i got the following files i didn tknow which one to use !
i got
2-3-pl T2 FGRE S-34403
4-DWI ASSET-26022
5-SAG T1-64094
6-Ax Flair irFSE H-80553
7-Ax Flair irFSE H-84835
8-AX 3D SPGR-43615
9-AX T1-06604
10-Prop T2 TRF-43669
11-COR GRE T2-05651
12-COR T1C-76492
13-AX T1C-70939
14-AX 3D SPGRC-87409
15-SAG T1C-18188
400-Exponential Apparent Diffusion Coefficient-42784
401-Apparent Diffusion Coefficient mm2s-56391

so can u guess which one i should use !!

**Comment by skoudoro** [comment]
Hi @imanusita,

This is not related to DIPY project. Closing.

ps: you can look at https://github.com/nipy/heudiconv project or ask to neuroimaging mailing list: https://mail.python.org/mailman/listinfo/neuroimaging
