### ISSUE TITLE
Signal to noise 

### ISSUE THREAD

**Issue by imanusita** [nipy/dipy#1845]
Is the snr goid or bad for the computational side i mean is it better when it s higher or liwer !? 
And can we change it using dipy !?

**Comment by arokem** [comment]
Higher SNR is better. There are some tools for denoising available in DIPY (see: http://nipy.org/dipy/examples_index.html#denoising), which should help in some respects.

**Comment by imanusita** [comment]
is it a parameter that we can calculate .. ? i mean how can we control it i saw in some papers statistics with different SNR how is tht ? thnx in advance

**Comment by arokem** [comment]
There's a tutorial about SNR calculation here: http://nipy.org/dipy/examples_built/snr_in_cc.html#example-snr-in-cc
