### ISSUE TITLE
point outside data error

### ISSUE THREAD

**Issue by imanusita** [nipy/dipy#1857]
what would be the problem i hv runned the same progrm with other data and i didn t hv problm 
![errroor](https://user-images.githubusercontent.com/48869104/59473322-51a0f700-8e42-11e9-8481-c4bf0c54f414.PNG)

**Comment by gabknight** [comment]
It looks like your seeds position are outside your diffusion images. Be sure your seed image is co-aligned with your diffusion images (e.g. image size, voxel size, affine matrix).

**Comment by imanusita** [comment]
how should i change them ? 
i used (seeds = random_seeds_from_mask(fa > 0.4, seeds_count=1)) for two kinds of data it worked to one of them .it worked for data of size (128,128,72,71) , but not for (256,256,72,71)

**Comment by gabknight** [comment]
You are probably providing the affine matrix to the `localTracking` function, by not the seeds generation function. Try adding your affine matrix to `random_seeds_from_mask(fa > 0.4, seeds_count=1, affine=affine)`

**Comment by gabknight** [comment]
If you still have issues with your data and affine transformation, you can reach us on https://gitter.im/nipy/dipy
