### ISSUE TITLE
get rotation and translation parameters of a rigid transformation

### ISSUE THREAD

**Issue by snapfinger** [nipy/dipy#1869]
## Description
Hi there, I was following [tutorial on registration](http://nipy.org/dipy/examples_built/affine_registration_3d.html) doing a rigid registration and trying to extract rotation and translation params from it. With the following code I was able to register and get the transformation matrix, however I want to extract translation and rotation params separately.

```python
transform = RigidTransform3D()
params0 = None
rigid = affreg.optimize(test_scan, retest_scan, transform, params0)
print rigid.affine
```

In [transform.pyx](https://github.com/nipy/dipy/blob/37fb6fe1e8bdee3e90829c7163ac1df49f7dd79c/dipy/align/transforms.pyx#L522) I saw there's a `theta` vector containing these info, but there's no such field for the object
```python
transform
```
or
```python
rigid
``` 
Any suggestions? Is there anyway to get these transformation parameters separately?

**Comment by snapfinger** [comment]
Guess if there's no direct method to get values I can just compute myself using formulas [here](https://www.fil.ion.ucl.ac.uk/spm/doc/books/hbf2/pdfs/Ch2.pdf)

**Comment by skoudoro** [comment]
Hi @snapfinger, the affine matrix give you all the transformation informations. If you do `rigid.affine`, the last matrix colon is the translation, the first one is the rotation, etc....

Let me know if it is clear or if you need more information.

**Comment by skoudoro** [comment]
More information about affine matrix ,[here](https://en.m.wikipedia.org/wiki/Affine_transformation)

**Comment by snapfinger** [comment]
Hi @skoudoro, thanks for your response.  Translation params are indeed easy to get (last column excluding the last one), however, since `rigid.affine` gives the multiplication of the rotation matrices about x, y, z axis and translation, I'm afraid one is not able to directly read the rotation degrees wrt each axis directly from it

**Comment by arokem** [comment]
[dipy.core.geometry.decompose_matrix](https://github.com/nipy/dipy/blob/master/dipy/core/geometry.py#L689) should give you this.

**Comment by skoudoro** [comment]
Oh, I didn't know that! really nice! I should add it to our Todo list to add this function on our tutorial!

**Comment by arokem** [comment]
Yes. We could use a tutorial on geometry in general. See also https://github.com/nipy/dipy/pull/1850#issuecomment-499712925

**Comment by snapfinger** [comment]
Thank you guys!
