### ISSUE TITLE
Documentation example  of MSMT CSD

### ISSUE THREAD

**Issue by arokem** [nipy/dipy#1870]
Follow up on #1858

**Comment by skoudoro** [comment]
Hi @ShreyasFadnavis, 

What is the status of this? Any chance to have it ready for the release next week?

**Comment by ShreyasFadnavis** [comment]
@skoudoro Yes, I will follow up with a PR shortly!
Thanks :+1:

**Comment by ShreyasFadnavis** [comment]
Done!
Thanks!! @arokem and @skoudoro 👍
