### ISSUE TITLE
Add python_requires=">=3.5"

### ISSUE THREAD

**Issue by effigies** [nipy/dipy#1906]
## Description

I noticed that you've dropped tests, and presumably support, for Python 2.7 and 3.4. If you add the `python_requires=">= 3.5"` option to your `setuptools.setup()` call, then Python versions lower than 3.5 will not attempt to install versions built with that option.

It looks like the main effect in version 0.16.0 is that 2.7 and 3.4 manylinux wheels aren't getting built, so it just takes longer to install, but future versions will eventually break, so avoiding the installation would be nice.

**Comment by skoudoro** [comment]
>  If you add the python_requires=">= 3.5" ....

Thank you @effigies, that's a good idea, will do!

**Comment by skoudoro** [comment]
fixed by #1911, closing
