### ISSUE TITLE
dipy.io.peaks.load_peaks() IOError: This function supports only PAM5 (HDF5) files

### ISSUE THREAD

**Issue by luqily** [nipy/dipy#1930]
I have three arrays of fiber orientation. And I want to get streamlines using them. 
The function LocalTracking() need a 'direction_getter' parameter. So I wanted to convert the arrays into 'PeaksAndMetrics' objects and passed them to the parameter, but failed. Specifically, I wanted to write the arrays into the HDF5 files and used the function load_peaks().

There are code and error.
`
fiber_or1='/data1/fsl_track.bedpostX/dyads1.nii.gz'
orientation1=nib.load(fiber_or1).get_data()
f = h5py.File('/data1/orientation1.h5','w')
f['peaks']  = orientation1
f.close

peaks=load_peaks('/data1/orientation1.h5')

classifier=ThresholdTissueClassifier(orientation1,0)
streamlines_generator = LocalTracking(peaks, classifier, seeds,
                                      affine=np.eye(4), step_size=.5)
`
Traceback (most recent call last):
  File "bedpostx_tracking.py", line 41, in <module>
    peaks=load_peaks('/data1/orientation1.h5')
  File "/home/qilu/anaconda2/lib/python2.7/site-packages/dipy/io/peaks.py", line 45, in load_peaks
    raise IOError('This function supports only PAM5 (HDF5) files')
IOError: This function supports only PAM5 (HDF5) files

How should I modify it?
Or is there any other way I can get streamlines using the fiber orientation and seed?

Hope my question is not too naive...

**Comment by arokem** [comment]
Sorry that it has taken this long to reply here. I think that this is just due to file naming. The loading function you are using expects files to be named ending in the `pam5` extension (see [here](https://github.com/nipy/dipy/blob/master/dipy/io/peaks.py#L44-L45)). 

I am still not 100% sure that this would work, even if you changed that detail, but worth trying.

**Comment by luqily** [comment]
> Sorry that it has taken this long to reply here. I think that this is just due to file naming. The loading function you are using expects files to be named ending in the `pam5` extension (see [here](https://github.com/nipy/dipy/blob/master/dipy/io/peaks.py#L44-L45)).
> 
> I am still not 100% sure that this would work, even if you changed that detail, but worth trying.

Thanks for your reply! ^^
