### ISSUE TITLE
StatefullTractogram error in Horizon

### ISSUE THREAD

**Issue by Garyfallidis** [nipy/dipy#1950]
In Horizon when 's' is pressed the .trk is not saved and an error is given.
```
Traceback (most recent call last):
  File "/home/elef/Devel/dipy/dipy/viz/app.py", line 524, in key_press
    Space.RASMM)
  File "/home/elef/Devel/dipy/dipy/io/stateful_tractogram.py", line 83, in __init__
    space_attribute = get_reference_info(reference)
  File "/home/elef/Devel/dipy/dipy/io/utils.py", line 162, in get_reference_info
    header = nib.load(reference).header
  File "/home/elef/anaconda3/lib/python3.7/site-packages/nibabel/loadsave.py", line 42, in load
    raise FileNotFoundError("No such file or no access: '%s'" % filename)
FileNotFoundError: No such file or no access: 'same'
```
@frheault ?

**Comment by skoudoro** [comment]
Just to be more explicit, it will be nice to have the same feature as `load_tractogram` with `same` keywords.
here the problem: `sft = StatefulTractogram(streamlines, 'same', Space.RASMM)`  do not work

**Comment by Garyfallidis** [comment]
Yeah, I was just explaining the same. The 'same' parameter is not checked. Thanks @frheault.

**Comment by frheault** [comment]
@skoudoro @Garyfallidis Yeah but you can't do that, how is the object supposed to know "same" when you are creating the object ? 
If you want to save something using the same reference as another StatefulTractogram, you can use a StatefulTractogram as a reference too.

But "same" when you create the object does not make any sense, you have to provide something

**Comment by skoudoro** [comment]
Make sense, closing this issue. A workaround needs to be found for this part of Horizon.

Thank you @frheault!
