### ISSUE TITLE
Better warning when dipy is installed without fury

### ISSUE THREAD

**Issue by arokem** [nipy/dipy#1976]
## Description

If dipy is installed without fury, and the following line (from our examples) is run: 

`from dipy.viz import actor, window, ui`

the user will likely see an uninformative error: 

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-5eadb5980917> in <module>
----> 1 from dipy.viz import actor, window, ui

ImportError: cannot import name 'actor' from 'dipy.viz' (/Users/arokem/.virtualenvs/test_dipy_no_fury/lib/python3.7/site-packages/dipy/viz/__init__.py)`
```

This is because the current implementation of `optional_pkg` doesn't handle `from foo import bar` imports elegantly. 

I think that we should provide more useful information [here](https://github.com/nipy/dipy/blob/master/dipy/viz/__init__.py#L6-L10)

**Comment by skoudoro** [comment]
Fixed by #1977 , closing
