### ISSUE TITLE
Artefacts in DKI reconstruction

### ISSUE THREAD

**Issue by mdesco** [nipy/dipy#2003]
I wrote a personal email to @RafaelNH about problems I was having using DKI reconstruction on multi-shell data. I move the discussion here because it may help other dipy users.

> Hey Rafael,
> 
> I've turned your Dipy example into a script for our multi-shell data to extract kurtosis maps (ak, rk, mk). Unfortunately, I always have some very bad degenerate voxels, especially in voxels of very high anisotropy (CC, CST voxels). I get this no matter how I denoise the DWI (lpca, nlm, gaussian)... I was wondering if you had any insights on the problem?

Answer from @RafaelNH :

> Yes! I am quite familiarized with this kurtosis artefact! This is induced by the low radial diffusivities of aligned white matter (CC, CST voxels). Since it is very hard to capture non-Gaussian information due to the low decays in radial direction, its kurtosis estimates have very low robustness. Noisy kurtosis estimates tend to be negative and its absolute values can have order of magnitudes higher than the typical kurtosis values. Consequently, these negative kurtosis values will heavily propagate to the mean and radial kurtosis metrics. I've reported this artefact in my master thesis back in 2012 (https://repositorio.ul.pt/bitstream/10451/8511/1/ulfc104137_tm_Rafael_Henriques.pdf, see chapter 3).
> 
> One way that I've come up to overcome this issue is to compute the kurtosis values from powder-averaged diffusion-weighted signals. On powder-averaged signal decays, you don't have this low diffusivity issue and your kurtosis estimates have much higher precision (additionally they are independent to the fODF). To compute the kurtosis of powder-average signals in dipy follow the tutorial:
> 
> https://dipy.org/documentation/1.0.0./examples_built/reconst_msdki/#example-reconst-msdki
> 

This indeed helped and the MSDKI model is much more robust in these artefacted voxels.

Thanks!
(issue closed)

**Comment by arokem** [comment]
Thanks so much for reporting here! Since this seems already resolved, I will go ahead and close it.

**Comment by Garyfallidis** [comment]
Thanks for reporting @mdesco !

**Comment by Garyfallidis** [comment]
I suggest this information also be added in the tutorial as advice @RafaelNH if not already there.

**Comment by skoudoro** [comment]
I didn't check the tutorial but I think it would be good to add this information in the tutorial. So we should keep this issue open for informing the users. 

Thank you for reporting!

**Comment by arokem** [comment]
Yes. Good call! Reopening.

**Comment by skoudoro** [comment]
closed by #2009
