### ISSUE TITLE
Add wheels for python 3.8 to pypi

### ISSUE THREAD

**Issue by fvdnabee** [nipy/dipy#2004]
## Description
Currently users have to build their own wheel from source when installing dipy 1.0 via pip under python 3.8. [Pypi](https://pypi.org/project/dipy/#files) lists 3.5, 3.6 and 3.7 wheels for dipy 1.0. Consider providing 3.8 wheels for the supported platforms.

**Comment by skoudoro** [comment]
Thank you for pointing that @fvdnabee! We will look into it. 
We should add some matrix to our CI's too.

**Comment by skoudoro** [comment]
- wheels added on PyPi and Conda-forge with the new release DIPY 1.1.0. closing.
- Python 3.8 Matrix added on Travis and azure

Thanks @fvdnabee, closing
