### ISSUE TITLE
get_data deprecated

### ISSUE THREAD

**Issue by skoudoro** [nipy/dipy#2006]
Nibabel deprecate `get_data()`. We should start slowly to replace `get_data()` by either

- `get_fdata()` from Nibabel
- `load_nifti`.  this is our small interface

I suggest updating our tutorials with `load_nifti`. I have no strong opinion concerning the rest of our codebase.

**Comment by safwan20** [comment]
I am new to this codebase ..so may I know the filename so that I can make contributions.

**Comment by skoudoro** [comment]
Sorry @safwan20 , there is already a Pull Request for this one which is #2015. So it is almost done.
