### ISSUE TITLE
Median otsu figures in example don't look good

### ISSUE THREAD

**Issue by Garyfallidis** [nipy/dipy#321]
Hi @matthieudumont and all,

It is difficult to see the background that was removed after brain extraction in this example
http://nipy.org/dipy/examples_built/brain_extraction_dwi.html#example-brain-extraction-dwi

also the figures are not shown in the standard way.

**Comment by skoudoro** [comment]
Should we close this one @Garyfallidis  ?

**Comment by Garyfallidis** [comment]
Sure.
