### ISSUE TITLE
Missing content in tracking.utils' documentation

### ISSUE THREAD

**Issue by jchoude** [nipy/dipy#322]
When checking the page for dipy.tracking.utils documentation (http://nipy.org/dipy/reference/dipy.tracking.utils.html#module-dipy.tracking.utils), it seems that the content is broken, especially starting at the example of the affine transform.

**Comment by skoudoro** [comment]
Can you close this one @jchoude  ? it seems to be ok :-)

**Comment by jchoude** [comment]
@skoudoro I might not be looking in the correct place, but I still don't find the tracking.utils documentation when looking at the link in my initial issue. Is it somewhere else?

**Comment by skoudoro** [comment]
My bad, you are right, it seems to be excluded here: https://github.com/nipy/dipy/blob/master/doc/tools/build_modref_templates.py#L71

all packages dipy.*.utils are not included. I will create a PR.

**Comment by skoudoro** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#322](https://trello.com/c/N9RPVik9/7-322)

**Comment by skoudoro** [comment]
website updated : http://nipy.org/dipy/reference/dipy.tracking.html#module-dipy.tracking.utils

**Comment by jchoude** [comment]
Thanks guys!
