### ISSUE TITLE
"incompatible" import of peaks_from_model in your recent publication

### ISSUE THREAD

**Issue by kodiweera** [nipy/dipy#328]
I was following code in your recent DiPy paper in frontiers (using recent 0.7.1 release).  While in the section 6.5, I typed "from dipy.reconstruct.odf import peaks_from_model" which resulted in ImportError because in 0.6.0-564-gbdeca9e you refactored it into a separate peaks submodule.  It would be nice if current 0.7.x stayed compatible with at least the code in the reference DiPy publication!

Thank you in advance!

**Comment by skoudoro** [comment]
It seems to be done, I close
