### ISSUE TITLE
Update citation page

### ISSUE THREAD

**Issue by arokem** [nipy/dipy#344]
We should probably add the Frontiers paper here: 

http://nipy.org/dipy/cite.html

I know it's on the front page, but still.

**Comment by souravsingh** [comment]
Are we talking about the paper [linked here](http://journal.frontiersin.org/article/10.3389/fninf.2014.00008/abstract). If so, I can make a quick PR to fix it.

**Comment by arokem** [comment]
This one's already resolved. Thanks for floating it. Closing.
