### ISSUE TITLE
fvtk.label won't show up if called twice 

### ISSUE THREAD

**Issue by samuelstjean** [nipy/dipy#353]
Try this : 

> > > from dipy.viz import fvtk
> > > r=fvtk.ren()
> > > l=fvtk.label(r)
> > > fvtk.add(r,l)
> > > fvtk.show(r)

You get origin in white, show it again, and you only get a black scene (on my computer). 
fvtk.show(r) # nothing happens :( 

I'm on ubuntu 12.04, could be a vtk problem or a rendering problem, points show up fine for example and don't exibit this behavior.

**Comment by skoudoro** [comment]
This issue was moved to fury-gl/fury#1
