### ISSUE TITLE
Test failures of 0.7.1 on wheezy and squeeze 32bit

### ISSUE THREAD

**Issue by yarikoptic** [nipy/dipy#354]
per report on the mailing list

wheezy:
```
======================================================================
ERROR: dipy.tests.test_scripts.test_dipy_fit_tensor_again
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/tmp/buildd/dipy-0.7.1/debian/tmp/usr/lib/python2.6/dist-packages/dipy/tests/test_scripts.py", line 161, in test_dipy_fit_tensor_again
    out = run_command(cmd)
  File "/tmp/buildd/dipy-0.7.1/debian/tmp/usr/lib/python2.6/dist-packages/dipy/tests/test_scripts.py", line 120, in run_command
    """.format(cmd, stdout, stderr))
RuntimeError: Command "['dipy_fit_tensor', '--mask=none', 'small_25.nii.gz']" failed with
            stdout
            ------

            stderr
            ------
            /tmp/buildd/dipy-0.7.1/debian/tmp/usr/lib/python2.6/dist-packages/dipy/core/sphere.py:12: RuntimeWarning: compiletime version 2.6 of module 'dipy.reconst.recspeed' does not match runtime version 2.7
  from dipy.reconst.recspeed import remove_similar_vertices



======================================================================
FAIL: dipy.tests.test_scripts.test_dipy_peak_extraction
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/tmp/buildd/dipy-0.7.1/debian/tmp/usr/lib/python2.6/dist-packages/dipy/tests/test_scripts.py", line 128, in test_dipy_peak_extraction
    assert_equal(code, 2)
AssertionError: -11 != 2

======================================================================
FAIL: dipy.tests.test_scripts.test_dipy_fit_tensor
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/tmp/buildd/dipy-0.7.1/debian/tmp/usr/lib/python2.6/dist-packages/dipy/tests/test_scripts.py", line 135, in test_dipy_fit_tensor
    assert_equal(code, 2)
AssertionError: -11 != 2

======================================================================
FAIL: dipy.tests.test_scripts.test_dipy_sh_estimate
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/tmp/buildd/dipy-0.7.1/debian/tmp/usr/lib/python2.6/dist-packages/dipy/tests/test_scripts.py", line 142, in test_dipy_sh_estimate
    assert_equal(code, 2)
AssertionError: -11 != 2

----------------------------------------------------------------------
Ran 212 tests in 105.679s

FAILED (SKIP=4, errors=1, failures=3)
```

squeeze:

```
======================================================================
ERROR: dipy.reconst.tests.test_shore_odf.test_shore_odf
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/nose/case.py", line 183, in runTest
    self.test(*self.arg)
  File "/tmp/buildd/dipy-0.7.1/debian/tmp/usr/lib/python2.6/dist-packages/dipy/reconst/tests/test_shore_odf.py", line 37, in test_shore_odf
    directions, _ , _ = peak_directions(odf, sphere, .35, 25)
  File "/tmp/buildd/dipy-0.7.1/debian/tmp/usr/lib/python2.6/dist-packages/dipy/reconst/peaks.py", line 130, in peak_directions
    values, indices = local_maxima(odf, sphere.edges)
  File "recspeed.pyx", line 269, in dipy.reconst.recspeed.local_maxima (dipy/reconst/recspeed.c:4339)
ValueError: odf can not have nans

======================================================================
ERROR: dipy.tests.test_scripts.test_qb_commandline
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/nose/case.py", line 183, in runTest
    self.test(*self.arg)
  File "/usr/lib/pymodules/python2.6/numpy/testing/decorators.py", line 146, in skipper_func
    return f(*args, **kwargs)
  File "/tmp/buildd/dipy-0.7.1/debian/tmp/usr/lib/python2.6/dist-packages/dipy/tests/test_scripts.py", line 208, in test_qb_commandline
    out = run_command(cmd)
  File "/tmp/buildd/dipy-0.7.1/debian/tmp/usr/lib/python2.6/dist-packages/dipy/tests/test_scripts.py", line 120, in run_command
    """.format(cmd, stdout, stderr))
RuntimeError: Command "['dipy_quickbundles', '/tmp/buildd/dipy-0.7.1/debian/tmp/usr/lib/python2.6/dist-packages/dipy/data/tracks300.trk', '--pkl_file', 'mypickle.pkl', '--out_file', 'tracks300.trk']" failed with
            stdout
            ------

            stderr
            ------
            Traceback (most recent call last):
  File "/tmp/buildd/dipy-0.7.1/debian/tmp/usr/bin/dipy_quickbundles", line 53, in <module>
    np.array(streamlines)[clusters[c]['indices']]]
ValueError: setting an array element with a sequence.



======================================================================
FAIL: dipy.reconst.tests.test_shore_metrics.test_shore_metrics
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/nose/case.py", line 183, in runTest
    self.test(*self.arg)
  File "/tmp/buildd/dipy-0.7.1/debian/tmp/usr/lib/python2.6/dist-packages/dipy/reconst/tests/test_shore_metrics.py", line 90, in test_shore_metrics
    assert_equal(msd_mt / msd_shore < 1.05 and msd_mt / msd_shore > 0.95, True)
  File "/usr/lib/pymodules/python2.6/numpy/testing/utils.py", line 309, in assert_equal
    raise AssertionError(msg)
AssertionError:
Items are not equal:
 ACTUAL: False
 DESIRED: True

```

**Comment by yarikoptic** [comment]
just a note that issue is still open and exists with 0.8.0 release

**Comment by matthew-brett** [comment]
Do all these errors still come up with the 0.8.0 release?

This error:

    /tmp/buildd/dipy-0.7.1/debian/tmp/usr/lib/python2.6/dist-packages/dipy/core/sphere.py:12: RuntimeWarning: compiletime version 2.6 of module 'dipy.reconst.recspeed' does not match runtime version 2.7
  from dipy.reconst.recspeed import remove_similar_vertices

seems to show that the machine is getting confused between Python 2.6 and Python 2.7 - any ideas why that might be?

**Comment by matthew-brett** [comment]
We do run a buildbot on a 32-bit Ubuntu 12.04 system - no problems there: http://nipy.bic.berkeley.edu/builders/dipy-py2.6-32

**Comment by yarikoptic** [comment]
I am not quite sure (didn't look though) why it didn't fail on amd64 as it did on i386 but the reason why it is failing is that the test is for running a script, which is executed without use of sys.executable  while PYTHONPATH is overidden to point to another, non default, python and run tests outside of the original source tree (under build/) to not interfere anyhow with the original source tree.  The easiest resolution for me would be I guess just to support a single (default) version of python and drop supporting multiple on older debians where still both 2.6 and 2.7 were supported.  Otherwise it would be a bit messier solution (e.g. informing where the scripts are via some env variable).  I just shouldn't forget to do that for the next upload... closing for now since it is not really an issue for stock dipy ;)

**Comment by matthew-brett** [comment]
Is it right that using `nd_login` I will have to build numpy, scipy in the resulting environment?

Is there something strange about how the test are run?   At the moment, the test machinery will import `dipy` and then look for a `setup.py` in the directory below the `dipy` directory.  If it finds `setup.py` it assumes the tests are running in a local directory, so appends the `dipy` directory to `PYTHONPATH`, and uses ``sys.executable`` to run the script files.  Otherwise it just runs the script files directly, as in:

    ['dipy_fit_tensor', '--mask=none', 'small_25.nii.gz']

In this case, the file `dipy_fit_tensor` found in the path, needs to be the one just installed, and not a version installed using another Python version, because the Python version will be that specified in the shebang line of the script, which I believe gets put there by the distutils installer.  

For example, in the case above, which `dipy_fit_tensor` gets found?  And what is it's shebang line?

**Comment by yarikoptic** [comment]
oh no -- after nd_login  you would just apt-get install whatever is needed, or even better, you just run
on your debian/ubuntu box with nd_ tools installed

```
apt-get update
apt-get source python-dipy
sudo nd_build nd+debian wheezy i386 *dsc --hookdir=$HOME/neurodebian/tools/hooks
```
where neurodebian is our github.com/neurodebian/neurodebian
which should try building that .dsc (Source package), fail, and get you into the shell where it was building the beast but failed

**Comment by yarikoptic** [comment]
the scripts are found by me adjusting PATH to point to the topdir bin/  while I am under build ;)

**Comment by matthew-brett** [comment]
You mean the 'bin' directory at the dipy root directory containing 'setup.py'?  These haven't had their shebang lines adjusted by the installer, so pick up `/usr/bin/env python`.    It's a bit ugly to try and hack round that - what do you think?

What about the non-script errors - do you still get those?

**Comment by matthew-brett** [comment]
Getting this error:

```
Untrusted packages could compromise your system's security.
You should only proceed with the installation if you are certain that
this is what you want to do.

  neurodebian-popularity-contest python-nibabel 

Do you want to ignore this warning and proceed anyway?
To continue, enter "Yes"; to abort, enter "No": Abort.
E: pbuilder-satisfydepends failed.
```

**Comment by yarikoptic** [comment]
that is when you run nd_build command?? bizzare then... usually smth like that happens when apt key is not deployed but if you generated those environments using nd_ tools everything should be cool... or was it some manually configured environment where you just added apt lines but didn't add apt-key?

**Comment by yarikoptic** [comment]
those other errors (-11 != 2) I thought are pretty much the same caused by incorrect execution of the script -- didn't even look into them in detail.  as for squeeze -- just forget about it, too old numpy I guess :"RuntimeError: You have version 1.4.1 of package "numpy" but we need version >= 1.6"
I will eventually fix up wheezy i386 build, but probably no rush since unlikely many folks are still on 32bit or you have received complaints already? ;-)

**Comment by matthew-brett** [comment]
Yes, generated everything with nd_build command .

**Comment by yarikoptic** [comment]
nd_build doesn't generate ;)  nd_adddist or nd_adddistall do.  What is your base system? is that the NeuroDebian VM -- then I could try replicating

**Comment by matthew-brett** [comment]
Sorry, yes, everything built in updated NeuroDebian 7.4.201 machine, with `sudo nd_adddistall` as per page : http://neuro.debian.net/blog/2012/2012-04-14_ndtools.html

cmdsettings.sh default apart from:

```
allnddists="nd+debian-squeeze nd+debian-wheezy"
# alldists="$allnddists debian-squeeze debian-wheezy debian-jessie debian-sid"
alldists="$allnddists debian-squeeze debian-wheezy debian-jessie debian-sid"
```

I did a first `nd_addinstall` with just the debians, then later did another adding the neurodebians.

**Comment by matthew-brett** [comment]
Actually after `sudo nd_adddistall` I get:

```
SUMMARY:
 nd+debian-squeeze 	failed
 nd+debian-wheezy 	exists
 debian-squeeze 	exists
 debian-wheezy 	exists
 debian-jessie 	exists
 debian-sid 	exists
```

with previous error messages like:

```
W: GPG error: http://neuro.debian.net squeeze Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A5D32F012649A5A9
W: GPG error: http://neuro.debian.net data Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A5D32F012649A5A9
I: Obtaining the cached apt archive contents
ln: failed to create hard link `/home/neurodebian/cow/nd+debian-squeeze-i386.cow/var/cache/apt/archives/util-linux_2.17.2-9_i386.deb': File exists
ln: failed to create hard link `/home/neurodebian/cow/nd+debian-squeeze-i386.cow/var/cache/apt/archives/xz-utils_5.0.0-2_i386.deb': File exists
```

**Comment by yarikoptic** [comment]
well -- don't worry about squeeze (old stable) now that it is pretty much EOLed and only got some limited support through the "experimental LTS".  I will check if anything on our side could be done for a quick workaround to get those deployed.  But as it says -- you haave nd+debian-wheezy now so you should be set to troubleshoot that i386 wheezy issues.

**Comment by yarikoptic** [comment]
@matthew-brett  ok -- didn't see why it got that way but it should be sufficient to just run e.g. ```sudo nd_updateall```  or ```sudo nd_updatedist nd+debian wheezy``` and it should pick up the key it did have installed, and then nd_build should be working splendidly ;)
