### ISSUE TITLE
Add TESTs for resample

### ISSUE THREAD

**Issue by Garyfallidis** [nipy/dipy#369]
Function resample in aniso2iso doesn't have any tests. This should change. Task assigned to Eleftherios!

**Comment by skoudoro** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#369](https://trello.com/c/QudtmdZv/4-369)

**Comment by skoudoro** [comment]
The function resample from dipy.align.aniso2iso is deprecated and deleted from dipy 0.10 and became reslice from dipy.align.reslice.

Test for this function exist so I close this issue @Garyfallidis

**Comment by jagruti8** [comment]
Hi, does the function dipy.align.reslice take care of aliasing? Or we have to do some kind of preprocessing? I have to downsample diffusion data from 1.25 to 2.3 and anatomical data from 0.7 to 1.5. The dataset is HCP.
