### ISSUE TITLE
Peak directiions test error on PPC

### ISSUE THREAD

**Issue by matthew-brett** [nipy/dipy#375]
There is a test error on the PPC buildbot:

http://nipy.bic.berkeley.edu/builders/dipy-py2.6-osx-10.5-ppc/builds/293/steps/shell_8/logs/stdio

```
======================================================================
FAIL: dipy.reconst.tests.test_peaks.test_peak_directions_thorough
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/buildslave/.local/lib/python2.6/site-packages/nose-1.1.2-py2.6.egg/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/buildslave/osx-10.5-ppc/dipy-py2_6-osx-10_5-ppc/build/venv/lib/python2.6/site-packages/dipy/reconst/tests/test_peaks.py", line 222, in test_peak_directions_thorough
    assert_equal(AE < 2., True)
AssertionError: False != True
```

I had a look at the value for AE - it was 179.XXX (a floating point value, can't remember the values after the floating point. It seems very far off.  Any thoughts?  I can give a login to anyone who wants to debug.

**Comment by skoudoro** [comment]
This build is not anymore active, closing

**Comment by matthew-brett** [comment]
The point is not the PPC platform specifically, but understanding the error so we be confident that Dipy will work on less common platforms. Virtually none of the the bugs revealed by the PPC build are PPC-specific, but point to big-endian issues or bugs in the C code exposed by compilation non-Intel compiler.

**Comment by skoudoro** [comment]
Ok, I see. Thanks for this information.

can you make [the debian ppc build](https://nipy.bic.berkeley.edu/builders/dipy-py2.7-debian-ppc) work to see if it is the only failing test. it might help to understand what happens. 

Thank you

**Comment by matthew-brett** [comment]
Ah - sorry - I wasn't paying attention.  No, that build isn't active any more - it was building on PPC OSX 10.5, but the machine is now running Debian - the builds you're pointing to above.  That doesn't have the test failure at the moment:

http://nipy.bic.berkeley.edu/builders/dipy-py2.7-debian-ppc/builds/246

- so yes, good to close.
