### ISSUE TITLE
minmax_norm in peaks_directions does nothing

### ISSUE THREAD

**Issue by samuelstjean** [nipy/dipy#389]
In the function dipy.recont.peaks.peak_directions, the option minmax_norm does not seem used. A proper normalization is done in peaks from model, but the old, inner function still accepts the arguments without doing anything.

The doc doesn't even speak about it anymore. So should it be removed, or should it be re-enabled so that one can use the function on an odf (while using peaks_from model on an odf doesn't really seem intuitive)?

**Comment by jchoude** [comment]
Bump! I encountered exactly the same thing.

@Garyfallidis @arokem What should be the behavior here? I think it should directly be done in this function, to allow users to use precomputed ODFs without going through peaks_from_model (which is my current use case).

**Comment by arokem** [comment]
Just to understand, do you suggest doing something like this: 

https://github.com/nipy/dipy/blob/master/dipy/direction/peaks.py#L468

in here: 

https://github.com/nipy/dipy/blob/master/dipy/direction/peaks.py#L92

Seems right to me.

**Comment by jchoude** [comment]
Well, it's either we do that when minmax_norm=True, or we remove the argument in peak_directions. Right now, there is no effect of setting or not setting the param.

Furthermore, I would personnally change the default to False, but that's debattable. If you want to extract the AFD along the peak directions, you need the values to not be normalized.

**Comment by arokem** [comment]
I am for adding this as an option (default as False seems fine to me --
it's the current behavior anyhow ;D). Do you want to make PR with that?

**Comment by skoudoro** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#389](https://trello.com/c/OmnRHFyK/5-389)
