### ISSUE TITLE
Add travis-ci test without matplotlib installed

### ISSUE THREAD

**Issue by matthew-brett** [nipy/dipy#400]
From discussion here: #397 

We should consider adding a travis test for which matplotlib is not installed, to test the conditional imports.  We already have this covered for the buildbots.

**Comment by skoudoro** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#400](https://trello.com/c/2UWJ9nqo/16-400)

**Comment by skoudoro** [comment]
As we can see [here](https://github.com/nipy/dipy/blob/master/.travis.yml#L40), this matrix exist so I'm closing this old issue
