### ISSUE TITLE
local variable 'ftmp' referenced before assignment

### ISSUE THREAD

**Issue by matthew-brett** [nipy/dipy#449]
I'm getting this warning at build time :

    warning: dipy\tracking\propspeed.pyx:403:20: local variable 'ftmp' referenced before assignment

Sure enough, ``ftmp`` does seem to be referenced before assignment;

```
          #ftmp=floor(tmp+.5)
            if ftmp > qa_shape[i]-1 or tmp < 0.:
                 d=0
                 break
```

I guess this is a bug?

**Comment by arokem** [comment]
Closed through #534
