### ISSUE TITLE
streamtubes opacity kwarg

### ISSUE THREAD

**Issue by arokem** [nipy/dipy#459]
Any value < 1 renders the streamtubes invisible.

**Comment by arokem** [comment]
See #627.

**Comment by arybinski** [comment]
I tried to replicate this issue and ran:
```python
import numpy as np
from dipy.viz import fvtk
r=fvtk.ren()
lines=[np.random.rand(10, 3), np.random.rand(20, 3)]
colors=np.random.rand(2, 3)
c=fvtk.streamtube(lines, colors, opacity=0.5)
fvtk.add(r,c)
fvtk.show(r)
```
and the opacity with streamtubes works with latest version of Dipy, at least on my machine

**Comment by arokem** [comment]
Confirmed that this is not an issue. I am not sure under what conditions I originally thought I saw it.
