### ISSUE TITLE
Use chatroom for dev communications

### ISSUE THREAD

**Issue by arokem** [nipy/dipy#555]
How about using gitter (https://gitter.im/nipy/dipy) as another channel for communications? I think that it would be nice to have a channel that provides this kind of quick online communication

**Comment by Garyfallidis** [comment]
Can you explain what is the usage of this platform and why we should use it? Already the mailing list and github is enough. No? Gitter can be used like a public chat for all dipy developers? What is the usage for this? Something similar to having an IRC channel for dipy? Please explain.

**Comment by arokem** [comment]
Yes - similar to an IRC channel for the development of dipy. Check out
https://gitter.im/ipython/ipython for example.

It's for all those times you feel like you wanted to send one of the other
developers a g-chat message about something related to dipy development,
except it's public and open for other developers to jump in as well.

The advantage over the mailing list is that it has zero latency and its
"opt in" (you can easily just close the browser window), so we can go into
nitty gritty details, like "check out this weird log from the build bot",
that we would not usually go into on the mailing list.

Github is good for discussing something that can be defined as an "issue",
like this discussion, but for tiny little micro-issues, it's not clear
where to go right now, so we sometimes end up defaulting to some
combination of google hangouts, mailing list, github issues, etc.

**Comment by jchoude** [comment]
Out of curiosity, is there a way to see all the log? I tried scrolling back
on the Ipython one and couldn't go past January 12th... Except if that,s
when they started using it, it would be understandable in that case...

2015-01-14 16:30 GMT-05:00 Ariel Rokem <notifications@github.com>:

> Yes - similar to an IRC channel for the development of dipy. Check out
> https://gitter.im/ipython/ipython for example.
>
> It's for all those times you feel like you wanted to send one of the other
> developers a g-chat message about something related to dipy development,
> except it's public and open for other developers to jump in as well.
>
> The advantage over the mailing list is that it has zero latency and its
> "opt in" (you can easily just close the browser window), so we can go into
> nitty gritty details, like "check out this weird log from the build bot",
> that we would not usually go into on the mailing list.
>
> Github is good for discussing something that can be defined as an "issue",
> like this discussion, but for tiny little micro-issues, it's not clear
> where to go right now, so we sometimes end up defaulting to some
> combination of google hangouts, mailing list, github issues, etc.
>
> On Wed, Jan 14, 2015 at 1:24 PM, Eleftherios Garyfallidis <

**Comment by arokem** [comment]
Seems like it should be possible to see history back for ever:

https://gitter.zendesk.com/hc/en-us/articles/202169471-Message-history

**Comment by Garyfallidis** [comment]
+1 from me to start using this.

**Comment by arokem** [comment]
OK - let's try it out for a while and see if it makes our lives any better.
