### ISSUE TITLE
Allow setting of the zoom on fvtk ren objects

### ISSUE THREAD

**Issue by arokem** [nipy/dipy#558]
I think that this call: 

https://github.com/nipy/dipy/blob/master/dipy/viz/fvtk.py#L1708

to ren.ResetCamera means that the zoom is always reset. Sometimes you want to zoom in close.

**Comment by skoudoro** [comment]
Hi @arokem, I know that is an old issue but it seems you can easily do `set_camera` and turn off `reset_camera` in `renderer class`  with the new viz API as you can see [here](https://github.com/nipy/dipy/blob/b2bbb257429ddabf2e43ad7e4bd98db119c4ff49/dipy/viz/window.py#L139) and below

Can you / I close this issue?

**Comment by skoudoro** [comment]
It seems to be resolved so closing
