### ISSUE TITLE
The documentation for `dipy.viz` is not in the API reference

### ISSUE THREAD

**Issue by arokem** [nipy/dipy#570]
No-where to be found here: http://nipy.org/dipy/reference/index.html

**Comment by skoudoro** [comment]
@arokem "dipy.viz" is defined as skip pattern. you can see on this link https://github.com/nipy/dipy/blob/master/doc/tools/build_modref_templates.py#L72

Any reason for that ? should I change it ?

**Comment by arokem** [comment]
Unless someone has a compelling reason not to include this in the documentation, please do change it. You can add that in #1255

**Comment by skoudoro** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#570](https://trello.com/c/QXr0MNXu/11-570)

**Comment by skoudoro** [comment]
website updated : http://nipy.org/dipy/reference/dipy.viz.html
