### ISSUE TITLE
Make a cython style guide

### ISSUE THREAD

**Issue by arokem** [nipy/dipy#583]
As proposed by @matthew-brett here: 

https://github.com/nipy/dipy/pull/533#issuecomment-76256571

**Comment by Garyfallidis** [comment]
What about this? Pep8 everywhere except from the limitation for the length of lines.
Which is now recommendation only. With nested for loops the length restriction becomes difficult to sustain.

**Comment by matthew-brett** [comment]
I was thinking more in terms of things like:

```
cimport numpy as cnp
import numpy a np
```

Use of npy_intp for anything holding an index or shape value, when to use the ndarray Cython syntax compared to the memoryviews compared to simple C arrays, how to use nogil to root out Python-side stuff and optimize speed, that kind of thing.

**Comment by arokem** [comment]
I, for one, could use all the help I could get on how to write cython code.

@matthew-brett - do you think you could draft up something as a PR?

**Comment by jhlegarreta** [comment]
@skoudoro following what was discussed in today's dev meeting, I would close this issue. IMHO, it is unlikely that it gets more updates. We do have a minimal style guide, and it is a starting point. If at some point we find that it needs more content, we may re-open the issue then or just open a PR with the new content.

**Comment by skoudoro** [comment]
ok, I agree, let's close it.
