### ISSUE TITLE
tracking module not building on cython 0.22

### ISSUE THREAD

**Issue by samuelstjean** [nipy/dipy#597]
Error compiling Cython file:
------------------------------------------------------------
...
        def __get__(Feature self):
            return bool(self.is_order_invariant)
        def __set__(self, int value):
            self.is_order_invariant = bool(value)

    cdef Shape c_infer_shape(Feature self, Data2D datum) nogil:
        ^
------------------------------------------------------------

dipy/segment/featurespeed.pyx:39:9: Signature not compatible with previous declaration

Error compiling Cython file:
------------------------------------------------------------
...

cdef class Feature(object):
    cdef int is_order_invariant

    cdef Shape c_infer_shape(Feature self, Data2D datum) nogil except *
                           ^
------------------------------------------------------------

dipy/segment/featurespeed.pxd:7:28: Previous declaration is here

+++++++++++++++++

Seems like those except * are causing trouble for whatever reason. My fork has problems with the tracking module (while it has always been working before of course), but the latest master has a ton more issues. No buildbot error or anything else for anyone?

**Comment by MarcCote** [comment]
The code you show is part of the segment module, not the tracking one.
What version of Cython do you have?

**Comment by MarcCote** [comment]
Ah ok, Cython 0.22 :P

**Comment by samuelstjean** [comment]
0.22, it pretty much breaks everything in existence, including my fork dating back from september in the tracking module + the current master as shown above with the segment module.
