### ISSUE TITLE
Retired ARM buildbot

### ISSUE THREAD

**Issue by matthew-brett** [nipy/dipy#604]
I just retired the raspberry pi from building dipy, it was running out of memory on the build step, and fair enough, the poor little thing is not designed for hard work like that...

**Comment by Garyfallidis** [comment]
Such a hard worker! It died with honour and lived a good useful life. We will remember the small pi....

**Comment by matthew-brett** [comment]
The final goodbye : http://nipy.bic.berkeley.edu/builders/dipy-py2.6-arm/builds/204/steps/shell_5/logs/stdio

**Comment by Garyfallidis** [comment]
Goodbye... little pi... Dipy 0.9.2 was your last release.

**Comment by arokem** [comment]
Moving right along. Closing.
