### ISSUE TITLE
Extend the AUTHOR list with more information

### ISSUE THREAD

**Issue by arokem** [nipy/dipy#620]
See discussion here: https://github.com/nipy/dipy/pull/619

**Comment by skoudoro** [comment]
can you close this one @arokem  ?

**Comment by arokem** [comment]
No. We haven't done this yet.

**Comment by skoudoro** [comment]
After this PR #1368, can we close this issue?

**Comment by skoudoro** [comment]
Hi @arokem,

Closing this one, I think #1368 is doing the job and the next step is #1725. Feel free to reopen it!
