### ISSUE TITLE
Fast shm from scipy 0.15.0 does not work on rc version

### ISSUE THREAD

**Issue by samuelstjean** [nipy/dipy#622]
The strict version checker for the new shm function does not play well with non release version of scipy sadly, and everything breaks.

  File "/home/mpizzola/workspace/modules/scilpy/scilpy/denoising/smoothing.py", line 8, in <module>
  from dipy.reconst.shm import sph_harm_ind_list, real_sph_harm, lazy_index
  File "/user/mpizzola/home/workspace/modules/dipy/reconst/shm.py", line 43, in <module>
  if StrictVersion(scipy.version.short_version) >= StrictVersion('0.15.0'):
  File "/home/mpizzola/Installations/canopy/appdata/canopy-1.2.0.1610.rh5-x86_64/lib/python2.7/distutils/version.py", line 40, in _init_
  self.parse(vstring)
  File "/home/mpizzola/Installations/canopy/appdata/canopy-1.2.0.1610.rh5-x86_64/lib/python2.7/distutils/version.py", line 107, in parse
  raise ValueError, "invalid version number '%s'" % vstring
ValueError: invalid version number '0.14.1rc1'

**Comment by Garyfallidis** [comment]
The problem is that Marco has an invalid version number. Is that correct @matthew-brett ?

**Comment by matthew-brett** [comment]
He does have an invalid version number according to strict checking, but it is scipy's version number not Marco's.  I suspect that all non-release scipy version strings (rc1, dev etc) previous to the current scipy development version will fail this check.

**Comment by Garyfallidis** [comment]
Maybe the easiest fix would be that Marco upgrades to 0.14.1 or 0.15.0?
https://github.com/scipy/scipy/releases
Should we use LooseVersion to resolve this issue? What do you suggest?

**Comment by matthew-brett** [comment]
Is there any reason not to use LooseVersion?  It is annoying to force people to upgrade scipy unless there is a good reason.

**Comment by Garyfallidis** [comment]
I don't know. That is why I am asking you. If not we can then use LooseVersion.

**Comment by matthew-brett** [comment]
git blame says that Ariel put that check in - @arokem - any reason for the StrictVersion check in shm at line 43?

**Comment by arokem** [comment]
No - no particular reason. Seems like I was trying to deal with something
similar:

https://github.com/nipy/dipy/commit/4bce82e60ca6f16429b1f6016032183658dfe3b6

We should probably do the same that we do in core.optimize (i.e.
LooseVersion).

**Comment by Garyfallidis** [comment]
Okay, great can you make a quick PR?

**Comment by arokem** [comment]
Who is "you"?

**Comment by Garyfallidis** [comment]
Dr. Ariel Rokem! The Cool Dude!

**Comment by arokem** [comment]
Closed through #626 ?

**Comment by samuelstjean** [comment]
We should ask Marco, I was walking him through some code and everything broke in his face and I merely reported the issue.

**Comment by arokem** [comment]
Yes - please do ask Marco.

**Comment by arokem** [comment]
Any news on this? Can we close?

**Comment by samuelstjean** [comment]
Ask Marco, no idea if he has a github account though.

**Comment by arokem** [comment]
I don't know who Marco is.

**Comment by samuelstjean** [comment]
Oh right, I'll email then I guess.

**Comment by samuelstjean** [comment]
Well, he actually installled 0.15 in the meantime, so I'll try a virtualenv or something with a dev version I guess.

**Comment by arokem** [comment]
Thanks for following up on this!

**Comment by arokem** [comment]
Any conclusions here?

**Comment by samuelstjean** [comment]
Seems good, it does not crash and gives the right thing

In [1]: from distutils.version import LooseVersion

In [2]: version =  '0.14.1rc1'

In [3]:  LooseVersion(version) >= LooseVersion('0.15.0')
Out[3]: False

In [4]: version =  'wathever-0.17'

In [5]: LooseVersion(version) >= LooseVersion('0.15.0')
Out[5]: True
