### ISSUE TITLE
Possible documentation bug (?)

### ISSUE THREAD

**Issue by arokem** [nipy/dipy#630]
Is this description of the `affine` argument actually in the right direction? 

https://github.com/nipy/dipy/blob/master/dipy/tracking/utils.py#L451

Later in the code, this affine is used to transform streamlines to voxels: 

https://github.com/nipy/dipy/blob/master/dipy/tracking/utils.py#L478

**Comment by MrBago** [comment]
Ya it is, we take the inverse of the affine. The idea is that if you have,
for example, a nifti file and tracks in the mm space of the image you can
just pass the affine from the image. The code inverts the affine in
_mapping_to_voxel. We also use the same affine, vox to mm, in Local
Tracking. Hopefully by always using the vox to mm affine, and doing any
needed inverting ourselves, we make it less confusing for the user.

Bago

**Comment by arokem** [comment]
Oh yes - here it is: https://github.com/nipy/dipy/blob/master/dipy/tracking/_utils.py#L45. 

OK - I will try to follow this convention in some new stuff as well. Thanks for the swift reply! Closing this issue.
