### ISSUE TITLE
tutorial example, code in text format

### ISSUE THREAD

**Issue by StongeEtienne** [nipy/dipy#638]
http://nipy.org/dipy/examples_built/reconst_csd.html#example-reconst-csd

Code line, wish appear as text
data_small = data[20:50, 55:85, 38:39] csd_fit = csd_model.fit(data_small)

is not in code format, so this line doest compile (csd_fit doesnt exist) :
csd_odf = csd_fit.odf(sphere)

**Comment by arokem** [comment]
Thanks for noticing and reporting!

https://github.com/nipy/dipy/pull/639

**Comment by arokem** [comment]
Close through #639.
