### ISSUE TITLE
Tests raise a deprecation warning

### ISSUE THREAD

**Issue by arokem** [nipy/dipy#641]
`UserWarning: This function is deprecated please use dipy.align.reslice.reslice instead.`

**Comment by arokem** [comment]
More deprecation warnings: 

```/Users/arokem/anaconda/lib/python3.5/site-packages/scikit_image-0.12.dev0-py3.5-macosx-10.5-x86_64.egg/skimage/filter/__init__.py:6: skimage_deprecation: The `skimage.filter` module has been renamed to `skimage.filters`.  This placeholder module will be removed in v0.13.
  warn(skimage_deprecation('The `skimage.filter` module has been renamed '```

**Comment by arokem** [comment]
```/Users/arokem/source/dipy/dipy/workflows/docstring_parser.py:145: UserWarning: Unknown section Yields
  warn("Unknown section %s" % key)```

**Comment by OrkoHunter** [comment]
I'm on it !

We can have a `expected_warnings()` context in similar fashion as [scikit-image](https://github.com/scikit-image/scikit-image/blob/master/skimage/_shared/_warnings.py#L77), for the warnings which are not to be eliminated but are expected to be raised.

**Comment by OrkoHunter** [comment]
Oops ! This issue is actually about deprecation warnings only, but I think I overlooked and worked on every warning being raised.

**Comment by skoudoro** [comment]
Hi @arokem, 

Should we keep this issue? Can we close it? What should we fix exactly?

**Comment by arokem** [comment]
We can probably close this one.
