### ISSUE TITLE
Use appveyor for Windows CI?

### ISSUE THREAD

**Issue by arokem** [nipy/dipy#643]
http://www.appveyor.com/

Here's how astropy does it: https://github.com/astropy/astropy/tree/master/.continuous-integration

**Comment by stefanv** [comment]
AppVeyor build times fluctuate quite a lot for scikit-image.  We 
decided to do our tests without Conda, so here is how you'd go 
about doing that:

https://github.com/scikit-image/scikit-image/blob/master/appveyor.yml

**Comment by souravsingh** [comment]
I would like to work on the issue.Where do I start?

**Comment by arokem** [comment]
This is still going on over at #787

**Comment by skoudoro** [comment]
Appveyor is ON and #787 is merged! Closing
