### ISSUE TITLE
Dipy visualization: it does not seem possible to position tensor ellipsoid slice in fvtk

### ISSUE THREAD

**Issue by mick-d** [nipy/dipy#644]
I am trying to display tensor information with `fvtk.tensor` and add other information such as streamlines or FA slices but they do not align. It seems like `fvtk.tensor` does not have a parameter to set the 3D position of a slice.

For example I do not see any option to change the z-position of the axial slice below in the visualization. Plotting another axial slice (`iAxial = 25`) will simply be overlaid over the previous one (`iAxial = 20`).

```
iAxial = 20
fvtk.add(r, fvtk.tensor(tenfit.evals[:,:,iAxial:iAxial+1], tenfit.evecs[:,:,iAxial:iAxial+1], RGB_scaled[:,:,iAxial:iAxial+1], sphere))
iAxial = 25
fvtk.add(r, fvtk.tensor(tenfit.evals[:,:,iAxial:iAxial+1], tenfit.evecs[:,:,iAxial:iAxial+1], RGB_scaled[:,:,iAxial:iAxial+1], sphere))
fvtk.show(r)
```

**Comment by skoudoro** [comment]
Hi @mick-d,  I know this is a quite old issue :-) but currently,  You can easily set your slice with `tensor_slicer.display_extent`.  I close this issue but feel free to reopen it if needed.  you have an example [on this test](https://github.com/nipy/dipy/blob/master/dipy/viz/tests/test_actors.py#L572)  or below:

```
from dipy.viz import actor, window
from dipy.data import get_sphere
import numpy as np

# setup the data
evals = np.array([1.4, .35, .35]) * 10 ** (-3)
evecs = np.eye(3)
mevals = np.zeros((3, 2, 4, 3))
mevecs = np.zeros((3, 2, 4, 3, 3))
mevals[..., :] = evals
mevecs[..., :, :] = evecs
sphere = get_sphere('symmetric724')
affine = np.eye(4)
    
renderer = window.Renderer()
tensor_actor = actor.tensor_slicer(mevals, mevecs, affine=affine, sphere=sphere,  scale=.3)
I, J, K = mevals.shape[:3]
renderer.add(tensor_actor)
renderer.reset_camera()
renderer.reset_clipping_range()

tensor_actor.display_extent(0, 1, 0, J, 0, K)
window.show(renderer, reset_camera=False)
```
