### ISSUE TITLE
ROI seeds not placed at the center of the voxels

### ISSUE THREAD

**Issue by mick-d** [nipy/dipy#649]
I am trying to perform tractography from a ROI and create seeds at the center of each voxel of this ROI.

The ROI includes 8 voxels: 9 voxels forming a square (in a single sagittal slice), less one corner voxel. To create seeds at the center of each voxel, do the tractography and display the results, I run the following commands:
```
tenmodel = dti.TensorModel(my_gradient_table)
tenfit = tenmodel.fit(my_dmri_data)
seeds = seeds_from_mask(my_ROI_data, density=[1, 1, 1])
sphere = get_sphere('symmetric724')
ind = quantize_evecs(tenfit.evecs, sphere.vertices)
eu = EuDX(a=tenfit.fa, ind=ind, seeds=seeds, odf_vertices=sphere.vertices, a_low=.15)
streamlines = list(eu)
r = fvtk.ren()
fvtk.add(r, fvtk.line(streamlines, line_colors(streamlines)))
fvtk.add(r, fvtk.slicer(my_ROI_data, plane_i=[49], plane_j=None, plane_k=None, outline=False))
fvtk.show(r)
```
The seeds still do not seem at the center of the voxels as shown by the `streamlines` object `seed_list` attribute:
```
> streamlines.seed_list
array([[ 49.,  38.,  24.],
       [ 49.,  38.,  25.],
       [ 49.,  38.,  26.],
       [ 49.,  39.,  24.],
       [ 49.,  39.,  25.],
       [ 49.,  39.,  26.],
       [ 49.,  40.,  25.],
       [ 49.,  40.,  26.]])
```
And as seen on the image below. Then is there a solution to generate the streamlines at the voxels centre?
![toy_seed2](https://cloud.githubusercontent.com/assets/4580257/7614418/acc9bc4c-f964-11e4-9e3a-f311cc7a8981.png)

**Comment by MrBago** [comment]
This is a problem with fvtk not with the seeds. Dipy uses the convention as the nifti standard for real world coordinates which means that, assuming a diagonal affine, the center of each voxel is at an integer multiple of the voxel size. Based on your seed_list array it seems like you have (1, 1, 1) voxels and the seeds are in the centers of those voxels.

Unfortunatly the current fvtk has some issues, but @Garyfallidis is already on the case :) see #587.

**Comment by mick-d** [comment]
Thanks for your answer Bago. If the voxel size are integers (i did not use
the real size due to other issues with fvtk), the voxel centers should be
half-integers, so why is it not the case?

**Comment by MrBago** [comment]
It depends on whether you think of voxels as little boxes going from (0, 0,
0) to (1, 1, 1) or as points at live at a single point :). The nifti folks
decided to treat them as points and we kept their convention. The signal
value sorted at index (i, j, k) is associated with point (x, y, z) where
(x, y, z, 1) = A @ (i, j, k, 1). A is the affine matrix and @ is matrix
multiply. If A == eye(4), then the points live on a grid that goes from (0,
0, 0) to (Nx - 1, Ny - 1, Nz - 1). The point (.5, 0, 0) lies half way
between the points (0, 0, 0) and (1, 0, 0).

If you read the latest dipy tracking examples, I'm trying to push people to
always use the affine matrix any time points need to be associated with
volumes. This makes keeping tracking of all this much more explicit and
strait forward. I think as fvtk gets re-factored we need to make sure that
all actor objects have proper affine support.

Hope that's useful,
Bago

**Comment by mick-d** [comment]
Thanks a lot for your feedback Bago. It looks like I will just have to double-check the streamlines in another way for now.

**Comment by arokem** [comment]
It seems that this discussion has been resolved. I am closing it.
