### ISSUE TITLE
Development documentation instructs to remove `master`

### ISSUE THREAD

**Issue by arokem** [nipy/dipy#655]
Is that really a good idea?

I wasn't sure how to rebase on top of upstream/master from a feature branch in this configuration.

**Comment by matthew-brett** [comment]
I think it is a good idea, to avoid very common confusion as to which
'master' you have.

For simplicity I recommend rebasing on `upstream/master` or equivalent.

I sometimes have a local branch 'main-master' that tracks upstream master.

**Comment by arokem** [comment]
How do you go about creating a `main-master` branch once you have nuked the
`master` branch, if all the branches you have are feature branches that
have diverged from `master`?

**Comment by matthew-brett** [comment]
You can't easily nuke the upstream reference, so:

`git branch main-master -t upstream/master`

**Comment by arokem** [comment]
You might want to add that here: http://matthew-brett.github.io/pydagogue/gh_delete_master.html
