### ISSUE TITLE
Build-bot status

### ISSUE THREAD

**Issue by arokem** [nipy/dipy#656]
This can be seen on the buildbots: 

http://nipy.bic.berkeley.edu/builders/dipy-py2.7-osx-10.8/builds/362/steps/shell_5/logs/stdio

And I also get this on my machine after pulling from `master`. I believe @RafaelNH is seeing something similar on his machine as well.

**Comment by omarocegueda** [comment]
It seems like it is complaining about cimport-ing inline functions. I think it makes sense that doing that is not valid, but it's weird that it works on other platforms (e.g. Travis and windows)

**Comment by arokem** [comment]
It's failing on Windows as well:
http://nipy.bic.berkeley.edu/builders/dipy-bdist32-33/builds/126/steps/shell_6/logs/stdio

**Comment by omarocegueda** [comment]
Oh! you're right! I tested this on linux and windows 8.1 with no issues. I'm checking what's the problem with defining pointers to inline functions (that's what cython is trying to do). It may be an undefined behavior which is handled differently by different compilers.

**Comment by omarocegueda** [comment]
I think this is a cython bug. We can actually define a pointer to an inline function as follows:
```
#include <stdio.h>
int inline my_inline(int x){
    return 2*x;
}
static int (*fpointer)(int);

int main(){
    fpointer = my_inline;
    int y = fpointer(5);
    printf("%d\n", y);
    return 0;
}
```
The above code compiles and runs with output `10`. However if we add `inline` to the `fpointer` variable, it will of course fail, because a variable cannot be declared as inline. So, Cython should remove the CYTHON_INLINE prefix to the declaration. However we should see this error everywhere, not just on some platforms... still investigating...

**Comment by omarocegueda** [comment]
Ok, according to his:
http://docs.cython.org/src/tutorial/pxd_files.html
inline functions should be defined (not just declared) in the pxd. I'll try_branch with that...

**Comment by omarocegueda** [comment]
Oh! no! I no longer have access to the buildbots =( 
WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!
I cannot try_branch, any ideas?

**Comment by matthew-brett** [comment]
Omar - sorry - we comprehensively upgraded the server, and that included
getting a new server key.

It's no problem I think - however you are using ssh, you should get some
more text with that error telling you that, if you believe the server is
OK, you should delete the old line from the `known_hosts` file and try
again.

For the Cython bug - if you think this is a bug - would you mind reporting
to the Cython issues or mailing list?

**Comment by arokem** [comment]
#657 seems to have helped with a lot of our bots, but this one seems to be lacking nibabel: 

http://nipy.bic.berkeley.edu/builders/dipy-py2.7-osx-10.6/builds/438/steps/shell_5/logs/stdio

And there's this mysterious one: 

http://nipy.bic.berkeley.edu/builders/dipy-py3.3/builds/369/steps/shell_6/logs/stdio

Other bots are now up-to-date with recent scipy, so they have this one: 

http://nipy.bic.berkeley.edu/builders/dipy-py2.7-win32/builds/249/steps/shell_6/logs/stdio

That should be fixed with #612 

This one's new (to me), and most likely related to #629:

http://nipy.bic.berkeley.edu/builders/dipy-py2.6-32/builds/541/steps/shell_6/logs/stdio

Anyone know what that's all about?

**Comment by matthew-brett** [comment]
I think I fixed the problem with nibabel being missing - that was a configuration change for the buildbots, that I hadn't finished cleaning up.

I can replicate:

http://nipy.bic.berkeley.edu/builders/dipy-py3.3/builds/369/steps/shell_6/logs/stdio

with just `np.load('dev_trees/dipy/dipy/data/t1_coronal_slice.npy')` on Python 3.3 using numpy 1.7.1 through 1.8.1 (haven't tested 1.8.2 or 1.9.0).  Maybe this is a problem with the npy file format?

**Comment by matthew-brett** [comment]
Relevant SO post here: http://stackoverflow.com/questions/27145273/compatibility-numpy-1-7-vs-numpy-1-8

I just tried loading and resaving the file with numpy 1.9.2 - seems to work. 

https://github.com/nipy/dipy/pull/658

**Comment by matthew-brett** [comment]
Just set off a build : http://nipy.bic.berkeley.edu/builders/dipy-py3.3/builds/370  

I won't be online to see it finish, probably.

**Comment by arokem** [comment]
OK - I will monitor that and merge if/when it comes back green.

**Comment by matthew-brett** [comment]
Looks to be passing the tests that were failing earlier : 

http://nipy.bic.berkeley.edu/builders/dipy-py3.3/builds/370/steps/shell_6/logs/stdio

**Comment by omarocegueda** [comment]
Thanks Matthew!,
I guess it should be possible to detect when a function is inline and just
remove the CYTHON_INLINE from the pointer declaration in that case. But
since moving the inline functions to the pxd solved the issue (and since it
is actually documented), it would be more a feature request rather than a
bug.

On Tue, May 26, 2015 at 9:39 AM, Matthew Brett <notifications@github.com>
wrote:

> Omar - sorry - we comprehensively upgraded the server, and that included
> getting a new server key.
>
> It's no problem I think - however you are using ssh, you should get some
> more text with that error telling you that, if you believe the server is
> OK, you should delete the old line from the `known_hosts` file and try
> again.
>
> For the Cython bug - if you think this is a bug - would you mind reporting
> to the Cython issues or mailing list?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nipy/dipy/issues/656#issuecomment-105547332>.
>



-- 
"Cada quien es dueño de lo que calla y esclavo de lo que dice"
-Proverbio chino.
"We all are owners of what we keep silent and slaves of what we say"
-Chinese proverb.

http://www.cimat.mx/~omar

**Comment by arokem** [comment]
This one seems to be outdated - closing.
