### ISSUE TITLE
Online tutorial of quickbundles does not work for released version on macosx

### ISSUE THREAD

**Issue by Garyfallidis** [nipy/dipy#665]
Possible cause is that the api has changed between the development and the released version.

**Comment by MarcCote** [comment]
What kind of errors do you get?

**Comment by jmollink** [comment]
Is there any workaround for this issue?

**Comment by arokem** [comment]
The version online is from the bleeding edge of our github repo. Try using an older version of the tutorial: https://github.com/nipy/dipy/blob/0.8.0/doc/examples/segment_quickbundles.py

**Comment by MarcCote** [comment]
Dipy 0.8 is quite old. In Dipy 0.9 the new QuickBundles (faster) uses the new clustering framework.
@jmollink can you paste the error it gives you?

**Comment by jmollink** [comment]
@MarcCote in the online quickbundles tutorial (http://nipy.org/dipy/examples_built/segment_quickbundles.html), the line:

clusters = qb.cluster(streamlines)

Gave the following error: 

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jmollink/anaconda/lib/python2.7/site-packages/dipy/segment/clustering.py", line 459, in cluster
    ordering=ordering)
  File "dipy/segment/clustering_algorithms.pyx", line 110, in dipy.segment.clustering_algorithms.quickbundles (dipy/segment/clustering_algorithms.c:3293)
  File "dipy/segment/clusteringspeed.pyx", line 277, in dipy.segment.clusteringspeed.QuickBundles.assignment_step (dipy/segment/clusteringspeed.c:3970)
ValueError: All features do not have the same shape! QuickBundles requires this to compute centroids!

I'm not a python expert, so wasn't sure whether this had anything to do with my own lack of skills until I saw this thread. Using the older version of the tutorial as suggest by @arokem worked fine for me. 

Thanks,
Jeroen

**Comment by MarcCote** [comment]
@jmollink ok yes, I confirmed that you must have dipy 0.9 (which is the latest stable release). So you should use this tutorial [Dipy 0.9 - Segment streamlines with QuickBundles](https://github.com/nipy/dipy/blob/maint/0.9.x/doc/examples/segment_quickbundles.py).

In that tutorial, notice the following line:
`streamlines = set_number_of_points(streamlines, nb_points=18)`

All streamlines will be modified to have the same number of points (which is required by QuickBundles algorithm)! If needed, you can keep a copy of the streamlines like this:
`resampled_streamlines = set_number_of_points(streamlines, nb_points=18)`

And use `resampled_streamlines` when doing the clustering:
`clusters = qb.cluster(resampled_streamlines)`.

@Garyfallidis @arokem how is that the tutorials on http://dipy.org do not reflect the latest stable Dipy release?

**Comment by arokem** [comment]
On Wed, Jul 29, 2015 at 6:31 AM, Marc-Alexandre Côté <
notifications@github.com> wrote:

> @jmollink <https://github.com/jmollink> ok yes, I confirmed that you must
> have dipy 0.9 (which is the latest stable release). So you should use this
> tutorial Dipy 0.9 - Segment streamlines with QuickBundles
> <https://github.com/nipy/dipy/blob/maint/0.9.x/doc/examples/segment_quickbundles.py>
> .
>
> In that tutorial, notice the following line:
> streamlines = set_number_of_points(streamlines, nb_points=18)
>
> All streamlines will be modified to have the same number of points (which
> is required by QuickBundles algorithm)! If needed, you can keep a copy of
> the streamlines like this:
> resampled_streamlines = set_number_of_points(streamlines, nb_points=18)
>
> And use resampled_streamlines when doing the clustering:
> clusters = qb.cluster(resampled_streamlines).
>
> @Garyfallidis <https://github.com/Garyfallidis> @arokem
> <https://github.com/arokem> how is that the tutorials on http://dipy.org
> do not reflect the latest stable Dipy release?
>
>
We occasionally update the content on the website independently of the
release cycle. For example, when we want to advertise that we will be at a
conference. At that point, the current state of the docs on `master` gets
rendered into the examples, which means that we end up with these kinds of
discrepancies. Hopefully this situation will be remedied once we're done
with the GSoC work and have another release cycle (mid-September?)

**Comment by MarcCote** [comment]
This issue should be fixed by the incoming release.

**Comment by arokem** [comment]
0.10 is now out. Presumably resolved. Closing
