### ISSUE TITLE
dipy.test() fails on centos 6.x / python2.6

### ISSUE THREAD

**Issue by hassemlal** [nipy/dipy#688]
Hi,
I tried running the dipy test suite, but it returns multiple failures (see below). I am running on centos 6.5 with python2.6 and virtualenv.

```
$ python -c "import dipy; dipy.test()"
.................Running unit tests for dipy
NumPy version 1.9.2
NumPy is installed in /home/hassemlal/dipy/venv/lib/python2.6/site-packages/numpy
Python version 2.6.6 (r266:84292, Jan 22 2014, 09:42:36) [GCC 4.4.7 20120313 (Red Hat 4.4.7-4)]
nose version 1.3.7

[clip]

.........SS.........
======================================================================
FAIL: dipy.core.tests.test_sphere.test_interp_rbf
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/hassemlal/dipy/venv/lib/python2.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/hassemlal/dipy/dipy/core/tests/test_sphere.py", line 374, in test_interp_rbf
    nt.assert_(np.mean(np.abs(interp_data_a - expected)) < 0.1)
  File "/home/hassemlal/dipy/venv/lib/python2.6/site-packages/numpy/testing/utils.py", line 53, in assert_
    raise AssertionError(smsg)  
AssertionError

======================================================================
FAIL: dipy.reconst.tests.test_csdeconv.test_odfdeconv
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/hassemlal/dipy/venv/lib/python2.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/hassemlal/dipy/dipy/reconst/tests/test_csdeconv.py", line 220, in test_odfdeconv
    assert_equal(len(w) > 0, False)
  File "/home/hassemlal/dipy/venv/lib/python2.6/site-packages/numpy/testing/utils.py", line 334, in assert_equal
    raise AssertionError(msg)   
AssertionError:
Items are not equal:
 ACTUAL: True
 DESIRED: False

======================================================================
FAIL: dipy.segment.tests.test_metric.test_metric_cosine
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/hassemlal/dipy/venv/lib/python2.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/hassemlal/dipy/dipy/segment/tests/test_metric.py", line 177, in test_metric_cosine
    assert_equal(distance, 0.)  
AssertionError: array([[  4.74318692e-09]]) != 0.0

----------------------------------------------------------------------
Ran 451 tests in 1043.841s

FAILED (SKIP=9, failures=3)
```

**Comment by arokem** [comment]
The RBF test failure is also reproduced on my laptop, mac OS 10.10 with Python 3.4

**Comment by arokem** [comment]
The cosine test also looks familiar: http://nipy.bic.berkeley.edu/builders/dipy-bdist32-34/builds/129/steps/shell_8/logs/stdio

**Comment by hanke** [comment]
Hi,

the test_interp_rbf failure is currently holding up a bugfix upload to Debian. Build log with failure is here

https://bugs.debian.org/cgi-bin/bugreport.cgi?msg=12;bug=785991;att=1;filename=dipy_0.9.2-2_amd64-20150825-2109.build

I already found the commit that is supposed to fix the other failure.

**Comment by arokem** [comment]
Sorry for the delay on this one. For now, a little bit more information:
this happens upon upgrading from scipy 0.15 to scipy 0.16.

**Comment by arokem** [comment]
This is happening when using the "angle" norm option: 

![download](https://cloud.githubusercontent.com/assets/118582/9506477/37815c06-4bfd-11e5-9808-b1740bd3b552.png)

**Comment by arokem** [comment]
Here's the diff for the RBF code between scipy 0.15 and 0.16: 

https://github.com/scipy/scipy/compare/v0.15.0...v0.16.0#diff-ab6ec58ea7c610075c487a649a4170e2R186

The only thing I can see that might be offensive is the treatment of epsilon. Digging into that.

**Comment by arokem** [comment]
The change to this behavior changed here: 

https://github.com/scipy/scipy/pull/4643

As a solution to the problem described here:

https://github.com/scipy/scipy/issues/4523

I'll ping the scipy dev list about this.

**Comment by arokem** [comment]
Also relevant: https://github.com/scipy/scipy/issues/2020

**Comment by arokem** [comment]
Also: http://mail.scipy.org/pipermail/scipy-dev/2015-August/020912.html

**Comment by stefanv** [comment]
@arokem Any idea why the new epsilon estimation (mean distance between nodes) is worse for our use case?

**Comment by arokem** [comment]
Not a clue, but there seems to be some shakiness on the scipy side
surrounding this as well.

**Comment by stefanv** [comment]
Is this something we should look into?  We can merge the current change, which will make dipy backward compatible with newer versions of scipy, or we can try to figure out a good heuristic.

**Comment by arokem** [comment]
How about adding a few more tests to see whether this is indeed a good
heuristic for a few more test cases? Would that be enough, barring actual
deep understanding of what's going on here (which I will also attempt, but
can't promise to actually achieve...).

**Comment by stefanv** [comment]
Excellent idea!

**Comment by arokem** [comment]
Hey @hassemlal - is this still an issue for you? Should be fixed through #707

**Comment by hassemlal** [comment]
Hi Ariel,
I gave it a try today on commit f0d46ce01c01702e2bf53bb1e6b3e49f7a913afb. The tests run fine, thank you for fixing it.

**Comment by Garyfallidis** [comment]
Cool! Thx for the feedback @hassemlal.
