### ISSUE TITLE
In current segment_quickbundles tutorial there is no example for changing number of points

### ISSUE THREAD

**Issue by Garyfallidis** [nipy/dipy#715]
This makes it difficult for people who were used to the previous version of the algorithm. And they may not that the default is 12. I suggest to add the ResampleFeature in this first tutorial.

**Comment by MarcCote** [comment]
In PR #682 we now mention the fact that we can change that number of points and link toward the tutorial. See https://github.com/nipy/dipy/pull/682/files#diff-4fd5bda93a614a7c76b8af7cf10de023R40

**Comment by arokem** [comment]
Where does that one stand, by the way? I made a couple of suggestions there, but the discussion kinda fizzled.

**Comment by MarcCote** [comment]
Fixed in PR #682.
