### ISSUE TITLE
Many interpolation functions in different places can they all go to same module?

### ISSUE THREAD

**Issue by Garyfallidis** [nipy/dipy#728]
Hi all,
we have different interpolation functions in different places. Should they all or some of them go to one place? Maybe dipy.core.interpolation?
I can see for example that we have trilinear interpolation in viz, tracking, denoising and align. Many of these do different things. So I would like to hear some opinions here. @MrBago, @omarocegueda ?
Otherwise, maybe I can make a start and move my trilinear interpolation function to dipy.core.interpolation and then we see how it goes. By the way this is a non-critical issue. So put it in lower priority. But at the same it is good to try not to replicate code when it makes sense and stick to a good practice.

**Comment by samuelstjean** [comment]
Where is the interpolation in the denoising module? There is only a mirror padding as I recall.

**Comment by Garyfallidis** [comment]
yeah okay.

**Comment by omarocegueda** [comment]
+1 for dipy.core.interpolation!

**Comment by jchoude** [comment]
Has anyone touched this?
