### ISSUE TITLE
One viz test still failing on mac os

### ISSUE THREAD

**Issue by arokem** [nipy/dipy#758]
At least on my laptop. Let's see what the buildbots have to say about that, though. 

I will also try to debug this locally.

```
======================================================================
FAIL: dipy.viz.tests.test_fvtk_widgets.test_text_widget
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/arokem/anaconda/envs/py2/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/arokem/anaconda/envs/py2/lib/python2.7/site-packages/nose/util.py", line 620, in newfunc
    return func(*arg, **kw)
  File "/Users/arokem/source/dipy/dipy/testing/decorators.py", line 63, in test_with_xvfb
    my_test()
  File "/Users/arokem/anaconda/envs/py2/lib/python2.7/site-packages/numpy/testing/decorators.py", line 146, in skipper_func
    return f(*args, **kwargs)
  File "/Users/arokem/anaconda/envs/py2/lib/python2.7/site-packages/numpy/testing/decorators.py", line 146, in skipper_func
    return f(*args, **kwargs)
  File "/Users/arokem/source/dipy/dipy/viz/tests/test_fvtk_widgets.py", line 180, in test_text_widget
    npt.assert_equal(report.objects, 3)
  File "/Users/arokem/anaconda/envs/py2/lib/python2.7/site-packages/numpy/testing/utils.py", line 354, in assert_equal
    raise AssertionError(msg)
AssertionError: 
Items are not equal:
 ACTUAL: 492
 DESIRED: 3
```

**Comment by arokem** [comment]
This is the spot to follow along: http://nipy.bic.berkeley.edu/builders/dipy-py2.7-osx-10.7/builds/353

**Comment by Garyfallidis** [comment]
This is the one we know about correct? Some driver issue on Macosx with the screenshot.

**Comment by Garyfallidis** [comment]
Sorry I mean ``snapshot``.

**Comment by arokem** [comment]
Yes - that's the one. Just want to make sure we don't lost track.

**Comment by Garyfallidis** [comment]
These buildbots may not have VTK I believe. Those tests were skipped before. And they should stay this way. I think we need to be slowly progressing on enabling visual tests in all platforms. Snapshot was designed for start for Linux.

**Comment by arokem** [comment]
Yeah - but users are going to run these tests. It's great to have tests that run on one platform, but it's truly invaluable to have tests that run robustly on all platforms.

**Comment by arokem** [comment]
Agree that we need to figure this out locally, before we start running this on the bots, though.

**Comment by Garyfallidis** [comment]
Yes, but we don't know if that is feasible with visual tests in all platforms.

**Comment by Garyfallidis** [comment]
The idea with snapshot was that it would be completely stealthmode.

**Comment by Garyfallidis** [comment]
But what we see is that offscreen renderering is not supported by all OS with VTK

**Comment by Garyfallidis** [comment]
And there are also differences even in Linux with VTK 5 and 6. Differences that are difficult to monitor. The same with ordered transparency.

**Comment by Garyfallidis** [comment]
What we could do is for the tests that fail in the Mac using record instead and analyze the png (rather than using snapshot). Record is a bit more robust and the problem we had before where sometimes the recorded png was completely black is now resolved using render.reset_clipping_plane.

**Comment by arokem** [comment]
This one's resolved. Closing.
