### ISSUE TITLE
How to resolve python-vtk6 link issues in Ubuntu 

### ISSUE THREAD

**Issue by Garyfallidis** [nipy/dipy#759]
Moving back to python-vtk6 from vtk5(python-vtk) creates an error

```
<ipython-input-1-b7e11aadda62> in <module>()
----> 1 import vtk

/usr/lib/python2.7/dist-packages/vtk/__init__.py in <module>()
37 
38 # --------------------------------------
---> 39 from vtkCommonCore import *
40 from vtkCommonMath import *
41 from vtkCommonMisc import *

/usr/lib/python2.7/dist-packages/vtk/vtkCommonCore.py in <module>()
----> 1 from vtkCommonCorePython import *

ImportError: No module named vtkCommonCorePython
```

The resolution was to relink the broken so files

```
So I went to /usr/lib/x86_64-linux-gnu and ran for i in *-6.0.so.6.0; do sudo ln -s $i ${i/-6.0.so.6.0/-6.0.so}; done. 
```

(May need sudo first too)

The rest of the discussion is found here
http://stackoverflow.com/questions/13495285/importerror-no-module-named-vtkcommonpython

**Comment by Garyfallidis** [comment]
@arokem is this the same error you got the other day in Travis?

**Comment by arokem** [comment]
Yes. Looks the same. We should be able to run that in the vtk6 machine on
travis

**Comment by MarcCote** [comment]
I saw that we have a Travis build that is supposed to use VTK6 but Ubuntu 12.04 "precise", the one currently used by Travis, doesn't offer the package `python-vtk6`. See
https://travis-ci.org/nipy/dipy/jobs/167835093#L399

This means tests related to VTK are skipped in that build. Maybe we should drop that specific Travis build (speed up the testing) or try the Travis's Trusty beta environment (https://docs.travis-ci.com/user/trusty-ci-environment)?

Also, I think Anaconda now comes with VTK 6.3 (https://anaconda.org/anaconda/vtk)

**Comment by Garyfallidis** [comment]
A generic comment. Can you check again the PR for length limit? I believe you go beyond 79 characters quite a few times.

**Comment by Garyfallidis** [comment]
I think what you suggest is a good idea. +1

**Comment by MarcCote** [comment]
I'm not sure if we can use Trusty beta environment only for a specific build (i.e. the one testing VTK6). That might impact the other builds we have. The easiest solution would be to drop the build with Python-vtk6.

**Comment by skoudoro** [comment]
This issue was moved to fury-gl/fury#5
