### ISSUE TITLE
reading dconn.nii

### ISSUE THREAD

**Issue by Dazzid** [nipy/dipy#761]
Hi,
Not sure if this is the place for this question. I'm trying to read a big file (33GB) called HCP_S500_R468_MIGPd4500ROW.dconn.nii downloaded from HCP.
I'm trying to extract the info of the correlation matrix using niBabel but after many hours (two days) trying, I'm still lost in the method. I don't make it using the  examples in the nibabel related to nift-2i.
I'm developing a software of brain activity visualization and the app started with Hagmann connectome data that is actually quite old, a colleague told me to use HCP connectome to update our models.

Thanks for the help
David

**Comment by arokem** [comment]
Hi David, 

Since this is a question about the nibabel library, a better place to ask is probably the neuroimaging@python.org mailing list: https://mail.python.org/mailman/listinfo/neuroimaging

and/or neurostars: https://neurostars.org/

**Comment by Dazzid** [comment]
Hi Arokem,
Thanks for your answer, I posted to question there

**Comment by arokem** [comment]
I think this can be closed.
