### ISSUE TITLE
Possible divide by zero in reconst.sfm.py

### ISSUE THREAD

**Issue by omarocegueda** [nipy/dipy#791]
We need to handle the case where the mean B0 is zero at some voxels:
https://github.com/nipy/dipy/blob/master/dipy/reconst/sfm.py#L83

Here is the warning:
http://nipy.bic.berkeley.edu/builders/dipy-py2.6-32/builds/646/steps/shell_9/logs/stdio

**Comment by arokem** [comment]
See #816

**Comment by skoudoro** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#791](https://trello.com/c/5QvMVEGR/8-791)

**Comment by skoudoro** [comment]
Can we close this issue @omarocegueda @arokem ?

**Comment by arokem** [comment]
Yes. I believe it is addressed here: https://github.com/nipy/dipy/pull/816/files#diff-70928c7fdc6e49e6bfc52a0214958986R423

**Comment by skoudoro** [comment]
great! Thanks! closing
