### ISSUE TITLE
Multiple failures on Windows Python 3.5 build

### ISSUE THREAD

**Issue by matthew-brett** [nipy/dipy#805]
Finally got the Python 3.5 build working on Windows and:

```
FAILED (SKIP=32, errors=28, failures=9)
```

http://nipy.bic.berkeley.edu/builders/dipy-bdist32-35/builds/26/steps/shell_10/logs/stdio

Failures are a combination of the Python 3.5 doctest errors that should now be fixed, some other import errors that I need to look into (might be the same as for doctest errors), and quite a few registration errors, of form:

```
======================================================================
FAIL: Classical Circle-To-C experiment for 2D Monomodal registration. This test
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\buildslaves\win7-32-mini\dipy-bdist32-35\build\venv\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "c:\Python35\lib\site-packages\numpy\testing\decorators.py", line 146, in skipper_func
    return f(*args, **kwargs)
  File "C:\buildslaves\win7-32-mini\dipy-bdist32-35\build\venv\lib\site-packages\dipy-0.11.0.dev0-py3.5-win32.egg\dipy\align\tests\test_imwarp.py", line 436, in test_ssd_2d_demons
    expected_profile, decimal=5)
  File "c:\Python35\lib\site-packages\numpy\testing\utils.py", line 842, in assert_array_almost_equal
    precision=decimal)
  File "c:\Python35\lib\site-packages\numpy\testing\utils.py", line 665, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not almost equal to 5 decimals

(mismatch 90.0%)
 x: array([ 312.68133,   98.17322,   60.98301,   47.75387,   34.11067,
        122.91901,   19.75599,   14.28764,   36.336  ,   88.62427])
 y: array([ 312.68133,   80.74626,   49.43591,   34.08871,   25.18287,
         17.78955,   25.91335,   20.16932,   43.86083,   79.09666])
```

**Comment by matthew-brett** [comment]
Incidentally, I have to take this machine offline in 20 minutes or so, back online later today.

**Comment by arokem** [comment]
I am reproducing this on Appveyor  with 3.5 as well: 

https://ci.appveyor.com/project/arokem/dipy/build/1.0.506/job/c7eainr9rx1k3ne4

All other versions are now passing on Appveyor, but each build takes about 2.5 hours...

**Comment by omarocegueda** [comment]
I got the same failures in my local Windows 8 64bit machine

**Comment by arokem** [comment]
Should say: reproducing the failures, *not* the errors!

**Comment by arokem** [comment]
Is this still an issue? I believe not: https://ci.appveyor.com/project/arokem/dipy/build/1.0.576/job/6kut9mau3xngivvn

**Comment by matthew-brett** [comment]
Build passing on this machine since December 31st: http://nipy.bic.berkeley.edu/builders/dipy-bdist32-35
