### ISSUE TITLE
Could you help me ?  "URLError：<urlopen error [Errno 10060]>"

### ISSUE THREAD

**Issue by mutou7** [nipy/dipy#822]
Excuse me! I got an error when I learnning dipy, and I can not resolve it. I study it from  the examples. The first line code is wrong! Type "from dipy.data import fetch_sherbrooke_3shell     ,     fetch_sherbrooke_3shell()", there is an error discussed above. I have any idear about that, could you help me ? Thanks!

**Comment by arokem** [comment]
Hi @mutou7 - might be an issue with your proxy settings. See here: http://stackoverflow.com/questions/15820739/python-urlerror-urlopen-error-errno-10060

**Comment by arokem** [comment]
Hello @mutou7 : did you manage to resolve this?

**Comment by arokem** [comment]
Closing this for now. If this recurs, please feel free to reopen it.
