### ISSUE TITLE
ACT tracking example gives weird streamlines

### ISSUE THREAD

**Issue by samuelstjean** [nipy/dipy#831]
So I was happily running the example from http://nipy.org/dipy/examples_built/tracking_tissue_classifier.html#example-tracking-tissue-classifier. 
The last part about the ACT should only give streamlines going from GM to GM, but if you zoom on the results you get small nonsense streamlines. I also saw the same thing in another viewer, so it's probably not a bug of visualisation. So did I understand wrong what the ACT is doing, is the given segmentation in the example just too rough or is there a weird underlying bug?

![screenshot from 2016-01-11 12 21 37](https://cloud.githubusercontent.com/assets/3030760/12232465/19403fe0-b85f-11e5-8c53-1ea82244984b.png)

Just run block 1 from the example, then the last block about ACT with only valid streamlines and zoom in the window, you should be able to spot these fibers hopefully.

**Comment by samuelstjean** [comment]
I used Gab's tracking script with the same maps and tracking parameters, and it does not produce these streamlines. If I ask it to return all the streamlines, there are some which do not make sense like in the picture above, so there may be a problem with the return_all=True option of the tracking.

**Comment by samuelstjean** [comment]
More pictures :

From the example 

![screenshot](https://cloud.githubusercontent.com/assets/3030760/12649670/de7b4150-c5df-11e5-9cc4-9f6c5613626f.png)

From the other ACT implementation, which does not have the small fibers

![screenshot_gab](https://cloud.githubusercontent.com/assets/3030760/12649675/e76ec296-c5df-11e5-9d4b-0c102a8f1272.png)

**Comment by arokem** [comment]
@gabknight - any ideas?

**Comment by gabknight** [comment]
hey guys,

I just look thought it and, as far as I can see, everything behave as expected. The problem with those short streamlines is that the seed position is right in voxels with partial volume fraction of gm > 0.5 (see figure). So what we see is a line formed with the seed position and one step in forward and backward directions, both stopped in valid ending tissue (gm). 
I will make a PR updating the example's seed mask, taking into account pves.

![image](https://cloud.githubusercontent.com/assets/702455/12682402/3763379a-c681-11e5-958a-5624a1bfef69.png)

**Comment by samuelstjean** [comment]
If I use your script with act, no pft, same masks, it doesn't produce those
small streamlines. Also tried 10 seeds/voxels just in case, still works. I
did not check your act implementation and assumed it does the same as the
dipy one though.

hey guys,

I just look thought it and, as far as I can see, everything behave as
expected. The problem with those short streamlines is that the seed
position is right in voxels with partial volume fraction of gm > 0.5 (see
figure). So what we see is a line formed with the seed position and one
step in forward and backward directions, both stopped in valid ending
tissue (gm).
I will make a PR updating the example's seed mask, taking into account pves.

[image: image]
<https://cloud.githubusercontent.com/assets/702455/12682402/3763379a-c681-11e5-958a-5624a1bfef69.png>

—
Reply to this email directly or view it on GitHub
<https://github.com/nipy/dipy/issues/831#issuecomment-176869874>.

**Comment by gabknight** [comment]
The tracking script you refer to uses another strategy to ensure seeds placed in partial volume fraction of gray matter do not stop immediately and produces longer streamlines. This is something else, that could be included in dipy's tracking at some point, but is not ACT.

**Comment by arokem** [comment]
Does the script contain a filtering stop to remove short streamlines?
Unless you post this script somewhere where I can look at it, I can only
guess.

**Comment by arokem** [comment]
Thanks Gab. I'm becoming more curious by the minute...

**Comment by gabknight** [comment]
A minimum length can also be set. The script is not online but what is done is quite simple: the tracking drops the flag TissueTypes.ENDPOINT (aka gm reached) when it is raised by ACT before a voxel with 100% wm was reached. If ever the flag TissueTypes.INVALIDPOINT (aka csf reached) is raised before reaching the wm, the tracking falls back on the position where TissueTypes.ENDPOINT was raise the first time and ends the tracking, keeping the streamline.

Essentially, this tell the tracking use the ACT criterion, but if the seed is place in partial volume fraction of gm, be sure to reach the wm before stopping in the gm.

This is very useful when you want to initiate the tracking close to the gm, e.g. wm-gm interface, and use tissue-based stopping criterion.

**Comment by samuelstjean** [comment]
Fixed with new masks for the example.
