### ISSUE TITLE
New pip fails on 3.2

### ISSUE THREAD

**Issue by arokem** [nipy/dipy#842]
With the message: "UserWarning: Support for Python 3.0-3.2 has been dropped. Future versions will fail here." 

Should we drop support for 3.0 - 3.2?

**Comment by arokem** [comment]
For example: https://travis-ci.org/nipy/dipy/jobs/103951526

**Comment by matthew-brett** [comment]
I think it's reasonable to drop 3.2 support - e.g. https://github.com/matthew-brett/nibabel/commit/b96d6d6e71acce216e1540c053039d9657bf7e7e
