### ISSUE TITLE
Problem with spherical harmonics computations on some Anaconda python versions

### ISSUE THREAD

**Issue by grlee77** [nipy/dipy#852]
I am unable to run CSD models in Python 3.4 that were working fine for Python 2.7.  In both cases I am at `numpy` 1.10.2, `scipy` 0.16.1 on 64-bit linux using Anaconda.

For example, I get the following traceback from `introduction_to_basic_tracking.py`

```
  File "introduction_to_basic_tracking.py", line 153, in <module>
    csd_fit = csd_model.fit(data, mask=white_matter)
  File "/home/lee8rx/anaconda/envs/py34acc/lib/python3.4/site-packages/dipy/reconst/multi_voxel.py", line 33, in new_fit
    fit_array[ijk] = single_voxel_fit(self, data[ijk])
  File "/home/lee8rx/anaconda/envs/py34acc/lib/python3.4/site-packages/dipy/reconst/csdeconv.py", line 179, in fit
    P=self._P)
  File "/home/lee8rx/anaconda/envs/py34acc/lib/python3.4/site-packages/dipy/reconst/csdeconv.py", line 536, in csdeconv
    fodf_sh = _solve_cholesky(P, z)
  File "/home/lee8rx/anaconda/envs/py34acc/lib/python3.4/site-packages/dipy/reconst/csdeconv.py", line 403, in _solve_cholesky
    raise la.LinAlgError(msg)
numpy.linalg.linalg.LinAlgError: 4-th leading minor not positive definite
```

I tracked the source of the error to a bad output from `scipy.special.sph_harm`.  If I comment out the import of `sph_harm` and use `dipy.reconst.shm.spherical_harmonic` instead, the example completes sucessfully on Python 3.4 as well.

From the discussion here (https://github.com/scipy/scipy/issues/5376), it seems the problem is specific to Anaconda, so I don't think there is anything you need to fix on the `dipy` side, but I just wanted to give a heads up for others who may encounter this issue:

**Comment by Garyfallidis** [comment]
Hi Gregory, thank you very much the excellent feedback on this. Our Python 3.4 bots look good http://nipy.bic.berkeley.edu/builders and our Travis bots are all green on 3.4 too. https://travis-ci.org/nipy/dipy/builds/105693106 So, I am quite positive that this is an installation/packaging issue with Anaconda thing and it will most likely resolve itself.

**Comment by arokem** [comment]
I don't think this has been fixed yet. I'm thinking it might be nice to introspect, and if the user is on Python 3 and scipy is from conda, use the "old" version of spherical_harmonics from here: https://github.com/nipy/dipy/blob/master/dipy/reconst/shm.py#L160

Anyone know how we can tell if scipy is from conda?

**Comment by arokem** [comment]
Well, I've answered my own question in #1057

**Comment by jchoude** [comment]
Going through old issues to find a specific one, I stumbled upon this one. Should we close it?

**Comment by skoudoro** [comment]
+1 for closing this one

**Comment by arokem** [comment]
Yep. Ideally we would get rid of the ugliness introduced in https://github.com/arokem/dipy/commit/c4a113dd7ae4e28a9e701fa2143018881cb2e48b at some point, but I think it's not quite there yet.
