### ISSUE TITLE
PEP8 in `test_crosscorr`

### ISSUE THREAD

**Issue by arokem** [nipy/dipy#862]
dipy/align/tests/test_crosscorr.py:6:1: E302 expected 2 blank lines, found 1
dipy/align/tests/test_crosscorr.py:12:58: E231 missing whitespace after ','
dipy/align/tests/test_crosscorr.py:13:64: E231 missing whitespace after ','
dipy/align/tests/test_crosscorr.py:17:59: E231 missing whitespace after ','
dipy/align/tests/test_crosscorr.py:17:61: E231 missing whitespace after ','
dipy/align/tests/test_crosscorr.py:18:65: E231 missing whitespace after ','
dipy/align/tests/test_crosscorr.py:18:67: E231 missing whitespace after ','
dipy/align/tests/test_crosscorr.py:28:61: E231 missing whitespace after ','
dipy/align/tests/test_crosscorr.py:28:64: E231 missing whitespace after ','
dipy/align/tests/test_crosscorr.py:29:67: E231 missing whitespace after ','
dipy/align/tests/test_crosscorr.py:29:70: E231 missing whitespace after ','
dipy/align/tests/test_crosscorr.py:33:59: E231 missing whitespace after ','
dipy/align/tests/test_crosscorr.py:33:61: E231 missing whitespace after ','
dipy/align/tests/test_crosscorr.py:34:65: E231 missing whitespace after ','
dipy/align/tests/test_crosscorr.py:34:67: E231 missing whitespace after ','
dipy/align/tests/test_crosscorr.py:39:5: E265 block comment should start with '# '
dipy/align/tests/test_crosscorr.py:43:5: E265 block comment should start with '# '
dipy/align/tests/test_crosscorr.py:47:5: E265 block comment should start with '# '
dipy/align/tests/test_crosscorr.py:50:36: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_crosscorr.py:50:38: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_crosscorr.py:52:10: E231 missing whitespace after ','
dipy/align/tests/test_crosscorr.py:52:13: E225 missing whitespace around operator
dipy/align/tests/test_crosscorr.py:53:10: E231 missing whitespace after ','
dipy/align/tests/test_crosscorr.py:53:13: E225 missing whitespace around operator
dipy/align/tests/test_crosscorr.py:55:5: E265 block comment should start with '# '
dipy/align/tests/test_crosscorr.py:58:37: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_crosscorr.py:58:39: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_crosscorr.py:59:37: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_crosscorr.py:59:39: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_crosscorr.py:61:80: E501 line too long (87 > 79 characters)
dipy/align/tests/test_crosscorr.py:65:80: E501 line too long (87 > 79 characters)
dipy/align/tests/test_crosscorr.py:69:38: E231 missing whitespace after ','
dipy/align/tests/test_crosscorr.py:71:38: E231 missing whitespace after ','
dipy/align/tests/test_crosscorr.py:71:49: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_crosscorr.py:71:51: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_crosscorr.py:72:43: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_crosscorr.py:72:45: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_crosscorr.py:82:5: E265 block comment should start with '# '
dipy/align/tests/test_crosscorr.py:84:38: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_crosscorr.py:84:40: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_crosscorr.py:86:5: E265 block comment should start with '# '
dipy/align/tests/test_crosscorr.py:92:32: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_crosscorr.py:92:34: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_crosscorr.py:92:51: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_crosscorr.py:92:53: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_crosscorr.py:93:17: E231 missing whitespace after ','
dipy/align/tests/test_crosscorr.py:93:80: E501 line too long (89 > 79 characters)
dipy/align/tests/test_crosscorr.py:94:17: E231 missing whitespace after ','
dipy/align/tests/test_crosscorr.py:94:80: E501 line too long (89 > 79 characters)
dipy/align/tests/test_crosscorr.py:97:26: E231 missing whitespace after ','
dipy/align/tests/test_crosscorr.py:105:5: E265 block comment should start with '# '
dipy/align/tests/test_crosscorr.py:106:17: E231 missing whitespace after ','
dipy/align/tests/test_crosscorr.py:106:80: E501 line too long (89 > 79 characters)
dipy/align/tests/test_crosscorr.py:107:17: E231 missing whitespace after ','
dipy/align/tests/test_crosscorr.py:107:80: E501 line too long (89 > 79 characters)
dipy/align/tests/test_crosscorr.py:110:26: E231 missing whitespace after ','
dipy/align/tests/test_crosscorr.py:115:80: E501 line too long (80 > 79 characters)
dipy/align/tests/test_crosscorr.py:123:5: E265 block comment should start with '# '
dipy/align/tests/test_crosscorr.py:127:5: E265 block comment should start with '# '
dipy/align/tests/test_crosscorr.py:131:36: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_crosscorr.py:131:38: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_crosscorr.py:133:10: E231 missing whitespace after ','
dipy/align/tests/test_crosscorr.py:133:13: E225 missing whitespace around operator
dipy/align/tests/test_crosscorr.py:134:10: E231 missing whitespace after ','
dipy/align/tests/test_crosscorr.py:134:13: E225 missing whitespace around operator
dipy/align/tests/test_crosscorr.py:135:10: E231 missing whitespace after ','
dipy/align/tests/test_crosscorr.py:135:13: E225 missing whitespace around operator
dipy/align/tests/test_crosscorr.py:137:5: E265 block comment should start with '# '
dipy/align/tests/test_crosscorr.py:139:37: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_crosscorr.py:139:39: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_crosscorr.py:140:37: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_crosscorr.py:140:39: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_crosscorr.py:142:80: E501 line too long (87 > 79 characters)
dipy/align/tests/test_crosscorr.py:146:80: E501 line too long (87 > 79 characters)
dipy/align/tests/test_crosscorr.py:150:38: E231 missing whitespace after ','
dipy/align/tests/test_crosscorr.py:152:38: E231 missing whitespace after ','
dipy/align/tests/test_crosscorr.py:152:49: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_crosscorr.py:152:51: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_crosscorr.py:153:43: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_crosscorr.py:153:45: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_crosscorr.py:163:5: E265 block comment should start with '# '
dipy/align/tests/test_crosscorr.py:165:38: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_crosscorr.py:165:40: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_crosscorr.py:167:5: E265 block comment should start with '# '
dipy/align/tests/test_crosscorr.py:173:32: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_crosscorr.py:173:34: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_crosscorr.py:173:51: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_crosscorr.py:173:53: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_crosscorr.py:174:17: E231 missing whitespace after ','
dipy/align/tests/test_crosscorr.py:174:80: E501 line too long (89 > 79 characters)
dipy/align/tests/test_crosscorr.py:175:17: E231 missing whitespace after ','
dipy/align/tests/test_crosscorr.py:175:80: E501 line too long (89 > 79 characters)
dipy/align/tests/test_crosscorr.py:176:17: E231 missing whitespace after ','
dipy/align/tests/test_crosscorr.py:176:80: E501 line too long (89 > 79 characters)
dipy/align/tests/test_crosscorr.py:179:26: E231 missing whitespace after ','
dipy/align/tests/test_crosscorr.py:189:5: E265 block comment should start with '# '
dipy/align/tests/test_crosscorr.py:190:17: E231 missing whitespace after ','
dipy/align/tests/test_crosscorr.py:190:80: E501 line too long (89 > 79 characters)
dipy/align/tests/test_crosscorr.py:191:17: E231 missing whitespace after ','
dipy/align/tests/test_crosscorr.py:191:80: E501 line too long (89 > 79 characters)
dipy/align/tests/test_crosscorr.py:192:17: E231 missing whitespace after ','
dipy/align/tests/test_crosscorr.py:192:80: E501 line too long (89 > 79 characters)
dipy/align/tests/test_crosscorr.py:195:26: E231 missing whitespace after ','
dipy/align/tests/test_crosscorr.py:202:80: E501 line too long (80 > 79 characters)
dipy/align/tests/test_crosscorr.py:206:12: E225 missing whitespace around operator

**Comment by ghoshbishakh** [comment]
This can be closed

**Comment by arokem** [comment]
Closed through?

**Comment by ghoshbishakh** [comment]
#897 ?

**Comment by arokem** [comment]
Thanks! Closed through #897
