### ISSUE TITLE
PEP8 in `test_imaffine`

### ISSUE THREAD

**Issue by arokem** [nipy/dipy#864]
dipy/align/tests/test_imaffine.py:32:80: E501 line too long (84 > 79 characters)
dipy/align/tests/test_imaffine.py:35:80: E501 line too long (82 > 79 characters)
dipy/align/tests/test_imaffine.py:57:13: E261 at least two spaces before inline comment
dipy/align/tests/test_imaffine.py:57:14: E262 inline comment should start with '# '
dipy/align/tests/test_imaffine.py:65:48: E261 at least two spaces before inline comment
dipy/align/tests/test_imaffine.py:65:49: E262 inline comment should start with '# '
dipy/align/tests/test_imaffine.py:66:36: E231 missing whitespace after ','
dipy/align/tests/test_imaffine.py:69:18: E231 missing whitespace after ','
dipy/align/tests/test_imaffine.py:81:33: E703 statement ends with a semicolon
dipy/align/tests/test_imaffine.py:85:80: E501 line too long (82 > 79 characters)
dipy/align/tests/test_imaffine.py:86:80: E501 line too long (82 > 79 characters)
dipy/align/tests/test_imaffine.py:93:13: E261 at least two spaces before inline comment
dipy/align/tests/test_imaffine.py:93:14: E262 inline comment should start with '# '
dipy/align/tests/test_imaffine.py:95:51: E261 at least two spaces before inline comment
dipy/align/tests/test_imaffine.py:95:52: E262 inline comment should start with '# '
dipy/align/tests/test_imaffine.py:96:37: E261 at least two spaces before inline comment
dipy/align/tests/test_imaffine.py:96:38: E262 inline comment should start with '# '
dipy/align/tests/test_imaffine.py:108:44: E231 missing whitespace after ','
dipy/align/tests/test_imaffine.py:110:26: E231 missing whitespace after ','
dipy/align/tests/test_imaffine.py:116:80: E501 line too long (80 > 79 characters)
dipy/align/tests/test_imaffine.py:120:60: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_imaffine.py:120:62: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_imaffine.py:123:60: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_imaffine.py:123:62: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_imaffine.py:126:41: E703 statement ends with a semicolon
dipy/align/tests/test_imaffine.py:131:25: E128 continuation line under-indented for visual indent
dipy/align/tests/test_imaffine.py:138:13: E261 at least two spaces before inline comment
dipy/align/tests/test_imaffine.py:138:14: E262 inline comment should start with '# '
dipy/align/tests/test_imaffine.py:140:51: E261 at least two spaces before inline comment
dipy/align/tests/test_imaffine.py:140:52: E262 inline comment should start with '# '
dipy/align/tests/test_imaffine.py:141:37: E261 at least two spaces before inline comment
dipy/align/tests/test_imaffine.py:141:38: E262 inline comment should start with '# '
dipy/align/tests/test_imaffine.py:153:44: E231 missing whitespace after ','
dipy/align/tests/test_imaffine.py:155:26: E231 missing whitespace after ','
dipy/align/tests/test_imaffine.py:161:80: E501 line too long (80 > 79 characters)
dipy/align/tests/test_imaffine.py:167:41: E703 statement ends with a semicolon
dipy/align/tests/test_imaffine.py:171:80: E501 line too long (82 > 79 characters)
dipy/align/tests/test_imaffine.py:172:53: E128 continuation line under-indented for visual indent
dipy/align/tests/test_imaffine.py:179:80: E501 line too long (80 > 79 characters)
dipy/align/tests/test_imaffine.py:180:80: E501 line too long (81 > 79 characters)
dipy/align/tests/test_imaffine.py:182:80: E501 line too long (83 > 79 characters)
dipy/align/tests/test_imaffine.py:194:80: E501 line too long (81 > 79 characters)
dipy/align/tests/test_imaffine.py:195:25: E127 continuation line over-indented for visual indent
dipy/align/tests/test_imaffine.py:213:23: E228 missing whitespace around modulo operator
dipy/align/tests/test_imaffine.py:240:80: E501 line too long (81 > 79 characters)
dipy/align/tests/test_imaffine.py:241:25: E127 continuation line over-indented for visual indent
dipy/align/tests/test_imaffine.py:267:27: E228 missing whitespace around modulo operator
dipy/align/tests/test_imaffine.py:274:27: E228 missing whitespace around modulo operator
dipy/align/tests/test_imaffine.py:282:80: E501 line too long (80 > 79 characters)
dipy/align/tests/test_imaffine.py:283:80: E501 line too long (81 > 79 characters)
dipy/align/tests/test_imaffine.py:307:80: E501 line too long (83 > 79 characters)
dipy/align/tests/test_imaffine.py:329:80: E501 line too long (82 > 79 characters)
dipy/align/tests/test_imaffine.py:379:26: E231 missing whitespace after ','
dipy/align/tests/test_imaffine.py:440:80: E501 line too long (81 > 79 characters)
dipy/align/tests/test_imaffine.py:460:80: E501 line too long (81 > 79 characters)
dipy/align/tests/test_imaffine.py:461:80: E501 line too long (80 > 79 characters)
dipy/align/tests/test_imaffine.py:470:80: E501 line too long (81 > 79 characters)
dipy/align/tests/test_imaffine.py:481:80: E501 line too long (85 > 79 characters)
dipy/align/tests/test_imaffine.py:482:80: E501 line too long (87 > 79 characters)
dipy/align/tests/test_imaffine.py:484:80: E501 line too long (80 > 79 characters)
dipy/align/tests/test_imaffine.py:508:32: E231 missing whitespace after ','
dipy/align/tests/test_imaffine.py:508:34: E231 missing whitespace after ','
dipy/align/tests/test_imaffine.py:508:36: E231 missing whitespace after ','
dipy/align/tests/test_imaffine.py:518:80: E501 line too long (80 > 79 characters)
dipy/align/tests/test_imaffine.py:524:1: E303 too many blank lines (3)
dipy/align/tests/test_imaffine.py:526:31: E231 missing whitespace after ','
dipy/align/tests/test_imaffine.py:526:34: E231 missing whitespace after ','
dipy/align/tests/test_imaffine.py:527:31: E231 missing whitespace after ','
dipy/align/tests/test_imaffine.py:527:34: E231 missing whitespace after ','

**Comment by ghoshbishakh** [comment]
closed through #964
