### ISSUE TITLE
PEP8 in test_imwarp

### ISSUE THREAD

**Issue by arokem** [nipy/dipy#865]
dipy/align/tests/test_imwarp.py:53:5: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:67:5: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:72:42: E231 missing whitespace after ','
dipy/align/tests/test_imwarp.py:77:5: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:81:5: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:82:5: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:83:19: E231 missing whitespace after ','
dipy/align/tests/test_imwarp.py:84:20: E231 missing whitespace after ','
dipy/align/tests/test_imwarp.py:85:19: E231 missing whitespace after ','
dipy/align/tests/test_imwarp.py:86:19: E231 missing whitespace after ','
dipy/align/tests/test_imwarp.py:88:5: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:89:40: E231 missing whitespace after ','
dipy/align/tests/test_imwarp.py:89:55: E231 missing whitespace after ','
dipy/align/tests/test_imwarp.py:91:5: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:93:43: E127 continuation line over-indented for visual indent
dipy/align/tests/test_imwarp.py:94:43: E127 continuation line over-indented for visual indent
dipy/align/tests/test_imwarp.py:95:43: E127 continuation line over-indented for visual indent
dipy/align/tests/test_imwarp.py:98:5: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:99:5: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:103:9: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:105:9: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:106:9: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:109:9: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:111:9: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:112:9: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:115:9: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:123:5: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:125:43: E127 continuation line over-indented for visual indent
dipy/align/tests/test_imwarp.py:126:43: E127 continuation line over-indented for visual indent
dipy/align/tests/test_imwarp.py:126:80: E501 line too long (80 > 79 characters)
dipy/align/tests/test_imwarp.py:131:9: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:133:9: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:134:9: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:137:9: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:139:9: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:140:9: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:143:5: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:144:5: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:146:43: E127 continuation line over-indented for visual indent
dipy/align/tests/test_imwarp.py:147:43: E127 continuation line over-indented for visual indent
dipy/align/tests/test_imwarp.py:148:43: E127 continuation line over-indented for visual indent
dipy/align/tests/test_imwarp.py:151:5: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:152:5: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:155:5: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:157:43: E127 continuation line over-indented for visual indent
dipy/align/tests/test_imwarp.py:158:43: E127 continuation line over-indented for visual indent
dipy/align/tests/test_imwarp.py:159:43: E127 continuation line over-indented for visual indent
dipy/align/tests/test_imwarp.py:162:5: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:163:5: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:167:5: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:172:27: E231 missing whitespace after ','
dipy/align/tests/test_imwarp.py:191:5: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:211:5: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:212:5: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:218:5: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:220:43: E127 continuation line over-indented for visual indent
dipy/align/tests/test_imwarp.py:221:43: E127 continuation line over-indented for visual indent
dipy/align/tests/test_imwarp.py:222:43: E127 continuation line over-indented for visual indent
dipy/align/tests/test_imwarp.py:223:41: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_imwarp.py:223:43: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_imwarp.py:224:45: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_imwarp.py:224:47: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_imwarp.py:225:5: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:228:5: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:230:5: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:232:5: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:233:5: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:235:5: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:255:5: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:279:5: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:280:5: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:286:5: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:288:43: E127 continuation line over-indented for visual indent
dipy/align/tests/test_imwarp.py:289:43: E127 continuation line over-indented for visual indent
dipy/align/tests/test_imwarp.py:290:43: E127 continuation line over-indented for visual indent
dipy/align/tests/test_imwarp.py:291:41: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_imwarp.py:291:43: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_imwarp.py:292:45: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_imwarp.py:292:47: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_imwarp.py:293:5: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:296:5: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:298:5: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:300:5: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:301:5: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:303:5: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:311:1: E302 expected 2 blank lines, found 1
dipy/align/tests/test_imwarp.py:314:5: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:324:5: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:325:51: E231 missing whitespace after ','
dipy/align/tests/test_imwarp.py:325:55: E231 missing whitespace after ','
dipy/align/tests/test_imwarp.py:327:5: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:328:5: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:341:33: E231 missing whitespace after ','
dipy/align/tests/test_imwarp.py:341:35: E231 missing whitespace after ','
dipy/align/tests/test_imwarp.py:351:1: E302 expected 2 blank lines, found 1
dipy/align/tests/test_imwarp.py:386:5: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:389:80: E501 line too long (80 > 79 characters)
dipy/align/tests/test_imwarp.py:391:5: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:399:9: E128 continuation line under-indented for visual indent
dipy/align/tests/test_imwarp.py:401:5: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:448:5: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:454:5: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:462:9: E128 continuation line under-indented for visual indent
dipy/align/tests/test_imwarp.py:464:5: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:527:5: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:538:5: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:551:5: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:553:38: E231 missing whitespace after ','
dipy/align/tests/test_imwarp.py:555:5: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:566:5: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:569:32: E231 missing whitespace after ','
dipy/align/tests/test_imwarp.py:570:18: E231 missing whitespace after ','
dipy/align/tests/test_imwarp.py:571:18: E231 missing whitespace after ','
dipy/align/tests/test_imwarp.py:573:5: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:576:34: E231 missing whitespace after ','
dipy/align/tests/test_imwarp.py:577:19: E231 missing whitespace after ','
dipy/align/tests/test_imwarp.py:578:19: E231 missing whitespace after ','
dipy/align/tests/test_imwarp.py:591:15: E231 missing whitespace after ','
dipy/align/tests/test_imwarp.py:592:15: E231 missing whitespace after ','
dipy/align/tests/test_imwarp.py:593:15: E231 missing whitespace after ','
dipy/align/tests/test_imwarp.py:594:15: E231 missing whitespace after ','
dipy/align/tests/test_imwarp.py:596:5: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:602:5: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:610:9: E128 continuation line under-indented for visual indent
dipy/align/tests/test_imwarp.py:632:15: E231 missing whitespace after ','
dipy/align/tests/test_imwarp.py:633:15: E231 missing whitespace after ','
dipy/align/tests/test_imwarp.py:634:15: E231 missing whitespace after ','
dipy/align/tests/test_imwarp.py:635:15: E231 missing whitespace after ','
dipy/align/tests/test_imwarp.py:637:5: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:643:5: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:651:9: E128 continuation line under-indented for visual indent
dipy/align/tests/test_imwarp.py:680:5: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:685:5: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:717:5: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:722:5: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:730:9: E128 continuation line under-indented for visual indent
dipy/align/tests/test_imwarp.py:761:5: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:762:11: E225 missing whitespace around operator
dipy/align/tests/test_imwarp.py:763:15: E225 missing whitespace around operator
dipy/align/tests/test_imwarp.py:764:16: E225 missing whitespace around operator
dipy/align/tests/test_imwarp.py:765:13: E225 missing whitespace around operator
dipy/align/tests/test_imwarp.py:766:20: E225 missing whitespace around operator
dipy/align/tests/test_imwarp.py:767:14: E225 missing whitespace around operator
dipy/align/tests/test_imwarp.py:771:5: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:778:9: E128 continuation line under-indented for visual indent
dipy/align/tests/test_imwarp.py:808:5: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:809:11: E225 missing whitespace around operator
dipy/align/tests/test_imwarp.py:810:15: E225 missing whitespace around operator
dipy/align/tests/test_imwarp.py:811:13: E225 missing whitespace around operator
dipy/align/tests/test_imwarp.py:812:20: E225 missing whitespace around operator
dipy/align/tests/test_imwarp.py:813:14: E225 missing whitespace around operator
dipy/align/tests/test_imwarp.py:817:5: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:849:5: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:850:11: E225 missing whitespace around operator
dipy/align/tests/test_imwarp.py:851:15: E225 missing whitespace around operator
dipy/align/tests/test_imwarp.py:852:16: E225 missing whitespace around operator
dipy/align/tests/test_imwarp.py:853:13: E225 missing whitespace around operator
dipy/align/tests/test_imwarp.py:854:20: E225 missing whitespace around operator
dipy/align/tests/test_imwarp.py:855:14: E225 missing whitespace around operator
dipy/align/tests/test_imwarp.py:859:5: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:866:9: E128 continuation line under-indented for visual indent
dipy/align/tests/test_imwarp.py:895:5: E265 block comment should start with '# '
dipy/align/tests/test_imwarp.py:896:11: E225 missing whitespace around operator
dipy/align/tests/test_imwarp.py:897:15: E225 missing whitespace around operator
dipy/align/tests/test_imwarp.py:898:13: E225 missing whitespace around operator
dipy/align/tests/test_imwarp.py:899:20: E225 missing whitespace around operator
dipy/align/tests/test_imwarp.py:900:14: E225 missing whitespace around operator
dipy/align/tests/test_imwarp.py:904:5: E265 block comment should start with '# '

**Comment by ghoshbishakh** [comment]
@arokem closed through #947 ?
