### ISSUE TITLE
PEP8 in test_metrics

### ISSUE THREAD

**Issue by arokem** [nipy/dipy#866]
dipy/align/tests/test_metrics.py:11:27: E231 missing whitespace after ','
dipy/align/tests/test_metrics.py:11:29: E231 missing whitespace after ','
dipy/align/tests/test_metrics.py:11:31: E231 missing whitespace after ','
dipy/align/tests/test_metrics.py:11:33: E231 missing whitespace after ','
dipy/align/tests/test_metrics.py:24:5: E265 block comment should start with '# '
dipy/align/tests/test_metrics.py:26:80: E501 line too long (86 > 79 characters)
dipy/align/tests/test_metrics.py:27:5: E265 block comment should start with '# '
dipy/align/tests/test_metrics.py:36:1: E302 expected 2 blank lines, found 1
dipy/align/tests/test_metrics.py:50:5: E265 block comment should start with '# '
dipy/align/tests/test_metrics.py:53:5: E265 block comment should start with '# '
dipy/align/tests/test_metrics.py:57:5: E265 block comment should start with '# '
dipy/align/tests/test_metrics.py:60:36: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_metrics.py:60:38: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_metrics.py:62:10: E231 missing whitespace after ','
dipy/align/tests/test_metrics.py:62:13: E225 missing whitespace around operator
dipy/align/tests/test_metrics.py:63:10: E231 missing whitespace after ','
dipy/align/tests/test_metrics.py:63:13: E225 missing whitespace around operator
dipy/align/tests/test_metrics.py:65:5: E265 block comment should start with '# '
dipy/align/tests/test_metrics.py:69:5: E265 block comment should start with '# '
dipy/align/tests/test_metrics.py:70:38: E231 missing whitespace after ','
dipy/align/tests/test_metrics.py:71:38: E231 missing whitespace after ','
dipy/align/tests/test_metrics.py:73:5: E265 block comment should start with '# '
dipy/align/tests/test_metrics.py:77:5: E265 block comment should start with '# '
dipy/align/tests/test_metrics.py:80:5: E265 block comment should start with '# '
dipy/align/tests/test_metrics.py:81:5: E265 block comment should start with '# '
dipy/align/tests/test_metrics.py:83:5: E265 block comment should start with '# '
dipy/align/tests/test_metrics.py:84:5: E265 block comment should start with '# '
dipy/align/tests/test_metrics.py:85:5: E265 block comment should start with '# '
dipy/align/tests/test_metrics.py:87:5: E265 block comment should start with '# '
dipy/align/tests/test_metrics.py:89:52: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_metrics.py:89:54: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_metrics.py:90:52: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_metrics.py:90:54: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_metrics.py:91:44: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_metrics.py:91:46: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_metrics.py:92:44: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_metrics.py:92:46: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_metrics.py:93:51: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_metrics.py:93:53: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_metrics.py:94:63: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_metrics.py:94:65: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_metrics.py:95:51: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_metrics.py:95:53: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_metrics.py:96:63: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_metrics.py:96:65: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_metrics.py:98:5: E265 block comment should start with '# '
dipy/align/tests/test_metrics.py:102:5: E265 block comment should start with '# '
dipy/align/tests/test_metrics.py:105:41: E261 at least two spaces before inline comment
dipy/align/tests/test_metrics.py:105:42: E262 inline comment should start with '# '
dipy/align/tests/test_metrics.py:105:80: E501 line too long (82 > 79 characters)
dipy/align/tests/test_metrics.py:108:5: E265 block comment should start with '# '
dipy/align/tests/test_metrics.py:109:80: E501 line too long (85 > 79 characters)
dipy/align/tests/test_metrics.py:110:80: E501 line too long (85 > 79 characters)
dipy/align/tests/test_metrics.py:114:41: E261 at least two spaces before inline comment
dipy/align/tests/test_metrics.py:114:42: E262 inline comment should start with '# '
dipy/align/tests/test_metrics.py:114:80: E501 line too long (82 > 79 characters)
dipy/align/tests/test_metrics.py:117:5: E265 block comment should start with '# '
dipy/align/tests/test_metrics.py:118:80: E501 line too long (85 > 79 characters)
dipy/align/tests/test_metrics.py:119:80: E501 line too long (85 > 79 characters)
dipy/align/tests/test_metrics.py:139:5: E265 block comment should start with '# '
dipy/align/tests/test_metrics.py:142:5: E265 block comment should start with '# '
dipy/align/tests/test_metrics.py:146:5: E265 block comment should start with '# '
dipy/align/tests/test_metrics.py:150:36: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_metrics.py:150:38: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_metrics.py:152:10: E231 missing whitespace after ','
dipy/align/tests/test_metrics.py:152:13: E225 missing whitespace around operator
dipy/align/tests/test_metrics.py:153:10: E231 missing whitespace after ','
dipy/align/tests/test_metrics.py:153:13: E225 missing whitespace around operator
dipy/align/tests/test_metrics.py:154:10: E231 missing whitespace after ','
dipy/align/tests/test_metrics.py:154:13: E225 missing whitespace around operator
dipy/align/tests/test_metrics.py:156:5: E265 block comment should start with '# '
dipy/align/tests/test_metrics.py:160:5: E265 block comment should start with '# '
dipy/align/tests/test_metrics.py:161:38: E231 missing whitespace after ','
dipy/align/tests/test_metrics.py:162:38: E231 missing whitespace after ','
dipy/align/tests/test_metrics.py:164:5: E265 block comment should start with '# '
dipy/align/tests/test_metrics.py:168:5: E265 block comment should start with '# '
dipy/align/tests/test_metrics.py:171:5: E265 block comment should start with '# '
dipy/align/tests/test_metrics.py:172:5: E265 block comment should start with '# '
dipy/align/tests/test_metrics.py:174:5: E265 block comment should start with '# '
dipy/align/tests/test_metrics.py:175:5: E265 block comment should start with '# '
dipy/align/tests/test_metrics.py:176:5: E265 block comment should start with '# '
dipy/align/tests/test_metrics.py:178:5: E265 block comment should start with '# '
dipy/align/tests/test_metrics.py:180:52: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_metrics.py:180:54: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_metrics.py:181:52: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_metrics.py:181:54: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_metrics.py:182:44: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_metrics.py:182:46: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_metrics.py:183:44: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_metrics.py:183:46: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_metrics.py:184:51: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_metrics.py:184:53: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_metrics.py:185:63: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_metrics.py:185:65: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_metrics.py:186:51: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_metrics.py:186:53: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_metrics.py:187:63: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_metrics.py:187:65: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_metrics.py:189:5: E265 block comment should start with '# '
dipy/align/tests/test_metrics.py:193:5: E265 block comment should start with '# '
dipy/align/tests/test_metrics.py:200:5: E265 block comment should start with '# '
dipy/align/tests/test_metrics.py:201:80: E501 line too long (85 > 79 characters)
dipy/align/tests/test_metrics.py:202:80: E501 line too long (85 > 79 characters)
dipy/align/tests/test_metrics.py:203:80: E501 line too long (85 > 79 characters)
dipy/align/tests/test_metrics.py:211:5: E265 block comment should start with '# '
dipy/align/tests/test_metrics.py:212:80: E501 line too long (85 > 79 characters)
dipy/align/tests/test_metrics.py:213:80: E501 line too long (85 > 79 characters)
dipy/align/tests/test_metrics.py:214:80: E501 line too long (85 > 79 characters)
dipy/align/tests/test_metrics.py:220:12: E225 missing whitespace around operator

**Comment by ghoshbishakh** [comment]
closed through #947
