### ISSUE TITLE
PEP8 in test_parzenhist

### ISSUE THREAD

**Issue by arokem** [nipy/dipy#867]
dipy/align/tests/test_parzenhist.py:11:27: E128 continuation line under-indented for visual indent
dipy/align/tests/test_parzenhist.py:12:27: E128 continuation line under-indented for visual indent
dipy/align/tests/test_parzenhist.py:13:27: E128 continuation line under-indented for visual indent
dipy/align/tests/test_parzenhist.py:324:80: E501 line too long (82 > 79 characters)
dipy/align/tests/test_parzenhist.py:334:80: E501 line too long (80 > 79 characters)
dipy/align/tests/test_parzenhist.py:335:80: E501 line too long (81 > 79 characters)
dipy/align/tests/test_parzenhist.py:337:80: E501 line too long (83 > 79 characters)
dipy/align/tests/test_parzenhist.py:364:34: E128 continuation line under-indented for visual indent
dipy/align/tests/test_parzenhist.py:372:80: E501 line too long (83 > 79 characters)
dipy/align/tests/test_parzenhist.py:373:38: E128 continuation line under-indented for visual indent
dipy/align/tests/test_parzenhist.py:374:38: E128 continuation line under-indented for visual indent
dipy/align/tests/test_parzenhist.py:416:80: E501 line too long (80 > 79 characters)
dipy/align/tests/test_parzenhist.py:417:80: E501 line too long (81 > 79 characters)
dipy/align/tests/test_parzenhist.py:419:80: E501 line too long (83 > 79 characters)
dipy/align/tests/test_parzenhist.py:472:80: E501 line too long (80 > 79 characters)
dipy/align/tests/test_parzenhist.py:473:39: E128 continuation line under-indented for visual indent
dipy/align/tests/test_parzenhist.py:474:39: E128 continuation line under-indented for visual indent
dipy/align/tests/test_parzenhist.py:492:80: E501 line too long (82 > 79 characters)
dipy/align/tests/test_parzenhist.py:562:24: E231 missing whitespace after ','
dipy/align/tests/test_parzenhist.py:562:26: E231 missing whitespace after ','
dipy/align/tests/test_parzenhist.py:563:26: E231 missing whitespace after ','
dipy/align/tests/test_parzenhist.py:563:28: E231 missing whitespace after ','
dipy/align/tests/test_parzenhist.py:563:30: E231 missing whitespace after ','
dipy/align/tests/test_parzenhist.py:571:21: E231 missing whitespace after ','
dipy/align/tests/test_parzenhist.py:571:28: E231 missing whitespace after ','
dipy/align/tests/test_parzenhist.py:571:30: E231 missing whitespace after ','
dipy/align/tests/test_parzenhist.py:573:19: E225 missing whitespace around operator
dipy/align/tests/test_parzenhist.py:579:34: E231 missing whitespace after ','
dipy/align/tests/test_parzenhist.py:579:36: E231 missing whitespace after ','
dipy/align/tests/test_parzenhist.py:579:38: E231 missing whitespace after ','
dipy/align/tests/test_parzenhist.py:597:40: E231 missing whitespace after ','
dipy/align/tests/test_parzenhist.py:598:42: E231 missing whitespace after ','
dipy/align/tests/test_parzenhist.py:600:47: E231 missing whitespace after ','
dipy/align/tests/test_parzenhist.py:601:46: E231 missing whitespace after ','
dipy/align/tests/test_parzenhist.py:602:50: E231 missing whitespace after ','
dipy/align/tests/test_parzenhist.py:604:48: E231 missing whitespace after ','
dipy/align/tests/test_parzenhist.py:605:50: E231 missing whitespace after ','
dipy/align/tests/test_parzenhist.py:607:80: E501 line too long (80 > 79 characters)
dipy/align/tests/test_parzenhist.py:608:80: E501 line too long (80 > 79 characters)
dipy/align/tests/test_parzenhist.py:609:80: E501 line too long (84 > 79 characters)
dipy/align/tests/test_parzenhist.py:610:80: E501 line too long (90 > 79 characters)
dipy/align/tests/test_parzenhist.py:611:80: E501 line too long (84 > 79 characters)
dipy/align/tests/test_parzenhist.py:612:80: E501 line too long (85 > 79 characters)
dipy/align/tests/test_parzenhist.py:613:80: E501 line too long (84 > 79 characters)
dipy/align/tests/test_parzenhist.py:614:80: E501 line too long (85 > 79 characters)

**Comment by ghoshbishakh** [comment]
closed through #947
