### ISSUE TITLE
PEP8 in test_scalespace

### ISSUE THREAD

**Issue by arokem** [nipy/dipy#868]
dipy/align/tests/test_scalespace.py:14:1: E302 expected 2 blank lines, found 1
dipy/align/tests/test_scalespace.py:25:1: W293 blank line contains whitespace
dipy/align/tests/test_scalespace.py:28:80: E501 line too long (80 > 79 characters)
dipy/align/tests/test_scalespace.py:32:80: E501 line too long (85 > 79 characters)
dipy/align/tests/test_scalespace.py:37:56: E225 missing whitespace around operator
dipy/align/tests/test_scalespace.py:41:1: W293 blank line contains whitespace
dipy/align/tests/test_scalespace.py:48:1: W293 blank line contains whitespace
dipy/align/tests/test_scalespace.py:55:1: W293 blank line contains whitespace
dipy/align/tests/test_scalespace.py:65:5: E265 block comment should start with '# '
dipy/align/tests/test_scalespace.py:71:26: E231 missing whitespace after ','
dipy/align/tests/test_scalespace.py:76:26: E231 missing whitespace after ','

**Comment by souravsingh** [comment]
I would like to work on the issue

**Comment by ghoshbishakh** [comment]
closed through #946
