### ISSUE TITLE
PEP8 in test_sumsqdiff

### ISSUE THREAD

**Issue by arokem** [nipy/dipy#869]
dipy/align/tests/test_sumsqdiff.py:21:14: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:22:14: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:27:22: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:32:13: E265 block comment should start with '# '
dipy/align/tests/test_sumsqdiff.py:33:13: E265 block comment should start with '# '
dipy/align/tests/test_sumsqdiff.py:55:36: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:57:43: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:59:28: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:75:18: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:85:80: E501 line too long (84 > 79 characters)
dipy/align/tests/test_sumsqdiff.py:124:5: E265 block comment should start with '# '
dipy/align/tests/test_sumsqdiff.py:127:5: E265 block comment should start with '# '
dipy/align/tests/test_sumsqdiff.py:131:5: E265 block comment should start with '# '
dipy/align/tests/test_sumsqdiff.py:134:36: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_sumsqdiff.py:134:38: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_sumsqdiff.py:136:10: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:136:13: E225 missing whitespace around operator
dipy/align/tests/test_sumsqdiff.py:137:10: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:137:13: E225 missing whitespace around operator
dipy/align/tests/test_sumsqdiff.py:139:5: E265 block comment should start with '# '
dipy/align/tests/test_sumsqdiff.py:145:80: E501 line too long (87 > 79 characters)
dipy/align/tests/test_sumsqdiff.py:149:80: E501 line too long (87 > 79 characters)
dipy/align/tests/test_sumsqdiff.py:153:5: E265 block comment should start with '# '
dipy/align/tests/test_sumsqdiff.py:154:38: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:156:5: E265 block comment should start with '# '
dipy/align/tests/test_sumsqdiff.py:157:29: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:168:18: E222 multiple spaces after operator
dipy/align/tests/test_sumsqdiff.py:168:41: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_sumsqdiff.py:168:43: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_sumsqdiff.py:173:5: E265 block comment should start with '# '
dipy/align/tests/test_sumsqdiff.py:178:5: E265 block comment should start with '# '
dipy/align/tests/test_sumsqdiff.py:180:5: E265 block comment should start with '# '
dipy/align/tests/test_sumsqdiff.py:183:5: E265 block comment should start with '# '
dipy/align/tests/test_sumsqdiff.py:186:5: E265 block comment should start with '# '
dipy/align/tests/test_sumsqdiff.py:187:5: E265 block comment should start with '# '
dipy/align/tests/test_sumsqdiff.py:193:35: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_sumsqdiff.py:193:37: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_sumsqdiff.py:194:12: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:194:24: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:194:35: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:194:39: E261 at least two spaces before inline comment
dipy/align/tests/test_sumsqdiff.py:194:39: E262 inline comment should start with '# '
dipy/align/tests/test_sumsqdiff.py:195:12: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:195:23: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:195:33: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:195:38: E261 at least two spaces before inline comment
dipy/align/tests/test_sumsqdiff.py:195:38: E262 inline comment should start with '# '
dipy/align/tests/test_sumsqdiff.py:196:14: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:196:26: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:196:36: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:196:39: E261 at least two spaces before inline comment
dipy/align/tests/test_sumsqdiff.py:196:39: E262 inline comment should start with '# '
dipy/align/tests/test_sumsqdiff.py:197:13: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:197:24: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:197:35: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:197:38: E261 at least two spaces before inline comment
dipy/align/tests/test_sumsqdiff.py:197:38: E262 inline comment should start with '# '
dipy/align/tests/test_sumsqdiff.py:201:19: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:201:33: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:202:14: E127 continuation line over-indented for visual indent
dipy/align/tests/test_sumsqdiff.py:202:19: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:202:33: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:209:25: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:209:53: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:210:25: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:210:53: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:215:27: E225 missing whitespace around operator
dipy/align/tests/test_sumsqdiff.py:215:30: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:215:53: E225 missing whitespace around operator
dipy/align/tests/test_sumsqdiff.py:215:75: E225 missing whitespace around operator
dipy/align/tests/test_sumsqdiff.py:215:80: E501 line too long (82 > 79 characters)
dipy/align/tests/test_sumsqdiff.py:216:37: E127 continuation line over-indented for visual indent
dipy/align/tests/test_sumsqdiff.py:216:58: E225 missing whitespace around operator
dipy/align/tests/test_sumsqdiff.py:216:76: E225 missing whitespace around operator
dipy/align/tests/test_sumsqdiff.py:216:80: E501 line too long (82 > 79 characters)
dipy/align/tests/test_sumsqdiff.py:217:27: E225 missing whitespace around operator
dipy/align/tests/test_sumsqdiff.py:217:30: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:217:53: E225 missing whitespace around operator
dipy/align/tests/test_sumsqdiff.py:217:75: E225 missing whitespace around operator
dipy/align/tests/test_sumsqdiff.py:217:80: E501 line too long (82 > 79 characters)
dipy/align/tests/test_sumsqdiff.py:218:37: E127 continuation line over-indented for visual indent
dipy/align/tests/test_sumsqdiff.py:218:58: E225 missing whitespace around operator
dipy/align/tests/test_sumsqdiff.py:218:76: E225 missing whitespace around operator
dipy/align/tests/test_sumsqdiff.py:218:80: E501 line too long (82 > 79 characters)
dipy/align/tests/test_sumsqdiff.py:220:27: E225 missing whitespace around operator
dipy/align/tests/test_sumsqdiff.py:220:52: E225 missing whitespace around operator
dipy/align/tests/test_sumsqdiff.py:223:9: E303 too many blank lines (2)
dipy/align/tests/test_sumsqdiff.py:226:47: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_sumsqdiff.py:226:49: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_sumsqdiff.py:226:60: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_sumsqdiff.py:226:62: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_sumsqdiff.py:227:58: E261 at least two spaces before inline comment
dipy/align/tests/test_sumsqdiff.py:227:59: E262 inline comment should start with '# '
dipy/align/tests/test_sumsqdiff.py:227:80: E501 line too long (82 > 79 characters)
dipy/align/tests/test_sumsqdiff.py:232:47: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_sumsqdiff.py:232:49: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_sumsqdiff.py:232:60: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_sumsqdiff.py:232:62: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_sumsqdiff.py:241:17: E128 continuation line under-indented for visual indent
dipy/align/tests/test_sumsqdiff.py:245:17: E128 continuation line under-indented for visual indent
dipy/align/tests/test_sumsqdiff.py:245:80: E501 line too long (85 > 79 characters)
dipy/align/tests/test_sumsqdiff.py:247:51: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_sumsqdiff.py:247:53: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_sumsqdiff.py:247:64: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_sumsqdiff.py:247:66: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_sumsqdiff.py:251:5: E265 block comment should start with '# '
dipy/align/tests/test_sumsqdiff.py:254:5: E265 block comment should start with '# '
dipy/align/tests/test_sumsqdiff.py:258:5: E265 block comment should start with '# '
dipy/align/tests/test_sumsqdiff.py:262:36: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_sumsqdiff.py:262:38: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_sumsqdiff.py:264:10: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:264:13: E225 missing whitespace around operator
dipy/align/tests/test_sumsqdiff.py:265:10: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:265:13: E225 missing whitespace around operator
dipy/align/tests/test_sumsqdiff.py:266:10: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:266:13: E225 missing whitespace around operator
dipy/align/tests/test_sumsqdiff.py:269:5: E265 block comment should start with '# '
dipy/align/tests/test_sumsqdiff.py:269:5: E303 too many blank lines (2)
dipy/align/tests/test_sumsqdiff.py:275:80: E501 line too long (87 > 79 characters)
dipy/align/tests/test_sumsqdiff.py:279:80: E501 line too long (87 > 79 characters)
dipy/align/tests/test_sumsqdiff.py:283:5: E265 block comment should start with '# '
dipy/align/tests/test_sumsqdiff.py:284:38: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:286:5: E265 block comment should start with '# '
dipy/align/tests/test_sumsqdiff.py:287:29: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:298:18: E222 multiple spaces after operator
dipy/align/tests/test_sumsqdiff.py:298:41: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_sumsqdiff.py:298:43: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_sumsqdiff.py:303:5: E265 block comment should start with '# '
dipy/align/tests/test_sumsqdiff.py:308:5: E265 block comment should start with '# '
dipy/align/tests/test_sumsqdiff.py:310:5: E265 block comment should start with '# '
dipy/align/tests/test_sumsqdiff.py:313:5: E265 block comment should start with '# '
dipy/align/tests/test_sumsqdiff.py:316:5: E265 block comment should start with '# '
dipy/align/tests/test_sumsqdiff.py:317:5: E265 block comment should start with '# '
dipy/align/tests/test_sumsqdiff.py:323:35: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_sumsqdiff.py:323:37: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_sumsqdiff.py:324:12: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:324:14: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:324:26: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:324:28: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:324:39: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:324:41: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:324:45: E261 at least two spaces before inline comment
dipy/align/tests/test_sumsqdiff.py:324:45: E262 inline comment should start with '# '
dipy/align/tests/test_sumsqdiff.py:325:12: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:325:14: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:325:25: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:325:27: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:325:37: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:325:39: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:325:44: E261 at least two spaces before inline comment
dipy/align/tests/test_sumsqdiff.py:325:44: E262 inline comment should start with '# '
dipy/align/tests/test_sumsqdiff.py:326:12: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:326:16: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:326:26: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:326:30: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:326:39: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:326:42: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:326:45: E261 at least two spaces before inline comment
dipy/align/tests/test_sumsqdiff.py:326:45: E262 inline comment should start with '# '
dipy/align/tests/test_sumsqdiff.py:327:12: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:327:15: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:327:25: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:327:28: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:327:37: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:327:41: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:327:44: E261 at least two spaces before inline comment
dipy/align/tests/test_sumsqdiff.py:327:44: E262 inline comment should start with '# '
dipy/align/tests/test_sumsqdiff.py:328:14: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:328:16: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:328:28: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:328:30: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:328:40: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:328:42: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:328:45: E261 at least two spaces before inline comment
dipy/align/tests/test_sumsqdiff.py:328:45: E262 inline comment should start with '# '
dipy/align/tests/test_sumsqdiff.py:329:13: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:329:15: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:329:26: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:329:28: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:329:39: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:329:41: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:329:44: E261 at least two spaces before inline comment
dipy/align/tests/test_sumsqdiff.py:329:44: E262 inline comment should start with '# '
dipy/align/tests/test_sumsqdiff.py:333:19: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:333:33: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:334:14: E127 continuation line over-indented for visual indent
dipy/align/tests/test_sumsqdiff.py:334:19: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:334:33: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:335:14: E127 continuation line over-indented for visual indent
dipy/align/tests/test_sumsqdiff.py:335:19: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:335:33: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:342:29: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:342:57: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:348:31: E225 missing whitespace around operator
dipy/align/tests/test_sumsqdiff.py:348:34: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:348:57: E225 missing whitespace around operator
dipy/align/tests/test_sumsqdiff.py:348:79: E225 missing whitespace around operator
dipy/align/tests/test_sumsqdiff.py:348:80: E501 line too long (86 > 79 characters)
dipy/align/tests/test_sumsqdiff.py:349:62: E225 missing whitespace around operator
dipy/align/tests/test_sumsqdiff.py:349:80: E225 missing whitespace around operator
dipy/align/tests/test_sumsqdiff.py:349:80: E501 line too long (86 > 79 characters)
dipy/align/tests/test_sumsqdiff.py:351:27: E225 missing whitespace around operator
dipy/align/tests/test_sumsqdiff.py:351:52: E225 missing whitespace around operator
dipy/align/tests/test_sumsqdiff.py:356:47: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_sumsqdiff.py:356:49: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_sumsqdiff.py:356:60: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_sumsqdiff.py:356:62: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_sumsqdiff.py:357:58: E261 at least two spaces before inline comment
dipy/align/tests/test_sumsqdiff.py:357:59: E262 inline comment should start with '# '
dipy/align/tests/test_sumsqdiff.py:357:80: E501 line too long (82 > 79 characters)
dipy/align/tests/test_sumsqdiff.py:362:47: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_sumsqdiff.py:362:49: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_sumsqdiff.py:362:60: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_sumsqdiff.py:362:62: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_sumsqdiff.py:371:17: E128 continuation line under-indented for visual indent
dipy/align/tests/test_sumsqdiff.py:375:17: E128 continuation line under-indented for visual indent
dipy/align/tests/test_sumsqdiff.py:375:80: E501 line too long (85 > 79 characters)
dipy/align/tests/test_sumsqdiff.py:379:51: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_sumsqdiff.py:379:53: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_sumsqdiff.py:379:64: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_sumsqdiff.py:379:66: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_sumsqdiff.py:407:51: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_sumsqdiff.py:407:53: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_sumsqdiff.py:407:64: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_sumsqdiff.py:407:66: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_sumsqdiff.py:437:16: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:437:29: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:447:59: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_sumsqdiff.py:447:61: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_sumsqdiff.py:447:72: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_sumsqdiff.py:447:74: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_sumsqdiff.py:453:5: E265 block comment should start with '# '
dipy/align/tests/test_sumsqdiff.py:457:5: E265 block comment should start with '# '
dipy/align/tests/test_sumsqdiff.py:460:36: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_sumsqdiff.py:460:38: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_sumsqdiff.py:462:10: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:462:13: E225 missing whitespace around operator
dipy/align/tests/test_sumsqdiff.py:463:10: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:463:13: E225 missing whitespace around operator
dipy/align/tests/test_sumsqdiff.py:465:5: E265 block comment should start with '# '
dipy/align/tests/test_sumsqdiff.py:469:5: E265 block comment should start with '# '
dipy/align/tests/test_sumsqdiff.py:470:29: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:471:29: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:479:59: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_sumsqdiff.py:479:61: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_sumsqdiff.py:486:5: E265 block comment should start with '# '
dipy/align/tests/test_sumsqdiff.py:490:5: E265 block comment should start with '# '
dipy/align/tests/test_sumsqdiff.py:494:36: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_sumsqdiff.py:494:38: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_sumsqdiff.py:496:10: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:496:13: E225 missing whitespace around operator
dipy/align/tests/test_sumsqdiff.py:497:10: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:497:13: E225 missing whitespace around operator
dipy/align/tests/test_sumsqdiff.py:498:10: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:498:13: E225 missing whitespace around operator
dipy/align/tests/test_sumsqdiff.py:500:5: E265 block comment should start with '# '
dipy/align/tests/test_sumsqdiff.py:504:5: E265 block comment should start with '# '
dipy/align/tests/test_sumsqdiff.py:505:29: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:506:29: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:514:59: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_sumsqdiff.py:514:61: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_sumsqdiff.py:532:5: E265 block comment should start with '# '
dipy/align/tests/test_sumsqdiff.py:535:5: E265 block comment should start with '# '
dipy/align/tests/test_sumsqdiff.py:539:5: E265 block comment should start with '# '
dipy/align/tests/test_sumsqdiff.py:542:36: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_sumsqdiff.py:542:38: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_sumsqdiff.py:544:10: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:544:13: E225 missing whitespace around operator
dipy/align/tests/test_sumsqdiff.py:545:10: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:545:13: E225 missing whitespace around operator
dipy/align/tests/test_sumsqdiff.py:547:5: E265 block comment should start with '# '
dipy/align/tests/test_sumsqdiff.py:553:80: E501 line too long (87 > 79 characters)
dipy/align/tests/test_sumsqdiff.py:557:80: E501 line too long (87 > 79 characters)
dipy/align/tests/test_sumsqdiff.py:561:5: E265 block comment should start with '# '
dipy/align/tests/test_sumsqdiff.py:562:38: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:564:5: E265 block comment should start with '# '
dipy/align/tests/test_sumsqdiff.py:565:29: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:576:18: E222 multiple spaces after operator
dipy/align/tests/test_sumsqdiff.py:576:41: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_sumsqdiff.py:576:43: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_sumsqdiff.py:578:5: E265 block comment should start with '# '
dipy/align/tests/test_sumsqdiff.py:587:5: E265 block comment should start with '# '
dipy/align/tests/test_sumsqdiff.py:588:5: E265 block comment should start with '# '
dipy/align/tests/test_sumsqdiff.py:589:5: E265 block comment should start with '# '
dipy/align/tests/test_sumsqdiff.py:592:5: E265 block comment should start with '# '
dipy/align/tests/test_sumsqdiff.py:594:9: E265 block comment should start with '# '
dipy/align/tests/test_sumsqdiff.py:597:43: E261 at least two spaces before inline comment
dipy/align/tests/test_sumsqdiff.py:597:44: E262 inline comment should start with '# '
dipy/align/tests/test_sumsqdiff.py:597:80: E501 line too long (84 > 79 characters)
dipy/align/tests/test_sumsqdiff.py:602:9: E265 block comment should start with '# '
dipy/align/tests/test_sumsqdiff.py:628:5: E265 block comment should start with '# '
dipy/align/tests/test_sumsqdiff.py:631:5: E265 block comment should start with '# '
dipy/align/tests/test_sumsqdiff.py:635:5: E265 block comment should start with '# '
dipy/align/tests/test_sumsqdiff.py:639:36: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_sumsqdiff.py:639:38: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_sumsqdiff.py:641:10: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:641:13: E225 missing whitespace around operator
dipy/align/tests/test_sumsqdiff.py:642:10: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:642:13: E225 missing whitespace around operator
dipy/align/tests/test_sumsqdiff.py:643:10: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:643:13: E225 missing whitespace around operator
dipy/align/tests/test_sumsqdiff.py:645:5: E265 block comment should start with '# '
dipy/align/tests/test_sumsqdiff.py:651:80: E501 line too long (87 > 79 characters)
dipy/align/tests/test_sumsqdiff.py:655:80: E501 line too long (87 > 79 characters)
dipy/align/tests/test_sumsqdiff.py:659:5: E265 block comment should start with '# '
dipy/align/tests/test_sumsqdiff.py:660:38: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:662:5: E265 block comment should start with '# '
dipy/align/tests/test_sumsqdiff.py:663:29: E231 missing whitespace after ','
dipy/align/tests/test_sumsqdiff.py:674:18: E222 multiple spaces after operator
dipy/align/tests/test_sumsqdiff.py:674:41: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_sumsqdiff.py:674:43: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_sumsqdiff.py:676:5: E265 block comment should start with '# '
dipy/align/tests/test_sumsqdiff.py:685:5: E265 block comment should start with '# '
dipy/align/tests/test_sumsqdiff.py:686:5: E265 block comment should start with '# '
dipy/align/tests/test_sumsqdiff.py:687:5: E265 block comment should start with '# '
dipy/align/tests/test_sumsqdiff.py:690:5: E265 block comment should start with '# '
dipy/align/tests/test_sumsqdiff.py:692:9: E265 block comment should start with '# '
dipy/align/tests/test_sumsqdiff.py:695:43: E261 at least two spaces before inline comment
dipy/align/tests/test_sumsqdiff.py:695:44: E262 inline comment should start with '# '
dipy/align/tests/test_sumsqdiff.py:695:80: E501 line too long (84 > 79 characters)
dipy/align/tests/test_sumsqdiff.py:701:9: E265 block comment should start with '# '
dipy/align/tests/test_sumsqdiff.py:705:62: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_sumsqdiff.py:705:64: E251 unexpected spaces around keyword / parameter equals
dipy/align/tests/test_sumsqdiff.py:712:12: E225 missing whitespace around operator

**Comment by ghoshbishakh** [comment]
closed through #946
