### ISSUE TITLE
PEP8 in test_transforms

### ISSUE THREAD

**Issue by arokem** [nipy/dipy#870]
dipy/align/tests/test_transforms.py:9:1: E302 expected 2 blank lines, found 1
dipy/align/tests/test_transforms.py:10:42: E203 whitespace before ':'
dipy/align/tests/test_transforms.py:11:42: E203 whitespace before ':'
dipy/align/tests/test_transforms.py:12:39: E203 whitespace before ':'
dipy/align/tests/test_transforms.py:13:39: E203 whitespace before ':'
dipy/align/tests/test_transforms.py:14:36: E203 whitespace before ':'
dipy/align/tests/test_transforms.py:15:36: E203 whitespace before ':'
dipy/align/tests/test_transforms.py:16:38: E203 whitespace before ':'
dipy/align/tests/test_transforms.py:17:38: E203 whitespace before ':'
dipy/align/tests/test_transforms.py:18:37: E203 whitespace before ':'
dipy/align/tests/test_transforms.py:19:37: E203 whitespace before ':'
dipy/align/tests/test_transforms.py:22:80: E501 line too long (82 > 79 characters)
dipy/align/tests/test_transforms.py:67:15: E231 missing whitespace after ','
dipy/align/tests/test_transforms.py:68:15: E231 missing whitespace after ','
dipy/align/tests/test_transforms.py:104:29: E202 whitespace before ']'
dipy/align/tests/test_transforms.py:112:21: E203 whitespace before ','
dipy/align/tests/test_transforms.py:114:24: E261 at least two spaces before inline comment
dipy/align/tests/test_transforms.py:130:29: E202 whitespace before ']'
dipy/align/tests/test_transforms.py:138:21: E203 whitespace before ','
dipy/align/tests/test_transforms.py:140:24: E261 at least two spaces before inline comment
dipy/align/tests/test_transforms.py:162:15: E231 missing whitespace after ','
dipy/align/tests/test_transforms.py:163:15: E231 missing whitespace after ','
dipy/align/tests/test_transforms.py:164:15: E231 missing whitespace after ','
dipy/align/tests/test_transforms.py:190:5: E265 block comment should start with '# '
dipy/align/tests/test_transforms.py:214:27: E231 missing whitespace after ','
dipy/align/tests/test_transforms.py:218:80: E501 line too long (82 > 79 characters)
dipy/align/tests/test_transforms.py:251:12: E225 missing whitespace around operator

**Comment by souravsingh** [comment]
I would like to work on the issue.

**Comment by ghoshbishakh** [comment]
closed through #947
