### ISSUE TITLE
PEP8 in test_vector_fields

### ISSUE THREAD

**Issue by arokem** [nipy/dipy#871]
dipy/align/tests/test_vector_fields.py:776:17: E128 continuation line under-indented for visual indent
dipy/align/tests/test_vector_fields.py:782:17: E128 continuation line under-indented for visual indent
dipy/align/tests/test_vector_fields.py:787:9: E128 continuation line under-indented for visual indent
dipy/align/tests/test_vector_fields.py:791:9: E128 continuation line under-indented for visual indent
dipy/align/tests/test_vector_fields.py:801:80: E501 line too long (82 > 79 characters)
dipy/align/tests/test_vector_fields.py:803:80: E501 line too long (81 > 79 characters)
dipy/align/tests/test_vector_fields.py:804:80: E501 line too long (85 > 79 characters)
dipy/align/tests/test_vector_fields.py:862:17: E128 continuation line under-indented for visual indent
dipy/align/tests/test_vector_fields.py:868:17: E128 continuation line under-indented for visual indent
dipy/align/tests/test_vector_fields.py:873:9: E128 continuation line under-indented for visual indent
dipy/align/tests/test_vector_fields.py:877:36: E128 continuation line under-indented for visual indent
dipy/align/tests/test_vector_fields.py:888:80: E501 line too long (82 > 79 characters)
dipy/align/tests/test_vector_fields.py:890:80: E501 line too long (81 > 79 characters)
dipy/align/tests/test_vector_fields.py:891:80: E501 line too long (85 > 79 characters)

**Comment by ghoshbishakh** [comment]
@arokem closed through #947 ?
