### ISSUE TITLE
PEP8 in core

### ISSUE THREAD

**Issue by arokem** [nipy/dipy#873]
dipy/core/__init__.py:9:1: W391 blank line at end of file
dipy/core/geometry.py:981:80: E501 line too long (140 > 79 characters)
dipy/core/gradients.py:153:1: E302 expected 2 blank lines, found 1
dipy/core/gradients.py:247:45: E272 multiple spaces before keyword
dipy/core/graph.py:4:1: E302 expected 2 blank lines, found 1
dipy/core/graph.py:5:25: W291 trailing whitespace
dipy/core/graph.py:6:1: W293 blank line contains whitespace
dipy/core/graph.py:11:1: W293 blank line contains whitespace
dipy/core/graph.py:13:1: W293 blank line contains whitespace
dipy/core/graph.py:18:1: W293 blank line contains whitespace
dipy/core/graph.py:22:22: W291 trailing whitespace
dipy/core/graph.py:33:1: W293 blank line contains whitespace
dipy/core/graph.py:35:1: W293 blank line contains whitespace
dipy/core/graph.py:36:18: E225 missing whitespace around operator
dipy/core/graph.py:37:18: E225 missing whitespace around operator
dipy/core/graph.py:38:18: E225 missing whitespace around operator
dipy/core/graph.py:40:22: E231 missing whitespace after ','
dipy/core/graph.py:40:24: E231 missing whitespace after ','
dipy/core/graph.py:41:21: E225 missing whitespace around operator
dipy/core/graph.py:42:21: E225 missing whitespace around operator
dipy/core/graph.py:43:21: E225 missing whitespace around operator
dipy/core/graph.py:45:22: E231 missing whitespace after ','
dipy/core/graph.py:45:24: E231 missing whitespace after ','
dipy/core/graph.py:45:26: E231 missing whitespace after ','
dipy/core/graph.py:45:34: E231 missing whitespace after ','
dipy/core/graph.py:46:24: E225 missing whitespace around operator
dipy/core/graph.py:47:24: E225 missing whitespace around operator
dipy/core/graph.py:49:21: E231 missing whitespace after ','
dipy/core/graph.py:49:25: W291 trailing whitespace
dipy/core/graph.py:52:22: E231 missing whitespace after ','
dipy/core/graph.py:55:21: W291 trailing whitespace
dipy/core/graph.py:56:40: E231 missing whitespace after ','
dipy/core/graph.py:58:23: W291 trailing whitespace
dipy/core/graph.py:59:40: E231 missing whitespace after ','
dipy/core/graph.py:60:1: W293 blank line contains whitespace
dipy/core/graph.py:61:22: E231 missing whitespace after ','
dipy/core/graph.py:61:26: W291 trailing whitespace
dipy/core/graph.py:62:44: E231 missing whitespace after ','
dipy/core/graph.py:63:1: W293 blank line contains whitespace
dipy/core/graph.py:64:24: E231 missing whitespace after ','
dipy/core/graph.py:64:28: W291 trailing whitespace
dipy/core/graph.py:65:44: E231 missing whitespace after ','
dipy/core/graph.py:65:47: W291 trailing whitespace
dipy/core/graph.py:67:23: E231 missing whitespace after ','
dipy/core/graph.py:68:30: W291 trailing whitespace
dipy/core/graph.py:69:17: E225 missing whitespace around operator
dipy/core/graph.py:69:38: E225 missing whitespace around operator
dipy/core/graph.py:70:26: W291 trailing whitespace
dipy/core/graph.py:71:12: E713 test for membership should be 'not in'
dipy/core/graph.py:81:27: E231 missing whitespace after ','
dipy/core/graph.py:83:24: E225 missing whitespace around operator
dipy/core/graph.py:85:12: E713 test for membership should be 'not in'
dipy/core/graph.py:96:32: E231 missing whitespace after ','
dipy/core/graph.py:101:1: W293 blank line contains whitespace
dipy/core/graph.py:110:22: E231 missing whitespace after ','
dipy/core/graph.py:111:13: W291 trailing whitespace
dipy/core/graph.py:115:1: W293 blank line contains whitespace
dipy/core/graph.py:118:32: E225 missing whitespace around operator
dipy/core/graph.py:119:32: E225 missing whitespace around operator
dipy/core/graph.py:119:48: W291 trailing whitespace
dipy/core/graph.py:120:35: W291 trailing whitespace
dipy/core/graph.py:129:21: W291 trailing whitespace
dipy/core/graph.py:142:1: W391 blank line at end of file
dipy/core/histeq.py:21:5: E265 block comment should start with '# '
dipy/core/histeq.py:26:5: E265 block comment should start with '# '
dipy/core/ndindex.py:6:1: E302 expected 2 blank lines, found 1
dipy/core/onetime.py:58:1: E265 block comment should start with '# '
dipy/core/onetime.py:60:1: E265 block comment should start with '# '
dipy/core/onetime.py:209:1: E265 block comment should start with '# '
dipy/core/onetime.py:211:1: E265 block comment should start with '# '
dipy/core/profile.py:14:1: E302 expected 2 blank lines, found 1
dipy/core/profile.py:16:1: W293 blank line contains whitespace
dipy/core/profile.py:17:53: W291 trailing whitespace
dipy/core/profile.py:19:1: W293 blank line contains whitespace
dipy/core/profile.py:33:1: W293 blank line contains whitespace
dipy/core/profile.py:49:1: W293 blank line contains whitespace
dipy/core/profile.py:52:22: E231 missing whitespace after ','
dipy/core/profile.py:52:32: E231 missing whitespace after ','
dipy/core/profile.py:59:1: W293 blank line contains whitespace
dipy/core/profile.py:60:16: E225 missing whitespace around operator
dipy/core/profile.py:60:50: W291 trailing whitespace
dipy/core/profile.py:61:24: E231 missing whitespace after ','
dipy/core/profile.py:61:29: W291 trailing whitespace
dipy/core/profile.py:62:46: E261 at least two spaces before inline comment
dipy/core/profile.py:62:47: E262 inline comment should start with '# '
dipy/core/profile.py:64:42: E231 missing whitespace after ','
dipy/core/profile.py:64:47: E231 missing whitespace after ','
dipy/core/profile.py:64:60: E502 the backslash is redundant between brackets
dipy/core/profile.py:65:38: E231 missing whitespace after ','
dipy/core/profile.py:65:53: E231 missing whitespace after ','
dipy/core/profile.py:66:49: W291 trailing whitespace
dipy/core/profile.py:67:22: E225 missing whitespace around operator
dipy/core/profile.py:68:27: E225 missing whitespace around operator
dipy/core/profile.py:69:1: W293 blank line contains whitespace
dipy/core/profile.py:72:49: W291 trailing whitespace
dipy/core/profile.py:73:22: E225 missing whitespace around operator
dipy/core/profile.py:74:22: E225 missing whitespace around operator
dipy/core/profile.py:76:55: E231 missing whitespace after ','
dipy/core/profile.py:76:65: E231 missing whitespace after ','
dipy/core/profile.py:76:75: E502 the backslash is redundant between brackets
dipy/core/profile.py:77:33: E127 continuation line over-indented for visual indent
dipy/core/profile.py:79:18: E225 missing whitespace around operator
dipy/core/profile.py:80:23: E225 missing whitespace around operator
dipy/core/profile.py:83:5: E303 too many blank lines (2)
dipy/core/profile.py:86:25: E231 missing whitespace after ','
dipy/core/profile.py:95:1: W293 blank line contains whitespace
dipy/core/rng.py:7:1: E302 expected 2 blank lines, found 1
dipy/core/rng.py:12:80: E501 line too long (129 > 79 characters)
dipy/core/rng.py:13:80: E501 line too long (101 > 79 characters)
dipy/core/rng.py:27:9: E265 block comment should start with '# '
dipy/core/rng.py:27:80: E501 line too long (82 > 79 characters)
dipy/core/rng.py:35:9: E265 block comment should start with '# '
dipy/core/rng.py:38:27: E222 multiple spaces after operator
dipy/core/rng.py:38:51: E222 multiple spaces after operator
dipy/core/rng.py:39:27: E222 multiple spaces after operator
dipy/core/rng.py:39:51: E222 multiple spaces after operator
dipy/core/rng.py:40:27: E222 multiple spaces after operator
dipy/core/rng.py:40:37: E222 multiple spaces after operator
dipy/core/rng.py:40:51: E222 multiple spaces after operator
dipy/core/rng.py:95:27: E127 continuation line over-indented for visual indent
dipy/core/rng.py:95:27: W503 line break before binary operator
dipy/core/rng.py:116:7: E271 multiple spaces after keyword
dipy/core/sphere.py:564:27: E203 whitespace before ':'
dipy/core/sphere.py:565:25: E203 whitespace before ':'
dipy/core/sphere.py:569:25: E203 whitespace before ':'
dipy/core/sphere_stats.py:9:1: E302 expected 2 blank lines, found 1
dipy/core/sphere_stats.py:58:1: E302 expected 2 blank lines, found 1
dipy/core/sphere_stats.py:69:80: E501 line too long (86 > 79 characters)
dipy/core/sphere_stats.py:93:28: E231 missing whitespace after ','
dipy/core/sphere_stats.py:105:16: E231 missing whitespace after ','
dipy/core/sphere_stats.py:108:8: E231 missing whitespace after ','
dipy/core/sphere_stats.py:108:17: E231 missing whitespace after ','
dipy/core/sphere_stats.py:108:32: E231 missing whitespace after ','
dipy/core/sphere_stats.py:111:48: E231 missing whitespace after ','
dipy/core/sphere_stats.py:114:20: E231 missing whitespace after ','
dipy/core/sphere_stats.py:116:23: E231 missing whitespace after ','
dipy/core/sphere_stats.py:116:27: E231 missing whitespace after ','
dipy/core/sphere_stats.py:117:23: E231 missing whitespace after ','
dipy/core/sphere_stats.py:117:27: E231 missing whitespace after ','
dipy/core/sphere_stats.py:118:23: E231 missing whitespace after ','
dipy/core/sphere_stats.py:118:27: E231 missing whitespace after ','
dipy/core/sphere_stats.py:121:8: E231 missing whitespace after ','
dipy/core/sphere_stats.py:122:8: E231 missing whitespace after ','
dipy/core/sphere_stats.py:123:8: E231 missing whitespace after ','
dipy/core/sphere_stats.py:124:8: E231 missing whitespace after ','
dipy/core/sphere_stats.py:124:17: E231 missing whitespace after ','
dipy/core/sphere_stats.py:127:26: E231 missing whitespace after ','
dipy/core/sphere_stats.py:130:6: E231 missing whitespace after ','
dipy/core/sphere_stats.py:132:7: E225 missing whitespace around operator
dipy/core/sphere_stats.py:158:1: E302 expected 2 blank lines, found 1
dipy/core/sphere_stats.py:158:31: E231 missing whitespace after ','
dipy/core/sphere_stats.py:203:36: E231 missing whitespace after ','
dipy/core/sphere_stats.py:203:80: E501 line too long (90 > 79 characters)
dipy/core/sphere_stats.py:203:87: E231 missing whitespace after ','
dipy/core/sphere_stats.py:205:5: E265 block comment should start with '# '
dipy/core/sphere_stats.py:207:1: E302 expected 2 blank lines, found 1
dipy/core/sphere_stats.py:207:25: E231 missing whitespace after ','
dipy/core/sphere_stats.py:288:36: E231 missing whitespace after ','
dipy/core/sphere_stats.py:288:80: E501 line too long (90 > 79 characters)
dipy/core/sphere_stats.py:288:87: E231 missing whitespace after ','
dipy/core/sphere_stats.py:290:31: E261 at least two spaces before inline comment
dipy/core/sphere_stats.py:290:31: E262 inline comment should start with '# '
dipy/core/subdivide_octahedron.py:9:78: W291 trailing whitespace
dipy/core/subdivide_octahedron.py:15:1: E302 expected 2 blank lines, found 1
dipy/core/subdivide_octahedron.py:15:24: E201 whitespace after '('
dipy/core/subdivide_octahedron.py:15:42: E202 whitespace before ')'
dipy/core/subdivide_octahedron.py:41:1: E302 expected 2 blank lines, found 1
dipy/core/subdivide_octahedron.py:41:28: E201 whitespace after '('
dipy/core/subdivide_octahedron.py:41:46: E202 whitespace before ')'
dipy/core/subdivide_octahedron.py:61:33: E201 whitespace after '('
dipy/core/subdivide_octahedron.py:61:49: E202 whitespace before ')'
dipy/core/subdivide_octahedron.py:64:1: W391 blank line at end of file
dipy/core/tests/__init__.py:6:11: W292 no newline at end of file
dipy/core/tests/test_graph.py:4:1: W293 blank line contains whitespace
dipy/core/tests/test_graph.py:5:1: E302 expected 2 blank lines, found 1
dipy/core/tests/test_graph.py:7:6: E225 missing whitespace around operator
dipy/core/tests/test_graph.py:8:1: W293 blank line contains whitespace
dipy/core/tests/test_graph.py:9:19: E231 missing whitespace after ','
dipy/core/tests/test_graph.py:10:19: E231 missing whitespace after ','
dipy/core/tests/test_graph.py:11:19: E231 missing whitespace after ','
dipy/core/tests/test_graph.py:12:19: E231 missing whitespace after ','
dipy/core/tests/test_graph.py:13:1: W293 blank line contains whitespace
dipy/core/tests/test_graph.py:14:19: E231 missing whitespace after ','
dipy/core/tests/test_graph.py:15:19: E231 missing whitespace after ','
dipy/core/tests/test_graph.py:16:19: E231 missing whitespace after ','
dipy/core/tests/test_graph.py:17:19: E231 missing whitespace after ','
dipy/core/tests/test_graph.py:18:1: W293 blank line contains whitespace
dipy/core/tests/test_graph.py:20:18: W291 trailing whitespace
dipy/core/tests/test_graph.py:22:18: W291 trailing whitespace
dipy/core/tests/test_graph.py:24:18: W291 trailing whitespace
dipy/core/tests/test_graph.py:26:21: W291 trailing whitespace
dipy/core/tests/test_graph.py:28:23: W291 trailing whitespace
dipy/core/tests/test_graph.py:30:27: W291 trailing whitespace
dipy/core/tests/test_graph.py:32:29: W291 trailing whitespace
dipy/core/tests/test_graph.py:33:11: E201 whitespace after '('
dipy/core/tests/test_graph.py:34:5: E265 block comment should start with '# '
dipy/core/tests/test_graph.py:35:20: W291 trailing whitespace
dipy/core/tests/test_graph.py:36:11: E201 whitespace after '('
dipy/core/tests/test_graph.py:37:11: E201 whitespace after '('
dipy/core/tests/test_graph.py:37:19: W291 trailing whitespace
dipy/core/tests/test_graph.py:38:11: E201 whitespace after '('
dipy/core/tests/test_graph.py:39:11: E201 whitespace after '('
dipy/core/tests/test_graph.py:39:19: W291 trailing whitespace
dipy/core/tests/test_graph.py:40:11: E201 whitespace after '('
dipy/core/tests/test_graph.py:41:11: E201 whitespace after '('
dipy/core/tests/test_graph.py:42:1: W293 blank line contains whitespace
dipy/core/tests/test_graph.py:43:29: E231 missing whitespace after ','
dipy/core/tests/test_graph.py:44:29: E231 missing whitespace after ','
dipy/core/tests/test_graph.py:45:29: E231 missing whitespace after ','
dipy/core/tests/test_graph.py:46:1: W293 blank line contains whitespace
dipy/core/tests/test_graph.py:46:1: W391 blank line at end of file
dipy/core/tests/test_ndindex.py:6:1: E302 expected 2 blank lines, found 1
dipy/core/tests/test_ndindex.py:11:1: E302 expected 2 blank lines, found 1
dipy/core/tests/test_sphere.py:31:1: E302 expected 2 blank lines, found 1
dipy/core/tests/test_sphere.py:164:1: E302 expected 2 blank lines, found 1
dipy/core/tests/test_sphere.py:174:80: E501 line too long (80 > 79 characters)
dipy/core/tests/test_sphere.py:264:11: E201 whitespace after '['
dipy/core/tests/test_sphere.py:265:11: E201 whitespace after '['
dipy/core/tests/test_sphere.py:266:11: E201 whitespace after '['
dipy/core/tests/test_sphere.py:267:11: E201 whitespace after '['
dipy/core/tests/test_sphere.py:268:11: E201 whitespace after '['
dipy/core/tests/test_sphere.py:269:11: E201 whitespace after '['
dipy/core/tests/test_sphere.py:270:9: E124 closing bracket does not match visual indentation
dipy/core/tests/test_sphere.py:283:9: E124 closing bracket does not match visual indentation
dipy/core/tests/test_sphere.py:300:9: E124 closing bracket does not match visual indentation
dipy/core/tests/test_sphere.py:322:1: E302 expected 2 blank lines, found 1
dipy/core/tests/test_sphere.py:332:23: E222 multiple spaces after operator
dipy/core/tests/test_sphere.py:337:9: E265 block comment should start with '# '
dipy/core/tests/test_sphere.py:344:9: E265 block comment should start with '# '
dipy/core/tests/test_sphere.py:347:5: E265 block comment should start with '# '
dipy/core/tests/test_sphere.py:348:38: E231 missing whitespace after ','
dipy/core/tests/test_sphere.py:353:9: E265 block comment should start with '# '
dipy/core/tests/test_sphere.py:355:5: E265 block comment should start with '# '
dipy/core/tests/test_sphere.py:360:1: E302 expected 2 blank lines, found 1
dipy/core/tests/test_sphere.py:375:80: E501 line too long (82 > 79 characters)
dipy/core/tests/test_sphere.py:378:55: E251 unexpected spaces around keyword / parameter equals
dipy/core/tests/test_subdivide_octahedron.py:12:1: E302 expected 2 blank lines, found 1
dipy/core/tests/test_subdivide_octahedron.py:16:1: W391 blank line at end of file

**Comment by ghoshbishakh** [comment]
this can be closed I guess

**Comment by arokem** [comment]
Which PR closed this?

**Comment by ghoshbishakh** [comment]
#963 was merged so I thought this issue was fixed actually. May be I am missing something here.

**Comment by arokem** [comment]
No - you're spot on. Just needed that number. 

Closed through #963
