### ISSUE TITLE
PEP8 in external

### ISSUE THREAD

**Issue by arokem** [nipy/dipy#877]
dipy/external/fsl.py:110:80: E501 line too long (80 > 79 characters)
dipy/external/fsl.py:113:80: E501 line too long (80 > 79 characters)
dipy/external/fsl.py:128:80: E501 line too long (80 > 79 characters)
dipy/external/fsl.py:219:80: E501 line too long (119 > 79 characters)
dipy/external/fsl.py:220:80: E501 line too long (83 > 79 characters)
dipy/external/fsl.py:289:80: E501 line too long (87 > 79 characters)
dipy/external/fsl.py:290:80: E501 line too long (87 > 79 characters)
dipy/external/fsl.py:291:80: E501 line too long (87 > 79 characters)
dipy/external/fsl.py:300:80: E501 line too long (82 > 79 characters)
dipy/external/fsl.py:315:80: E501 line too long (88 > 79 characters)
dipy/external/fsl.py:332:1: W293 blank line contains whitespace
dipy/external/fsl.py:337:17: E203 whitespace before ':'
dipy/external/fsl.py:339:17: E203 whitespace before ':'
dipy/external/fsl.py:381:80: E501 line too long (88 > 79 characters)
dipy/external/fsl.py:400:80: E501 line too long (111 > 79 characters)
dipy/external/fsl.py:423:80: E501 line too long (113 > 79 characters)
dipy/external/fsl.py:424:80: E501 line too long (86 > 79 characters)
dipy/external/fsl.py:425:80: E501 line too long (118 > 79 characters)
dipy/external/fsl.py:426:80: E501 line too long (111 > 79 characters)
dipy/external/tests/__init__.py:2:1: W391 blank line at end of file

**Comment by manu-tej** [comment]
@arokem issue closed via #955
