### ISSUE TITLE
PEP8 in reconst

### ISSUE THREAD

**Issue by arokem** [nipy/dipy#880]
dipy/reconst/**init**.py:1:1: E265 block comment should start with '# '
dipy/reconst/**init**.py:12:1: W391 blank line at end of file
dipy/reconst/base.py:25:18: E225 missing whitespace around operator
dipy/reconst/base.py:27:34: E231 missing whitespace after ','
dipy/reconst/base.py:30:1: E302 expected 2 blank lines, found 1
dipy/reconst/cache.py:3:1: E302 expected 2 blank lines, found 1
dipy/reconst/csdeconv.py:94:80: E501 line too long (81 > 79 characters)
dipy/reconst/csdeconv.py:126:45: E712 comparison to False should be 'if cond is False:' or 'if not cond:'
dipy/reconst/csdeconv.py:142:80: E501 line too long (80 > 79 characters)
dipy/reconst/csdeconv.py:167:27: E221 multiple spaces before operator
dipy/reconst/csdeconv.py:183:5: E303 too many blank lines (2)
dipy/reconst/csdeconv.py:257:80: E501 line too long (81 > 79 characters)
dipy/reconst/csdeconv.py:278:45: E712 comparison to False should be 'if cond is False:' or 'if not cond:'
dipy/reconst/csdeconv.py:294:80: E501 line too long (80 > 79 characters)
dipy/reconst/csdeconv.py:399:1: E302 expected 2 blank lines, found 1
dipy/reconst/csdeconv.py:464:80: E501 line too long (80 > 79 characters)
dipy/reconst/csdeconv.py:572:13: E129 visually indented line with same indent as next logical line
dipy/reconst/csdeconv.py:590:80: E501 line too long (88 > 79 characters)
dipy/reconst/csdeconv.py:592:80: E501 line too long (92 > 79 characters)
dipy/reconst/csdeconv.py:628:80: E501 line too long (81 > 79 characters)
dipy/reconst/csdeconv.py:642:16: E203 whitespace before ':'
dipy/reconst/csdeconv.py:648:5: E265 block comment should start with '# '
dipy/reconst/csdeconv.py:658:13: E122 continuation line missing indentation or outdented
dipy/reconst/csdeconv.py:705:80: E501 line too long (80 > 79 characters)
dipy/reconst/csdeconv.py:818:80: E501 line too long (92 > 79 characters)
dipy/reconst/dsi.py:29:80: E501 line too long (116 > 79 characters)
dipy/reconst/dsi.py:203:80: E501 line too long (96 > 79 characters)
dipy/reconst/dsi.py:209:80: E501 line too long (86 > 79 characters)
dipy/reconst/dsi.py:243:80: E501 line too long (167 > 79 characters)
dipy/reconst/dsi.py:246:80: E501 line too long (92 > 79 characters)
dipy/reconst/dsi.py:251:80: E501 line too long (86 > 79 characters)
dipy/reconst/dsi.py:504:80: E501 line too long (174 > 79 characters)
dipy/reconst/dsi.py:505:80: E501 line too long (163 > 79 characters)
dipy/reconst/dsi.py:506:80: E501 line too long (166 > 79 characters)
dipy/reconst/dsi.py:649:80: E501 line too long (112 > 79 characters)
dipy/reconst/dti.py:1094:80: E501 line too long (94 > 79 characters)
dipy/reconst/dti.py:1786:5: E265 block comment should start with '# '
dipy/reconst/dti.py:1789:5: E265 block comment should start with '# '
dipy/reconst/gqi.py:40:1: W293 blank line contains whitespace
dipy/reconst/gqi.py:44:1: E101 indentation contains mixed spaces and tabs
dipy/reconst/gqi.py:44:1: W191 indentation contains tabs
dipy/reconst/gqi.py:44:66: W291 trailing whitespace
dipy/reconst/gqi.py:45:1: E101 indentation contains mixed spaces and tabs
dipy/reconst/gqi.py:45:74: W291 trailing whitespace
dipy/reconst/gqi.py:46:38: W291 trailing whitespace
dipy/reconst/gqi.py:56:74: W291 trailing whitespace
dipy/reconst/gqi.py:78:32: E261 at least two spaces before inline comment
dipy/reconst/gqi.py:112:18: E225 missing whitespace around operator
dipy/reconst/gqi.py:113:17: E265 block comment should start with '# '
dipy/reconst/gqi.py:114:80: E501 line too long (152 > 79 characters)
dipy/reconst/gqi.py:116:80: E501 line too long (160 > 79 characters)
dipy/reconst/gqi.py:123:39: W291 trailing whitespace
dipy/reconst/gqi.py:142:71: W291 trailing whitespace
dipy/reconst/gqi.py:143:51: W291 trailing whitespace
dipy/reconst/gqi.py:168:5: E265 block comment should start with '# '
dipy/reconst/gqi.py:173:80: E501 line too long (130 > 79 characters)
dipy/reconst/gqi.py:174:5: E265 block comment should start with '# '
dipy/reconst/gqi.py:176:14: E231 missing whitespace after ','
dipy/reconst/gqi.py:176:17: E231 missing whitespace after ','
dipy/reconst/gqi.py:176:20: E231 missing whitespace after ','
dipy/reconst/gqi.py:184:20: E231 missing whitespace after ','
dipy/reconst/gqi.py:184:64: E231 missing whitespace after ','
dipy/reconst/gqi.py:184:80: E501 line too long (105 > 79 characters)
dipy/reconst/gqi.py:192:20: E231 missing whitespace after ','
dipy/reconst/gqi.py:192:64: E231 missing whitespace after ','
dipy/reconst/gqi.py:192:80: E501 line too long (105 > 79 characters)
dipy/reconst/gqi.py:204:5: E265 block comment should start with '# '
dipy/reconst/gqi.py:206:80: E501 line too long (94 > 79 characters)
dipy/reconst/gqi.py:216:28: E231 missing whitespace after ','
dipy/reconst/gqi.py:220:20: E231 missing whitespace after ','
dipy/reconst/gqi.py:220:64: E231 missing whitespace after ','
dipy/reconst/gqi.py:220:80: E501 line too long (105 > 79 characters)
dipy/reconst/gqi.py:225:5: E265 block comment should start with '# '
dipy/reconst/gqi.py:227:80: E501 line too long (91 > 79 characters)
dipy/reconst/gqi.py:242:5: E265 block comment should start with '# '
dipy/reconst/gqi.py:244:80: E501 line too long (91 > 79 characters)
dipy/reconst/gqi.py:251:38: E231 missing whitespace after ','
dipy/reconst/gqi.py:255:52: E502 the backslash is redundant between brackets
dipy/reconst/gqi.py:256:47: E127 continuation line over-indented for visual indent
dipy/reconst/gqi.py:257:64: E231 missing whitespace after ','
dipy/reconst/gqi.py:257:80: E501 line too long (96 > 79 characters)
dipy/reconst/gqi.py:264:31: E231 missing whitespace after ','
dipy/reconst/gqi.py:264:50: E231 missing whitespace after ','
dipy/reconst/interpolate.py:1:80: E501 line too long (87 > 79 characters)
dipy/reconst/interpolate.py:13:1: E302 expected 2 blank lines, found 1
dipy/reconst/interpolate.py:16:1: E302 expected 2 blank lines, found 1
dipy/reconst/interpolate.py:22:1: E302 expected 2 blank lines, found 1
dipy/reconst/interpolate.py:34:1: E302 expected 2 blank lines, found 1
dipy/reconst/mapmri.py:23:74: W291 trailing whitespace
dipy/reconst/mapmri.py:26:76: W291 trailing whitespace
dipy/reconst/mapmri.py:55:80: E501 line too long (81 > 79 characters)
dipy/reconst/mapmri.py:60:80: E501 line too long (81 > 79 characters)
dipy/reconst/mapmri.py:61:78: W291 trailing whitespace
dipy/reconst/mapmri.py:64:80: W291 trailing whitespace
dipy/reconst/mapmri.py:82:72: W291 trailing whitespace
dipy/reconst/mapmri.py:93:80: E501 line too long (83 > 79 characters)
dipy/reconst/mapmri.py:97:80: E501 line too long (83 > 79 characters)
dipy/reconst/mapmri.py:111:80: E501 line too long (129 > 79 characters)
dipy/reconst/mapmri.py:305:80: E501 line too long (99 > 79 characters)
dipy/reconst/mapmri.py:322:80: E501 line too long (87 > 79 characters)
dipy/reconst/mapmri.py:325:80: E501 line too long (91 > 79 characters)
dipy/reconst/mapmri.py:410:80: E501 line too long (81 > 79 characters)
dipy/reconst/mapmri.py:610:80: E501 line too long (82 > 79 characters)
dipy/reconst/odf.py:8:1: E302 expected 2 blank lines, found 1
dipy/reconst/odf.py:70:1: W391 blank line at end of file
dipy/reconst/peaks.py:7:1: E402 module level import not at top of file
dipy/reconst/sfm.py:127:80: E501 line too long (80 > 79 characters)
dipy/reconst/sfm.py:129:1: E302 expected 2 blank lines, found 1
dipy/reconst/sfm.py:178:80: E501 line too long (81 > 79 characters)
dipy/reconst/sfm.py:227:80: E501 line too long (81 > 79 characters)
dipy/reconst/sfm.py:281:80: E501 line too long (81 > 79 characters)
dipy/reconst/sfm.py:295:80: E501 line too long (130 > 79 characters)
dipy/reconst/sfm.py:309:80: E501 line too long (80 > 79 characters)
dipy/reconst/sfm.py:344:13: E125 continuation line with same indent as next logical line
dipy/reconst/sfm.py:344:13: E128 continuation line under-indented for visual indent
dipy/reconst/sfm.py:391:65: E225 missing whitespace around operator
dipy/reconst/sfm.py:391:69: E203 whitespace before ':'
dipy/reconst/sfm.py:398:52: E127 continuation line over-indented for visual indent
dipy/reconst/shm.py:1040:80: E501 line too long (151 > 79 characters)
dipy/reconst/shore.py:21:1: E302 expected 2 blank lines, found 1
dipy/reconst/shore.py:210:80: E501 line too long (99 > 79 characters)
dipy/reconst/shore.py:245:17: W503 line break before binary operator
dipy/reconst/shore.py:263:80: E501 line too long (93 > 79 characters)
dipy/reconst/shore.py:271:80: E501 line too long (96 > 79 characters)
dipy/reconst/shore.py:382:80: E501 line too long (115 > 79 characters)
dipy/reconst/shore.py:383:80: E501 line too long (129 > 79 characters)
dipy/reconst/shore.py:384:80: E501 line too long (85 > 79 characters)
dipy/reconst/shore.py:385:80: E501 line too long (96 > 79 characters)
dipy/reconst/shore.py:419:20: E222 multiple spaces after operator
dipy/reconst/shore.py:439:80: E501 line too long (98 > 79 characters)
dipy/reconst/shore.py:450:80: E501 line too long (167 > 79 characters)
dipy/reconst/shore.py:453:80: E501 line too long (92 > 79 characters)
dipy/reconst/shore.py:464:24: E221 multiple spaces before operator
dipy/reconst/shore.py:465:56: E221 multiple spaces before operator
dipy/reconst/shore.py:465:59: E222 multiple spaces after operator
dipy/reconst/shore.py:465:80: E501 line too long (103 > 79 characters)
dipy/reconst/shore.py:585:79: E202 whitespace before ')'
dipy/reconst/shore.py:585:80: E501 line too long (83 > 79 characters)
dipy/reconst/shore.py:595:80: E501 line too long (87 > 79 characters)
dipy/reconst/shore.py:627:80: E501 line too long (88 > 79 characters)
dipy/reconst/shore.py:636:80: E501 line too long (80 > 79 characters)
dipy/reconst/shore.py:637:80: E501 line too long (94 > 79 characters)
dipy/reconst/shore.py:753:80: E501 line too long (91 > 79 characters)
dipy/reconst/shore.py:790:80: E501 line too long (91 > 79 characters)
dipy/reconst/utils.py:3:1: E302 expected 2 blank lines, found 1
dipy/reconst/benchmarks/bench_bounding_box.py:11:80: E501 line too long (80 > 79 characters)
dipy/reconst/benchmarks/bench_bounding_box.py:16:80: E501 line too long (84 > 79 characters)
dipy/reconst/benchmarks/bench_bounding_box.py:22:1: E302 expected 2 blank lines, found 1
dipy/reconst/benchmarks/bench_bounding_box.py:25:8: E211 whitespace before '['
dipy/reconst/benchmarks/bench_csd.py:9:1: E302 expected 2 blank lines, found 1
dipy/reconst/benchmarks/bench_peaks.py:9:80: E501 line too long (80 > 79 characters)
dipy/reconst/benchmarks/bench_squash.py:9:80: E501 line too long (80 > 79 characters)
dipy/reconst/benchmarks/bench_squash.py:29:1: E302 expected 2 blank lines, found 1
dipy/reconst/benchmarks/bench_squash.py:112:80: E501 line too long (80 > 79 characters)
dipy/reconst/benchmarks/bench_vec_val_sum.py:9:80: E501 line too long (80 > 79 characters)
dipy/reconst/benchmarks/bench_vec_val_sum.py:24:5: E731 do not assign a lambda expression, use a def
dipy/reconst/benchmarks/bench_vec_val_sum.py:24:27: E203 whitespace before ':'
dipy/reconst/benchmarks/bench_vec_val_sum.py:26:1: E302 expected 2 blank lines, found 1
dipy/reconst/benchmarks/bench_vec_val_sum.py:32:80: E501 line too long (80 > 79 characters)
dipy/reconst/tests/test_cache.py:6:1: E302 expected 2 blank lines, found 1
dipy/reconst/tests/test_csdeconv.py:62:80: E501 line too long (80 > 79 characters)
dipy/reconst/tests/test_csdeconv.py:128:80: E501 line too long (88 > 79 characters)
dipy/reconst/tests/test_csdeconv.py:144:1: E302 expected 2 blank lines, found 1
dipy/reconst/tests/test_csdeconv.py:295:14: E231 missing whitespace after ','
dipy/reconst/tests/test_csdeconv.py:295:16: E231 missing whitespace after ','
dipy/reconst/tests/test_csdeconv.py:333:15: E261 at least two spaces before inline comment
dipy/reconst/tests/test_csdeconv.py:333:16: E262 inline comment should start with '# '
dipy/reconst/tests/test_csdeconv.py:335:48: E262 inline comment should start with '# '
dipy/reconst/tests/test_csdeconv.py:374:1: E302 expected 2 blank lines, found 1
dipy/reconst/tests/test_csdeconv.py:463:49: E128 continuation line under-indented for visual indent
dipy/reconst/tests/test_csdeconv.py:465:49: E128 continuation line under-indented for visual indent
dipy/reconst/tests/test_csdeconv.py:471:21: E231 missing whitespace after ':'
dipy/reconst/tests/test_csdeconv.py:471:35: E231 missing whitespace after ':'
dipy/reconst/tests/test_csdeconv.py:471:50: E231 missing whitespace after ':'
dipy/reconst/tests/test_csdeconv.py:472:1: E302 expected 2 blank lines, found 0
dipy/reconst/tests/test_csdeconv.py:507:80: E501 line too long (80 > 79 characters)
dipy/reconst/tests/test_dsi.py:21:5: E265 block comment should start with '# '
dipy/reconst/tests/test_dsi.py:24:5: E265 block comment should start with '# '
dipy/reconst/tests/test_dsi.py:27:35: E231 missing whitespace after ','
dipy/reconst/tests/test_dsi.py:27:48: E231 missing whitespace after ','
dipy/reconst/tests/test_dsi.py:52:15: E225 missing whitespace around operator
dipy/reconst/tests/test_dsi.py:105:15: E225 missing whitespace around operator
dipy/reconst/tests/test_dsi_deconv.py:61:80: E501 line too long (80 > 79 characters)
dipy/reconst/tests/test_gqi.py:19:5: E265 block comment should start with '# '
dipy/reconst/tests/test_gqi.py:21:5: E265 block comment should start with '# '
dipy/reconst/tests/test_gqi.py:24:21: E231 missing whitespace after ','
dipy/reconst/tests/test_gqi.py:25:21: E231 missing whitespace after ','
dipy/reconst/tests/test_gqi.py:28:32: E128 continuation line under-indented for visual indent
dipy/reconst/tests/test_gqi.py:29:32: E128 continuation line under-indented for visual indent
dipy/reconst/tests/test_gqi.py:32:5: E265 block comment should start with '# '
dipy/reconst/tests/test_gqi.py:37:80: E501 line too long (80 > 79 characters)
dipy/reconst/tests/test_gqi.py:39:5: E265 block comment should start with '# '
dipy/reconst/tests/test_gqi.py:44:80: E501 line too long (80 > 79 characters)
dipy/reconst/tests/test_gqi.py:46:15: E225 missing whitespace around operator
dipy/reconst/tests/test_interpolate.py:13:1: E302 expected 2 blank lines, found 1
dipy/reconst/tests/test_interpolate.py:18:47: E231 missing whitespace after ','
dipy/reconst/tests/test_interpolate.py:18:49: E231 missing whitespace after ','
dipy/reconst/tests/test_interpolate.py:31:1: E302 expected 2 blank lines, found 1
dipy/reconst/tests/test_interpolate.py:37:41: E231 missing whitespace after ','
dipy/reconst/tests/test_interpolate.py:37:43: E231 missing whitespace after ','
dipy/reconst/tests/test_mapmri.py:15:44: W503 line break before binary operator
dipy/reconst/tests/test_mapmri.py:15:80: E501 line too long (81 > 79 characters)
dipy/reconst/tests/test_mapmri_odf.py:16:1: E302 expected 2 blank lines, found 1
dipy/reconst/tests/test_mapmri_odf.py:27:80: E501 line too long (84 > 79 characters)
dipy/reconst/tests/test_mapmri_odf.py:32:18: E203 whitespace before ','
dipy/reconst/tests/test_mapmri_odf.py:39:18: E203 whitespace before ','
dipy/reconst/tests/test_mapmri_odf.py:49:22: E203 whitespace before ','
dipy/reconst/tests/test_multi_voxel.py:63:18: E261 at least two spaces before inline comment
dipy/reconst/tests/test_multi_voxel.py:65:18: E261 at least two spaces before inline comment
dipy/reconst/tests/test_multi_voxel.py:67:25: E261 at least two spaces before inline comment
dipy/reconst/tests/test_multi_voxel.py:84:46: E261 at least two spaces before inline comment
dipy/reconst/tests/test_multi_voxel.py:87:18: E261 at least two spaces before inline comment
dipy/reconst/tests/test_multi_voxel.py:93:1: E303 too many blank lines (3)
dipy/reconst/tests/test_multi_voxel.py:163:27: E231 missing whitespace after ','
dipy/reconst/tests/test_multi_voxel.py:163:29: E231 missing whitespace after ','
dipy/reconst/tests/test_odf.py:73:5: E303 too many blank lines (2)
dipy/reconst/tests/test_peak_finding.py:11:1: E302 expected 2 blank lines, found 1
dipy/reconst/tests/test_reco_utils.py:7:51: E127 continuation line over-indented for visual indent
dipy/reconst/tests/test_reco_utils.py:35:5: E265 block comment should start with '# '
dipy/reconst/tests/test_sfm.py:46:80: E501 line too long (80 > 79 characters)
dipy/reconst/tests/test_sfm.py:79:20: E231 missing whitespace after ','
dipy/reconst/tests/test_sfm.py:79:22: E231 missing whitespace after ','
dipy/reconst/tests/test_shm.py:31:1: E302 expected 2 blank lines, found 1
dipy/reconst/tests/test_shm.py:69:30: E128 continuation line under-indented for visual indent
dipy/reconst/tests/test_shm.py:388:80: E501 line too long (85 > 79 characters)
dipy/reconst/tests/test_shm.py:389:32: E203 whitespace before ','
dipy/reconst/tests/test_shm.py:389:80: E501 line too long (85 > 79 characters)
dipy/reconst/tests/test_shm.py:390:80: E501 line too long (85 > 79 characters)
dipy/reconst/tests/test_shm.py:391:80: E501 line too long (85 > 79 characters)
dipy/reconst/tests/test_shm.py:392:80: E501 line too long (85 > 79 characters)
dipy/reconst/tests/test_shm.py:393:45: E203 whitespace before ','
dipy/reconst/tests/test_shm.py:393:80: E501 line too long (85 > 79 characters)
dipy/reconst/tests/test_shm.py:394:32: E203 whitespace before ','
dipy/reconst/tests/test_shm.py:394:80: E501 line too long (85 > 79 characters)
dipy/reconst/tests/test_shm.py:395:58: E203 whitespace before ','
dipy/reconst/tests/test_shm.py:395:80: E501 line too long (85 > 79 characters)
dipy/reconst/tests/test_shm.py:396:80: E501 line too long (85 > 79 characters)
dipy/reconst/tests/test_shm.py:397:32: E203 whitespace before ','
dipy/reconst/tests/test_shm.py:397:80: E501 line too long (85 > 79 characters)
dipy/reconst/tests/test_shm.py:398:45: E203 whitespace before ','
dipy/reconst/tests/test_shm.py:398:80: E501 line too long (85 > 79 characters)
dipy/reconst/tests/test_shm.py:399:80: E501 line too long (85 > 79 characters)
dipy/reconst/tests/test_shm.py:402:31: E203 whitespace before ','
dipy/reconst/tests/test_shm.py:402:70: E203 whitespace before ','
dipy/reconst/tests/test_shm.py:402:80: E501 line too long (84 > 79 characters)
dipy/reconst/tests/test_shm.py:403:80: E501 line too long (83 > 79 characters)
dipy/reconst/tests/test_shm.py:404:80: E501 line too long (84 > 79 characters)
dipy/reconst/tests/test_shm.py:405:80: E501 line too long (83 > 79 characters)
dipy/reconst/tests/test_shm.py:406:30: E203 whitespace before ','
dipy/reconst/tests/test_shm.py:406:80: E501 line too long (83 > 79 characters)
dipy/reconst/tests/test_shm.py:406:82: E203 whitespace before ','
dipy/reconst/tests/test_shm.py:407:70: E203 whitespace before ','
dipy/reconst/tests/test_shm.py:407:80: E501 line too long (84 > 79 characters)
dipy/reconst/tests/test_shm.py:408:80: E501 line too long (84 > 79 characters)
dipy/reconst/tests/test_shm.py:409:80: E501 line too long (84 > 79 characters)
dipy/reconst/tests/test_shm.py:410:56: E203 whitespace before ','
dipy/reconst/tests/test_shm.py:410:80: E501 line too long (83 > 79 characters)
dipy/reconst/tests/test_shm.py:411:69: E203 whitespace before ','
dipy/reconst/tests/test_shm.py:411:80: E501 line too long (83 > 79 characters)
dipy/reconst/tests/test_shm.py:412:80: E501 line too long (83 > 79 characters)
dipy/reconst/tests/test_shm.py:413:80: E501 line too long (84 > 79 characters)
dipy/reconst/tests/test_shm.py:421:1: E302 expected 2 blank lines, found 1
dipy/reconst/tests/test_shore_fitting.py:24:17: E701 multiple statements on one line (colon)
dipy/reconst/tests/test_shore_fitting.py:27:1: E302 expected 2 blank lines, found 1
dipy/reconst/tests/test_shore_fitting.py:30:30: E127 continuation line over-indented for visual indent
dipy/reconst/tests/test_shore_fitting.py:54:25: E225 missing whitespace around operator
dipy/reconst/tests/test_shore_fitting.py:70:34: E251 unexpected spaces around keyword / parameter equals
dipy/reconst/tests/test_shore_fitting.py:70:36: E251 unexpected spaces around keyword / parameter equals
dipy/reconst/tests/test_shore_fitting.py:80:9: E128 continuation line under-indented for visual indent
dipy/reconst/tests/test_shore_fitting.py:80:80: E501 line too long (94 > 79 characters)
dipy/reconst/tests/test_shore_metrics.py:6:80: E501 line too long (83 > 79 characters)
dipy/reconst/tests/test_shore_metrics.py:39:80: E501 line too long (112 > 79 characters)
dipy/reconst/tests/test_shore_metrics.py:59:42: E225 missing whitespace around operator
dipy/reconst/tests/test_shore_metrics.py:60:58: E225 missing whitespace around operator
dipy/reconst/tests/test_shore_metrics.py:60:80: E231 missing whitespace after ','
dipy/reconst/tests/test_shore_metrics.py:60:80: E501 line too long (95 > 79 characters)
dipy/reconst/tests/test_shore_metrics.py:64:80: E501 line too long (83 > 79 characters)
dipy/reconst/tests/test_shore_metrics.py:76:54: E251 unexpected spaces around keyword / parameter equals
dipy/reconst/tests/test_shore_metrics.py:86:47: E225 missing whitespace around operator
dipy/reconst/tests/test_shore_metrics.py:86:80: E501 line too long (96 > 79 characters)
dipy/reconst/tests/test_shore_odf.py:38:5: E303 too many blank lines (2)
dipy/reconst/tests/test_shore_odf.py:38:18: E203 whitespace before ','
dipy/reconst/tests/test_shore_odf.py:45:18: E203 whitespace before ','
dipy/reconst/tests/test_shore_odf.py:55:22: E203 whitespace before ','
dipy/reconst/tests/test_vec_val_vect.py:7:1: E302 expected 2 blank lines, found 1
dipy/reconst/tests/test_vec_val_vect.py:16:5: E731 do not assign a lambda expression, use a def
dipy/reconst/tests/test_vec_val_vect.py:16:27: E203 whitespace before ':'

**Comment by skoudoro** [comment]
can we close this one @arokem ?  (link #880)

**Comment by arokem** [comment]
yep
