### ISSUE TITLE
PEP8 in reconst tests/benchmarks

### ISSUE THREAD

**Issue by arokem** [nipy/dipy#882]
dipy/reconst/benchmarks/bench_bounding_box.py:11:80: E501 line too long (80 > 79 characters)
dipy/reconst/benchmarks/bench_bounding_box.py:16:80: E501 line too long (84 > 79 characters)
dipy/reconst/benchmarks/bench_bounding_box.py:22:1: E302 expected 2 blank lines, found 1
dipy/reconst/benchmarks/bench_bounding_box.py:25:8: E211 whitespace before '['
dipy/reconst/benchmarks/bench_csd.py:9:1: E302 expected 2 blank lines, found 1
dipy/reconst/benchmarks/bench_peaks.py:9:80: E501 line too long (80 > 79 characters)
dipy/reconst/benchmarks/bench_squash.py:9:80: E501 line too long (80 > 79 characters)
dipy/reconst/benchmarks/bench_squash.py:29:1: E302 expected 2 blank lines, found 1
dipy/reconst/benchmarks/bench_squash.py:112:80: E501 line too long (80 > 79 characters)
dipy/reconst/benchmarks/bench_vec_val_sum.py:9:80: E501 line too long (80 > 79 characters)
dipy/reconst/benchmarks/bench_vec_val_sum.py:24:5: E731 do not assign a lambda expression, use a def
dipy/reconst/benchmarks/bench_vec_val_sum.py:24:27: E203 whitespace before ':'
dipy/reconst/benchmarks/bench_vec_val_sum.py:26:1: E302 expected 2 blank lines, found 1
dipy/reconst/benchmarks/bench_vec_val_sum.py:32:80: E501 line too long (80 > 79 characters)
dipy/reconst/tests/test_cache.py:6:1: E302 expected 2 blank lines, found 1
dipy/reconst/tests/test_csdeconv.py:62:80: E501 line too long (80 > 79 characters)
dipy/reconst/tests/test_csdeconv.py:128:80: E501 line too long (88 > 79 characters)
dipy/reconst/tests/test_csdeconv.py:144:1: E302 expected 2 blank lines, found 1
dipy/reconst/tests/test_csdeconv.py:295:14: E231 missing whitespace after ','
dipy/reconst/tests/test_csdeconv.py:295:16: E231 missing whitespace after ','
dipy/reconst/tests/test_csdeconv.py:333:15: E261 at least two spaces before inline comment
dipy/reconst/tests/test_csdeconv.py:333:16: E262 inline comment should start with '# '
dipy/reconst/tests/test_csdeconv.py:335:48: E262 inline comment should start with '# '
dipy/reconst/tests/test_csdeconv.py:374:1: E302 expected 2 blank lines, found 1
dipy/reconst/tests/test_csdeconv.py:463:49: E128 continuation line under-indented for visual indent
dipy/reconst/tests/test_csdeconv.py:465:49: E128 continuation line under-indented for visual indent
dipy/reconst/tests/test_csdeconv.py:471:21: E231 missing whitespace after ':'
dipy/reconst/tests/test_csdeconv.py:471:35: E231 missing whitespace after ':'
dipy/reconst/tests/test_csdeconv.py:471:50: E231 missing whitespace after ':'
dipy/reconst/tests/test_csdeconv.py:472:1: E302 expected 2 blank lines, found 0
dipy/reconst/tests/test_csdeconv.py:507:80: E501 line too long (80 > 79 characters)
dipy/reconst/tests/test_dsi.py:21:5: E265 block comment should start with '# '
dipy/reconst/tests/test_dsi.py:24:5: E265 block comment should start with '# '
dipy/reconst/tests/test_dsi.py:27:35: E231 missing whitespace after ','
dipy/reconst/tests/test_dsi.py:27:48: E231 missing whitespace after ','
dipy/reconst/tests/test_dsi.py:52:15: E225 missing whitespace around operator
dipy/reconst/tests/test_dsi.py:105:15: E225 missing whitespace around operator
dipy/reconst/tests/test_dsi_deconv.py:61:80: E501 line too long (80 > 79 characters)
dipy/reconst/tests/test_gqi.py:19:5: E265 block comment should start with '# '
dipy/reconst/tests/test_gqi.py:21:5: E265 block comment should start with '# '
dipy/reconst/tests/test_gqi.py:24:21: E231 missing whitespace after ','
dipy/reconst/tests/test_gqi.py:25:21: E231 missing whitespace after ','
dipy/reconst/tests/test_gqi.py:28:32: E128 continuation line under-indented for visual indent
dipy/reconst/tests/test_gqi.py:29:32: E128 continuation line under-indented for visual indent
dipy/reconst/tests/test_gqi.py:32:5: E265 block comment should start with '# '
dipy/reconst/tests/test_gqi.py:37:80: E501 line too long (80 > 79 characters)
dipy/reconst/tests/test_gqi.py:39:5: E265 block comment should start with '# '
dipy/reconst/tests/test_gqi.py:44:80: E501 line too long (80 > 79 characters)
dipy/reconst/tests/test_gqi.py:46:15: E225 missing whitespace around operator
dipy/reconst/tests/test_interpolate.py:13:1: E302 expected 2 blank lines, found 1
dipy/reconst/tests/test_interpolate.py:18:47: E231 missing whitespace after ','
dipy/reconst/tests/test_interpolate.py:18:49: E231 missing whitespace after ','
dipy/reconst/tests/test_interpolate.py:31:1: E302 expected 2 blank lines, found 1
dipy/reconst/tests/test_interpolate.py:37:41: E231 missing whitespace after ','
dipy/reconst/tests/test_interpolate.py:37:43: E231 missing whitespace after ','
dipy/reconst/tests/test_mapmri.py:15:44: W503 line break before binary operator
dipy/reconst/tests/test_mapmri.py:15:80: E501 line too long (81 > 79 characters)
dipy/reconst/tests/test_mapmri_odf.py:16:1: E302 expected 2 blank lines, found 1
dipy/reconst/tests/test_mapmri_odf.py:27:80: E501 line too long (84 > 79 characters)
dipy/reconst/tests/test_mapmri_odf.py:32:18: E203 whitespace before ','
dipy/reconst/tests/test_mapmri_odf.py:39:18: E203 whitespace before ','
dipy/reconst/tests/test_mapmri_odf.py:49:22: E203 whitespace before ','
dipy/reconst/tests/test_multi_voxel.py:63:18: E261 at least two spaces before inline comment
dipy/reconst/tests/test_multi_voxel.py:65:18: E261 at least two spaces before inline comment
dipy/reconst/tests/test_multi_voxel.py:67:25: E261 at least two spaces before inline comment
dipy/reconst/tests/test_multi_voxel.py:84:46: E261 at least two spaces before inline comment
dipy/reconst/tests/test_multi_voxel.py:87:18: E261 at least two spaces before inline comment
dipy/reconst/tests/test_multi_voxel.py:93:1: E303 too many blank lines (3)
dipy/reconst/tests/test_multi_voxel.py:163:27: E231 missing whitespace after ','
dipy/reconst/tests/test_multi_voxel.py:163:29: E231 missing whitespace after ','
dipy/reconst/tests/test_odf.py:73:5: E303 too many blank lines (2)
dipy/reconst/tests/test_peak_finding.py:11:1: E302 expected 2 blank lines, found 1
dipy/reconst/tests/test_reco_utils.py:7:51: E127 continuation line over-indented for visual indent
dipy/reconst/tests/test_reco_utils.py:35:5: E265 block comment should start with '# '
dipy/reconst/tests/test_sfm.py:46:80: E501 line too long (80 > 79 characters)
dipy/reconst/tests/test_sfm.py:79:20: E231 missing whitespace after ','
dipy/reconst/tests/test_sfm.py:79:22: E231 missing whitespace after ','
dipy/reconst/tests/test_shm.py:31:1: E302 expected 2 blank lines, found 1
dipy/reconst/tests/test_shm.py:69:30: E128 continuation line under-indented for visual indent
dipy/reconst/tests/test_shm.py:388:80: E501 line too long (85 > 79 characters)
dipy/reconst/tests/test_shm.py:389:32: E203 whitespace before ','
dipy/reconst/tests/test_shm.py:389:80: E501 line too long (85 > 79 characters)
dipy/reconst/tests/test_shm.py:390:80: E501 line too long (85 > 79 characters)
dipy/reconst/tests/test_shm.py:391:80: E501 line too long (85 > 79 characters)
dipy/reconst/tests/test_shm.py:392:80: E501 line too long (85 > 79 characters)
dipy/reconst/tests/test_shm.py:393:45: E203 whitespace before ','
dipy/reconst/tests/test_shm.py:393:80: E501 line too long (85 > 79 characters)
dipy/reconst/tests/test_shm.py:394:32: E203 whitespace before ','
dipy/reconst/tests/test_shm.py:394:80: E501 line too long (85 > 79 characters)
dipy/reconst/tests/test_shm.py:395:58: E203 whitespace before ','
dipy/reconst/tests/test_shm.py:395:80: E501 line too long (85 > 79 characters)
dipy/reconst/tests/test_shm.py:396:80: E501 line too long (85 > 79 characters)
dipy/reconst/tests/test_shm.py:397:32: E203 whitespace before ','
dipy/reconst/tests/test_shm.py:397:80: E501 line too long (85 > 79 characters)
dipy/reconst/tests/test_shm.py:398:45: E203 whitespace before ','
dipy/reconst/tests/test_shm.py:398:80: E501 line too long (85 > 79 characters)
dipy/reconst/tests/test_shm.py:399:80: E501 line too long (85 > 79 characters)
dipy/reconst/tests/test_shm.py:402:31: E203 whitespace before ','
dipy/reconst/tests/test_shm.py:402:70: E203 whitespace before ','
dipy/reconst/tests/test_shm.py:402:80: E501 line too long (84 > 79 characters)
dipy/reconst/tests/test_shm.py:403:80: E501 line too long (83 > 79 characters)
dipy/reconst/tests/test_shm.py:404:80: E501 line too long (84 > 79 characters)
dipy/reconst/tests/test_shm.py:405:80: E501 line too long (83 > 79 characters)
dipy/reconst/tests/test_shm.py:406:30: E203 whitespace before ','
dipy/reconst/tests/test_shm.py:406:80: E501 line too long (83 > 79 characters)
dipy/reconst/tests/test_shm.py:406:82: E203 whitespace before ','
dipy/reconst/tests/test_shm.py:407:70: E203 whitespace before ','
dipy/reconst/tests/test_shm.py:407:80: E501 line too long (84 > 79 characters)
dipy/reconst/tests/test_shm.py:408:80: E501 line too long (84 > 79 characters)
dipy/reconst/tests/test_shm.py:409:80: E501 line too long (84 > 79 characters)
dipy/reconst/tests/test_shm.py:410:56: E203 whitespace before ','
dipy/reconst/tests/test_shm.py:410:80: E501 line too long (83 > 79 characters)
dipy/reconst/tests/test_shm.py:411:69: E203 whitespace before ','
dipy/reconst/tests/test_shm.py:411:80: E501 line too long (83 > 79 characters)
dipy/reconst/tests/test_shm.py:412:80: E501 line too long (83 > 79 characters)
dipy/reconst/tests/test_shm.py:413:80: E501 line too long (84 > 79 characters)
dipy/reconst/tests/test_shm.py:421:1: E302 expected 2 blank lines, found 1
dipy/reconst/tests/test_shore_fitting.py:24:17: E701 multiple statements on one line (colon)
dipy/reconst/tests/test_shore_fitting.py:27:1: E302 expected 2 blank lines, found 1
dipy/reconst/tests/test_shore_fitting.py:30:30: E127 continuation line over-indented for visual indent
dipy/reconst/tests/test_shore_fitting.py:54:25: E225 missing whitespace around operator
dipy/reconst/tests/test_shore_fitting.py:70:34: E251 unexpected spaces around keyword / parameter equals
dipy/reconst/tests/test_shore_fitting.py:70:36: E251 unexpected spaces around keyword / parameter equals
dipy/reconst/tests/test_shore_fitting.py:80:9: E128 continuation line under-indented for visual indent
dipy/reconst/tests/test_shore_fitting.py:80:80: E501 line too long (94 > 79 characters)
dipy/reconst/tests/test_shore_metrics.py:6:80: E501 line too long (83 > 79 characters)
dipy/reconst/tests/test_shore_metrics.py:39:80: E501 line too long (112 > 79 characters)
dipy/reconst/tests/test_shore_metrics.py:59:42: E225 missing whitespace around operator
dipy/reconst/tests/test_shore_metrics.py:60:58: E225 missing whitespace around operator
dipy/reconst/tests/test_shore_metrics.py:60:80: E231 missing whitespace after ','
dipy/reconst/tests/test_shore_metrics.py:60:80: E501 line too long (95 > 79 characters)
dipy/reconst/tests/test_shore_metrics.py:64:80: E501 line too long (83 > 79 characters)
dipy/reconst/tests/test_shore_metrics.py:76:54: E251 unexpected spaces around keyword / parameter equals
dipy/reconst/tests/test_shore_metrics.py:86:47: E225 missing whitespace around operator
dipy/reconst/tests/test_shore_metrics.py:86:80: E501 line too long (96 > 79 characters)
dipy/reconst/tests/test_shore_odf.py:38:5: E303 too many blank lines (2)
dipy/reconst/tests/test_shore_odf.py:38:18: E203 whitespace before ','
dipy/reconst/tests/test_shore_odf.py:45:18: E203 whitespace before ','
dipy/reconst/tests/test_shore_odf.py:55:22: E203 whitespace before ','
dipy/reconst/tests/test_vec_val_vect.py:7:1: E302 expected 2 blank lines, found 1
dipy/reconst/tests/test_vec_val_vect.py:16:5: E731 do not assign a lambda expression, use a def
dipy/reconst/tests/test_vec_val_vect.py:16:27: E203 whitespace before ':'

**Comment by manu-tej** [comment]
@arokem issue closed via #956
