### ISSUE TITLE
PEP8 in segment

### ISSUE THREAD

**Issue by arokem** [nipy/dipy#883]
dipy/segment/clustering.py:76:80: E501 line too long (80 > 79 characters)
dipy/segment/clustering.py:219:80: E501 line too long (81 > 79 characters)
dipy/segment/clustering.py:267:80: E501 line too long (101 > 79 characters)
dipy/segment/clustering.py:272:80: E501 line too long (118 > 79 characters)
dipy/segment/clustering.py:404:80: E501 line too long (93 > 79 characters)
dipy/segment/clustering.py:425:80: E501 line too long (80 > 79 characters)
dipy/segment/clustering.py:436:80: E501 line too long (88 > 79 characters)
dipy/segment/clustering.py:463:80: E501 line too long (93 > 79 characters)
dipy/segment/mask.py:237:80: E501 line too long (84 > 79 characters)
dipy/segment/mask.py:261:80: E501 line too long (82 > 79 characters)
dipy/segment/mask.py:269:1: E302 expected 2 blank lines, found 1
dipy/segment/mask.py:271:80: E501 line too long (82 > 79 characters)
dipy/segment/mask.py:291:80: E501 line too long (85 > 79 characters)
dipy/segment/quickbundles.py:8:1: W191 indentation contains tabs
dipy/segment/quickbundles.py:8:4: E128 continuation line under-indented for visual indent
dipy/segment/quickbundles.py:12:1: E101 indentation contains mixed spaces and tabs
dipy/segment/quickbundles.py:12:1: W293 blank line contains whitespace
dipy/segment/quickbundles.py:13:22: E231 missing whitespace after ','
dipy/segment/quickbundles.py:13:29: E231 missing whitespace after ','
dipy/segment/quickbundles.py:13:41: E231 missing whitespace after ','
dipy/segment/quickbundles.py:14:43: W291 trailing whitespace
dipy/segment/quickbundles.py:15:1: W293 blank line contains whitespace
dipy/segment/quickbundles.py:20:1: W293 blank line contains whitespace
dipy/segment/quickbundles.py:21:26: W291 trailing whitespace
dipy/segment/quickbundles.py:23:19: W291 trailing whitespace
dipy/segment/quickbundles.py:24:60: W291 trailing whitespace
dipy/segment/quickbundles.py:25:1: W293 blank line contains whitespace
dipy/segment/quickbundles.py:30:72: W291 trailing whitespace
dipy/segment/quickbundles.py:31:1: W293 blank line contains whitespace
dipy/segment/quickbundles.py:34:1: W293 blank line contains whitespace
dipy/segment/quickbundles.py:35:80: E501 line too long (82 > 79 characters)
dipy/segment/quickbundles.py:35:83: W291 trailing whitespace
dipy/segment/quickbundles.py:36:1: W293 blank line contains whitespace
dipy/segment/quickbundles.py:38:80: E501 line too long (80 > 79 characters)
dipy/segment/quickbundles.py:45:15: E225 missing whitespace around operator
dipy/segment/quickbundles.py:45:15: E711 comparison to None should be 'if cond is not None:'
dipy/segment/quickbundles.py:45:22: W291 trailing whitespace
dipy/segment/quickbundles.py:46:25: E225 missing whitespace around operator
dipy/segment/quickbundles.py:46:43: E231 missing whitespace after ','
dipy/segment/quickbundles.py:48:25: E225 missing whitespace around operator
dipy/segment/quickbundles.py:48:32: W291 trailing whitespace
dipy/segment/quickbundles.py:49:24: E225 missing whitespace around operator
dipy/segment/quickbundles.py:50:19: E225 missing whitespace around operator
dipy/segment/quickbundles.py:51:20: E225 missing whitespace around operator
dipy/segment/quickbundles.py:51:25: W291 trailing whitespace
dipy/segment/quickbundles.py:52:1: W293 blank line contains whitespace
dipy/segment/quickbundles.py:54:22: E225 missing whitespace around operator
dipy/segment/quickbundles.py:54:22: E711 comparison to None should be 'if cond is None:'
dipy/segment/quickbundles.py:55:23: E225 missing whitespace around operator
dipy/segment/quickbundles.py:55:80: E501 line too long (112 > 79 characters)
dipy/segment/quickbundles.py:56:26: W291 trailing whitespace
dipy/segment/quickbundles.py:61:1: W293 blank line contains whitespace
dipy/segment/quickbundles.py:62:23: E231 missing whitespace after ','
dipy/segment/quickbundles.py:63:23: E225 missing whitespace around operator
dipy/segment/quickbundles.py:63:23: E711 comparison to None should be 'if cond is None:'
dipy/segment/quickbundles.py:63:30: W291 trailing whitespace
dipy/segment/quickbundles.py:64:24: E225 missing whitespace around operator
dipy/segment/quickbundles.py:65:25: E225 missing whitespace around operator
dipy/segment/quickbundles.py:66:14: E225 missing whitespace around operator
dipy/segment/quickbundles.py:67:22: E225 missing whitespace around operator
dipy/segment/quickbundles.py:67:22: E711 comparison to None should be 'if cond is None:'
dipy/segment/quickbundles.py:68:23: E225 missing whitespace around operator
dipy/segment/quickbundles.py:68:36: W291 trailing whitespace
dipy/segment/quickbundles.py:70:24: E225 missing whitespace around operator
dipy/segment/quickbundles.py:70:61: W291 trailing whitespace
dipy/segment/quickbundles.py:71:18: E225 missing whitespace around operator
dipy/segment/quickbundles.py:71:74: E231 missing whitespace after ','
dipy/segment/quickbundles.py:71:80: E501 line too long (82 > 79 characters)
dipy/segment/quickbundles.py:72:18: E225 missing whitespace around operator
dipy/segment/quickbundles.py:73:19: E225 missing whitespace around operator
dipy/segment/quickbundles.py:75:48: W291 trailing whitespace
dipy/segment/quickbundles.py:77:1: W293 blank line contains whitespace
dipy/segment/quickbundles.py:80:1: W293 blank line contains whitespace
dipy/segment/quickbundles.py:85:10: E225 missing whitespace around operator
dipy/segment/quickbundles.py:86:38: W291 trailing whitespace
dipy/segment/quickbundles.py:87:1: W293 blank line contains whitespace
dipy/segment/quickbundles.py:88:27: E231 missing whitespace after ','
dipy/segment/quickbundles.py:90:1: W293 blank line contains whitespace
dipy/segment/quickbundles.py:91:29: E231 missing whitespace after ','
dipy/segment/quickbundles.py:92:59: W291 trailing whitespace
dipy/segment/quickbundles.py:93:1: W293 blank line contains whitespace
dipy/segment/quickbundles.py:94:26: E231 missing whitespace after ','
dipy/segment/quickbundles.py:94:33: E231 missing whitespace after ','
dipy/segment/quickbundles.py:96:5: E301 expected 1 blank line, found 0
dipy/segment/quickbundles.py:96:14: W291 trailing whitespace
dipy/segment/quickbundles.py:99:1: W293 blank line contains whitespace
dipy/segment/quickbundles.py:103:35: E231 missing whitespace after ','
dipy/segment/quickbundles.py:111:10: E225 missing whitespace around operator
dipy/segment/quickbundles.py:113:25: E225 missing whitespace around operator
dipy/segment/quickbundles.py:114:25: W291 trailing whitespace
dipy/segment/quickbundles.py:115:11: E225 missing whitespace around operator
dipy/segment/quickbundles.py:116:13: E225 missing whitespace around operator
dipy/segment/quickbundles.py:118:18: E225 missing whitespace around operator
dipy/segment/quickbundles.py:119:24: E225 missing whitespace around operator
dipy/segment/quickbundles.py:120:9: E265 block comment should start with '# '
dipy/segment/quickbundles.py:121:19: E225 missing whitespace around operator
dipy/segment/quickbundles.py:122:1: W293 blank line contains whitespace
dipy/segment/quickbundles.py:123:28: E231 missing whitespace after ','
dipy/segment/quickbundles.py:126:1: W293 blank line contains whitespace
dipy/segment/quickbundles.py:127:29: E231 missing whitespace after ','
dipy/segment/quickbundles.py:130:1: W293 blank line contains whitespace
dipy/segment/quickbundles.py:134:1: W293 blank line contains whitespace
dipy/segment/quickbundles.py:138:1: W391 blank line at end of file
dipy/segment/threshold.py:3:1: E302 expected 2 blank lines, found 1
dipy/segment/benchmarks/bench_quickbundles.py:9:80: E501 line too long (80 > 79 characters)
dipy/segment/benchmarks/bench_quickbundles.py:14:80: E501 line too long (84 > 79 characters)
dipy/segment/benchmarks/bench_quickbundles.py:50:5: E265 block comment should start with '# '
dipy/segment/benchmarks/bench_quickbundles.py:72:80: E501 line too long (80 > 79 characters)
dipy/segment/tests/test_clustering.py:37:80: E501 line too long (80 > 79 characters)
dipy/segment/tests/test_clustering.py:38:80: E501 line too long (82 > 79 characters)
dipy/segment/tests/test_clustering.py:90:80: E501 line too long (89 > 79 characters)
dipy/segment/tests/test_clustering.py:114:80: E501 line too long (95 > 79 characters)
dipy/segment/tests/test_clustering.py:139:80: E501 line too long (82 > 79 characters)
dipy/segment/tests/test_clustering.py:144:80: E501 line too long (82 > 79 characters)
dipy/segment/tests/test_clustering.py:218:80: E501 line too long (89 > 79 characters)
dipy/segment/tests/test_clustering.py:239:80: E501 line too long (95 > 79 characters)
dipy/segment/tests/test_clustering.py:281:80: E501 line too long (97 > 79 characters)
dipy/segment/tests/test_clustering.py:286:80: E501 line too long (97 > 79 characters)
dipy/segment/tests/test_clustering.py:305:80: E501 line too long (102 > 79 characters)
dipy/segment/tests/test_clustering.py:359:80: E501 line too long (82 > 79 characters)
dipy/segment/tests/test_clustering.py:366:80: E501 line too long (97 > 79 characters)
dipy/segment/tests/test_clustering.py:391:80: E501 line too long (94 > 79 characters)
dipy/segment/tests/test_clustering.py:453:80: E501 line too long (89 > 79 characters)
dipy/segment/tests/test_clustering.py:458:80: E501 line too long (87 > 79 characters)
dipy/segment/tests/test_clustering.py:459:80: E501 line too long (84 > 79 characters)
dipy/segment/tests/test_clustering.py:460:80: E501 line too long (89 > 79 characters)
dipy/segment/tests/test_clustering.py:461:80: E501 line too long (86 > 79 characters)
dipy/segment/tests/test_clustering.py:514:5: E265 block comment should start with '# '
dipy/segment/tests/test_clustering.py:518:9: E265 block comment should start with '# '
dipy/segment/tests/test_clustering.py:549:80: E501 line too long (88 > 79 characters)
dipy/segment/tests/test_clustering.py:559:80: E501 line too long (101 > 79 characters)
dipy/segment/tests/test_clustering.py:590:80: E501 line too long (102 > 79 characters)
dipy/segment/tests/test_clustering.py:615:80: E501 line too long (95 > 79 characters)
dipy/segment/tests/test_clustering.py:619:80: E501 line too long (82 > 79 characters)
dipy/segment/tests/test_clustering.py:626:80: E501 line too long (97 > 79 characters)
dipy/segment/tests/test_clustering.py:648:80: E501 line too long (94 > 79 characters)
dipy/segment/tests/test_clustering.py:725:80: E501 line too long (91 > 79 characters)
dipy/segment/tests/test_feature.py:58:80: E501 line too long (113 > 79 characters)
dipy/segment/tests/test_feature.py:71:80: E501 line too long (91 > 79 characters)
dipy/segment/tests/test_feature.py:79:80: E501 line too long (87 > 79 characters)
dipy/segment/tests/test_feature.py:86:80: E501 line too long (91 > 79 characters)
dipy/segment/tests/test_feature.py:219:80: E501 line too long (90 > 79 characters)
dipy/segment/tests/test_feature.py:231:80: E501 line too long (127 > 79 characters)
dipy/segment/tests/test_feature.py:243:80: E501 line too long (83 > 79 characters)
dipy/segment/tests/test_feature.py:249:80: E501 line too long (127 > 79 characters)
dipy/segment/tests/test_feature.py:299:80: E501 line too long (83 > 79 characters)
dipy/segment/tests/test_mask.py:105:39: E127 continuation line over-indented for visual indent
dipy/segment/tests/test_mask.py:106:39: E127 continuation line over-indented for visual indent
dipy/segment/tests/test_mask.py:110:39: E127 continuation line over-indented for visual indent
dipy/segment/tests/test_mask.py:111:39: E127 continuation line over-indented for visual indent
dipy/segment/tests/test_mask.py:117:1: W391 blank line at end of file
dipy/segment/tests/test_metric.py:5:80: E501 line too long (83 > 79 characters)
dipy/segment/tests/test_metric.py:11:80: E501 line too long (83 > 79 characters)
dipy/segment/tests/test_metric.py:39:80: E501 line too long (81 > 79 characters)
dipy/segment/tests/test_metric.py:49:13: E731 do not assign a lambda expression, use a def
dipy/segment/tests/test_metric.py:81:80: E501 line too long (81 > 79 characters)
dipy/segment/tests/test_metric.py:82:80: E501 line too long (87 > 79 characters)
dipy/segment/tests/test_metric.py:86:80: E501 line too long (80 > 79 characters)
dipy/segment/tests/test_metric.py:87:80: E501 line too long (80 > 79 characters)
dipy/segment/tests/test_metric.py:93:80: E501 line too long (83 > 79 characters)
dipy/segment/tests/test_metric.py:107:80: E501 line too long (80 > 79 characters)
dipy/segment/tests/test_metric.py:162:80: E501 line too long (80 > 79 characters)
dipy/segment/tests/test_metric.py:163:80: E501 line too long (80 > 79 characters)
dipy/segment/tests/test_metric.py:185:80: E501 line too long (80 > 79 characters)
dipy/segment/tests/test_metric.py:229:80: E501 line too long (80 > 79 characters)
dipy/segment/tests/test_metric.py:239:80: E501 line too long (81 > 79 characters)
dipy/segment/tests/test_qb.py:3:80: E501 line too long (98 > 79 characters)
dipy/segment/tests/test_qb.py:10:12: E231 missing whitespace after ','
dipy/segment/tests/test_qb.py:10:56: W291 trailing whitespace
dipy/segment/tests/test_qb.py:11:6: E225 missing whitespace around operator
dipy/segment/tests/test_qb.py:12:8: E225 missing whitespace around operator
dipy/segment/tests/test_qb.py:12:37: W291 trailing whitespace
dipy/segment/tests/test_qb.py:13:7: E225 missing whitespace around operator
dipy/segment/tests/test_qb.py:13:22: E231 missing whitespace after ','
dipy/segment/tests/test_qb.py:13:26: E231 missing whitespace after ','
dipy/segment/tests/test_qb.py:14:8: E225 missing whitespace around operator
dipy/segment/tests/test_qb.py:14:22: W291 trailing whitespace
dipy/segment/tests/test_qb.py:15:5: E265 block comment should start with '# '
dipy/segment/tests/test_qb.py:16:9: E231 missing whitespace after ','
dipy/segment/tests/test_qb.py:16:15: E225 missing whitespace around operator
dipy/segment/tests/test_qb.py:16:30: W291 trailing whitespace
dipy/segment/tests/test_qb.py:17:19: E231 missing whitespace after ','
dipy/segment/tests/test_quickbundles.py:40:80: E501 line too long (80 > 79 characters)
dipy/segment/tests/test_quickbundles.py:44:80: E501 line too long (81 > 79 characters)
dipy/segment/tests/test_quickbundles.py:50:80: E501 line too long (80 > 79 characters)
dipy/segment/tests/test_quickbundles.py:51:80: E501 line too long (80 > 79 characters)
dipy/segment/tests/test_quickbundles.py:61:80: E501 line too long (92 > 79 characters)
dipy/segment/tests/test_quickbundles.py:75:80: E501 line too long (81 > 79 characters)
dipy/segment/tests/test_quickbundles.py:100:80: E501 line too long (80 > 79 characters)
dipy/segment/tests/test_quickbundles.py:104:80: E501 line too long (87 > 79 characters)
dipy/segment/tests/test_quickbundles.py:106:80: E501 line too long (84 > 79 characters)
dipy/segment/tests/test_quickbundles.py:118:80: E501 line too long (98 > 79 characters)
dipy/segment/tests/test_quickbundles.py:130:80: E501 line too long (96 > 79 characters)

**Comment by souravsingh** [comment]
Ì would like to work on the issue
