### ISSUE TITLE
PEP8 in sims

### ISSUE THREAD

**Issue by arokem** [nipy/dipy#884]
dipy/sims/__init__.py:1:1: E265 block comment should start with '# '
dipy/sims/phantom.py:65:25: E231 missing whitespace after ','
dipy/sims/phantom.py:65:28: E231 missing whitespace after ','
dipy/sims/phantom.py:200:5: E266 too many leading '#' for block comment
dipy/sims/phantom.py:203:10: E225 missing whitespace around operator
dipy/sims/phantom.py:204:10: E225 missing whitespace around operator
dipy/sims/phantom.py:205:9: E265 block comment should start with '# '
dipy/sims/phantom.py:206:10: E225 missing whitespace around operator
dipy/sims/phantom.py:206:25: E231 missing whitespace after ','
dipy/sims/phantom.py:206:27: E231 missing whitespace after ','
dipy/sims/phantom.py:207:17: E231 missing whitespace after ','
dipy/sims/phantom.py:207:19: E231 missing whitespace after ','
dipy/sims/phantom.py:209:5: E265 block comment should start with '# '
dipy/sims/phantom.py:210:8: E225 missing whitespace around operator
dipy/sims/phantom.py:213:10: E225 missing whitespace around operator
dipy/sims/phantom.py:213:25: E231 missing whitespace after ','
dipy/sims/phantom.py:213:27: E231 missing whitespace after ','
dipy/sims/phantom.py:214:10: E225 missing whitespace around operator
dipy/sims/phantom.py:214:25: E231 missing whitespace after ','
dipy/sims/phantom.py:214:27: E231 missing whitespace after ','
dipy/sims/phantom.py:215:10: E225 missing whitespace around operator
dipy/sims/phantom.py:216:17: E231 missing whitespace after ','
dipy/sims/phantom.py:216:19: E231 missing whitespace after ','
dipy/sims/phantom.py:218:5: E265 block comment should start with '# '
dipy/sims/phantom.py:219:9: E225 missing whitespace around operator
dipy/sims/phantom.py:222:10: E225 missing whitespace around operator
dipy/sims/phantom.py:222:25: E231 missing whitespace after ','
dipy/sims/phantom.py:222:27: E231 missing whitespace after ','
dipy/sims/phantom.py:223:10: E225 missing whitespace around operator
dipy/sims/phantom.py:223:26: E231 missing whitespace after ','
dipy/sims/phantom.py:223:28: E231 missing whitespace after ','
dipy/sims/phantom.py:224:10: E225 missing whitespace around operator
dipy/sims/phantom.py:225:17: E231 missing whitespace after ','
dipy/sims/phantom.py:225:19: E231 missing whitespace after ','
dipy/sims/phantom.py:227:5: E265 block comment should start with '# '
dipy/sims/phantom.py:228:9: E225 missing whitespace around operator
dipy/sims/phantom.py:229:5: E265 block comment should start with '# '
dipy/sims/phantom.py:230:10: E225 missing whitespace around operator
dipy/sims/phantom.py:232:5: E265 block comment should start with '# '
dipy/sims/phantom.py:234:10: E225 missing whitespace around operator
dipy/sims/phantom.py:235:10: E225 missing whitespace around operator
dipy/sims/phantom.py:236:10: E225 missing whitespace around operator
dipy/sims/phantom.py:236:25: E231 missing whitespace after ','
dipy/sims/phantom.py:236:27: E231 missing whitespace after ','
dipy/sims/phantom.py:237:17: E231 missing whitespace after ','
dipy/sims/phantom.py:237:19: E231 missing whitespace after ','
dipy/sims/phantom.py:239:5: E265 block comment should start with '# '
dipy/sims/phantom.py:240:9: E225 missing whitespace around operator
dipy/sims/phantom.py:241:11: E225 missing whitespace around operator
dipy/sims/phantom.py:243:9: E225 missing whitespace around operator
dipy/sims/phantom.py:245:5: E265 block comment should start with '# '
dipy/sims/phantom.py:247:5: E265 block comment should start with '# '
dipy/sims/phantom.py:248:5: E265 block comment should start with '# '
dipy/sims/phantom.py:249:5: E265 block comment should start with '# '
dipy/sims/phantom.py:250:5: E265 block comment should start with '# '
dipy/sims/voxel.py:537:1: E303 too many blank lines (3)
dipy/sims/tests/__init__.py:4:11: W292 no newline at end of file
dipy/sims/tests/test_phantom.py:20:5: E231 missing whitespace after ','
dipy/sims/tests/test_phantom.py:20:12: E231 missing whitespace after ','
dipy/sims/tests/test_phantom.py:20:19: E225 missing whitespace around operator
dipy/sims/tests/test_phantom.py:21:6: E225 missing whitespace around operator
dipy/sims/tests/test_phantom.py:22:6: E225 missing whitespace around operator
dipy/sims/tests/test_phantom.py:23:23: E225 missing whitespace around operator
dipy/sims/tests/test_phantom.py:32:23: E231 missing whitespace after ','
dipy/sims/tests/test_phantom.py:32:25: E231 missing whitespace after ','
dipy/sims/tests/test_phantom.py:32:33: W291 trailing whitespace
dipy/sims/tests/test_phantom.py:33:23: E231 missing whitespace after ','
dipy/sims/tests/test_phantom.py:33:25: E231 missing whitespace after ','
dipy/sims/tests/test_phantom.py:34:23: E231 missing whitespace after ','
dipy/sims/tests/test_phantom.py:34:25: E231 missing whitespace after ','
dipy/sims/tests/test_phantom.py:35:13: E231 missing whitespace after ','
dipy/sims/tests/test_phantom.py:35:15: E231 missing whitespace after ','
dipy/sims/tests/test_phantom.py:58:18: E222 multiple spaces after operator
dipy/sims/tests/test_phantom.py:58:80: E501 line too long (115 > 79 characters)
dipy/sims/tests/test_phantom.py:58:82: E202 whitespace before ')'
dipy/sims/tests/test_phantom.py:89:1: E303 too many blank lines (3)

**Comment by souravsingh** [comment]
I would like to work on the issue
