### ISSUE TITLE
PEP8 in testing

### ISSUE THREAD

**Issue by arokem** [nipy/dipy#885]
dipy/testing/__init__.py:8:1: E402 module level import not at top of file
dipy/testing/__init__.py:9:1: E402 module level import not at top of file
dipy/testing/__init__.py:10:1: E402 module level import not at top of file
dipy/testing/spherepoints.py:5:1: E302 expected 2 blank lines, found 1
dipy/testing/spherepoints.py:7:25: E231 missing whitespace after ','
dipy/testing/spherepoints.py:9:20: E231 missing whitespace after ','
dipy/testing/spherepoints.py:9:22: E231 missing whitespace after ','
dipy/testing/spherepoints.py:10:20: E231 missing whitespace after ','
dipy/testing/spherepoints.py:10:22: E231 missing whitespace after ','
dipy/testing/spherepoints.py:17:29: E231 missing whitespace after ','
dipy/testing/spherepoints.py:17:31: E231 missing whitespace after ','
dipy/testing/spherepoints.py:22:1: W391 blank line at end of file
dipy/testing/tests/test_decorators.py:34:9: E128 continuation line under-indented for visual indent
dipy/testing/tests/test_decorators.py:47:9: E128 continuation line under-indented for visual indent

**Comment by ghoshbishakh** [comment]
@arokem closed through #958
