### ISSUE TITLE
PEP8 in tracking

### ISSUE THREAD

**Issue by arokem** [nipy/dipy#887]
dipy/tracking/_utils.py:68:1: W391 blank line at end of file
dipy/tracking/eudx.py:7:1: E302 expected 2 blank lines, found 1
dipy/tracking/eudx.py:65:80: E501 line too long (80 > 79 characters)
dipy/tracking/eudx.py:68:80: E501 line too long (80 > 79 characters)
dipy/tracking/eudx.py:79:80: E501 line too long (80 > 79 characters)
dipy/tracking/eudx.py:83:80: E501 line too long (80 > 79 characters)
dipy/tracking/eudx.py:123:80: E501 line too long (91 > 79 characters)
dipy/tracking/gui_tools.py:20:35: E201 whitespace after '('
dipy/tracking/gui_tools.py:20:48: E202 whitespace before ')'
dipy/tracking/gui_tools.py:21:35: E201 whitespace after '('
dipy/tracking/gui_tools.py:21:48: E202 whitespace before ')'
dipy/tracking/gui_tools.py:22:35: E201 whitespace after '('
dipy/tracking/gui_tools.py:22:48: E202 whitespace before ')'
dipy/tracking/gui_tools.py:23:35: E201 whitespace after '('
dipy/tracking/gui_tools.py:23:46: E202 whitespace before ')'
dipy/tracking/gui_tools.py:24:35: E201 whitespace after '('
dipy/tracking/gui_tools.py:24:72: E202 whitespace before ')'
dipy/tracking/gui_tools.py:27:35: E201 whitespace after '('
dipy/tracking/gui_tools.py:27:59: E202 whitespace before ')'
dipy/tracking/gui_tools.py:28:35: E201 whitespace after '('
dipy/tracking/gui_tools.py:28:54: E202 whitespace before ')'
dipy/tracking/gui_tools.py:31:35: E201 whitespace after '('
dipy/tracking/gui_tools.py:31:50: E202 whitespace before ')'
dipy/tracking/gui_tools.py:32:35: E201 whitespace after '('
dipy/tracking/gui_tools.py:32:48: E202 whitespace before ')'
dipy/tracking/gui_tools.py:33:35: E201 whitespace after '('
dipy/tracking/gui_tools.py:33:46: E202 whitespace before ')'
dipy/tracking/gui_tools.py:34:35: E201 whitespace after '('
dipy/tracking/gui_tools.py:34:44: E202 whitespace before ')'
dipy/tracking/gui_tools.py:35:35: E201 whitespace after '('
dipy/tracking/gui_tools.py:35:53: E202 whitespace before ')'
dipy/tracking/gui_tools.py:36:35: E201 whitespace after '('
dipy/tracking/gui_tools.py:36:54: E202 whitespace before ')'
dipy/tracking/gui_tools.py:37:35: E201 whitespace after '('
dipy/tracking/gui_tools.py:37:55: E202 whitespace before ')'
dipy/tracking/gui_tools.py:40:35: E201 whitespace after '('
dipy/tracking/gui_tools.py:40:51: E202 whitespace before ')'
dipy/tracking/gui_tools.py:43:30: E265 block comment should start with '# '
dipy/tracking/gui_tools.py:44:35: E201 whitespace after '('
dipy/tracking/gui_tools.py:45:35: E201 whitespace after '('
dipy/tracking/gui_tools.py:45:58: E202 whitespace before ')'
dipy/tracking/gui_tools.py:46:35: E201 whitespace after '('
dipy/tracking/gui_tools.py:49:35: E201 whitespace after '('
dipy/tracking/gui_tools.py:49:50: E202 whitespace before ')'
dipy/tracking/gui_tools.py:50:35: E201 whitespace after '('
dipy/tracking/gui_tools.py:50:52: E202 whitespace before ')'
dipy/tracking/gui_tools.py:53:35: E201 whitespace after '('
dipy/tracking/gui_tools.py:53:52: E202 whitespace before ')'
dipy/tracking/gui_tools.py:54:35: E201 whitespace after '('
dipy/tracking/gui_tools.py:54:45: E202 whitespace before ')'
dipy/tracking/gui_tools.py:57:35: E201 whitespace after '('
dipy/tracking/gui_tools.py:57:57: E202 whitespace before ')'
dipy/tracking/gui_tools.py:58:35: E201 whitespace after '('
dipy/tracking/gui_tools.py:58:52: E202 whitespace before ')'
dipy/tracking/gui_tools.py:60:35: E251 unexpected spaces around keyword / parameter equals
dipy/tracking/gui_tools.py:60:37: E251 unexpected spaces around keyword / parameter equals
dipy/tracking/gui_tools.py:61:17: E128 continuation line under-indented for visual indent
dipy/tracking/gui_tools.py:62:17: E128 continuation line under-indented for visual indent
dipy/tracking/gui_tools.py:64:1: E302 expected 2 blank lines, found 1
dipy/tracking/gui_tools.py:78:1: W391 blank line at end of file
dipy/tracking/interfaces.py:13:1: E402 module level import not at top of file
dipy/tracking/interfaces.py:14:1: E402 module level import not at top of file
dipy/tracking/interfaces.py:15:1: E402 module level import not at top of file
dipy/tracking/interfaces.py:17:1: E402 module level import not at top of file
dipy/tracking/interfaces.py:18:1: E402 module level import not at top of file
dipy/tracking/interfaces.py:27:1: E402 module level import not at top of file
dipy/tracking/interfaces.py:28:1: E402 module level import not at top of file
dipy/tracking/interfaces.py:30:1: E402 module level import not at top of file
dipy/tracking/interfaces.py:31:27: E128 continuation line under-indented for visual indent
dipy/tracking/interfaces.py:32:27: E128 continuation line under-indented for visual indent
dipy/tracking/interfaces.py:33:27: E128 continuation line under-indented for visual indent
dipy/tracking/interfaces.py:34:1: E402 module level import not at top of file
dipy/tracking/interfaces.py:35:35: E128 continuation line under-indented for visual indent
dipy/tracking/interfaces.py:36:1: E402 module level import not at top of file
dipy/tracking/interfaces.py:37:36: E128 continuation line under-indented for visual indent
dipy/tracking/interfaces.py:38:1: E402 module level import not at top of file
dipy/tracking/interfaces.py:39:30: E128 continuation line under-indented for visual indent
dipy/tracking/interfaces.py:40:1: E402 module level import not at top of file
dipy/tracking/interfaces.py:41:26: E128 continuation line under-indented for visual indent
dipy/tracking/interfaces.py:47:1: E302 expected 2 blank lines, found 1
dipy/tracking/interfaces.py:51:74: E225 missing whitespace around operator
dipy/tracking/interfaces.py:91:1: E302 expected 2 blank lines, found 1
dipy/tracking/interfaces.py:93:48: E231 missing whitespace after ','
dipy/tracking/interfaces.py:93:50: E231 missing whitespace after ','
dipy/tracking/interfaces.py:95:5: E301 expected 1 blank line, found 0
dipy/tracking/interfaces.py:97:9: E265 block comment should start with '# '
dipy/tracking/interfaces.py:99:1: E302 expected 2 blank lines, found 1
dipy/tracking/interfaces.py:100:48: E231 missing whitespace after ','
dipy/tracking/interfaces.py:100:50: E231 missing whitespace after ','
dipy/tracking/interfaces.py:108:1: E302 expected 2 blank lines, found 1
dipy/tracking/interfaces.py:126:1: E302 expected 2 blank lines, found 1
dipy/tracking/interfaces.py:137:20: E231 missing whitespace after ':'
dipy/tracking/interfaces.py:137:25: E231 missing whitespace after ','
dipy/tracking/interfaces.py:137:31: E231 missing whitespace after ':'
dipy/tracking/interfaces.py:137:41: E231 missing whitespace after ','
dipy/tracking/interfaces.py:137:51: E231 missing whitespace after ':'
dipy/tracking/interfaces.py:138:39: E231 missing whitespace after ':'
dipy/tracking/interfaces.py:139:33: E231 missing whitespace after ':'
dipy/tracking/interfaces.py:140:27: E231 missing whitespace after ':'
dipy/tracking/interfaces.py:140:56: E231 missing whitespace after ':'
dipy/tracking/interfaces.py:141:30: E231 missing whitespace after ':'
dipy/tracking/interfaces.py:142:29: E231 missing whitespace after ':'
dipy/tracking/interfaces.py:142:60: E231 missing whitespace after ':'
dipy/tracking/interfaces.py:142:80: E501 line too long (80 > 79 characters)
dipy/tracking/interfaces.py:144:1: E302 expected 2 blank lines, found 1
dipy/tracking/interfaces.py:150:61: E231 missing whitespace after ','
dipy/tracking/interfaces.py:150:63: E231 missing whitespace after ','
dipy/tracking/interfaces.py:154:5: E301 expected 1 blank line, found 0
dipy/tracking/interfaces.py:167:34: E231 missing whitespace after ','
dipy/tracking/interfaces.py:167:36: E231 missing whitespace after ','
dipy/tracking/interfaces.py:168:35: E231 missing whitespace after ','
dipy/tracking/interfaces.py:168:37: E231 missing whitespace after ','
dipy/tracking/interfaces.py:174:5: E265 block comment should start with '# '
dipy/tracking/interfaces.py:177:66: E231 missing whitespace after ','
dipy/tracking/interfaces.py:177:68: E231 missing whitespace after ','
dipy/tracking/interfaces.py:186:32: E231 missing whitespace after ','
dipy/tracking/interfaces.py:186:35: E231 missing whitespace after ','
dipy/tracking/interfaces.py:191:5: E265 block comment should start with '# '
dipy/tracking/interfaces.py:193:45: E231 missing whitespace after ','
dipy/tracking/interfaces.py:194:23: E231 missing whitespace after ','
dipy/tracking/interfaces.py:194:25: E231 missing whitespace after ','
dipy/tracking/interfaces.py:196:5: E265 block comment should start with '# '
dipy/tracking/interfaces.py:200:5: E265 block comment should start with '# '
dipy/tracking/interfaces.py:208:26: E231 missing whitespace after ','
dipy/tracking/interfaces.py:208:31: E231 missing whitespace after ','
dipy/tracking/interfaces.py:218:5: E265 block comment should start with '# '
dipy/tracking/interfaces.py:260:80: E501 line too long (91 > 79 characters)
dipy/tracking/interfaces.py:262:80: E501 line too long (80 > 79 characters)
dipy/tracking/interfaces.py:269:9: E265 block comment should start with '# '
dipy/tracking/interfaces.py:288:9: E265 block comment should start with '# '
dipy/tracking/interfaces.py:299:50: E127 continuation line over-indented for visual indent
dipy/tracking/interfaces.py:306:1: W391 blank line at end of file
dipy/tracking/learning.py:5:1: E302 expected 2 blank lines, found 1
dipy/tracking/learning.py:5:40: E231 missing whitespace after ','
dipy/tracking/learning.py:5:48: E231 missing whitespace after ','
dipy/tracking/learning.py:8:1: W293 blank line contains whitespace
dipy/tracking/learning.py:13:23: W291 trailing whitespace
dipy/tracking/learning.py:15:23: W291 trailing whitespace
dipy/tracking/learning.py:17:1: W293 blank line contains whitespace
dipy/tracking/learning.py:20:61: W291 trailing whitespace
dipy/tracking/learning.py:21:57: W291 trailing whitespace
dipy/tracking/learning.py:24:1: W293 blank line contains whitespace
dipy/tracking/learning.py:31:49: W291 trailing whitespace
dipy/tracking/learning.py:33:22: W291 trailing whitespace
dipy/tracking/learning.py:36:1: W293 blank line contains whitespace
dipy/tracking/learning.py:39:80: E501 line too long (98 > 79 characters)
dipy/tracking/learning.py:39:99: W291 trailing whitespace
dipy/tracking/learning.py:40:80: E501 line too long (96 > 79 characters)
dipy/tracking/learning.py:42:1: W293 blank line contains whitespace
dipy/tracking/learning.py:43:1: W293 blank line contains whitespace
dipy/tracking/learning.py:45:7: E225 missing whitespace around operator
dipy/tracking/learning.py:46:1: W293 blank line contains whitespace
dipy/tracking/learning.py:47:16: E225 missing whitespace around operator
dipy/tracking/learning.py:47:29: E231 missing whitespace after ','
dipy/tracking/learning.py:48:8: E225 missing whitespace around operator
dipy/tracking/learning.py:49:22: W291 trailing whitespace
dipy/tracking/learning.py:50:11: E225 missing whitespace around operator
dipy/tracking/learning.py:50:40: E231 missing whitespace after ','
dipy/tracking/learning.py:50:42: E231 missing whitespace after ','
dipy/tracking/learning.py:51:11: E225 missing whitespace around operator
dipy/tracking/learning.py:51:24: W291 trailing whitespace
dipy/tracking/learning.py:52:25: E225 missing whitespace around operator
dipy/tracking/learning.py:52:37: E231 missing whitespace after ','
dipy/tracking/learning.py:52:51: W291 trailing whitespace
dipy/tracking/learning.py:53:12: E225 missing whitespace around operator
dipy/tracking/learning.py:54:1: W293 blank line contains whitespace
dipy/tracking/learning.py:57:1: E302 expected 2 blank lines, found 1
dipy/tracking/learning.py:57:45: E231 missing whitespace after ','
dipy/tracking/learning.py:57:53: E231 missing whitespace after ','
dipy/tracking/learning.py:57:62: E231 missing whitespace after ','
dipy/tracking/learning.py:58:80: E501 line too long (91 > 79 characters)
dipy/tracking/learning.py:59:1: W293 blank line contains whitespace
dipy/tracking/learning.py:63:69: W291 trailing whitespace
dipy/tracking/learning.py:64:23: W291 trailing whitespace
dipy/tracking/learning.py:65:56: W291 trailing whitespace
dipy/tracking/learning.py:67:55: W291 trailing whitespace
dipy/tracking/learning.py:68:23: W291 trailing whitespace
dipy/tracking/learning.py:70:1: W293 blank line contains whitespace
dipy/tracking/learning.py:74:61: W291 trailing whitespace
dipy/tracking/learning.py:77:1: W293 blank line contains whitespace
dipy/tracking/learning.py:84:49: W291 trailing whitespace
dipy/tracking/learning.py:86:22: W291 trailing whitespace
dipy/tracking/learning.py:89:80: E501 line too long (81 > 79 characters)
dipy/tracking/learning.py:90:1: W293 blank line contains whitespace
dipy/tracking/learning.py:93:80: E501 line too long (98 > 79 characters)
dipy/tracking/learning.py:93:99: W291 trailing whitespace
dipy/tracking/learning.py:94:80: E501 line too long (96 > 79 characters)
dipy/tracking/learning.py:96:1: W293 blank line contains whitespace
dipy/tracking/learning.py:97:1: W293 blank line contains whitespace
dipy/tracking/learning.py:101:1: W293 blank line contains whitespace
dipy/tracking/learning.py:103:7: E225 missing whitespace around operator
dipy/tracking/learning.py:103:20: W291 trailing whitespace
dipy/tracking/learning.py:104:16: E225 missing whitespace around operator
dipy/tracking/learning.py:104:29: E231 missing whitespace after ','
dipy/tracking/learning.py:105:8: E225 missing whitespace around operator
dipy/tracking/learning.py:107:11: E225 missing whitespace around operator
dipy/tracking/learning.py:107:40: E231 missing whitespace after ','
dipy/tracking/learning.py:107:42: E231 missing whitespace after ','
dipy/tracking/learning.py:108:11: E225 missing whitespace around operator
dipy/tracking/learning.py:109:25: E225 missing whitespace around operator
dipy/tracking/learning.py:109:37: E231 missing whitespace after ','
dipy/tracking/learning.py:109:61: W291 trailing whitespace
dipy/tracking/learning.py:110:12: E225 missing whitespace around operator
dipy/tracking/learning.py:110:15: W291 trailing whitespace
dipy/tracking/learning.py:114:1: W391 blank line at end of file
dipy/tracking/markov.py:340:80: E501 line too long (80 > 79 characters)
dipy/tracking/markov.py:342:80: E501 line too long (80 > 79 characters)
dipy/tracking/metrics.py:28:6: E231 missing whitespace after ','
dipy/tracking/metrics.py:28:8: E231 missing whitespace after ','
dipy/tracking/metrics.py:28:10: E225 missing whitespace around operator
dipy/tracking/metrics.py:28:40: E231 missing whitespace after ','
dipy/tracking/metrics.py:28:48: E231 missing whitespace after ','
dipy/tracking/metrics.py:29:9: E225 missing whitespace around operator
dipy/tracking/metrics.py:29:20: E231 missing whitespace after ','
dipy/tracking/metrics.py:29:25: E231 missing whitespace after ','
dipy/tracking/metrics.py:31:9: E225 missing whitespace around operator
dipy/tracking/metrics.py:33:11: E225 missing whitespace around operator
dipy/tracking/metrics.py:34:11: E225 missing whitespace around operator
dipy/tracking/metrics.py:35:10: E225 missing whitespace around operator
dipy/tracking/metrics.py:35:20: E231 missing whitespace after ','
dipy/tracking/metrics.py:36:12: E225 missing whitespace around operator
dipy/tracking/metrics.py:37:13: E225 missing whitespace around operator
dipy/tracking/metrics.py:88:1: E302 expected 2 blank lines, found 1
dipy/tracking/metrics.py:106:1: E303 too many blank lines (3)
dipy/tracking/metrics.py:153:11: E225 missing whitespace around operator
dipy/tracking/metrics.py:154:8: E225 missing whitespace around operator
dipy/tracking/metrics.py:154:33: E225 missing whitespace around operator
dipy/tracking/metrics.py:155:9: E225 missing whitespace around operator
dipy/tracking/metrics.py:156:9: E225 missing whitespace around operator
dipy/tracking/metrics.py:157:7: E225 missing whitespace around operator
dipy/tracking/metrics.py:191:23: E231 missing whitespace after ','
dipy/tracking/metrics.py:193:1: E302 expected 2 blank lines, found 1
dipy/tracking/metrics.py:193:13: E231 missing whitespace after ','
dipy/tracking/metrics.py:197:8: E225 missing whitespace around operator
dipy/tracking/metrics.py:197:22: E231 missing whitespace after ','
dipy/tracking/metrics.py:198:9: E225 missing whitespace around operator
dipy/tracking/metrics.py:198:22: E225 missing whitespace around operator
dipy/tracking/metrics.py:199:14: E225 missing whitespace around operator
dipy/tracking/metrics.py:201:9: E225 missing whitespace around operator
dipy/tracking/metrics.py:202:27: E231 missing whitespace after ','
dipy/tracking/metrics.py:202:30: E231 missing whitespace after ','
dipy/tracking/metrics.py:203:32: E231 missing whitespace after ','
dipy/tracking/metrics.py:268:9: E225 missing whitespace around operator
dipy/tracking/metrics.py:269:10: E225 missing whitespace around operator
dipy/tracking/metrics.py:270:5: E265 block comment should start with '# '
dipy/tracking/metrics.py:271:6: E225 missing whitespace around operator
dipy/tracking/metrics.py:271:21: E231 missing whitespace after ','
dipy/tracking/metrics.py:271:31: E231 missing whitespace after ','
dipy/tracking/metrics.py:272:5: E265 block comment should start with '# '
dipy/tracking/metrics.py:273:7: E225 missing whitespace around operator
dipy/tracking/metrics.py:274:5: E265 block comment should start with '# '
dipy/tracking/metrics.py:275:21: E231 missing whitespace after ','
dipy/tracking/metrics.py:275:29: E231 missing whitespace after ','
dipy/tracking/metrics.py:276:5: E265 block comment should start with '# '
dipy/tracking/metrics.py:277:19: E231 missing whitespace after ','
dipy/tracking/metrics.py:278:5: E265 block comment should start with '# '
dipy/tracking/metrics.py:279:27: E231 missing whitespace after ','
dipy/tracking/metrics.py:279:34: E231 missing whitespace after ','
dipy/tracking/metrics.py:279:48: E231 missing whitespace after ','
dipy/tracking/metrics.py:280:5: E265 block comment should start with '# '
dipy/tracking/metrics.py:281:5: E265 block comment should start with '# '
dipy/tracking/metrics.py:282:20: E231 missing whitespace after ','
dipy/tracking/metrics.py:283:5: E265 block comment should start with '# '
dipy/tracking/metrics.py:284:13: E231 missing whitespace after ','
dipy/tracking/metrics.py:284:15: E231 missing whitespace after ','
dipy/tracking/metrics.py:284:17: E231 missing whitespace after ','
dipy/tracking/metrics.py:284:19: E231 missing whitespace after ','
dipy/tracking/metrics.py:286:1: E302 expected 2 blank lines, found 1
dipy/tracking/metrics.py:322:9: E225 missing whitespace around operator
dipy/tracking/metrics.py:323:10: E225 missing whitespace around operator
dipy/tracking/metrics.py:325:5: E265 block comment should start with '# '
dipy/tracking/metrics.py:326:27: E231 missing whitespace after ','
dipy/tracking/metrics.py:326:34: E231 missing whitespace after ','
dipy/tracking/metrics.py:326:48: E231 missing whitespace after ','
dipy/tracking/metrics.py:350:9: E225 missing whitespace around operator
dipy/tracking/metrics.py:352:24: E231 missing whitespace after ','
dipy/tracking/metrics.py:357:1: E303 too many blank lines (4)
dipy/tracking/metrics.py:382:9: E265 block comment should start with '# '
dipy/tracking/metrics.py:384:32: E231 missing whitespace after ','
dipy/tracking/metrics.py:385:25: E231 missing whitespace after ','
dipy/tracking/metrics.py:387:9: E265 block comment should start with '# '
dipy/tracking/metrics.py:394:1: E303 too many blank lines (3)
dipy/tracking/metrics.py:394:32: E231 missing whitespace after ','
dipy/tracking/metrics.py:426:15: E225 missing whitespace around operator
dipy/tracking/metrics.py:427:15: E225 missing whitespace around operator
dipy/tracking/metrics.py:429:17: E225 missing whitespace around operator
dipy/tracking/metrics.py:432:17: E225 missing whitespace around operator
dipy/tracking/metrics.py:436:25: E231 missing whitespace after ','
dipy/tracking/metrics.py:436:32: E231 missing whitespace after ','
dipy/tracking/metrics.py:469:11: E225 missing whitespace around operator
dipy/tracking/metrics.py:470:5: E265 block comment should start with '# '
dipy/tracking/metrics.py:472:7: E225 missing whitespace around operator
dipy/tracking/metrics.py:475:9: E265 block comment should start with '# '
dipy/tracking/metrics.py:476:11: E225 missing whitespace around operator
dipy/tracking/metrics.py:477:9: E265 block comment should start with '# '
dipy/tracking/metrics.py:478:11: E225 missing whitespace around operator
dipy/tracking/metrics.py:479:9: E265 block comment should start with '# '
dipy/tracking/metrics.py:480:10: E225 missing whitespace around operator
dipy/tracking/metrics.py:481:10: E225 missing whitespace around operator
dipy/tracking/metrics.py:481:21: E231 missing whitespace after ','
dipy/tracking/metrics.py:482:12: E225 missing whitespace around operator
dipy/tracking/metrics.py:483:10: E225 missing whitespace around operator
dipy/tracking/metrics.py:483:23: E231 missing whitespace after ','
dipy/tracking/metrics.py:484:10: E225 missing whitespace around operator
dipy/tracking/metrics.py:484:26: E231 missing whitespace after ','
dipy/tracking/metrics.py:484:46: E231 missing whitespace after ','
dipy/tracking/metrics.py:484:68: E231 missing whitespace after ','
dipy/tracking/metrics.py:484:80: E501 line too long (83 > 79 characters)
dipy/tracking/metrics.py:485:16: E225 missing whitespace around operator
dipy/tracking/metrics.py:486:9: E265 block comment should start with '# '
dipy/tracking/metrics.py:487:18: E225 missing whitespace around operator
dipy/tracking/metrics.py:487:51: E203 whitespace before ':'
dipy/tracking/metrics.py:487:53: E261 at least two spaces before inline comment
dipy/tracking/metrics.py:487:53: E262 inline comment should start with '# '
dipy/tracking/metrics.py:487:80: E501 line too long (89 > 79 characters)
dipy/tracking/metrics.py:489:20: E225 missing whitespace around operator
dipy/tracking/metrics.py:489:22: E261 at least two spaces before inline comment
dipy/tracking/metrics.py:489:23: E262 inline comment should start with '# '
dipy/tracking/metrics.py:490:15: E225 missing whitespace around operator
dipy/tracking/metrics.py:491:14: E225 missing whitespace around operator
dipy/tracking/metrics.py:492:13: E265 block comment should start with '# '
dipy/tracking/metrics.py:493:13: E265 block comment should start with '# '
dipy/tracking/metrics.py:494:29: E231 missing whitespace after ','
dipy/tracking/metrics.py:496:22: E261 at least two spaces before inline comment
dipy/tracking/metrics.py:496:23: E262 inline comment should start with '# '
dipy/tracking/metrics.py:497:15: E225 missing whitespace around operator
dipy/tracking/metrics.py:498:15: E225 missing whitespace around operator
dipy/tracking/metrics.py:499:15: E225 missing whitespace around operator
dipy/tracking/metrics.py:500:15: E225 missing whitespace around operator
dipy/tracking/metrics.py:501:13: E265 block comment should start with '# '
dipy/tracking/metrics.py:502:13: E265 block comment should start with '# '
dipy/tracking/metrics.py:503:30: E231 missing whitespace after ','
dipy/tracking/metrics.py:503:60: E231 missing whitespace after ','
dipy/tracking/metrics.py:507:1: E302 expected 2 blank lines, found 1
dipy/tracking/metrics.py:507:22: E231 missing whitespace after ','
dipy/tracking/metrics.py:507:29: E231 missing whitespace after ','
dipy/tracking/metrics.py:536:43: E231 missing whitespace after ','
dipy/tracking/metrics.py:536:52: E225 missing whitespace around operator
dipy/tracking/metrics.py:536:67: E225 missing whitespace around operator
dipy/tracking/metrics.py:539:29: E231 missing whitespace after ','
dipy/tracking/metrics.py:539:36: E231 missing whitespace after ','
dipy/tracking/metrics.py:569:47: E231 missing whitespace after ','
dipy/tracking/metrics.py:569:56: E225 missing whitespace around operator
dipy/tracking/metrics.py:574:1: E303 too many blank lines (4)
dipy/tracking/metrics.py:574:15: E231 missing whitespace after ','
dipy/tracking/metrics.py:574:19: E231 missing whitespace after ','
dipy/tracking/metrics.py:574:23: E231 missing whitespace after ','
dipy/tracking/metrics.py:639:9: E231 missing whitespace after ','
dipy/tracking/metrics.py:639:28: E231 missing whitespace after ','
dipy/tracking/metrics.py:639:31: E231 missing whitespace after ','
dipy/tracking/metrics.py:639:37: E231 missing whitespace after ','
dipy/tracking/metrics.py:639:40: E231 missing whitespace after ','
dipy/tracking/metrics.py:639:46: E231 missing whitespace after ','
dipy/tracking/metrics.py:639:50: E231 missing whitespace after ','
dipy/tracking/metrics.py:639:54: E231 missing whitespace after ','
dipy/tracking/metrics.py:639:58: E231 missing whitespace after ','
dipy/tracking/metrics.py:641:9: E231 missing whitespace after ','
dipy/tracking/metrics.py:641:14: E231 missing whitespace after ','
dipy/tracking/metrics.py:641:41: E231 missing whitespace after ','
dipy/tracking/metrics.py:641:43: E231 missing whitespace after ','
dipy/tracking/metrics.py:641:48: E231 missing whitespace after ','
dipy/tracking/metrics.py:642:27: E231 missing whitespace after ','
dipy/tracking/metrics.py:642:32: E231 missing whitespace after ','
dipy/tracking/metrics.py:704:23: E231 missing whitespace after ','
dipy/tracking/metrics.py:741:18: E225 missing whitespace around operator
dipy/tracking/metrics.py:744:8: E225 missing whitespace around operator
dipy/tracking/metrics.py:744:35: E225 missing whitespace around operator
dipy/tracking/metrics.py:745:9: E225 missing whitespace around operator
dipy/tracking/metrics.py:746:9: E225 missing whitespace around operator
dipy/tracking/metrics.py:747:7: E225 missing whitespace around operator
dipy/tracking/metrics.py:752:16: E231 missing whitespace after ','
dipy/tracking/metrics.py:752:23: E231 missing whitespace after ','
dipy/tracking/metrics.py:755:8: E225 missing whitespace around operator
dipy/tracking/metrics.py:755:35: E225 missing whitespace around operator
dipy/tracking/metrics.py:756:9: E225 missing whitespace around operator
dipy/tracking/metrics.py:757:9: E225 missing whitespace around operator
dipy/tracking/metrics.py:758:7: E225 missing whitespace around operator
dipy/tracking/metrics.py:763:19: E231 missing whitespace after ','
dipy/tracking/metrics.py:813:9: E225 missing whitespace around operator
dipy/tracking/metrics.py:814:18: E225 missing whitespace around operator
dipy/tracking/metrics.py:816:14: E225 missing whitespace around operator
dipy/tracking/metrics.py:820:7: E225 missing whitespace around operator
dipy/tracking/metrics.py:820:20: E231 missing whitespace after ','
dipy/tracking/metrics.py:820:31: E231 missing whitespace after ','
dipy/tracking/metrics.py:822:11: E225 missing whitespace around operator
dipy/tracking/metrics.py:824:9: E225 missing whitespace around operator
dipy/tracking/metrics.py:824:22: E231 missing whitespace after ','
dipy/tracking/metrics.py:824:29: E231 missing whitespace after ','
dipy/tracking/metrics.py:825:37: E231 missing whitespace after ','
dipy/tracking/metrics.py:856:6: E225 missing whitespace around operator
dipy/tracking/metrics.py:857:7: E231 missing whitespace after ','
dipy/tracking/metrics.py:857:10: E225 missing whitespace around operator
dipy/tracking/metrics.py:858:14: E231 missing whitespace after ','
dipy/tracking/metrics.py:861:23: E231 missing whitespace after ','
dipy/tracking/metrics.py:889:8: E225 missing whitespace around operator
dipy/tracking/streamline.py:14:1: E302 expected 2 blank lines, found 1
dipy/tracking/utils.py:439:80: E501 line too long (88 > 79 characters)
dipy/tracking/utils.py:445:80: E501 line too long (80 > 79 characters)
dipy/tracking/utils.py:816:9: E129 visually indented line with same indent as next logical line

**Comment by manu-tej** [comment]
PR #939 fixes the issues

**Comment by theaverageguy** [comment]
This can be closed @arokem @manu-tej ?

**Comment by manu-tej** [comment]
@arokem issue closed via #952
