### ISSUE TITLE
PEP8 in utils

### ISSUE THREAD

**Issue by arokem** [nipy/dipy#889]
dipy/utils/_importlib.py:6:1: E302 expected 2 blank lines, found 1
dipy/utils/_importlib.py:16:31: E127 continuation line over-indented for visual indent
dipy/utils/optpkg.py:24:1: E302 expected 2 blank lines, found 1
dipy/utils/optpkg.py:65:80: E501 line too long (120 > 79 characters)
dipy/utils/optpkg.py:83:10: E261 at least two spaces before inline comment
dipy/utils/optpkg.py:85:33: E203 whitespace before ':'
dipy/utils/optpkg.py:91:5: E301 expected 1 blank line, found 0
dipy/utils/optpkg.py:96:1: W391 blank line at end of file
dipy/utils/six.py:12:80: E501 line too long (80 > 79 characters)
dipy/utils/six.py:134:1: E303 too many blank lines (3)
dipy/utils/six.py:158:80: E501 line too long (87 > 79 characters)
dipy/utils/six.py:171:80: E501 line too long (80 > 79 characters)
dipy/utils/six.py:172:80: E501 line too long (80 > 79 characters)
dipy/utils/six.py:290:1: E302 expected 2 blank lines, found 1
dipy/utils/six.py:294:1: E302 expected 2 blank lines, found 1
dipy/utils/six.py:298:1: E302 expected 2 blank lines, found 1
dipy/utils/six.py:306:5: E301 expected 1 blank line, found 0
dipy/utils/six.py:324:5: E301 expected 1 blank line, found 0
dipy/utils/six.py:328:5: E301 expected 1 blank line, found 0
dipy/utils/six.py:330:5: E301 expected 1 blank line, found 0
dipy/utils/six.py:332:5: E301 expected 1 blank line, found 0
dipy/utils/six.py:345:5: E303 too many blank lines (2)
dipy/utils/six.py:351:5: E303 too many blank lines (2)
dipy/utils/six.py:368:5: E303 too many blank lines (2)
dipy/utils/six.py:373:5: E303 too many blank lines (2)
dipy/utils/six.py:378:9: E301 expected 1 blank line, found 0
dipy/utils/tripwire.py:4:1: E302 expected 2 blank lines, found 1
dipy/utils/tripwire.py:38:80: E501 line too long (96 > 79 characters)
dipy/utils/tests/test_arrfuncs.py:18:1: E302 expected 2 blank lines, found 1
dipy/utils/tests/test_arrfuncs.py:19:23: E261 at least two spaces before inline comment

**Comment by waseem18** [comment]
Hello @arokem 

I'm interested in working on this issue.

**Comment by ghoshbishakh** [comment]
@waseem18 as you can see above there is already a pull request so someone else is already into it.

**Comment by arokem** [comment]
Indeed. Closed through #959
