### ISSUE TITLE
PEP8 in viz

### ISSUE THREAD

**Issue by arokem** [nipy/dipy#890]
dipy/viz/colormap.py:152:18: E222 multiple spaces after operator
dipy/viz/fvtk.py:4:80: E501 line too long (136 > 79 characters)
dipy/viz/fvtk.py:5:80: E501 line too long (120 > 79 characters)
dipy/viz/fvtk.py:287:80: E501 line too long (86 > 79 characters)
dipy/viz/fvtk.py:295:80: E501 line too long (114 > 79 characters)
dipy/viz/fvtk.py:440:80: E501 line too long (155 > 79 characters)
dipy/viz/fvtk.py:441:80: E501 line too long (112 > 79 characters)
dipy/viz/fvtk.py:475:80: E501 line too long (96 > 79 characters)
dipy/viz/fvtk.py:676:29: E231 missing whitespace after ':'
dipy/viz/fvtk.py:676:47: E231 missing whitespace after ':'
dipy/viz/fvtk.py:677:1: E302 expected 2 blank lines, found 0
dipy/viz/fvtk.py:910:32: E127 continuation line over-indented for visual indent
dipy/viz/fvtk.py:917:80: E501 line too long (80 > 79 characters)
dipy/viz/projections.py:17:1: E402 module level import not at top of file
dipy/viz/projections.py:19:1: E402 module level import not at top of file
dipy/viz/projections.py:48:80: E501 line too long (81 > 79 characters)
dipy/viz/projections.py:59:80: E501 line too long (89 > 79 characters)
dipy/viz/projections.py:79:46: E231 missing whitespace after ','
dipy/viz/projections.py:79:48: E231 missing whitespace after ','
dipy/viz/projections.py:79:52: E231 missing whitespace after ','
dipy/viz/projections.py:79:55: E231 missing whitespace after ','
dipy/viz/projections.py:79:57: E231 missing whitespace after ','
dipy/viz/projections.py:79:60: E231 missing whitespace after ','
dipy/viz/projections.py:79:63: E231 missing whitespace after ','
dipy/viz/projections.py:79:65: E231 missing whitespace after ','
dipy/viz/projections.py:79:80: E501 line too long (81 > 79 characters)
dipy/viz/projections.py:81:80: E501 line too long (80 > 79 characters)
dipy/viz/projections.py:82:36: E225 missing whitespace around operator
dipy/viz/projections.py:105:9: E122 continuation line missing indentation or outdented
dipy/viz/projections.py:105:51: E231 missing whitespace after ','
dipy/viz/projections.py:106:51: E231 missing whitespace after ','
dipy/viz/projections.py:107:65: E231 missing whitespace after ','
dipy/viz/projections.py:113:12: E225 missing whitespace around operator
dipy/viz/projections.py:113:15: E225 missing whitespace around operator
dipy/viz/projections.py:114:12: E225 missing whitespace around operator
dipy/viz/projections.py:114:15: E225 missing whitespace around operator
dipy/viz/projections.py:116:44: E231 missing whitespace after ','
dipy/viz/projections.py:116:46: E231 missing whitespace after ','
dipy/viz/projections.py:131:40: E261 at least two spaces before inline comment
dipy/viz/projections.py:134:1: W391 blank line at end of file
dipy/viz/regtools.py:20:1: E302 expected 2 blank lines, found 1
dipy/viz/regtools.py:68:23: E127 continuation line over-indented for visual indent
dipy/viz/regtools.py:76:1: E302 expected 2 blank lines, found 1
dipy/viz/regtools.py:281:80: E501 line too long (81 > 79 characters)
dipy/viz/regtools.py:302:23: E127 continuation line over-indented for visual indent
dipy/viz/regtools.py:303:23: E127 continuation line over-indented for visual indent
dipy/viz/regtools.py:311:1: E302 expected 2 blank lines, found 1
dipy/viz/regtools.py:385:23: E127 continuation line over-indented for visual indent
dipy/viz/regtools.py:386:23: E127 continuation line over-indented for visual indent
dipy/viz/widget.py:21:26: E251 unexpected spaces around keyword / parameter equals
dipy/viz/widget.py:21:28: E251 unexpected spaces around keyword / parameter equals
dipy/viz/widget.py:136:80: E501 line too long (80 > 79 characters)
dipy/viz/widget.py:137:80: E501 line too long (83 > 79 characters)
dipy/viz/widget.py:221:80: E501 line too long (80 > 79 characters)
dipy/viz/widget.py:222:80: E501 line too long (83 > 79 characters)
dipy/viz/widget.py:318:80: E501 line too long (80 > 79 characters)
dipy/viz/widget.py:319:80: E501 line too long (83 > 79 characters)
dipy/viz/tests/__init__.py:5:11: W292 no newline at end of file
dipy/viz/tests/test_regtools.py:34:50: E251 unexpected spaces around keyword / parameter equals
dipy/viz/tests/test_regtools.py:34:52: E251 unexpected spaces around keyword / parameter equals

**Comment by ghoshbishakh** [comment]
I hope that meets the pep8 guide
