### ISSUE TITLE
math is broken in doc

### ISSUE THREAD

**Issue by samuelstjean** [nipy/dipy#905]
Anything changed recently? I've been viewing a few examples and none render correctly in either chrome or firefox.

![screenshot from 2016-02-10 15-48-59](https://cloud.githubusercontent.com/assets/3030760/12950565/0eced6a4-d00e-11e5-9813-e1e9a308477a.png)

**Comment by Garyfallidis** [comment]
Good catch!

**Comment by Garyfallidis** [comment]
We need to rebuild the website and re-upload. A bit strange ... @arokem did you update the website? Could it be that some of the latex modules were missing?

**Comment by arokem** [comment]
Oh crikey. Do you see anything obvious missing in the docker configuration? 

https://hub.docker.com/r/arokem/dipy-docbuild/~/dockerfile/

Can you build it and upload it from your maint/0.10.x branch for the time being?

**Comment by Garyfallidis** [comment]
I don't know what is missing from the docker file. It looks good. I am on a computer now running some heavy experiments and I cannot lunch the doc creation at the same time. Maybe in an hour from now.

**Comment by Garyfallidis** [comment]
Please also next time make sure you check some of the examples for issues like this. I hope this is not happening for many days now.

**Comment by Garyfallidis** [comment]
The website is now updated. I had some memory issues compiling the examples. For some reason the examples need more memory than expected. I am on a machine with 16GBytes and I had to close the browser to use all available memory to compile the website.

@arokem in your script you go directly to ``make upload``. You need to first do a ``make html`` test that the script somehow finished and rendered correctly the website and then do a ``make upload``.

**Comment by matthew-brett** [comment]
https://github.com/nipy/dipy/pull/907 might help.

**Comment by Garyfallidis** [comment]
This does not require installing latex locally?

**Comment by arokem** [comment]
Testing that it got built properly is a bit tricky on the remote set up, because I can't pop a browser open there (no screen). I think that I would want to push to my fork first - check that everything is OK, and then upload. I might add a make rule for that.
