### ISSUE TITLE
Inconsistent output for values_from_volume

### ISSUE THREAD

**Issue by MarcCote** [nipy/dipy#909]
@arokem thanks for that function, really useful. I played a bit more with it and found some corner cases, that haven't been tested. For instance,

``` python
from dipy.tracking.streamline import values_from_volume
data3D = np.ones((2,2,2))
streamlines = np.ones((10, 2, 3))
values_from_volume(data3D, streamlines).shape
>>> (10, 2)  # So far so good.
streamlines = np.ones((10, 1, 3))
values_from_volume(data3D, streamlines).shape
>>> (10,)  # I would expect (10, 1)

data4D = np.ones((2,2,2,2))
streamlines = np.ones((10, 1, 3))
values_from_volume(data4D, streamlines).shape  # Even worst
>>> ValueError: bad axis1 argument to swapaxes
```

```
/data/research/src/dipy/dipy/tracking/streamline.py in values_from_volume(data, streamlines, affine)
    449 
    450         if isinstance(vals[-1], np.ndarray):
--> 451             return np.swapaxes(np.array(vals), 2, 1).T
    452         else:
    453             new_vals = []

/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.pyc in swapaxes(a, axis1, axis2)
    487     except AttributeError:
    488         return _wrapit(a, 'swapaxes', axis1, axis2)
--> 489     return swapaxes(axis1, axis2)
    490 
    491 

ValueError: bad axis1 argument to swapaxes
```

I think I found the source of the problem; the `.squeeze()` here:
https://github.com/nipy/dipy/blob/master/dipy/tracking/streamline.py#L394

Is the squeeze really necessary?

**Comment by arokem** [comment]
Thanks for reporting this. As you can see I've started a PR to work on this. 

Just to understand how this arises: is this an actual use-case? Do you actually have a situation where you have a bunch of streamlines and each one has just one node? That might be a tractography problem :-)

**Comment by arokem** [comment]
And to answer your question: that squeeze seems to be necessary for some other use-cases. You'll see the test failure appear soon for this commit: https://github.com/arokem/dipy/commit/a0eb5be64f6550021d061751bd61332caed92fef

**Comment by arokem** [comment]
Is there something obviously wrong about the fix in the most recent commit on #910?

**Comment by MarcCote** [comment]
Yes, it is an actual use-case and no, it is not a tractography problem. On the contrary, it was arising during the tracking ;-). I'm extracting values from a volume one point at the time for many streamlines in parallel.

**Comment by MarcCote** [comment]
It seems I forgot to close this one, so I'm closing it now.
