### ISSUE TITLE
Unable to build documentation with Python 3

### ISSUE THREAD

**Issue by ghoshbishakh** [nipy/dipy#912]
`make html` only works with python 2 and when dipy is installed with python 2

**Comment by theaverageguy** [comment]
How do we fix this? Any hints ?

**Comment by arokem** [comment]
First, we probably wait for VTK to be easily available on Python 3 (e.g. through conda). Then, it's actually pretty straightforward. There are just a few small things that are py2-centric.

**Comment by ghoshbishakh** [comment]
actually it is not that simple. I was looking at it for quite a few days and could not manage to get the api generation script to work properly.

specifically `apigen.py`

**Comment by arokem** [comment]
Huh. Maybe we kick this one a bit further down the road?
