### ISSUE TITLE
change size of colorbar in viz module

### ISSUE THREAD

**Issue by samuelstjean** [nipy/dipy#923]
Is there an option to do that? I looked at the docstring of some actors from this example http://nipy.org/dipy/examples_built/viz_bundles.html#example-viz-bundles and there does not seem to be a way to change the size of the bar/numbers. Looks a bit too big in comparison with the bundle, and fiddling with the window size change the number size but not the bar size itself.

![dipy](https://cloud.githubusercontent.com/assets/3030760/13046866/9afcaf4a-d3db-11e5-84e2-4f8820c844a2.png)

**Comment by arokem** [comment]
This seems like a question better discussed on the mailing list.

**Comment by samuelstjean** [comment]
This also seems like a missing feature/needs better documentation. Maybe it
is even impossible, could not find out.

2016-02-15 17:09 GMT+01:00 Ariel Rokem <notifications@github.com>:

**Comment by arokem** [comment]
The point is that if an answer is provided here, and we close this issue, it will be hard for a casual user to ever find this answer again.

**Comment by samuelstjean** [comment]
*I rather saw this as*

*1. here is how to do it*

*1.a. We should edit the doc example so it's easier to find for random
people.*

*or*



*2. Oh right, that could be useful to have.*

2016-02-15 17:14 GMT+01:00 Ariel Rokem <notifications@github.com>:

**Comment by samuelstjean** [comment]
It can be done by accessing directly the vtk properties of the bar actor, albeit not super user friendly.

Example

~~~python
bar = actor.scalar_bar(lut_cmap)
# bar.SetHeight(0.5)
# bar.SetWidth(0.15)
~~~
Some position properties also can do that according to the vtk doc.

![dipy](https://cloud.githubusercontent.com/assets/3030760/13252446/fecb342c-da36-11e5-9106-9260c09f13f1.png)

**Comment by skoudoro** [comment]
This issue was moved to fury-gl/fury#7
