### ISSUE TITLE
in dipy/io/tests/test_bvectxt.py function with same name is defined twice

### ISSUE THREAD

**Issue by ghoshbishakh** [nipy/dipy#924]
`
def test_reorient_vectors():
    bvec = np.arange(12).reshape((3, 4))
    assert_array_equal(reorient_vectors(bvec, 'ras', 'ras'), bvec)
    assert_array_equal(reorient_vectors(bvec, 'ras', 'lpi'), -bvec)
    result = bvec[[1, 2, 0]]
    assert_array_equal(reorient_vectors(bvec, 'ras', 'asr'), result)
    bvec = result
    result = bvec[[1, 0, 2]] * [[-1], [1], [-1]]
    assert_array_equal(reorient_vectors(bvec, 'asr', 'ial'), result)
    result = bvec[[1, 0, 2]] * [[-1], [1], [1]]
    assert_array_equal(reorient_vectors(bvec, 'asr', 'iar'), result)
    assert_raises(ValueError, reorient_vectors, bvec, 'ras', 'ra')

def test_reorient_vectors():
    bvec = np.arange(12).reshape((3, 4))
    assert_array_equal(reorient_vectors(bvec, 'ras', 'ras'), bvec)
    assert_array_equal(reorient_vectors(bvec, 'ras', 'lpi'), -bvec)
    result = bvec[[1, 2, 0]]
    assert_array_equal(reorient_vectors(bvec, 'ras', 'asr'), result)
    bvec = result
    result = bvec[[1, 0, 2]] * [[-1], [1], [-1]]
    assert_array_equal(reorient_vectors(bvec, 'asr', 'ial'), result)
    result = bvec[[1, 0, 2]] * [[-1], [1], [1]]
    assert_array_equal(reorient_vectors(bvec, 'asr', 'iar'), result)
    assert_raises(ValueError, reorient_vectors, bvec, 'ras', 'ra')

    bvec = np.arange(12).reshape((3, 4))
    bvec = bvec.T
    assert_array_equal(reorient_vectors(bvec, 'ras', 'ras', axis=1), bvec)
    assert_array_equal(reorient_vectors(bvec, 'ras', 'lpi', axis=1), -bvec)
    result = bvec[:, [1, 2, 0]]
    assert_array_equal(reorient_vectors(bvec, 'ras', 'asr', axis=1), result)
    bvec = result
    result = bvec[:, [1, 0, 2]] * [-1, 1, -1]
    assert_array_equal(reorient_vectors(bvec, 'asr', 'ial', axis=1), result)
    result = bvec[:, [1, 0, 2]] * [-1, 1, 1]
    assert_array_equal(reorient_vectors(bvec, 'asr', 'iar', axis=1), result)
`

**Comment by arokem** [comment]
Yup. That seems like a strange oversight. Would you please make a PR with the deletion of one of these? Thanks!

**Comment by ghoshbishakh** [comment]
ok i can delete one of these but which one to delete?

**Comment by arokem** [comment]
Aren't they identical? You can delete either one.

**Comment by Garyfallidis** [comment]
Just remove the first @ghoshbishakh 
Thx!

**Comment by ghoshbishakh** [comment]
@arokem opened a PR. you may have a look :smile:
