### ISSUE TITLE
dipy/tracking/streamlinespeed set_number_of_points crash when nb_points=0

### ISSUE THREAD

**Issue by samuelstjean** [nipy/dipy#931]
Would be useful to check for this case and warn/raise error, since its in cython the whole session stops working. Might also do weird stuff if you ask for 1 points, I did not check explicitly for this case.

**Comment by arokem** [comment]
Could you provide a minimal code snippet to demonstrate this? That would be helpful in debugging.

**Comment by samuelstjean** [comment]
~~~python
In [1]: from dipy.tracking.streamline import set_number_of_points

In [2]: 

In [2]: fib = [np.ones((10,3)), np.ones((10,3))]

In [3]: fibers = set_number_of_points(fib, nb_points=0)
*** Error in `/usr/bin/python': free(): invalid next size (fast): 0x00000000034b1930 ***



Aborted (core dumped)
~~~
Killed my poor ipython notebook cause I had nb_points=variable, which was 0 by mistake, leading to the crash.

**Comment by arokem** [comment]
Is this an actual use-case? Why would you do this?

**Comment by Garyfallidis** [comment]
No it is not a user case. Fib is not a fiber and 0 is irrelevant also. Maybe it is better to leave it crash.

**Comment by jchoude** [comment]
Well, even if it's not a real use case, shouldn't it at least raise an understandable exception?

**Comment by Garyfallidis** [comment]
I was just adding now... That still we can add an if statement  that number of points should be more than a number...

**Comment by Garyfallidis** [comment]
and raise a value error accordingly.

**Comment by jchoude** [comment]
;) Great minds think alike. I'll stop replying too fast to your emails ;)

**Comment by Garyfallidis** [comment]
:)

**Comment by samuelstjean** [comment]
Well anyway, it is an actual use case as I mentionned (or mistake, but whatever), and it is better to just say something like 'this is stupid, don't do that' intead of crashing, always.

**Comment by sahmed95** [comment]
If it is a valid use case, can put a checking condition where it checks for negative dimensions. 
```python
import numpy as np
from dipy.tracking.streamline import set_number_of_points
fib = [np.ones((10,3)), np.ones((10,3))]
fibers = set_number_of_points(fib, nb_points=-1)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-8-3fad3a2a831c> in <module>()
      2 from dipy.tracking.streamline import set_number_of_points
      3 fib = [np.ones((10,3)), np.ones((10,3))]
----> 4 fibers = set_number_of_points(fib, nb_points=-1)

dipy/tracking/streamlinespeed.pyx in dipy.tracking.streamlinespeed.set_number_of_points (dipy/tracking/streamlinespeed.c:5088)()

ValueError: negative dimensions are not allowed```

**Comment by sahmed95** [comment]
can add a check in the function at "dipy/tracking/streamlinespeed.pyx"
What should be the error message ?
```python
def set_number_of_points(streamlines, nb_points=3):
    ''' Change the number of points of streamlines
        (either by downsampling or upsampling)
......................n(s) for s in modified_streamlines]
    [10, 10]
    '''
    only_one_streamlines = False
    if type(streamlines) is np.ndarray:
        only_one_streamlines = True
        streamlines = [streamlines]

    if len(streamlines) == 0:
        return []

    if (nb_points == 0):
        raise ValueError("nb_points cannot be 0")
```

**Comment by arokem** [comment]
You might want to take this on a PR instead.

**Comment by sahmed95** [comment]
On it. Also, a few pep8 issues. Should I go ahead and fix them too or keep it seperate ?

streamlinespeed.pyx:6:1: E402 module level import not at top of file
streamlinespeed.pyx:8:1: E402 module level import not at top of file
streamlinespeed.pyx:15:21: E225 missing whitespace around operator
streamlinespeed.pyx:16:11: E225 missing whitespace around operator
streamlinespeed.pyx:39:80: E501 line too long (82 > 79 characters)
streamlinespeed.pyx:62:80: E501 line too long (87 > 79 characters)
streamlinespeed.pyx:95:80: E501 line too long (93 > 79 characters)
streamlinespeed.pyx:116:80: E501 line too long (107 > 79 characters)
streamlinespeed.pyx:121:80: E501 line too long (122 > 79 characters)
streamlinespeed.pyx:132:53: E225 missing whitespace around operator
streamlinespeed.pyx:168:22: E231 missing whitespace after ','
streamlinespeed.pyx:168:42: E231 missing whitespace after ','
streamlinespeed.pyx:168:47: E703 statement ends with a semicolon
streamlinespeed.pyx:175:80: E501 line too long (86 > 79 characters)
streamlinespeed.pyx:178:22: E231 missing whitespace after ','
streamlinespeed.pyx:178:44: E231 missing whitespace after ','
streamlinespeed.pyx:178:73: E231 missing whitespace after ','
streamlinespeed.pyx:178:80: E501 line too long (100 > 79 characters)
streamlinespeed.pyx:178:95: E231 missing whitespace after ','
streamlinespeed.pyx:188:20: E231 missing whitespace after ','
streamlinespeed.pyx:188:42: E231 missing whitespace after ','
streamlinespeed.pyx:265:80: E501 line too long (93 > 79 characters)
streamlinespeed.pyx:268:80: E501 line too long (89 > 79 characters)
streamlinespeed.pyx:270:80: E501 line too long (80 > 79 characters)
streamlinespeed.pyx:272:80: E501 line too long (81 > 79 characters)
streamlinespeed.pyx:281:80: E501 line too long (100 > 79 characters)
streamlinespeed.pyx:289:80: E501 line too long (100 > 79 characters)
streamlinespeed.pyx:294:80: E501 line too long (107 > 79 characters)
streamlinespeed.pyx:297:80: E501 line too long (100 > 79 characters)
streamlinespeed.pyx:299:80: E501 line too long (80 > 79 characters)
streamlinespeed.pyx:302:80: E501 line too long (122 > 79 characters)
streamlinespeed.pyx:305:80: E501 line too long (100 > 79 characters)
streamlinespeed.pyx:307:80: E501 line too long (80 > 79 characters)
streamlinespeed.pyx:370:80: E501 line too long (90 > 79 characters)
streamlinespeed.pyx:433:80: E501 line too long (80 > 79 characters)
streamlinespeed.pyx:507:80: E501 line too long (89 > 79 characters)
streamlinespeed.pyx:517:80: E501 line too long (89 > 79 characters)
streamlinespeed.pyx:518:80: E501 line too long (85 > 79 characters)
streamlinespeed.pyx:520:80: E501 line too long (90 > 79 characters)
streamlinespeed.pyx:521:80: E501 line too long (86 > 79 characters)

**Comment by sahmed95** [comment]
Notebook dies even for the case when nb_points is accidently set to a fraction. Should there be a check for fractions too ? Instead of a crash ? 
```ipython
In [6]: fibers = set_number_of_points(fib, nb_points= 0.1)
*** Error in `/usr/bin/python3': malloc(): memory corruption (fast): 0x0a11afb8 ***
Aborted (core dumped)
```

**Comment by samuelstjean** [comment]
you can use this to check for it
~~~python
In [6]: import numbers

In [8]: isinstance(3, numbers.Integral)
Out[8]: True

In [9]: isinstance(3., numbers.Integral)
Out[9]: False
~~~

**Comment by MarcCote** [comment]
Regarding `nb_points=0.1` the 0.1 seems to get cast to integer by `np.empty`, in this case 0.1->0, so we obtain the same memory error as with `nb_points=0`. This means that checking that `nb_points > 2` would be enough to avoid malloc error. That said, `nb_points=5.3` would be fine and produce the same result as `nb_points=5`.

Also, with numpy 1.8.2 I get a DeprecationWarning saying:
> DeprecationWarning: using a *non-integer* number instead of an integer will result in an error in the future.

So eventually, this will raise an exception even with `nb_points=5.` (a float) and will make the proposed integer check obsolete. We should probably just do `nb_points = int(nb_points)` at the beginning of the function and mention this behaviour in the docstring.
 
@arokem, @Garyfallidis what option do you think is the best here? Integer check vs. integer casting?
