### ISSUE TITLE
Drop python 2.6

### ISSUE THREAD

**Issue by samuelstjean** [nipy/dipy#940]
It is old and unmaintained, even pip warns against it now.

![screenshot from 2016-02-24 10-37-32](https://cloud.githubusercontent.com/assets/3030760/13281216/c1936e88-dae2-11e5-9a1c-ac84d72974b4.png)

**Comment by theaverageguy** [comment]
Where do we make changes for this?

**Comment by samuelstjean** [comment]
In the setup.py, it's pretty much just deleting a line. We just need people
to actually say 'this is a good idea, go ahead' or 'this is retarded'
before though.
But with all the new people around for gsoc, it seems like everyone is
swarmed with reviewing a ton of small PR, so it's not really important
right now since python 2.6 is not deprecated yet, just soon.

Always good to know what is coming anyway.

2016-03-21 17:53 GMT+01:00 theaverageguy <notifications@github.com>:

**Comment by samuelstjean** [comment]
My mistake, I meant rather the travis.yml file, as this drops the testing
part. It does not make it stops working with 2.6, rather means that if it
works, good for you, if not, good time to update then. Should stop
responding to email late before leaving I guess.

**Comment by theaverageguy** [comment]
@samuelstjean I would wait till you or some other mentor gives a green flag then. :)

**Comment by theaverageguy** [comment]
@arokem Any call on this one?

**Comment by arokem** [comment]
Closed through #1075
