### ISSUE TITLE
"pip3 install dipy" in Installation for python3

### ISSUE THREAD

**Issue by theaverageguy** [nipy/dipy#986]
For python3, [installation guide](http://nipy.org/dipy/installation.html) should mention installation using 
`pip3 install dipy`

**Comment by ghoshbishakh** [comment]
@theaverageguy that depends. I am using arch linux and for me pip is python 3 and pip2 is for python2

**Comment by arokem** [comment]
I would prefer to go with simplicity here. I believe that `pip` will install on whatever python you get when you type `python` (and that will depend on how you set up your system). I believe the current recommendation is generic enough. Closing for now, but feel free to pipe up if you think this should be reopened.
