### ISSUE TITLE
Practical FAQs don't have hyperlinks to modules/libraries.

### ISSUE THREAD

**Issue by theaverageguy** [nipy/dipy#987]
In [practical FAQs](http://nipy.org/dipy/faq.html) , matplotlib has a hyperlink for easy access of that library's page. However , numpy, ipython and cpython are used for different tasks but there are no hyperlinks for them.
This should be consistent.

**Comment by theaverageguy** [comment]
Working on this one.

**Comment by ArjitJ** [comment]
This is the txt file for the code of [practical FAQs](http://nipy.org/dipy/faq.html) with the link for ipython added.
[faq.txt](https://github.com/nipy/dipy/files/1698087/faq.txt)

**Comment by skoudoro** [comment]
Hi @ArjitJ,  Can you create a PR for this issue. Look at [this file](https://github.com/nipy/dipy/blob/master/doc/faq.rst) and make the needed change. 

Thanks!

**Comment by ArjitJ** [comment]
@skoudoro  #1416
