### ISSUE TITLE
Documentation footer has 2008-2015 mentioned.

### ISSUE THREAD

**Issue by theaverageguy** [nipy/dipy#991]
Where exactly can I change it?

**Comment by arokem** [comment]
Try using `git grep 2015` to find all the mentions of "2015" in the repo.

**Comment by theaverageguy** [comment]
@arokem I searched for "copyright 2008-2015" directly on the repo on github. 
Would that be equivalent? I couldn't find it like that though.

**Comment by souravsingh** [comment]
On doing a ``git grep 2015`` This is the list which is produced- [http://paste.ubuntu.com/15474406/](http://paste.ubuntu.com/15474406/)

**Comment by arokem** [comment]
Seems resolved here: https://github.com/nipy/dipy/commit/8fd22929653a3d3bcc2454b1d401c241eaf597b3

Closing.
